@{
    # Module manifest — RegiLattice PowerShell Module
    # Auto-generated by PowerShellModuleGenerator.cs; hand-editable.

    # Module identity
    ModuleVersion     = '6.27.0'
    GUID              = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
    Author            = 'YairRajwan'
    CompanyName       = 'RegiLattice'
    Copyright         = '(c) RegiLattice. All rights reserved.'
    Description       = 'PowerShell interface for RegiLattice — inspect, apply, and remove Windows registry tweaks from the pipeline.'

    # PowerShell / OS requirements
    PowerShellVersion = '5.1'

    # Module entry point
    RootModule        = 'RegiLattice.psm1'

    # Cmdlets exported from this module
    FunctionsToExport = @(
        'Get-RLTweak',
        'Get-RLTweakStatus',
        'Invoke-RLApply',
        'Invoke-RLRemove',
        'Get-RLHealthScore',
        'Set-RLTweak',
        'Get-RLProfile',
        'Set-RLProfile',
        'Export-RLSnapshot',
        'Restore-RLSnapshot',
        'Invoke-RLBatch'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @(
        'grt',   # Get-RLTweak
        'grts',  # Get-RLTweakStatus
        'ira',   # Invoke-RLApply
        'irr',   # Invoke-RLRemove
        'srt',   # Set-RLTweak
        'grp',   # Get-RLProfile
        'srp',   # Set-RLProfile
        'irb'    # Invoke-RLBatch
    )

    # Module metadata (shown in `Find-Module`, `Get-Module -ListAvailable`)
    PrivateData       = @{
        PSData = @{
            Tags         = @('Windows', 'Registry', 'Tweaks', 'RegiLattice', 'Performance', 'Privacy')
            ProjectUri   = 'https://github.com/RajwanYair/RegiLattice'
            LicenseUri   = 'https://github.com/RajwanYair/RegiLattice/blob/main/LICENSE'
            ReleaseNotes = 'PowerShell module for RegiLattice v6.0.6. Adds Set-RLTweak, Get-RLProfile, Set-RLProfile, Export-RLSnapshot, Restore-RLSnapshot, Invoke-RLBatch (B4/B7).'
        }
    }
}
