@{
    # Module manifest — RegiLattice PowerShell Module
    # Auto-generated by PowerShellModuleGenerator.cs; hand-editable.

    # Module identity
    ModuleVersion     = '6.33.0'
    GUID              = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
    Author            = 'YairRajwan'
    CompanyName       = 'RegiLattice'
    Copyright         = '(c) RegiLattice. All rights reserved.'
    Description       = 'PowerShell interface for RegiLattice — inspect, apply, and remove Windows registry tweaks from the pipeline.'

    # PowerShell / OS requirements
    PowerShellVersion = '5.1'

    # Module entry point
    RootModule        = 'RegiLattice.psm1'

    # Cmdlets exported from this module
    FunctionsToExport = @(
        # Original cmdlets
        'Get-RLTweak',
        'Get-RLTweakStatus',
        'Invoke-RLApply',
        'Invoke-RLRemove',
        'Get-RLHealthScore',
        'Set-RLTweak',
        'Get-RLProfile',
        'Set-RLProfile',
        'Export-RLSnapshot',
        'Restore-RLSnapshot',
        'Invoke-RLBatch',
        # Phase 7.4 — discovery, diff, export/import, validation, diagnostics
        'Get-RLCategory',
        'Get-RLTag',
        'Compare-RLSnapshot',
        'Export-RLJson',
        'Export-RLReg',
        'Import-RLJson',
        'Invoke-RLValidate',
        'Get-RLStats',
        'Invoke-RLDoctor',
        'Get-RLHwInfo',
        'Get-RLDependency'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @(
        'grt',   # Get-RLTweak
        'grts',  # Get-RLTweakStatus
        'ira',   # Invoke-RLApply
        'irr',   # Invoke-RLRemove
        'srt',   # Set-RLTweak
        'grp',   # Get-RLProfile
        'srp',   # Set-RLProfile
        'irb',   # Invoke-RLBatch
        'grc',   # Get-RLCategory
        'grtg',  # Get-RLTag
        'crs',   # Compare-RLSnapshot
        'erj',   # Export-RLJson
        'irv',   # Invoke-RLValidate
        'grst',  # Get-RLStats
        'ird',   # Invoke-RLDoctor
        'grdp'   # Get-RLDependency
    )

    # Module metadata (shown in `Find-Module`, `Get-Module -ListAvailable`)
    PrivateData       = @{
        PSData = @{
            Tags         = @('Windows', 'Registry', 'Tweaks', 'RegiLattice', 'Performance', 'Privacy')
            ProjectUri   = 'https://github.com/RajwanYair/RegiLattice'
            LicenseUri   = 'https://github.com/RajwanYair/RegiLattice/blob/main/LICENSE'
            ReleaseNotes = 'v6.30.0: Phase 7.4 — 11 new cmdlets (Get-RLCategory, Get-RLTag, Compare-RLSnapshot, Export-RLJson, Export-RLReg, Import-RLJson, Invoke-RLValidate, Get-RLStats, Invoke-RLDoctor, Get-RLHwInfo, Get-RLDependency). Total: 22 public functions + 16 aliases. Requires RegiLattice CLI v6.30.0+.'
        }
    }
}
