@{
    # Module manifest — RegiLattice PowerShell Module
    # Auto-generated by PowerShellModuleGenerator.cs; hand-editable.

    # Module identity
    ModuleVersion     = '4.3.0'
    GUID              = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
    Author            = 'YairRajwan'
    CompanyName       = 'RegiLattice'
    Copyright         = '(c) RegiLattice. All rights reserved.'
    Description       = 'PowerShell interface for RegiLattice — inspect, apply, and remove Windows registry tweaks from the pipeline.'

    # PowerShell / OS requirements
    PowerShellVersion = '5.1'

    # Module entry point
    RootModule        = 'RegiLattice.psm1'

    # Cmdlets exported from this module
    FunctionsToExport = @(
        'Get-RLTweak',
        'Get-RLTweakStatus',
        'Invoke-RLApply',
        'Invoke-RLRemove',
        'Get-RLHealthScore'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @(
        'grt',   # Get-RLTweak
        'grts',  # Get-RLTweakStatus
        'ira',   # Invoke-RLApply
        'irr'    # Invoke-RLRemove
    )

    # Module metadata (shown in `Find-Module`, `Get-Module -ListAvailable`)
    PrivateData       = @{
        PSData = @{
            Tags         = @('Windows', 'Registry', 'Tweaks', 'RegiLattice', 'Performance', 'Privacy')
            ProjectUri   = 'https://github.com/RajwanYair/RegiLattice'
            LicenseUri   = 'https://github.com/RajwanYair/RegiLattice/blob/main/LICENSE'
            ReleaseNotes = 'Initial PowerShell module scaffold for RegiLattice v4.3.0.'
        }
    }
}
