// RegiLattice.GUI — Forms/SmartScanDialog.cs
// Smart Scan dialog — shows the top 25 prioritised tweak recommendations
// and lets users apply individual tweaks or all "Quick Wins" at once.
// Wire-up: Tools menu → "Smart Scan…" → OnOpenSmartScan() in MainForm.cs

namespace RegiLattice.GUI.Forms;

using RegiLattice.Core;
using RegiLattice.Core.Models;

/// <summary>
/// Smart Scan dialog — presents a ranked list of unapplied tweak recommendations
/// generated by <see cref="SmartScanService"/>.
/// </summary>
internal sealed class SmartScanDialog : Form
{
    // ── Dependencies ─────────────────────────────────────────────────────────
    private readonly TweakEngine _engine;
    private readonly IReadOnlyDictionary<string, TweakResult>? _statusCache;

    // ── Controls ─────────────────────────────────────────────────────────────
    private readonly ListView _lstRecs = new() { FullRowSelect = true, MultiSelect = true, View = View.Details };
    private readonly Label _lblSummary = new();
    private readonly Label _lblStatus = new();
    private readonly Button _btnApplyQuickWins = new();
    private readonly Button _btnApplySelected = new();
    private readonly Button _btnRescan = new();
    private readonly Button _btnClose = new();
    private readonly ProgressBar _progressBar = new() { Style = ProgressBarStyle.Marquee, Visible = false };
    private readonly Panel _detailPanel = new();
    private readonly Label _lblDetailText = new();

    // ── State ─────────────────────────────────────────────────────────────────
    private ScanResult? _lastResult;

    // ── Constructor ───────────────────────────────────────────────────────────

    internal SmartScanDialog(
        TweakEngine engine,
        IReadOnlyDictionary<string, TweakResult>? statusCache = null
    )
    {
        _engine = engine;
        _statusCache = statusCache;

        Text = "\u26A1 Smart Scan — Tweak Recommendations";
        Icon = AppIcons.AppIcon;
        FormBorderStyle = FormBorderStyle.Sizable;
        StartPosition = FormStartPosition.CenterParent;
        MinimumSize = new Size(800, 540);
        ClientSize = new Size(920, 640);
        BackColor = AppTheme.Bg;
        ForeColor = AppTheme.Fg;
        Font = AppTheme.Regular;

        BuildLayout();
        Load += async (_, _) => await RunScanAsync();
    }

    // ── Layout ────────────────────────────────────────────────────────────────

    private void BuildLayout()
    {
        // Title bar label
        var lblTitle = new Label
        {
            Text = "\u26A1 Smart Scan",
            Font = AppTheme.Title,
            ForeColor = AppTheme.Accent,
            Dock = DockStyle.Top,
            Height = 38,
            TextAlign = ContentAlignment.MiddleLeft,
            Padding = new Padding(8, 0, 0, 0),
        };

        // Summary row
        _lblSummary.Dock = DockStyle.Top;
        _lblSummary.Height = 28;
        _lblSummary.TextAlign = ContentAlignment.MiddleLeft;
        _lblSummary.Padding = new Padding(8, 0, 0, 0);
        _lblSummary.ForeColor = AppTheme.FgDim;
        _lblSummary.Text = "Scanning…";

        // Progress bar (shown while scanning)
        _progressBar.Dock = DockStyle.Top;
        _progressBar.Height = 4;
        _progressBar.MarqueeAnimationSpeed = 40;

        // Status bar at bottom
        _lblStatus.Dock = DockStyle.Bottom;
        _lblStatus.Height = 24;
        _lblStatus.TextAlign = ContentAlignment.MiddleLeft;
        _lblStatus.Padding = new Padding(8, 0, 0, 0);
        _lblStatus.ForeColor = AppTheme.FgDim;

        // Button row
        var btnPanel = new Panel { Dock = DockStyle.Bottom, Height = 50, BackColor = AppTheme.Surface };
        ConfigureButton(_btnApplyQuickWins, "\u2714 Apply Quick Wins", AppTheme.Green, 180, new Point(8, 10));
        ConfigureButton(_btnApplySelected, "\u25B6 Apply Selected", AppTheme.Accent, 150, new Point(196, 10));
        ConfigureButton(_btnRescan, "\U0001F504 Rescan", AppTheme.FgDim, 100, new Point(354, 10));
        ConfigureButton(_btnClose, "Close", AppTheme.FgDim, 80, new Point(462, 10));
        btnPanel.Controls.AddRange([_btnApplyQuickWins, _btnApplySelected, _btnRescan, _btnClose]);

        _btnApplyQuickWins.Click += async (_, _) => await ApplyQuickWinsAsync();
        _btnApplySelected.Click += async (_, _) => await ApplySelectedAsync();
        _btnRescan.Click += async (_, _) => await RunScanAsync();
        _btnClose.Click += (_, _) => Close();

        // Detail panel (bottom of list — shows description of selected rec)
        _detailPanel.Dock = DockStyle.Bottom;
        _detailPanel.Height = 80;
        _detailPanel.BackColor = AppTheme.Surface;
        _detailPanel.Padding = new Padding(8, 4, 8, 4);
        _lblDetailText.Dock = DockStyle.Fill;
        _lblDetailText.ForeColor = AppTheme.FgDim;
        _lblDetailText.MaximumSize = new Size(0, 0);
        _detailPanel.Controls.Add(_lblDetailText);

        // ListView (main content area)
        _lstRecs.Dock = DockStyle.Fill;
        _lstRecs.BackColor = AppTheme.Surface;
        _lstRecs.ForeColor = AppTheme.Fg;
        _lstRecs.GridLines = true;
        _lstRecs.BorderStyle = BorderStyle.None;
        _lstRecs.Columns.Add("#", 36);
        _lstRecs.Columns.Add("Quick Win", 80);
        _lstRecs.Columns.Add("Tweak", 340);
        _lstRecs.Columns.Add("Category", 160);
        _lstRecs.Columns.Add("Impact", 60);
        _lstRecs.Columns.Add("Safety", 60);
        _lstRecs.Columns.Add("Priority", 65);
        _lstRecs.SelectedIndexChanged += OnRecSelectionChanged;
        _lstRecs.DoubleClick += async (_, _) => await ApplySelectedAsync();

        Controls.Add(_lstRecs);
        Controls.Add(_detailPanel);
        Controls.Add(btnPanel);
        Controls.Add(_progressBar);
        Controls.Add(_lblSummary);
        Controls.Add(lblTitle);
        Controls.Add(_lblStatus);
    }

    private static void ConfigureButton(Button btn, string text, Color fore, int width, Point loc)
    {
        btn.Text = text;
        btn.ForeColor = fore;
        btn.BackColor = AppTheme.Surface;
        btn.FlatStyle = FlatStyle.Flat;
        btn.FlatAppearance.BorderColor = fore;
        btn.Width = width;
        btn.Height = 30;
        btn.Location = loc;
        btn.Font = AppTheme.Regular;
    }

    // ── Scan ──────────────────────────────────────────────────────────────────

    private async Task RunScanAsync()
    {
        SetBusy(true);
        _lblSummary.Text = "Scanning your tweak status…";
        _lstRecs.Items.Clear();
        _btnApplyQuickWins.Enabled = false;
        _btnApplySelected.Enabled = false;

        try
        {
            bool corpSafe = CorporateGuard.IsCorporateNetwork();
            ScanResult result = await SmartScanService.ScanAsync(_engine, _statusCache, forceCorpSafe: corpSafe);
            _lastResult = result;
            PopulateList(result);
        }
        catch (Exception ex)
        {
            _lblSummary.Text = $"Scan error: {ex.Message}";
        }
        finally
        {
            SetBusy(false);
        }
    }

    private void PopulateList(ScanResult result)
    {
        _lstRecs.BeginUpdate();
        _lstRecs.Items.Clear();

        int rank = 0;
        foreach (ScanRecommendation rec in result.Recommendations)
        {
            rank++;
            var item = new ListViewItem(rank.ToString());
            item.SubItems.Add(rec.IsQuickWin ? "\u2605 Yes" : "");
            item.SubItems.Add(rec.Tweak.Label);
            item.SubItems.Add(rec.Tweak.Category);
            item.SubItems.Add(rec.Tweak.ImpactScore.ToString());
            item.SubItems.Add(rec.Tweak.SafetyRating.ToString());
            item.SubItems.Add(rec.PriorityScore.ToString());
            item.Tag = rec;

            if (rec.IsQuickWin)
                item.ForeColor = AppTheme.Green;
            else if (rec.PriorityScore >= 12)
                item.ForeColor = AppTheme.Accent;

            _lstRecs.Items.Add(item);
        }

        _lstRecs.EndUpdate();

        int qw = result.QuickWinsCount;
        _lblSummary.Text = $"Scanned {result.ScannedCount} tweaks — {result.Recommendations.Count} recommendations"
            + (qw > 0 ? $", {qw} Quick Wins" : "");
        _btnApplyQuickWins.Enabled = qw > 0;
        _btnApplySelected.Enabled = false;
        SetStatus("Scan complete.");
    }

    // ── Apply ─────────────────────────────────────────────────────────────────

    private async Task ApplyQuickWinsAsync()
    {
        if (_lastResult is null)
            return;

        List<TweakDef> targets = _lastResult
            .Recommendations.Where(r => r.IsQuickWin)
            .Select(r => r.Tweak)
            .ToList();

        await ApplyBatchAsync(targets, "Quick Win");
    }

    private async Task ApplySelectedAsync()
    {
        if (_lstRecs.SelectedItems.Count == 0)
            return;

        List<TweakDef> targets = _lstRecs
            .SelectedItems.Cast<ListViewItem>()
            .Where(i => i.Tag is ScanRecommendation)
            .Select(i => ((ScanRecommendation)i.Tag!).Tweak)
            .ToList();

        await ApplyBatchAsync(targets, "selected");
    }

    private async Task ApplyBatchAsync(List<TweakDef> targets, string label)
    {
        if (targets.Count == 0)
            return;

        SetBusy(true);
        SetStatus($"Applying {targets.Count} {label} tweaks…");

        try
        {
            int applied = 0;
            int failed = 0;

            await Task.Run(() =>
            {
                foreach (TweakDef td in targets)
                {
                    try
                    {
                        _engine.Apply(td);
                        applied++;
                    }
                    catch
                    {
                        failed++;
                    }
                }
            });

            SetStatus(
                failed == 0
                    ? $"Applied {applied} tweaks successfully."
                    : $"Applied {applied}, failed {failed}."
            );

            // Re-run scan to update recommendations.
            await RunScanAsync();
        }
        finally
        {
            SetBusy(false);
        }
    }

    // ── Event handlers ────────────────────────────────────────────────────────

    private void OnRecSelectionChanged(object? sender, EventArgs e)
    {
        _btnApplySelected.Enabled = _lstRecs.SelectedItems.Count > 0;

        if (
            _lstRecs.SelectedItems.Count == 1
            && _lstRecs.SelectedItems[0].Tag is ScanRecommendation rec
        )
        {
            _lblDetailText.Text = rec.Reason;
        }
        else
        {
            _lblDetailText.Text = string.Empty;
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private void SetBusy(bool busy)
    {
        _progressBar.Visible = busy;
        _btnRescan.Enabled = !busy;
        _btnApplyQuickWins.Enabled = !busy && (_lastResult?.QuickWinsCount ?? 0) > 0;
        _btnApplySelected.Enabled = !busy && _lstRecs.SelectedItems.Count > 0;
    }

    private void SetStatus(string text)
    {
        if (InvokeRequired)
        {
            BeginInvoke(() => _lblStatus.Text = text);
            return;
        }
        _lblStatus.Text = text;
    }
}
