// RegiLattice.Core — Services/IntuneOmaUriExporter.cs
// Exports Registry-kind tweaks as OMA-URI JSON for Microsoft Intune Custom Configuration.
// OMA-URI format: ./Device/Vendor/MSFT/Registry/HKLM/<KeyPath>/<ValueName>
// Supports DWORD, QWORD (as Integer), REG_SZ, REG_EXPAND_SZ (as String).

using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Win32;
using RegiLattice.Core.Models;

namespace RegiLattice.Core;

/// <summary>A single OMA-URI setting for an Intune Custom Configuration policy.</summary>
public sealed class OmaUriSetting
{
    /// <summary>The originating tweak ID.</summary>
    [JsonPropertyName("tweakId")]
    public required string TweakId { get; init; }

    /// <summary>Human-readable tweak label.</summary>
    [JsonPropertyName("label")]
    public required string Label { get; init; }

    /// <summary>Tweak category for grouping.</summary>
    [JsonPropertyName("category")]
    public required string Category { get; init; }

    /// <summary>
    /// OMA-URI path, e.g.
    /// <c>./Device/Vendor/MSFT/Registry/HKLM/SOFTWARE/Policies/Microsoft/Windows/DataCollection/AllowTelemetry</c>.
    /// </summary>
    [JsonPropertyName("omaUri")]
    public required string OmaUri { get; init; }

    /// <summary>Intune data type: "Integer" (DWORD/QWORD) or "String" (REG_SZ/REG_EXPAND_SZ).</summary>
    [JsonPropertyName("dataType")]
    public required string DataType { get; init; }

    /// <summary>String representation of the value to write.</summary>
    [JsonPropertyName("value")]
    public required string Value { get; init; }

    /// <summary>Optional short description / motivation.</summary>
    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; init; }
}

/// <summary>A tweak that could not be mapped to an OMA-URI.</summary>
public sealed class UnmappedTweak
{
    /// <summary>Tweak identifier.</summary>
    [JsonPropertyName("tweakId")]
    public required string TweakId { get; init; }

    /// <summary>Human-readable label.</summary>
    [JsonPropertyName("label")]
    public required string Label { get; init; }

    /// <summary>TweakKind preventing the mapping.</summary>
    [JsonPropertyName("kind")]
    public required string Kind { get; init; }

    /// <summary>Human-readable reason why the tweak was not mapped.</summary>
    [JsonPropertyName("reason")]
    public required string Reason { get; init; }
}

/// <summary>Root object written to the exported Intune JSON file.</summary>
public sealed class IntuneExportDocument
{
    /// <summary>Policy display name shown in Intune.</summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = "RegiLattice Custom Configuration";

    /// <summary>Policy description shown in Intune.</summary>
    [JsonPropertyName("description")]
    public string Description { get; init; } = "Generated by RegiLattice";

    /// <summary>UTC timestamp of export in ISO-8601 format.</summary>
    [JsonPropertyName("exportedAt")]
    public string ExportedAt { get; init; } = DateTime.UtcNow.ToString("O");

    /// <summary>Generator identification string.</summary>
    [JsonPropertyName("generator")]
    public string Generator { get; init; } = "RegiLattice";

    /// <summary>Mapped OMA-URI settings; one entry per ApplyOp that was successfully mapped.</summary>
    [JsonPropertyName("settings")]
    public required IReadOnlyList<OmaUriSetting> Settings { get; init; }

    /// <summary>Tweaks that could not be mapped (non-registry kind, delete ops, binary values).</summary>
    [JsonPropertyName("unmappedTweaks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<UnmappedTweak>? UnmappedTweaks { get; init; }

    /// <summary>Count of successfully mapped settings (computed, not serialized).</summary>
    [JsonIgnore]
    public int MappedCount => Settings.Count;

    /// <summary>Count of tweaks that could not be mapped (computed, not serialized).</summary>
    [JsonIgnore]
    public int UnmappedCount => UnmappedTweaks?.Count ?? 0;
}

/// <summary>
/// Exports Registry-kind tweaks as OMA-URI JSON for Microsoft Intune Custom Configuration.
/// Only HKLM tweaks with DWORD, QWORD, REG_SZ, or REG_EXPAND_SZ values are mappable.
/// </summary>
public static class IntuneOmaUriExporter
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true, Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    /// <summary>Builds the export document without writing to disk.</summary>
    /// <param name="engine">Fully registered <see cref="TweakEngine"/>.</param>
    /// <param name="machineOnly">
    /// When <c>true</c> (default), only HKLM tweaks are exported (recommended for device profiles).
    /// Pass <c>false</c> to also include HKCU tweaks under <c>./User/Vendor/MSFT/Registry/HKCU/</c>.
    /// </param>
    public static IntuneExportDocument Build(TweakEngine engine, bool machineOnly = true)
    {
        ArgumentNullException.ThrowIfNull(engine);

        var settings = new List<OmaUriSetting>();
        var unmapped = new List<UnmappedTweak>();

        foreach (TweakDef td in engine.AllTweaks())
        {
            if (!td.HasOperations)
                continue;

            if (td.Kind != TweakKind.Registry && td.Kind != TweakKind.GroupPolicy)
            {
                unmapped.Add(
                    new UnmappedTweak
                    {
                        TweakId = td.Id,
                        Label = td.Label,
                        Kind = td.Kind.ToString(),
                        Reason = $"TweakKind is {td.Kind}; only Registry and GroupPolicy tweaks are OMA-URI mappable.",
                    }
                );
                continue;
            }

            var mapped = MapTweakOps(td, machineOnly);
            if (mapped.Count > 0)
            {
                settings.AddRange(mapped);
            }
            else
            {
                unmapped.Add(
                    new UnmappedTweak
                    {
                        TweakId = td.Id,
                        Label = td.Label,
                        Kind = "Registry",
                        Reason = machineOnly
                            ? "No HKLM ApplyOps with supported value kinds (DWORD/QWORD/REG_SZ/REG_EXPAND_SZ)."
                            : "No ApplyOps with supported value kinds (DWORD/QWORD/REG_SZ/REG_EXPAND_SZ).",
                    }
                );
            }
        }

        return new IntuneExportDocument { Settings = settings, UnmappedTweaks = unmapped.Count > 0 ? unmapped : null };
    }

    /// <summary>Exports all mappable tweaks to <paramref name="outputPath"/> as pretty-printed JSON.</summary>
    public static void Export(TweakEngine engine, string outputPath, bool machineOnly = true)
    {
        ArgumentNullException.ThrowIfNull(engine);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputPath);

        var doc = Build(engine, machineOnly);
        var json = JsonSerializer.Serialize(doc, JsonOptions);
        File.WriteAllText(outputPath, json, System.Text.Encoding.UTF8);
    }

    // ── Private helpers ──────────────────────────────────────────────────────

    private static IReadOnlyList<OmaUriSetting> MapTweakOps(TweakDef td, bool machineOnly)
    {
        var result = new List<OmaUriSetting>();

        foreach (RegOp op in td.ApplyOps)
        {
            if (op.Kind != RegOpKind.SetValue)
                continue;

            bool isHklm = IsHklm(op.Path);
            bool isHkcu = IsHkcu(op.Path);

            if (machineOnly && !isHklm)
                continue;
            if (!isHklm && !isHkcu)
                continue; // unknown hive — skip

            if (
                op.ValueKind is not (RegistryValueKind.DWord or RegistryValueKind.QWord or RegistryValueKind.String or RegistryValueKind.ExpandString)
            )
                continue; // binary/multi-sz not mappable

            string omaUri = BuildOmaUri(op.Path, op.Name, isHklm);
            (string dataType, string value) = MapValue(op);

            result.Add(
                new OmaUriSetting
                {
                    TweakId = td.Id,
                    Label = td.Label,
                    Category = td.Category,
                    OmaUri = omaUri,
                    DataType = dataType,
                    Value = value,
                    Description = td.Description.Length is > 0 and <= 120 ? td.Description : null,
                }
            );
        }

        return result;
    }

    private static bool IsHklm(string path) =>
        path.StartsWith("HKEY_LOCAL_MACHINE\\", StringComparison.OrdinalIgnoreCase) || path.StartsWith("HKLM\\", StringComparison.OrdinalIgnoreCase);

    private static bool IsHkcu(string path) =>
        path.StartsWith("HKEY_CURRENT_USER\\", StringComparison.OrdinalIgnoreCase) || path.StartsWith("HKCU\\", StringComparison.OrdinalIgnoreCase);

    private static string BuildOmaUri(string regPath, string valueName, bool isHklm)
    {
        // Strip hive prefix
        string keyPath = regPath;
        if (keyPath.StartsWith("HKEY_LOCAL_MACHINE\\", StringComparison.OrdinalIgnoreCase))
            keyPath = keyPath["HKEY_LOCAL_MACHINE\\".Length..];
        else if (keyPath.StartsWith("HKLM\\", StringComparison.OrdinalIgnoreCase))
            keyPath = keyPath["HKLM\\".Length..];
        else if (keyPath.StartsWith("HKEY_CURRENT_USER\\", StringComparison.OrdinalIgnoreCase))
            keyPath = keyPath["HKEY_CURRENT_USER\\".Length..];
        else if (keyPath.StartsWith("HKCU\\", StringComparison.OrdinalIgnoreCase))
            keyPath = keyPath["HKCU\\".Length..];

        // Convert backslashes to forward slashes
        keyPath = keyPath.Replace('\\', '/');

        string prefix = isHklm ? "./Device/Vendor/MSFT/Registry/HKLM" : "./User/Vendor/MSFT/Registry/HKCU";

        return $"{prefix}/{keyPath}/{valueName}";
    }

    private static (string DataType, string Value) MapValue(RegOp op) =>
        op.ValueKind switch
        {
            RegistryValueKind.DWord => ("Integer", Convert.ToInt32(op.Value).ToString()),
            RegistryValueKind.QWord => ("Integer", Convert.ToInt64(op.Value).ToString()),
            RegistryValueKind.String => ("String", op.Value as string ?? ""),
            RegistryValueKind.ExpandString => ("String", op.Value as string ?? ""),
            _ => ("String", ""),
        };
}
