// RegiLattice.Core — Services/PolicyExporter.cs
// Policy export utilities merged from IntuneOmaUriExporter.cs and GroupPolicyExporter.cs.
// Exports tweaks as Intune OMA-URI JSON or Group Policy ADMX/ADML templates.

using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Xml;
using Microsoft.Win32;
using RegiLattice.Core.Models;

namespace RegiLattice.Core;

// ── Intune OMA-URI Export ──────────────────────────────────────────────────

/// <summary>A single OMA-URI setting for an Intune Custom Configuration policy.</summary>
public sealed class OmaUriSetting
{
    [JsonPropertyName("tweakId")]
    public required string TweakId { get; init; }

    [JsonPropertyName("label")]
    public required string Label { get; init; }

    [JsonPropertyName("category")]
    public required string Category { get; init; }

    [JsonPropertyName("omaUri")]
    public required string OmaUri { get; init; }

    [JsonPropertyName("dataType")]
    public required string DataType { get; init; }

    [JsonPropertyName("value")]
    public required string Value { get; init; }

    [JsonPropertyName("description")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Description { get; init; }
}

/// <summary>A tweak that could not be mapped to an OMA-URI.</summary>
public sealed class UnmappedTweak
{
    [JsonPropertyName("tweakId")]
    public required string TweakId { get; init; }

    [JsonPropertyName("label")]
    public required string Label { get; init; }

    [JsonPropertyName("kind")]
    public required string Kind { get; init; }

    [JsonPropertyName("reason")]
    public required string Reason { get; init; }
}

/// <summary>Root object written to the exported Intune JSON file.</summary>
public sealed class IntuneExportDocument
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = "RegiLattice Custom Configuration";

    [JsonPropertyName("description")]
    public string Description { get; init; } = "Generated by RegiLattice";

    [JsonPropertyName("exportedAt")]
    public string ExportedAt { get; init; } = DateTime.UtcNow.ToString("O");

    [JsonPropertyName("generator")]
    public string Generator { get; init; } = "RegiLattice";

    [JsonPropertyName("settings")]
    public required IReadOnlyList<OmaUriSetting> Settings { get; init; }

    [JsonPropertyName("unmappedTweaks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public IReadOnlyList<UnmappedTweak>? UnmappedTweaks { get; init; }

    [JsonIgnore]
    public int MappedCount => Settings.Count;

    [JsonIgnore]
    public int UnmappedCount => UnmappedTweaks?.Count ?? 0;
}

/// <summary>
/// Exports Registry-kind tweaks as OMA-URI JSON for Microsoft Intune Custom Configuration.
/// </summary>
public static class IntuneOmaUriExporter
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true, Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    /// <summary>Builds the export document without writing to disk.</summary>
    public static IntuneExportDocument Build(TweakEngine engine, bool machineOnly = true)
    {
        ArgumentNullException.ThrowIfNull(engine);

        var settings = new List<OmaUriSetting>();
        var unmapped = new List<UnmappedTweak>();

        foreach (TweakDef td in engine.AllTweaks())
        {
            if (!td.HasOperations)
                continue;

            if (td.Kind != TweakKind.Registry && td.Kind != TweakKind.GroupPolicy)
            {
                unmapped.Add(
                    new UnmappedTweak
                    {
                        TweakId = td.Id,
                        Label = td.Label,
                        Kind = td.Kind.ToString(),
                        Reason = $"TweakKind is {td.Kind}; only Registry and GroupPolicy tweaks are OMA-URI mappable.",
                    }
                );
                continue;
            }

            var mapped = MapTweakOps(td, machineOnly);
            if (mapped.Count > 0)
                settings.AddRange(mapped);
            else
                unmapped.Add(
                    new UnmappedTweak
                    {
                        TweakId = td.Id,
                        Label = td.Label,
                        Kind = "Registry",
                        Reason = machineOnly
                            ? "No HKLM ApplyOps with supported value kinds (DWORD/QWORD/REG_SZ/REG_EXPAND_SZ)."
                            : "No ApplyOps with supported value kinds (DWORD/QWORD/REG_SZ/REG_EXPAND_SZ).",
                    }
                );
        }

        return new IntuneExportDocument { Settings = settings, UnmappedTweaks = unmapped.Count > 0 ? unmapped : null };
    }

    /// <summary>Exports all mappable tweaks to <paramref name="outputPath"/> as pretty-printed JSON.</summary>
    public static void Export(TweakEngine engine, string outputPath, bool machineOnly = true)
    {
        ArgumentNullException.ThrowIfNull(engine);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputPath);

        var doc = Build(engine, machineOnly);
        File.WriteAllText(outputPath, JsonSerializer.Serialize(doc, JsonOptions), System.Text.Encoding.UTF8);
    }

    private static IReadOnlyList<OmaUriSetting> MapTweakOps(TweakDef td, bool machineOnly)
    {
        var result = new List<OmaUriSetting>();
        foreach (RegOp op in td.ApplyOps)
        {
            if (op.Kind != RegOpKind.SetValue)
                continue;

            bool isHklm =
                op.Path.StartsWith("HKEY_LOCAL_MACHINE\\", StringComparison.OrdinalIgnoreCase)
                || op.Path.StartsWith("HKLM\\", StringComparison.OrdinalIgnoreCase);
            bool isHkcu =
                op.Path.StartsWith("HKEY_CURRENT_USER\\", StringComparison.OrdinalIgnoreCase)
                || op.Path.StartsWith("HKCU\\", StringComparison.OrdinalIgnoreCase);

            if (machineOnly && !isHklm)
                continue;
            if (!isHklm && !isHkcu)
                continue;

            if (
                op.ValueKind is not (RegistryValueKind.DWord or RegistryValueKind.QWord or RegistryValueKind.String or RegistryValueKind.ExpandString)
            )
                continue;

            string omaUri = BuildOmaUri(op.Path, op.Name, isHklm);
            (string dataType, string value) = op.ValueKind switch
            {
                RegistryValueKind.DWord => ("Integer", Convert.ToInt32(op.Value).ToString()),
                RegistryValueKind.QWord => ("Integer", Convert.ToInt64(op.Value).ToString()),
                RegistryValueKind.String => ("String", op.Value as string ?? ""),
                RegistryValueKind.ExpandString => ("String", op.Value as string ?? ""),
                _ => ("String", ""),
            };

            result.Add(
                new OmaUriSetting
                {
                    TweakId = td.Id,
                    Label = td.Label,
                    Category = td.Category,
                    OmaUri = omaUri,
                    DataType = dataType,
                    Value = value,
                    Description = td.Description.Length is > 0 and <= 120 ? td.Description : null,
                }
            );
        }
        return result;
    }

    private static string BuildOmaUri(string regPath, string valueName, bool isHklm)
    {
        string keyPath = regPath;
        if (keyPath.StartsWith("HKEY_LOCAL_MACHINE\\", StringComparison.OrdinalIgnoreCase))
            keyPath = keyPath["HKEY_LOCAL_MACHINE\\".Length..];
        else if (keyPath.StartsWith("HKLM\\", StringComparison.OrdinalIgnoreCase))
            keyPath = keyPath["HKLM\\".Length..];
        else if (keyPath.StartsWith("HKEY_CURRENT_USER\\", StringComparison.OrdinalIgnoreCase))
            keyPath = keyPath["HKEY_CURRENT_USER\\".Length..];
        else if (keyPath.StartsWith("HKCU\\", StringComparison.OrdinalIgnoreCase))
            keyPath = keyPath["HKCU\\".Length..];

        keyPath = keyPath.Replace('\\', '/');
        string prefix = isHklm ? "./Device/Vendor/MSFT/Registry/HKLM" : "./User/Vendor/MSFT/Registry/HKCU";
        return $"{prefix}/{keyPath}/{valueName}";
    }
}

// ── Group Policy ADMX/ADML Export ──────────────────────────────────────────

/// <summary>
/// Generates an .admx Group Policy administrative template and a matching .adml string table
/// from the <c>GroupPolicy</c>-kind tweaks registered in a <see cref="TweakEngine"/>.
/// </summary>
public static class GroupPolicyExporter
{
    private const string Namespace = "RegiLattice";
    private const string DisplayName = "RegiLattice Tweaks";
    private const string SchemaVersion = "1.192";

    /// <summary>
    /// Exports all <see cref="TweakKind.GroupPolicy"/> tweaks to <paramref name="admxPath"/>.
    /// Creates a companion <em>.adml</em> file in the same directory.
    /// </summary>
    public static void Export(TweakEngine engine, string admxPath)
    {
        ArgumentNullException.ThrowIfNull(engine);
        ArgumentException.ThrowIfNullOrWhiteSpace(admxPath);

        var gpoTweaks = engine
            .AllTweaks()
            .Where(t => t.Kind == TweakKind.GroupPolicy && t.ApplyOps.Count > 0)
            .OrderBy(t => t.Category)
            .ThenBy(t => t.Label)
            .ToList();

        var admlDir = Path.Combine(Path.GetDirectoryName(admxPath) ?? ".", "en-US");
        Directory.CreateDirectory(admlDir);

        File.WriteAllText(admxPath, BuildAdmx(gpoTweaks), Encoding.UTF8);
        File.WriteAllText(Path.Combine(admlDir, Path.ChangeExtension(Path.GetFileName(admxPath), ".adml")), BuildAdml(gpoTweaks), Encoding.UTF8);
    }

    private static string BuildAdmx(IReadOnlyList<TweakDef> tweaks)
    {
        var sb = new StringBuilder();
        using var w = XmlWriter.Create(
            sb,
            new XmlWriterSettings
            {
                Indent = true,
                Encoding = Encoding.UTF8,
                OmitXmlDeclaration = false,
            }
        );

        w.WriteStartDocument();
        w.WriteStartElement("policyDefinitions", "http://schemas.microsoft.com/GroupPolicy/2006/07/PolicyDefinitions");
        w.WriteAttributeString("revision", "1.0");
        w.WriteAttributeString("schemaVersion", SchemaVersion);

        w.WriteStartElement("policyNamespaces");
        w.WriteStartElement("target");
        w.WriteAttributeString("prefix", Namespace);
        w.WriteAttributeString("namespace", $"Microsoft.Policies.{Namespace}");
        w.WriteEndElement();
        w.WriteEndElement();

        w.WriteStartElement("resources");
        w.WriteAttributeString("minRequiredRevision", "1.0");
        w.WriteEndElement();

        var categories = tweaks.Select(t => t.Category).Distinct().OrderBy(c => c).ToList();
        w.WriteStartElement("categories");
        w.WriteStartElement("category");
        w.WriteAttributeString("name", $"{Namespace}::{Namespace}");
        w.WriteStartElement("parentCategory");
        w.WriteAttributeString("ref", "windows:WindowsComponents");
        w.WriteEndElement();
        w.WriteEndElement();
        foreach (var cat in categories)
        {
            w.WriteStartElement("category");
            w.WriteAttributeString("name", $"{Namespace}::{Sanitize(cat)}");
            w.WriteStartElement("parentCategory");
            w.WriteAttributeString("ref", $"{Namespace}::{Namespace}");
            w.WriteEndElement();
            w.WriteEndElement();
        }
        w.WriteEndElement();

        w.WriteStartElement("policies");
        foreach (var tw in tweaks)
        {
            var firstOp = tw.ApplyOps[0];
            w.WriteStartElement("policy");
            w.WriteAttributeString("name", $"{Namespace}::{Sanitize(tw.Id)}");
            w.WriteAttributeString("class", "Machine");
            w.WriteAttributeString("displayName", $"$(string.{Sanitize(tw.Id)}_Name)");
            w.WriteAttributeString("explainText", $"$(string.{Sanitize(tw.Id)}_Help)");
            w.WriteAttributeString("key", firstOp.Path);
            w.WriteStartElement("parentCategory");
            w.WriteAttributeString("ref", $"{Namespace}::{Sanitize(tw.Category)}");
            w.WriteEndElement();
            w.WriteStartElement("supportedOn");
            w.WriteAttributeString("ref", "windows:SUPPORTED_WIN10");
            w.WriteEndElement();
            w.WriteEndElement();
        }
        w.WriteEndElement();
        w.WriteEndElement();
        w.WriteEndDocument();
        w.Flush();
        return sb.ToString();
    }

    private static string BuildAdml(IReadOnlyList<TweakDef> tweaks)
    {
        var sb = new StringBuilder();
        using var w = XmlWriter.Create(
            sb,
            new XmlWriterSettings
            {
                Indent = true,
                Encoding = Encoding.UTF8,
                OmitXmlDeclaration = false,
            }
        );

        w.WriteStartDocument();
        w.WriteStartElement("policyDefinitionResources", "http://schemas.microsoft.com/GroupPolicy/2006/07/PolicyDefinitions");
        w.WriteAttributeString("revision", "1.0");
        w.WriteAttributeString("schemaVersion", SchemaVersion);
        w.WriteStartElement("displayName");
        w.WriteString(DisplayName);
        w.WriteEndElement();
        w.WriteStartElement("description");
        w.WriteString($"Group Policy definitions generated by RegiLattice ({tweaks.Count} policies).");
        w.WriteEndElement();
        w.WriteStartElement("resources");
        w.WriteStartElement("stringTable");

        w.WriteStartElement("string");
        w.WriteAttributeString("id", $"{Namespace}_{Namespace}");
        w.WriteString(DisplayName);
        w.WriteEndElement();

        foreach (var cat in tweaks.Select(t => t.Category).Distinct().OrderBy(c => c))
        {
            w.WriteStartElement("string");
            w.WriteAttributeString("id", $"{Namespace}_{Sanitize(cat)}_Category");
            w.WriteString(cat);
            w.WriteEndElement();
        }

        foreach (var tw in tweaks)
        {
            var safe = Sanitize(tw.Id);
            w.WriteStartElement("string");
            w.WriteAttributeString("id", $"{safe}_Name");
            w.WriteString(tw.Label);
            w.WriteEndElement();
            w.WriteStartElement("string");
            w.WriteAttributeString("id", $"{safe}_Help");
            w.WriteString(string.IsNullOrWhiteSpace(tw.Description) ? tw.Label : tw.Description);
            w.WriteEndElement();
        }

        w.WriteEndElement();
        w.WriteEndElement();
        w.WriteEndElement();
        w.WriteEndDocument();
        w.Flush();
        return sb.ToString();
    }

    private static string Sanitize(string s) => System.Text.RegularExpressions.Regex.Replace(s, @"[^A-Za-z0-9_]", "_");
}

// ── Ansible win_regedit Export ─────────────────────────────────────────────

/// <summary>
/// Generates an Ansible <c>win_regedit</c> task-list YAML playbook
/// for all Registry and GroupPolicy-kind tweaks.
/// </summary>
public static class AnsibleExporter
{
    /// <summary>Builds the Ansible YAML playbook content (returns string, does not write to disk).</summary>
    public static string Build(TweakEngine engine)
    {
        ArgumentNullException.ThrowIfNull(engine);

        var sb = new StringBuilder();
        sb.AppendLine("---");
        sb.AppendLine("# Generated by RegiLattice — Ansible win_regedit tasks");
        sb.AppendLine($"# Exported: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("- name: Apply RegiLattice registry tweaks");
        sb.AppendLine("  hosts: windows");
        sb.AppendLine("  gather_facts: false");
        sb.AppendLine("  tasks:");

        foreach (TweakDef td in engine.AllTweaks())
        {
            if (td.Kind != TweakKind.Registry && td.Kind != TweakKind.GroupPolicy)
                continue;
            foreach (RegOp op in td.ApplyOps)
            {
                if (op.Kind != RegOpKind.SetValue)
                    continue;
                sb.AppendLine();
                sb.AppendLine($"    - name: \"{EscapeYaml(td.Label)}\"");
                sb.AppendLine($"      ansible.windows.win_regedit:");
                sb.AppendLine($"        path: {NormPath(op.Path)}");
                sb.AppendLine($"        name: \"{op.Name}\"");
                sb.AppendLine($"        data: {FormatAnsibleValue(op.Value, op.ValueKind)}");
                sb.AppendLine($"        type: {KindToAnsible(op.ValueKind)}");
                sb.AppendLine($"        state: present");
            }
        }
        return sb.ToString();
    }

    /// <summary>Exports tweaks to <paramref name="outputPath"/> as Ansible YAML.</summary>
    public static void Export(TweakEngine engine, string outputPath)
    {
        ArgumentNullException.ThrowIfNull(engine);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputPath);
        File.WriteAllText(outputPath, Build(engine), Encoding.UTF8);
    }

    private static string NormPath(string path)
    {
        if (path.StartsWith("HKEY_LOCAL_MACHINE\\", StringComparison.OrdinalIgnoreCase))
            return $"'HKLM:\\{path["HKEY_LOCAL_MACHINE\\".Length..]}'";
        if (path.StartsWith("HKLM\\", StringComparison.OrdinalIgnoreCase))
            return $"'HKLM:\\{path["HKLM\\".Length..]}'";
        if (path.StartsWith("HKEY_CURRENT_USER\\", StringComparison.OrdinalIgnoreCase))
            return $"'HKCU:\\{path["HKEY_CURRENT_USER\\".Length..]}'";
        if (path.StartsWith("HKCU\\", StringComparison.OrdinalIgnoreCase))
            return $"'HKCU:\\{path["HKCU\\".Length..]}'";
        return $"'{path}'";
    }

    private static string KindToAnsible(RegistryValueKind kind) =>
        kind switch
        {
            RegistryValueKind.DWord => "dword",
            RegistryValueKind.QWord => "qword",
            RegistryValueKind.String => "string",
            RegistryValueKind.ExpandString => "expandstring",
            RegistryValueKind.MultiString => "multistring",
            RegistryValueKind.Binary => "binary",
            _ => "string",
        };

    private static string FormatAnsibleValue(object? v, RegistryValueKind kind) =>
        kind switch
        {
            RegistryValueKind.DWord => Convert.ToInt32(v).ToString(),
            RegistryValueKind.QWord => Convert.ToInt64(v).ToString(),
            RegistryValueKind.Binary => v is byte[] b ? Convert.ToHexString(b).ToLowerInvariant() : "00",
            _ => $"\"{EscapeYaml(v?.ToString() ?? "")}\"",
        };

    private static string EscapeYaml(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

// ── PowerShell DSC Export ──────────────────────────────────────────────────

/// <summary>
/// Generates a PowerShell Desired State Configuration <c>.ps1</c> file using
/// <c>PSDscResources\Registry</c> resources for Registry and GroupPolicy-kind tweaks.
/// </summary>
public static class DscExporter
{
    /// <summary>Builds the DSC <c>.ps1</c> script content (returns string, does not write to disk).</summary>
    public static string Build(TweakEngine engine, string configName = "RegiLatticeConfig")
    {
        ArgumentNullException.ThrowIfNull(engine);
        if (string.IsNullOrWhiteSpace(configName))
            configName = "RegiLatticeConfig";

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by RegiLattice — PowerShell DSC Configuration");
        sb.AppendLine($"# Exported: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("# Requires: Install-Module PSDscResources");
        sb.AppendLine();
        sb.AppendLine($"Configuration {configName}");
        sb.AppendLine("{");
        sb.AppendLine("    Import-DscResource -ModuleName PSDscResources");
        sb.AppendLine();
        sb.AppendLine("    Node localhost");
        sb.AppendLine("    {");

        int idx = 0;
        foreach (TweakDef td in engine.AllTweaks())
        {
            if (td.Kind != TweakKind.Registry && td.Kind != TweakKind.GroupPolicy)
                continue;
            foreach (RegOp op in td.ApplyOps)
            {
                if (op.Kind != RegOpKind.SetValue)
                    continue;
                idx++;
                string res = DscResName(td.Id, idx);
                sb.AppendLine($"        Registry {res}");
                sb.AppendLine("        {");
                sb.AppendLine($"            Key       = '{NormPath(op.Path)}'");
                sb.AppendLine($"            ValueName = '{op.Name}'");
                sb.AppendLine($"            ValueData = {DscValue(op.Value, op.ValueKind)}");
                sb.AppendLine($"            ValueType = '{KindToDsc(op.ValueKind)}'");
                sb.AppendLine($"            Ensure    = 'Present'");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"{configName} -OutputPath .\\{configName}");
        return sb.ToString();
    }

    /// <summary>Exports tweaks to <paramref name="outputPath"/> as a DSC <c>.ps1</c> script.</summary>
    public static void Export(TweakEngine engine, string outputPath, string configName = "RegiLatticeConfig")
    {
        ArgumentNullException.ThrowIfNull(engine);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputPath);
        File.WriteAllText(outputPath, Build(engine, configName), Encoding.UTF8);
    }

    private static string NormPath(string path)
    {
        if (path.StartsWith("HKEY_LOCAL_MACHINE\\", StringComparison.OrdinalIgnoreCase))
            return $"HKLM:\\{path["HKEY_LOCAL_MACHINE\\".Length..]}";
        if (path.StartsWith("HKLM\\", StringComparison.OrdinalIgnoreCase))
            return $"HKLM:\\{path["HKLM\\".Length..]}";
        if (path.StartsWith("HKEY_CURRENT_USER\\", StringComparison.OrdinalIgnoreCase))
            return $"HKCU:\\{path["HKEY_CURRENT_USER\\".Length..]}";
        if (path.StartsWith("HKCU\\", StringComparison.OrdinalIgnoreCase))
            return $"HKCU:\\{path["HKCU\\".Length..]}";
        return path;
    }

    private static string KindToDsc(RegistryValueKind kind) =>
        kind switch
        {
            RegistryValueKind.DWord => "Dword",
            RegistryValueKind.QWord => "Qword",
            RegistryValueKind.String => "String",
            RegistryValueKind.ExpandString => "ExpandString",
            RegistryValueKind.MultiString => "MultiString",
            RegistryValueKind.Binary => "Binary",
            _ => "String",
        };

    private static string DscValue(object? v, RegistryValueKind kind) =>
        kind switch
        {
            RegistryValueKind.DWord => $"'{Convert.ToInt32(v)}'",
            RegistryValueKind.QWord => $"'{Convert.ToInt64(v)}'",
            RegistryValueKind.Binary => v is byte[] b ? $"'{Convert.ToHexString(b).ToLowerInvariant()}'" : "'00'",
            _ => $"'{(v?.ToString() ?? "").Replace("'", "''")}'",
        };

    private static string DscResName(string id, int idx)
    {
        string name = System.Text.RegularExpressions.Regex.Replace(id, @"[^A-Za-z0-9_]", "_");
        return $"{name}_{idx}";
    }
}
