// RegiLattice.Core — Services/PowerShellModuleGenerator.cs
// Generates a PowerShell module (.psd1 manifest + .psm1 implementation) that wraps
// the Core library, providing Get-Tweak, Get-TweakStatus, Apply-Tweak, Remove-Tweak,
// Get-HealthScore, Get-TweakProfile, Search-Tweak, and related cmdlets.
// Sprint 70 — Phase D1.

using System;
using System.IO;

namespace RegiLattice.Core.Services;

/// <summary>
/// Generates a PowerShell module that wraps RegiLattice.Core.
/// The emitted .psm1 loads the Core DLL via Add-Type and surfaces all
/// TweakEngine operations as standard PowerShell cmdlets.
/// </summary>
public static class PowerShellModuleGenerator
{
    private const string ModuleName = "RegiLattice";
    private const string ModuleVersion = "4.3.0";
    private const string CorePathToken = "CORE_PATH_PLACEHOLDER";

    /// <summary>
    /// Write <c>RegiLattice.psd1</c> and <c>RegiLattice.psm1</c> to <paramref name="outputDirectory"/>.
    /// </summary>
    public static void Generate(string outputDirectory, string coreAssemblyPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(outputDirectory);
        ArgumentException.ThrowIfNullOrWhiteSpace(coreAssemblyPath);

        Directory.CreateDirectory(outputDirectory);
        File.WriteAllText(Path.Combine(outputDirectory, $"{ModuleName}.psd1"), BuildManifest());
        File.WriteAllText(Path.Combine(outputDirectory, $"{ModuleName}.psm1"), BuildScript(coreAssemblyPath));
    }

    /// <summary>Returns the PowerShell module manifest (.psd1) content as a string.</summary>
    public static string BuildManifest()
    {
        return _manifestTemplate.Replace("MODULE_VERSION_PLACEHOLDER", ModuleVersion).Replace("MODULE_NAME_PLACEHOLDER", ModuleName);
    }

    /// <summary>Returns the PowerShell module implementation (.psm1) content as a string.</summary>
    public static string BuildScript(string coreAssemblyPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(coreAssemblyPath);
        var safePath = coreAssemblyPath.Replace("'", "''");
        return _psm1Template.Replace(CorePathToken, safePath);
    }

    // ── Non-interpolated raw string templates ────────────────────────────────
    // Using plain raw strings so PowerShell $variables and { braces } are literal.
    // C# substitution is done via .Replace() on named tokens.

    private static readonly string _manifestTemplate = """
        @{
            ModuleVersion     = 'MODULE_VERSION_PLACEHOLDER'
            GUID              = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
            Author            = 'RajwanYair'
            CompanyName       = 'RegiLattice'
            Description       = 'Windows 11 registry tweak management via PowerShell. Wraps RegiLattice.Core.'
            PowerShellVersion = '7.0'
            RootModule        = 'MODULE_NAME_PLACEHOLDER.psm1'
            FunctionsToExport = @(
                'Get-Tweak',
                'Search-Tweak',
                'Get-TweakStatus',
                'Get-TweakCategory',
                'Apply-Tweak',
                'Remove-Tweak',
                'Get-TweakProfile',
                'Apply-TweakProfile',
                'Get-HealthScore',
                'Export-TweakSelection',
                'Import-TweakSelection'
            )
            CmdletsToExport   = @()
            AliasesToExport   = @()
            Tags              = @('Windows', 'Registry', 'Tweaks', 'Optimization', 'Privacy', 'Security')
            ProjectUri        = 'https://github.com/RajwanYair/RegiLattice'
            LicenseUri        = 'https://github.com/RajwanYair/RegiLattice/blob/main/LICENSE'
        }
        """;

    private static readonly string _psm1Template = """
        # RegiLattice.psm1 — Auto-generated by RegiLattice.Core.Services.PowerShellModuleGenerator
        # DO NOT EDIT MANUALLY. Regenerate with: regilattice --generate-ps-module

        [CmdletBinding()]
        param()

        Set-StrictMode -Version Latest

        # ── Load Core DLL ──────────────────────────────────────────────────────
        $script:CorePath = 'CORE_PATH_PLACEHOLDER'
        if (-not (Test-Path $script:CorePath)) {
            throw "RegiLattice.Core.dll not found at '$script:CorePath'. Re-run with correct path."
        }
        Add-Type -Path $script:CorePath -ErrorAction Stop

        # ── Shared engine singleton ──────────────────────────────────────────
        $script:Engine = $null

        function Get-Engine {
            if ($null -eq $script:Engine) {
                $script:Engine = [RegiLattice.Core.TweakEngine]::new()
                $script:Engine.RegisterBuiltins()
            }
            return $script:Engine
        }

        # ──────────────────────────────────────────────────────────────────────
        # Get-Tweak
        # ──────────────────────────────────────────────────────────────────────
        function Get-Tweak {
            <#
            .SYNOPSIS
                Retrieve one or all RegiLattice tweaks.
            .PARAMETER Id
                The tweak ID (e.g. priv-disable-telemetry). If omitted, returns all tweaks.
            .PARAMETER Category
                Filter by category name (partial, case-insensitive).
            .EXAMPLE
                Get-Tweak -Id priv-disable-telemetry
            .EXAMPLE
                Get-Tweak -Category Privacy
            #>
            [CmdletBinding()]
            param(
                [Parameter(Position = 0, ValueFromPipeline, ValueFromPipelineByPropertyName)]
                [string] $Id,

                [string] $Category
            )
            $engine = Get-Engine
            if ($Id) {
                $t = $engine.GetTweak($Id)
                if ($null -eq $t) { Write-Error "Tweak '$Id' not found."; return }
                return $t
            }
            $all = $engine.AllTweaks()
            if ($Category) { $all = $all | Where-Object { $_.Category -match $Category } }
            return $all
        }

        # ──────────────────────────────────────────────────────────────────────
        # Search-Tweak
        # ──────────────────────────────────────────────────────────────────────
        function Search-Tweak {
            <#
            .SYNOPSIS
                Full-text search across tweak labels, descriptions, and tags.
            .PARAMETER Query
                Search query (supports NLP synonym expansion).
            .EXAMPLE
                Search-Tweak -Query "disable telemetry"
            #>
            [CmdletBinding()]
            param(
                [Parameter(Mandatory, Position = 0)]
                [string] $Query
            )
            $engine = Get-Engine
            return $engine.Search($Query)
        }

        # ──────────────────────────────────────────────────────────────────────
        # Get-TweakStatus
        # ──────────────────────────────────────────────────────────────────────
        function Get-TweakStatus {
            <#
            .SYNOPSIS
                Check whether a tweak is currently applied or not.
            .PARAMETER Id
                Tweak ID. Accepts pipeline input.
            .EXAMPLE
                Get-TweakStatus -Id priv-disable-telemetry
            .EXAMPLE
                Get-Tweak -Category Privacy | Get-TweakStatus
            #>
            [CmdletBinding()]
            param(
                [Parameter(Mandatory, Position = 0, ValueFromPipeline, ValueFromPipelineByPropertyName)]
                [string] $Id
            )
            process {
                $engine = Get-Engine
                $t = $engine.GetTweak($Id)
                if ($null -eq $t) { Write-Error "Tweak '$Id' not found."; return }
                $status = $engine.DetectStatus($t)
                [PSCustomObject]@{ Id = $Id; Status = $status.ToString(); Label = $t.Label }
            }
        }

        # ──────────────────────────────────────────────────────────────────────
        # Get-TweakCategory
        # ──────────────────────────────────────────────────────────────────────
        function Get-TweakCategory {
            <#
            .SYNOPSIS
                List all tweak categories.
            #>
            [CmdletBinding()]
            param()
            $engine = Get-Engine
            return $engine.Categories()
        }

        # ──────────────────────────────────────────────────────────────────────
        # Apply-Tweak
        # ──────────────────────────────────────────────────────────────────────
        function Apply-Tweak {
            <#
            .SYNOPSIS
                Apply (enable) a registry tweak. Requires Administrator.
            .PARAMETER Id
                Tweak ID.
            .PARAMETER DryRun
                Preview without writing to registry.
            .PARAMETER Force
                Override Corporate Guard check.
            .EXAMPLE
                Apply-Tweak -Id priv-disable-telemetry -WhatIf
            #>
            [CmdletBinding(SupportsShouldProcess)]
            param(
                [Parameter(Mandatory, Position = 0, ValueFromPipeline, ValueFromPipelineByPropertyName)]
                [string] $Id,

                [switch] $DryRun,
                [switch] $Force
            )
            process {
                $engine = Get-Engine
                $t = $engine.GetTweak($Id)
                if ($null -eq $t) { Write-Error "Tweak '$Id' not found."; return }

                if ($PSCmdlet.ShouldProcess($Id, "Apply tweak '$($t.Label)'")) {
                    $result = $engine.Apply($t, $DryRun.IsPresent, $Force.IsPresent)
                    [PSCustomObject]@{ Id = $Id; Result = $result.ToString(); Label = $t.Label }
                }
            }
        }

        # ──────────────────────────────────────────────────────────────────────
        # Remove-Tweak
        # ──────────────────────────────────────────────────────────────────────
        function Remove-Tweak {
            <#
            .SYNOPSIS
                Remove (revert) an applied registry tweak. Requires Administrator.
            .PARAMETER Id
                Tweak ID.
            .PARAMETER DryRun
                Preview without writing to registry.
            .EXAMPLE
                Remove-Tweak -Id priv-disable-telemetry
            #>
            [CmdletBinding(SupportsShouldProcess)]
            param(
                [Parameter(Mandatory, Position = 0, ValueFromPipeline, ValueFromPipelineByPropertyName)]
                [string] $Id,

                [switch] $DryRun
            )
            process {
                $engine = Get-Engine
                $t = $engine.GetTweak($Id)
                if ($null -eq $t) { Write-Error "Tweak '$Id' not found."; return }

                if ($PSCmdlet.ShouldProcess($Id, "Remove tweak '$($t.Label)'")) {
                    $result = $engine.Remove($t, $DryRun.IsPresent)
                    [PSCustomObject]@{ Id = $Id; Result = $result.ToString(); Label = $t.Label }
                }
            }
        }

        # ──────────────────────────────────────────────────────────────────────
        # Get-TweakProfile
        # ──────────────────────────────────────────────────────────────────────
        function Get-TweakProfile {
            <#
            .SYNOPSIS
                List available built-in profiles or get tweaks for a specific profile.
            .PARAMETER Name
                Profile name: business, gaming, privacy, minimal, server.
            #>
            [CmdletBinding()]
            param(
                [Parameter(Position = 0)]
                [string] $Name
            )
            $engine = Get-Engine
            if ($Name) {
                $p = $engine.GetProfile($Name)
                if ($null -eq $p) { Write-Error "Profile '$Name' not found."; return }
                return $engine.TweaksForProfile($p)
            }
            return $engine.Profiles
        }

        # ──────────────────────────────────────────────────────────────────────
        # Apply-TweakProfile
        # ──────────────────────────────────────────────────────────────────────
        function Apply-TweakProfile {
            <#
            .SYNOPSIS
                Apply all tweaks in a built-in profile.
            .PARAMETER Name
                Profile name: business, gaming, privacy, minimal, server.
            .PARAMETER DryRun
                Preview without writing to registry.
            .EXAMPLE
                Apply-TweakProfile -Name privacy -WhatIf
            #>
            [CmdletBinding(SupportsShouldProcess)]
            param(
                [Parameter(Mandatory, Position = 0)]
                [string] $Name,

                [switch] $DryRun,
                [switch] $Force
            )
            $engine = Get-Engine
            $p = $engine.GetProfile($Name)
            if ($null -eq $p) { Write-Error "Profile '$Name' not found."; return }

            if ($PSCmdlet.ShouldProcess($Name, "Apply profile '$Name'")) {
                $results = $engine.ApplyProfile($p, $DryRun.IsPresent, $Force.IsPresent)
                $results | ForEach-Object { [PSCustomObject]@{ Id = $_.Key; Result = $_.Value.ToString() } }
            }
        }

        # ──────────────────────────────────────────────────────────────────────
        # Get-HealthScore
        # ──────────────────────────────────────────────────────────────────────
        function Get-HealthScore {
            <#
            .SYNOPSIS
                Compute the system health score across Privacy, Performance, Security, and Maintenance.
            .EXAMPLE
                Get-HealthScore
            #>
            [CmdletBinding()]
            param()
            try {
                $svc = [RegiLattice.Core.Services.HealthScoreService]::new((Get-Engine))
                $score = $svc.Compute()
                [PSCustomObject]@{
                    Overall     = $score.Overall
                    Privacy     = $score.Privacy
                    Performance = $score.Performance
                    Security    = $score.Security
                    Maintenance = $score.Maintenance
                    Grade       = $score.Grade
                }
            } catch {
                Write-Warning "HealthScoreService unavailable: $($_.Exception.Message)"
            }
        }

        # ──────────────────────────────────────────────────────────────────────
        # Export-TweakSelection
        # ──────────────────────────────────────────────────────────────────────
        function Export-TweakSelection {
            <#
            .SYNOPSIS
                Export a list of tweak IDs to a JSON file compatible with 'regilattice --import-json'.
            .PARAMETER Path
                Output file path.
            .PARAMETER Ids
                Array of tweak IDs to export.
            .EXAMPLE
                @('priv-disable-telemetry','perf-disable-animations') | Export-TweakSelection -Path .\my-tweaks.json
            #>
            [CmdletBinding()]
            param(
                [Parameter(Mandatory)]
                [string] $Path,

                [Parameter(Mandatory, ValueFromPipeline)]
                [string[]] $Ids
            )
            begin { $allIds = [System.Collections.Generic.List[string]]::new() }
            process { $allIds.AddRange($Ids) }
            end {
                $json = [System.Text.Json.JsonSerializer]::Serialize([string[]]$allIds)
                Set-Content -Path $Path -Value $json -Encoding UTF8
                Write-Verbose "Exported $($allIds.Count) tweak IDs to '$Path'."
            }
        }

        # ──────────────────────────────────────────────────────────────────────
        # Import-TweakSelection
        # ──────────────────────────────────────────────────────────────────────
        function Import-TweakSelection {
            <#
            .SYNOPSIS
                Import and apply a previously exported JSON tweak selection.
            .PARAMETER Path
                Path to JSON file produced by Export-TweakSelection.
            .PARAMETER DryRun
                Preview without writing to registry.
            .EXAMPLE
                Import-TweakSelection -Path .\my-tweaks.json -DryRun
            #>
            [CmdletBinding(SupportsShouldProcess)]
            param(
                [Parameter(Mandatory, Position = 0)]
                [string] $Path,

                [switch] $DryRun
            )
            if (-not (Test-Path $Path)) { Write-Error "File not found: '$Path'"; return }
            $json   = Get-Content -Path $Path -Raw -Encoding UTF8
            $ids    = [System.Text.Json.JsonSerializer]::Deserialize($json, [string[]])
            $engine = Get-Engine

            foreach ($id in $ids) {
                $t = $engine.GetTweak($id)
                if ($null -eq $t) { Write-Warning "Tweak '$id' not found, skipping."; continue }
                if ($PSCmdlet.ShouldProcess($id, "Apply tweak '$($t.Label)'")) {
                    $result = $engine.Apply($t, $DryRun.IsPresent, $false)
                    Write-Verbose "$id -> $($result.ToString())"
                }
            }
        }

        Export-ModuleMember -Function @(
            'Get-Tweak', 'Search-Tweak', 'Get-TweakStatus', 'Get-TweakCategory',
            'Apply-Tweak', 'Remove-Tweak', 'Get-TweakProfile', 'Apply-TweakProfile',
            'Get-HealthScore', 'Export-TweakSelection', 'Import-TweakSelection'
        )
        """;
}
