namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class AccountLockoutPolicy
{
    private const string LsaKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System";
    private const string WinlogonKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon";
    private const string LockoutKey = @"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\RemoteAccess\Parameters\AccountLockout";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "acctlkout-disable-last-username-display",
            Label = "Account Lockout Policy: Do Not Display Last Username at Logon",
            Category = "Account Lockout Policy",
            Description = "Prevents Windows from displaying the last signed-in username on the logon screen. Hiding the username forces an attacker to know both the username and password rather than just the password. Applies to both local logon and domain logon screens.",
            Tags = ["logon", "username", "lockout", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [WinlogonKey],
            ApplyOps = [RegOp.SetDword(WinlogonKey, "DontDisplayLastUserName", 1)],
            RemoveOps = [RegOp.DeleteValue(WinlogonKey, "DontDisplayLastUserName")],
            DetectOps = [RegOp.CheckDword(WinlogonKey, "DontDisplayLastUserName", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Hides last logged-in username; forces attacker to know both username and password.",
        },
        new TweakDef
        {
            Id = "acctlkout-require-ctrl-alt-del",
            Label = "Account Lockout Policy: Require Ctrl+Alt+Del Before Logon",
            Category = "Account Lockout Policy",
            Description = "Requires users to press Ctrl+Alt+Del before the logon screen appears. This secure attention sequence (SAS) ensures the logon dialog is presented by the Windows kernel rather than a user-mode trojan masquerading as the logon screen — a classic credential harvesting attack vector.",
            Tags = ["logon", "ctrl-alt-del", "secure attention sequence", "lockout", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [WinlogonKey],
            ApplyOps = [RegOp.SetDword(WinlogonKey, "DisableCAD", 0)],
            RemoveOps = [RegOp.DeleteValue(WinlogonKey, "DisableCAD")],
            DetectOps = [RegOp.CheckDword(WinlogonKey, "DisableCAD", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Enforces Ctrl+Alt+Del SAS to prevent credential-stealing logon spoof UIs.",
        },
        new TweakDef
        {
            Id = "acctlkout-restrict-blank-password-remote",
            Label = "Account Lockout Policy: Limit Blank Password Accounts to Console Logon",
            Category = "Account Lockout Policy",
            Description = "Prevents accounts with blank passwords from being used over network connections. Accounts without passwords may be used for local interactive logon only. This prevents blank-password accounts from being exploited remotely via SMB, RDP, or network services.",
            Tags = ["logon", "blank password", "network access", "lockout", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa", "LimitBlankPasswordUse", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa", "LimitBlankPasswordUse")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa", "LimitBlankPasswordUse", 1)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Blocks blank-password accounts from remote logins; local consoles remain unaffected.",
        },
        new TweakDef
        {
            Id = "acctlkout-disable-locked-account-message",
            Label = "Account Lockout Policy: Do Not Display Locked Account Message",
            Category = "Account Lockout Policy",
            Description = "Suppresses the message informing a user that their account is locked out. Showing a lockout message leaks information to an attacker performing a password-spray attack — confirming correct usernames. Hiding the message converts an unlocking error into a generic access denied.",
            Tags = ["logon", "lockout", "message", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [LsaKey],
            ApplyOps = [RegOp.SetDword(LsaKey, "DontDisplayLockedUserId", 3)],
            RemoveOps = [RegOp.DeleteValue(LsaKey, "DontDisplayLockedUserId")],
            DetectOps = [RegOp.CheckDword(LsaKey, "DontDisplayLockedUserId", 3)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Hides lockout confirmation from attackers doing password-spray attacks.",
        },
        new TweakDef
        {
            Id = "acctlkout-disable-automatic-admin-logon",
            Label = "Account Lockout Policy: Disable Automatic Administrator Logon",
            Category = "Account Lockout Policy",
            Description = "Clears the AutoAdminLogon registry value that enables Windows to log on automatically with saved administrator credentials. Autologon with elevated credentials bypasses all logon security and allows anyone with physical access to the machine to gain an admin session simply by rebooting.",
            Tags = ["logon", "autologon", "admin", "lockout", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [WinlogonKey],
            ApplyOps = [RegOp.SetString(WinlogonKey, "AutoAdminLogon", "0")],
            RemoveOps = [RegOp.DeleteValue(WinlogonKey, "AutoAdminLogon")],
            DetectOps = [RegOp.CheckString(WinlogonKey, "AutoAdminLogon", "0")],
            ImpactScore = 5,
            SafetyRating = 5,
            ImpactNote = "Disables auto-login; anyone who can reboot will not get an automatic admin session.",
        },
        new TweakDef
        {
            Id = "acctlkout-limit-ras-lockout-count",
            Label = "Account Lockout Policy: Limit RAS Account Lockout Attempts to 3",
            Category = "Account Lockout Policy",
            Description = "Sets the Remote Access Service (RAS/VPN) account lockout threshold to 3 failed authentication attempts. Without a RAS lockout threshold, attackers can brute-force VPN credentials indefinitely without triggering a local account lockout. Applies only to RAS/VPN dial-in connections.",
            Tags = ["ras", "vpn", "lockout", "brute force", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [LockoutKey],
            ApplyOps = [RegOp.SetDword(LockoutKey, "MaxDenials", 3)],
            RemoveOps = [RegOp.DeleteValue(LockoutKey, "MaxDenials")],
            DetectOps = [RegOp.CheckDword(LockoutKey, "MaxDenials", 3)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Blocks VPN brute-force by locking RAS accounts after 3 failed attempts.",
        },
        new TweakDef
        {
            Id = "acctlkout-set-ras-lockout-reset-interval",
            Label = "Account Lockout Policy: Set RAS Lockout Reset Interval to 60 Minutes",
            Category = "Account Lockout Policy",
            Description = "Configures the RAS account lockout observation window (reset interval) to 60 minutes. After a RAS account is locked due to too many failed authentication attempts, the failure counter is reset after 60 minutes without requiring administrative intervention.",
            Tags = ["ras", "vpn", "lockout", "reset", "interval", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [LockoutKey],
            ApplyOps = [RegOp.SetDword(LockoutKey, "ResetTime (mins)", 60)],
            RemoveOps = [RegOp.DeleteValue(LockoutKey, "ResetTime (mins)")],
            DetectOps = [RegOp.CheckDword(LockoutKey, "ResetTime (mins)", 60)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Auto-resets RAS lockout counter after 60 minutes without admin intervention.",
        },
        new TweakDef
        {
            Id = "acctlkout-disable-logon-hours-lock",
            Label = "Account Lockout Policy: Force Logoff When Logon Hours Expire",
            Category = "Account Lockout Policy",
            Description = "Configures Windows to disconnect users when their logon hours expire instead of allowing continued access. Without this setting, users who are already logged on continue working past their permitted logon window, defeating time-based access controls.",
            Tags = ["logon", "hours", "force logoff", "access control", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [LsaKey],
            ApplyOps = [RegOp.SetDword(LsaKey, "ForceUnlockLogon", 0)],
            RemoveOps = [RegOp.DeleteValue(LsaKey, "ForceUnlockLogon")],
            DetectOps = [RegOp.CheckDword(LsaKey, "ForceUnlockLogon", 0)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Enforces time-based access expiry; may disconnect users at scheduled hours.",
        },
        new TweakDef
        {
            Id = "acctlkout-disable-network-unlock-message",
            Label = "Account Lockout Policy: Hide Network Logon Username",
            Category = "Account Lockout Policy",
            Description = "Prevents Windows from pre-populating the username field on network authentication dialogs with the currently signed-in user account name. Pre-populated usernames expose account credentials to shoulder-surfing and reduce the security of multi-user environments.",
            Tags = ["logon", "network", "username", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [LsaKey],
            ApplyOps = [RegOp.SetDword(LsaKey, "DontDisplayNetworkSelectionUI", 1)],
            RemoveOps = [RegOp.DeleteValue(LsaKey, "DontDisplayNetworkSelectionUI")],
            DetectOps = [RegOp.CheckDword(LsaKey, "DontDisplayNetworkSelectionUI", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Hides username in network auth dialogs; reduces shoulder-surfing risk.",
        },
        new TweakDef
        {
            Id = "acctlkout-enable-inactive-account-shutdown",
            Label = "Account Lockout Policy: Require Password After Screen Saver Activation",
            Category = "Account Lockout Policy",
            Description = "Forces password re-entry when the screen saver activates. This ensures that an unattended workstation is effectively locked — any user returning must authenticate before accessing the desktop. Prevents tailgating attacks on unattended, logged-in workstations.",
            Tags = ["logon", "screen saver", "password", "inactive", "lock", "policy"],
            NeedsAdmin = false,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop", "ScreenSaverIsSecure", "1")],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop", "ScreenSaverIsSecure")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop", "ScreenSaverIsSecure", "1")],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Enforces password-on-resume from screen saver; prevents tailgating attacks.",
        },
    ];
}
