// RegiLattice.Core — Tweaks/AppReadinessPolicy.cs
// Sprint 287: App Readiness Policy tweaks (10 tweaks)
// Category: "App Readiness Policy" | Slug: apprdy
// Registry: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppReadiness

namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class AppReadinessPolicy
{
    private const string Key = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppReadiness";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "apprdy-disable-service",
            Label = "Disable App Readiness Service",
            Category = "App Readiness Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 4,
            Description =
                "The Windows App Readiness service prepares applications for first use after installation or user sign-in. Disabling this policy prevents the service from executing post-install configuration tasks during logon. This reduces CPU and I/O activity associated with first-run application setup, improving login responsiveness. The setting is most beneficial on enterprise systems with pre-configured application images. Consumer scenarios where users regularly install new Store applications may experience delayed first launches. No impact on application functionality once an application has completed its initial setup phase.",
            Tags = ["app-readiness", "startup", "performance", "policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "DisableAppReadiness", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "DisableAppReadiness")],
            DetectOps = [RegOp.CheckDword(Key, "DisableAppReadiness", 1)],
        },
        new TweakDef
        {
            Id = "apprdy-disable-logging",
            Label = "Disable App Readiness Logging",
            Category = "App Readiness Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            Description =
                "App Readiness diagnostic logging captures detailed information about application preparation activities to event logs. Disabling this policy suppresses verbose logging from the App Readiness subsystem, reducing event log volume. Log data generated by this service is rarely consulted in enterprise environments with stable application stacks. Suppressing these events reduces noise in operational monitoring dashboards and SIEM pipelines. The diagnostic value of App Readiness logs is limited outside of application deployment troubleshooting scenarios. Removing this telemetry has no impact on application functionality or system stability.",
            Tags = ["app-readiness", "logging", "telemetry", "policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "DisableAppReadinessLogging", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "DisableAppReadinessLogging")],
            DetectOps = [RegOp.CheckDword(Key, "DisableAppReadinessLogging", 1)],
        },
        new TweakDef
        {
            Id = "apprdy-disable-prelaunch",
            Label = "Disable App Pre-Launch",
            Category = "App Readiness Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 4,
            Description =
                "Windows pre-launches applications in the background to reduce perceived startup time for users. The pre-launch mechanism consumes memory and CPU resources before the user has actually requested the application. Disabling pre-launch ensures applications only start when explicitly requested by the user, freeing system resources for foreground tasks. On systems with limited RAM, pre-launched applications can cause memory pressure and paging activity. Enterprise workstations benefit from having resources dedicated to active business applications rather than speculative pre-launched apps. This setting is recommended for environments where resource predictability is more important than app launch latency.",
            Tags = ["app-readiness", "prelaunch", "performance", "policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "DisablePrelaunch", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "DisablePrelaunch")],
            DetectOps = [RegOp.CheckDword(Key, "DisablePrelaunch", 1)],
        },
        new TweakDef
        {
            Id = "apprdy-disable-prefetch",
            Label = "Disable App Readiness Prefetch",
            Category = "App Readiness Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 4,
            Description =
                "App Readiness prefetch proactively loads application binaries and data into memory based on predicted usage patterns. This process runs during system idle periods and consumes I/O throughput that could otherwise be used by foreground workloads. Disabling policy-controlled prefetch gives administrators explicit control over memory residency of application components. On SSDs with low read latency, the benefit of prefetch is diminished and disabling it reduces unnecessary I/O wear. Servers and RDS hosts benefit from disabling prefetch to prevent memory bloat from unpredictable application load patterns. Applications continue to function normally with their standard operating system loader mechanisms.",
            Tags = ["app-readiness", "prefetch", "performance", "policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "DisablePrefetch", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "DisablePrefetch")],
            DetectOps = [RegOp.CheckDword(Key, "DisablePrefetch", 1)],
        },
        new TweakDef
        {
            Id = "apprdy-disable-telemetry",
            Label = "Disable App Readiness Telemetry",
            Category = "App Readiness Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            Description =
                "App Readiness telemetry transmits usage metrics and diagnostic information about application preparation activities to Microsoft. This data includes timing information, failure rates, and application identifiers associated with the readiness process. Disabling this telemetry prevents application usage patterns from being transmitted outside the enterprise boundary. Privacy-sensitive organizations and regulated industries have compliance obligations to minimize telemetry data flows. The telemetry collection has no bearing on local application functionality or performance. Administrators can maintain equivalent diagnostic capability through internal logging and monitoring tools.",
            Tags = ["app-readiness", "telemetry", "privacy", "policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "DisableAppReadinessTelemetry", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "DisableAppReadinessTelemetry")],
            DetectOps = [RegOp.CheckDword(Key, "DisableAppReadinessTelemetry", 1)],
        },
        new TweakDef
        {
            Id = "apprdy-disable-readiness-score",
            Label = "Disable App Readiness Score",
            Category = "App Readiness Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 1,
            SafetyRating = 5,
            Description =
                "Windows computes application readiness scores to prioritize which applications should be prepared first during sign-in. The scoring algorithm consumes CPU cycles evaluating application state and historical usage patterns. Disabling the readiness score calculation reduces CPU overhead associated with sign-in processing. Enterprise environments with standardized application sets and predictable launch orders benefit from eliminating this adaptive algorithm. The scoring feature is primarily designed to optimize cold-start performance on consumer devices with diverse application ecosystems. Disabling it has no meaningful impact on application availability or usability in managed environments.",
            Tags = ["app-readiness", "startup", "performance", "policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "DisableReadinessScore", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "DisableReadinessScore")],
            DetectOps = [RegOp.CheckDword(Key, "DisableReadinessScore", 1)],
        },
        new TweakDef
        {
            Id = "apprdy-zero-max-wait",
            Label = "Set Max App Readiness Wait to Zero",
            Category = "App Readiness Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 4,
            Description =
                "The maximum wait time controls how long Windows delays sign-in completion while awaiting application readiness tasks. Setting this value to zero prevents any delay in sign-in completion due to App Readiness processing. This ensures that users can access their desktop immediately without waiting for speculative application preparation. Enterprise environments with fast SSD storage and pre-staged applications benefit most from eliminating this wait. Reducing sign-in latency improves user satisfaction and productivity on shared or hot-desk workstations. Application functionality is unaffected because apps load on demand when actually launched by the user.",
            Tags = ["app-readiness", "logon", "performance", "policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "MaxWaitSeconds", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "MaxWaitSeconds")],
            DetectOps = [RegOp.CheckDword(Key, "MaxWaitSeconds", 0)],
        },
        new TweakDef
        {
            Id = "apprdy-disable-first-signin-animation",
            Label = "Disable First Sign-In Animation",
            Category = "App Readiness Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            Description =
                "Windows displays a first-run welcome animation when a user signs in for the first time, presenting tips about the operating system. This animation delays desktop availability by several seconds and is unnecessary in enterprise environments where users receive training separately. Disabling the first sign-in animation skips the welcome screen and brings users directly to their desktop. Provisioned systems configured for immediate productivity benefit from removing this consumer-oriented onboarding experience. MDM and Group Policy deployments typically disable this feature as a standard hardening step. No functionality is removed by suppressing this animation.",
            Tags = ["app-readiness", "logon", "oobe", "policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "DisableFirstSigninAnimation", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "DisableFirstSigninAnimation")],
            DetectOps = [RegOp.CheckDword(Key, "DisableFirstSigninAnimation", 1)],
        },
        new TweakDef
        {
            Id = "apprdy-disable-registration-prompt",
            Label = "Disable App Registration Prompt",
            Category = "App Readiness Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            Description =
                "Windows may prompt users to register applications during first sign-in or after updates to handle file type associations and protocol handlers. These prompts interrupt productivity workflows and generate confusion in enterprise environments with managed application policies. Disabling the app registration prompt prevents these dialogs from appearing during or after the sign-in sequence. Application associations are typically managed through Group Policy or MDM configurations in enterprise deployments. Administrators maintain full control over file type and protocol handler assignments without user prompts. This setting is a standard component of enterprise desktop imaging and provisioning workflows.",
            Tags = ["app-readiness", "applications", "oobe", "policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "DisableAppRegistrationPrompt", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "DisableAppRegistrationPrompt")],
            DetectOps = [RegOp.CheckDword(Key, "DisableAppRegistrationPrompt", 1)],
        },
        new TweakDef
        {
            Id = "apprdy-disable-default-apps-choice",
            Label = "Disable Default Apps Choice Screen",
            Category = "App Readiness Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            Description =
                "Windows presents a default apps choice screen to new users asking them to select preferred applications for common tasks such as web browsing and email. This screen is irrelevant in enterprise environments where default application associations are centrally managed. Disabling this policy prevents the default apps choice dialog from appearing at any point during the user session. Enterprise deployments benefit from deterministic application association policies without user intervention. Managed default associations ensure consistent user experiences and prevent unsanctioned applications from being set as defaults. Application association management remains fully available to administrators through centralized policy mechanisms.",
            Tags = ["app-readiness", "default-apps", "oobe", "policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "DisableDefaultAppsChoice", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "DisableDefaultAppsChoice")],
            DetectOps = [RegOp.CheckDword(Key, "DisableDefaultAppsChoice", 1)],
        },
    ];
}
