namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class BuiltinAdminPolicy
{
    private const string SamKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System";
    private const string LsaKey = @"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa";
    private const string SecurityKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "biadmin-disable-guest-account-elevate",
            Label = "Built-in Admin Policy: Disable Guest Account Network Access",
            Category = "Built-in Admin Policy",
            Description = "Restricts the local Guest account from being used for network resource access. The Guest account has no password by default and, if network access is not blocked, can be used to access shares and remote services anonymously. This setting forces Guest logon attempts to fail at the network level.",
            Tags = ["guest", "network", "access", "builtin", "admin", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [LsaKey],
            ApplyOps = [RegOp.SetDword(LsaKey, "RestrictAnonymous", 1)],
            RemoveOps = [RegOp.DeleteValue(LsaKey, "RestrictAnonymous")],
            DetectOps = [RegOp.CheckDword(LsaKey, "RestrictAnonymous", 1)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Blocks anonymous/Guest network access; SMB share enumeration will fail for unauthenticated users.",
        },
        new TweakDef
        {
            Id = "biadmin-disable-anonymous-sam-enumeration",
            Label = "Built-in Admin Policy: Prevent Anonymous SAM Account Enumeration",
            Category = "Built-in Admin Policy",
            Description = "Prevents anonymous users from enumerating SAM account names and shares. Without this restriction, attackers on the local network can list all local user accounts and share names via null-session connections — a classic pre-XP recon technique still exploitable in default configurations.",
            Tags = ["sam", "anonymous", "enumeration", "builtin", "admin", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [LsaKey],
            ApplyOps = [RegOp.SetDword(LsaKey, "RestrictAnonymousSAM", 1)],
            RemoveOps = [RegOp.DeleteValue(LsaKey, "RestrictAnonymousSAM")],
            DetectOps = [RegOp.CheckDword(LsaKey, "RestrictAnonymousSAM", 1)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Prevents null-session SAM enumeration; attackers cannot list local accounts anonymously.",
        },
        new TweakDef
        {
            Id = "biadmin-enable-admin-approval-mode",
            Label = "Built-in Admin Policy: Enable Admin Approval Mode for Built-in Administrator",
            Category = "Built-in Admin Policy",
            Description = "Enables UAC Admin Approval Mode (AAM) for the built-in Administrator account. By default, the built-in Administrator runs all programs at full administrator privilege without UAC prompts. Enabling AAM forces the built-in admin through standard elevation prompts, matching the security model used for all other admin accounts.",
            Tags = ["uac", "admin approval", "builtin", "admin", "elevation", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "FilterAdministratorToken", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "FilterAdministratorToken")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "FilterAdministratorToken", 1)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Forces built-in Administrator through UAC elevation prompts like any other admin account.",
        },
        new TweakDef
        {
            Id = "biadmin-disable-local-system-blank-password",
            Label = "Built-in Admin Policy: Restrict System Logon to Local Accounts with Blank Passwords",
            Category = "Built-in Admin Policy",
            Description = "Prevents local accounts that have blank passwords from being used for interactive or remote logon via services, scheduled tasks, or batch jobs. This closes a privilege escalation vector where an unattended service running as a blank-password local admin could be exploited.",
            Tags = ["blank password", "local account", "system service", "builtin", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [LsaKey],
            ApplyOps = [RegOp.SetDword(LsaKey, "LimitBlankPasswordUse", 1)],
            RemoveOps = [RegOp.DeleteValue(LsaKey, "LimitBlankPasswordUse")],
            DetectOps = [RegOp.CheckDword(LsaKey, "LimitBlankPasswordUse", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Prevents blank-password local accounts from being used in service or scheduled task contexts.",
        },
        new TweakDef
        {
            Id = "biadmin-require-elevation-uac",
            Label = "Built-in Admin Policy: Elevate Only Signed Executables Without Prompting Admin",
            Category = "Built-in Admin Policy",
            Description = "Configures UAC to silently elevate only executables that are securely signed and validated. Unsigned executables that request elevation will prompt the administrator. This prevents unsigned trojans and malware from silently elevating by mimicking a legitimate system binary.",
            Tags = ["uac", "elevation", "signed", "builtin", "admin", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "ConsentPromptBehaviorAdmin", 2)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "ConsentPromptBehaviorAdmin")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "ConsentPromptBehaviorAdmin", 2)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "UAC prompts admin for unsigned elevations; signed system binaries elevate silently.",
        },
        new TweakDef
        {
            Id = "biadmin-block-uac-virtualization",
            Label = "Built-in Admin Policy: Disable UAC File/Registry Virtualization for Admins",
            Category = "Built-in Admin Policy",
            Description = "Disables User Account Control file and registry write virtualization for administrators. UAC virtualization redirects writes from protected system locations to per-user virtual stores for standard users. Admins who need direct writes should use elevation rather than rely on virtualization, which may mask application privilege requirements.",
            Tags = ["uac", "virtualization", "registry", "file", "admin", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "EnableVirtualization", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "EnableVirtualization")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "EnableVirtualization", 0)],
            ImpactScore = 3,
            SafetyRating = 3,
            ImpactNote = "Disables UAC write virtualization; legacy apps writing to HKLM or Program Files may break.",
        },
        new TweakDef
        {
            Id = "biadmin-uac-prompt-on-secure-desktop",
            Label = "Built-in Admin Policy: Show UAC Elevation Prompt on Secure Desktop",
            Category = "Built-in Admin Policy",
            Description = "Ensures that UAC elevation prompts are always displayed on the secure desktop (isolated input desktop), preventing user-mode software from spoofing the UAC dialog or capturing keystrokes entered in the elevation prompt. This is the default but may be changed by policy on some corporate images.",
            Tags = ["uac", "secure desktop", "elevation", "builtin", "admin", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "PromptOnSecureDesktop", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "PromptOnSecureDesktop")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "PromptOnSecureDesktop", 1)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Prevents UAC spoof UIs; elevation prompt is shown on isolated secure desktop.",
        },
        new TweakDef
        {
            Id = "biadmin-disable-uac-installer-detection",
            Label = "Built-in Admin Policy: Enable UAC Installer Detection for All Users",
            Category = "Built-in Admin Policy",
            Description = "Enables the UAC installer detection algorithm that heuristically detects setup programs and automatically prompts for elevation. Without this, legacy installers that do not include a proper elevation manifest silently fail without requesting admin rights, leaving software partially or incorrectly installed.",
            Tags = ["uac", "installer", "detection", "elevation", "admin", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "EnableInstallerDetection", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "EnableInstallerDetection")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "EnableInstallerDetection", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Heuristically detects legacy installers and prompts for elevation to prevent silent failures.",
        },
        new TweakDef
        {
            Id = "biadmin-restrict-run-as-logon",
            Label = "Built-in Admin Policy: Restrict Secondary Logon (RunAs) Service",
            Category = "Built-in Admin Policy",
            Description = "Applies policy restrictions to the Secondary Logon (RunAs) service, limiting which users can invoke it. Secondary Logon can be abused by malware to silently launch processes under alternative credentials without displaying a logon UI. Policy restriction prevents abuse of the service on non-administrative accounts.",
            Tags = ["runas", "secondary logon", "logon", "admin", "builtin", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SamKey],
            ApplyOps = [RegOp.SetDword(SamKey, "DisableRunAs", 0)],
            RemoveOps = [RegOp.DeleteValue(SamKey, "DisableRunAs")],
            DetectOps = [RegOp.CheckDword(SamKey, "DisableRunAs", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Ensures RunAs (Secondary Logon) policy is correctly set; does not disable the service.",
        },
        new TweakDef
        {
            Id = "biadmin-enable-uac-main-switch",
            Label = "Built-in Admin Policy: Ensure UAC Main Switch Is Enabled",
            Category = "Built-in Admin Policy",
            Description = "Ensures that the master User Account Control (UAC) enable switch is set to 1 (enabled). If UAC is disabled globally, all elevation prompts are suppressed and all processes run at the full token of whichever user is logged on. This is the single most impactful UAC configuration value.",
            Tags = ["uac", "main switch", "elevation", "admin", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "EnableLUA", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "EnableLUA")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", "EnableLUA", 1)],
            ImpactScore = 5,
            SafetyRating = 5,
            ImpactNote = "Master UAC switch — must be 1 for any UAC elevation to function at all.",
        },
    ];
}
