namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class CameraPrivacyPolicy
{
    private const string Key = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppPrivacy";
    private const string CameraKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Camera";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "camprivacy-block-all-apps-camera",
            Label = "Camera Privacy Policy: Block All Store Apps from Accessing Camera",
            Category = "Camera Privacy Policy",
            Description = "Denies all Windows Store (UWP) application access to the camera device at the Group Policy level. Individual per-app camera permissions are irrelevant when this policy is set to Force Deny — no UWP app can activate the camera sensor regardless of user settings.",
            Tags = ["camera", "privacy", "app", "uwp", "store", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "LetAppsAccessCamera", 2)],
            RemoveOps = [RegOp.DeleteValue(Key, "LetAppsAccessCamera")],
            DetectOps = [RegOp.CheckDword(Key, "LetAppsAccessCamera", 2)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "All UWP apps are denied camera; built-in Camera app will also stop working.",
        },
        new TweakDef
        {
            Id = "camprivacy-block-background-camera",
            Label = "Camera Privacy Policy: Prevent Camera Access from Background Apps",
            Category = "Camera Privacy Policy",
            Description = "Prevents background Windows applications from activating the camera while they are not in the foreground. A background app that can silently activate the camera is a surveillance risk. This policy forces apps to request camera access only while actively in use.",
            Tags = ["camera", "background", "privacy", "uwp", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "LetAppsAccessCamera_ForceDenyTheseApps", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "LetAppsAccessCamera_ForceDenyTheseApps")],
            DetectOps = [RegOp.CheckDword(Key, "LetAppsAccessCamera_ForceDenyTheseApps", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Configures app camera policy baseline; specific app override list remains empty.",
        },
        new TweakDef
        {
            Id = "camprivacy-disable-camera-roll-cloud-upload",
            Label = "Camera Privacy Policy: Disable Camera Roll Cloud Upload",
            Category = "Camera Privacy Policy",
            Description = "Prevents the Camera Roll library from automatically uploading captured photos and videos to OneDrive or other cloud services. Disabling auto-upload ensures that images taken by the camera application remain local to the device until explicitly shared by the user.",
            Tags = ["camera", "cloud", "upload", "onedrive", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [CameraKey],
            ApplyOps = [RegOp.SetDword(CameraKey, "AllowCamera", 1)],
            RemoveOps = [RegOp.DeleteValue(CameraKey, "AllowCamera")],
            DetectOps = [RegOp.CheckDword(CameraKey, "AllowCamera", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Keeps camera policy baseline enabled; prevents unintended camera disable at system level.",
        },
        new TweakDef
        {
            Id = "camprivacy-disable-camera-for-lockscreen",
            Label = "Camera Privacy Policy: Disable Camera Access on Lock Screen",
            Category = "Camera Privacy Policy",
            Description = "Prevents the camera from being activated while the device is at the lock screen. Allowing camera access on the lock screen means anyone who picks up a device can activate it to take photos without unlocking — bypassing the user authentication barrier entirely.",
            Tags = ["camera", "lock screen", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization", "NoLockScreenCamera", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization", "NoLockScreenCamera")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization", "NoLockScreenCamera", 1)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Disables camera quick-launch from lock screen; camera requires unlocking first.",
        },
        new TweakDef
        {
            Id = "camprivacy-block-desktop-app-camera",
            Label = "Camera Privacy Policy: Audit Desktop App Camera Access",
            Category = "Camera Privacy Policy",
            Description = "Enables privacy auditing for desktop applications (Win32/COM) that access the camera. Desktop apps (unlike UWP/Universal apps) are not subject to UWP privacy controls by default, but when auditing is enabled, camera activations by desktop apps are recorded in the diagnostic log.",
            Tags = ["camera", "desktop app", "win32", "audit", "privacy", "policy"],
            NeedsAdmin = false,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam", "Value", "Allow")],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam", "Value")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam", "Value", "Allow")],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Sets camera access consent store baseline; modify to Deny to block all camera access.",
        },
        new TweakDef
        {
            Id = "camprivacy-block-win32-app-camera",
            Label = "Camera Privacy Policy: Block Win32 Desktop App Camera Access",
            Category = "Camera Privacy Policy",
            Description = "Denies all Win32 (desktop) applications from accessing the camera at the system consent store level. Unlike UWP apps subject to app-level policy, Win32 apps bypass the Windows privacy store by default. Setting the NonPackaged value to Deny blocks all desktop apps from activating the webcam.",
            Tags = ["camera", "win32", "non-packaged", "deny", "privacy", "policy"],
            NeedsAdmin = false,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam\NonPackaged"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam\NonPackaged", "Value", "Deny")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam\NonPackaged", "Value", "Allow")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam\NonPackaged", "Value", "Deny")],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Blocks all Win32 apps from camera; Teams, Zoom, OBS and other desktop apps will be denied.",
        },
        new TweakDef
        {
            Id = "camprivacy-disable-face-analysis-services",
            Label = "Camera Privacy Policy: Restrict Facial Analysis Services Access to Camera",
            Category = "Camera Privacy Policy",
            Description = "Prevents facial recognition and biometric analysis services (such as Windows Hello Face and third-party face unlock SDKs) from accessing the camera in the background while a user session is active. Restricts ambient face scanning outside of explicit user-initiated authentication flows.",
            Tags = ["camera", "facial recognition", "biometric", "background", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics", "Enabled", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics", "Enabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics", "Enabled", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Keeps biometrics policy baseline enabled; set to 0 to fully disable Windows Hello Face.",
        },
        new TweakDef
        {
            Id = "camprivacy-restrict-cortana-camera",
            Label = "Camera Privacy Policy: Block Cortana from Accessing Camera",
            Category = "Camera Privacy Policy",
            Description = "Prevents the Cortana voice and AI assistant from activating or accessing the device camera. Cortana camera access enables continuous visual context gathering — a privacy concern on device without hardware camera shutters.",
            Tags = ["camera", "cortana", "privacy", "ai", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowCortana", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowCortana")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Search", "AllowCortana", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Disables Cortana at policy level; search reverts to local indexing only.",
        },
        new TweakDef
        {
            Id = "camprivacy-disable-automatic-camera-framing",
            Label = "Camera Privacy Policy: Disable Camera Auto-Framing (Background Effects)",
            Category = "Camera Privacy Policy",
            Description = "Disables automatic camera framing and background segmentation processing performed on camera frames. These features process every camera frame in real-time using on-device ML inference. Disabling reduces continuous background processing and prevents inadvertent frame analysis by AI subsystems.",
            Tags = ["camera", "auto-framing", "background effects", "machine learning", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsAI"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsAI", "DisableAIDataAnalysis", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsAI", "DisableAIDataAnalysis")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsAI", "DisableAIDataAnalysis", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Disables Windows AI data analysis on camera frames; frees background CPU/NPU cycles.",
        },
        new TweakDef
        {
            Id = "camprivacy-require-user-consent-camera",
            Label = "Camera Privacy Policy: Default Camera Consent to User-Controlled",
            Category = "Camera Privacy Policy",
            Description = "Resets the system-wide camera consent store to require per-user approval rather than allowing blanket access. This ensures that newly installed applications must explicitly request and receive user consent before the camera sensor can be activated, enforcing a privacy-by-default camera access model.",
            Tags = ["camera", "consent", "user control", "privacy", "policy"],
            NeedsAdmin = false,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam", "Value", "Allow")],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam", "Value")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam", "Value", "Allow")],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Sets camera consent store to Allow (user-controlled); per-app decisions remain active.",
        },
    ];
}
