namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class Chrome
{
    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "chrome-disable-renderer-code-integrity",
            Label = "Disable Chrome Renderer Code Integrity",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables renderer code integrity checks in Chrome. Fixes compatibility issues with certain security software. Default: enabled.",
            Tags = ["chrome", "renderer", "code-integrity", "compatibility"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "RendererCodeIntegrityEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "RendererCodeIntegrityEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "RendererCodeIntegrityEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-preloading",
            Label = "Disable Chrome Page Preloading",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome from preloading pages it predicts you might visit. Saves bandwidth. Default: enabled.",
            Tags = ["chrome", "preloading", "bandwidth", "prediction"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "NetworkPredictionOptions", 2)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "NetworkPredictionOptions")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "NetworkPredictionOptions", 2)],
        },
        new TweakDef
        {
            Id = "chrome-disable-autofill-addresses",
            Label = "Disable Chrome Address Autofill",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome's autofill suggestions for addresses. Prevents address data storage. Default: enabled.",
            Tags = ["chrome", "autofill", "addresses", "privacy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "AutofillAddressEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "AutofillAddressEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "AutofillAddressEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-search-suggestions",
            Label = "Disable Chrome Search Suggestions",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables search and URL suggestions in the Chrome address bar. Prevents keystrokes from being sent to Google. Default: enabled.",
            Tags = ["chrome", "search", "suggestions", "privacy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SearchSuggestEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SearchSuggestEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SearchSuggestEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-background-mode",
            Label = "Disable Chrome Background Mode",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Prevents Chrome from running in background after all windows are closed. Frees system resources. Default: enabled.",
            Tags = ["chrome", "background", "mode", "performance"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BackgroundModeEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BackgroundModeEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BackgroundModeEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-metrics-reporting",
            Label = "Disable Chrome Metrics Reporting",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome usage and crash-related data reporting to Google. Default: enabled.",
            Tags = ["chrome", "metrics", "telemetry", "privacy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "MetricsReportingEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "MetricsReportingEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "MetricsReportingEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-safe-browsing-extended",
            Label = "Disable Chrome Enhanced Safe Browsing",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables enhanced Safe Browsing which sends URLs to Google in real-time. Standard protection remains active. Default: standard.",
            Tags = ["chrome", "safe-browsing", "privacy", "security"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SafeBrowsingProtectionLevel", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SafeBrowsingProtectionLevel")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SafeBrowsingProtectionLevel", 1)],
        },
        new TweakDef
        {
            Id = "chrome-disable-translate",
            Label = "Disable Chrome Built-in Translation",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables the built-in page translation prompt in Chrome. Default: enabled.",
            Tags = ["chrome", "translate", "language", "ux"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "TranslateEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "TranslateEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "TranslateEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-autofill-credit-cards",
            Label = "Disable Chrome Credit Card Autofill",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome from saving and auto-filling credit card information. Default: enabled.",
            Tags = ["chrome", "autofill", "credit-card", "privacy", "security"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "AutofillCreditCardEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "AutofillCreditCardEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "AutofillCreditCardEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-password-manager",
            Label = "Disable Chrome Built-in Password Manager",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome's built-in password manager. Use a dedicated password manager instead. Default: enabled.",
            Tags = ["chrome", "password", "manager", "security"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PasswordManagerEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PasswordManagerEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PasswordManagerEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-spell-check-service",
            Label = "Disable Chrome Spell Check Service",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome's online spell check service that sends text to Google. Local spell check still works. Default: enabled.",
            Tags = ["chrome", "spell-check", "privacy", "service"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SpellCheckServiceEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SpellCheckServiceEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SpellCheckServiceEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-block-third-party-cookies",
            Label = "Block Third-Party Cookies in Chrome",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Blocks third-party cookies in Chrome to prevent cross-site tracking. Default: allowed.",
            Tags = ["chrome", "cookies", "tracking", "privacy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BlockThirdPartyCookies", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BlockThirdPartyCookies")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BlockThirdPartyCookies", 1)],
        },
        new TweakDef
        {
            Id = "chrome-disable-webrtc-leak",
            Label = "Restrict Chrome WebRTC IP Leaking",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Restricts WebRTC from exposing local IP addresses. Enhances VPN privacy. Default: unrestricted.",
            Tags = ["chrome", "webrtc", "ip", "leak", "vpn", "privacy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetString(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "WebRtcIPHandling", "disable_non_proxied_udp")],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "WebRtcIPHandling")],
            DetectOps = [RegOp.CheckString(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "WebRtcIPHandling", "disable_non_proxied_udp")],
        },
        new TweakDef
        {
            Id = "chrome-disable-signin-promo",
            Label = "Disable Chrome Sign-In Promotion",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Suppresses Chrome sign-in prompts and promotional popups. Default: shown.",
            Tags = ["chrome", "sign-in", "promotion", "ux"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PromotionalTabsEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PromotionalTabsEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PromotionalTabsEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-force-dns-over-https",
            Label = "Enable Chrome DNS-over-HTTPS",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Enables DNS-over-HTTPS in Chrome with Cloudflare resolver. Encrypts DNS queries for privacy. Default: disabled.",
            Tags = ["chrome", "dns", "doh", "privacy", "security"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps =
            [
                RegOp.SetString(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DnsOverHttpsMode", "automatic"),
                RegOp.SetString(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DnsOverHttpsTemplates", "https://cloudflare-dns.com/dns-query"),
            ],
            RemoveOps =
            [
                RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DnsOverHttpsMode"),
                RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DnsOverHttpsTemplates"),
            ],
            DetectOps = [RegOp.CheckString(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DnsOverHttpsMode", "automatic")],
        },
        new TweakDef
        {
            Id = "chrome-disable-chrome-update",
            Label = "Disable Chrome Auto-Update",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = false,
            Description = "Prevents Chrome from auto-updating via Google Update policy. Useful for version-pinned environments.",
            Tags = ["chrome", "browser", "update"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update"],
            ApplyOps =
            [
                RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update", "UpdateDefault", 0),
                RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update", "AutoUpdateCheckPeriodMinutes", 0),
            ],
            RemoveOps =
            [
                RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update", "UpdateDefault"),
                RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update", "AutoUpdateCheckPeriodMinutes"),
            ],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Update", "UpdateDefault", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-chrome-telemetry",
            Label = "Disable Chrome Telemetry",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = false,
            Description = "Disables Chrome usage statistics and crash reporting via policy.",
            Tags = ["chrome", "browser", "telemetry", "privacy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps =
            [
                RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "MetricsReportingEnabled", 0),
                RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DeviceMetricsReportingEnabled", 0),
            ],
            RemoveOps =
            [
                RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "MetricsReportingEnabled"),
                RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DeviceMetricsReportingEnabled"),
            ],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "MetricsReportingEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-chrome-bg",
            Label = "Disable Chrome Background Mode",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Prevents Chrome from running in the background after all windows are closed.",
            Tags = ["chrome", "browser", "background", "performance"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BackgroundModeEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BackgroundModeEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BackgroundModeEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-chrome-signin",
            Label = "Disable Chrome Sign-In",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome browser sign-in with Google account via policy.",
            Tags = ["chrome", "browser", "signin", "privacy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BrowserSignin", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BrowserSignin")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BrowserSignin", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-chrome-hwaccel",
            Label = "Disable Chrome Hardware Acceleration",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables hardware acceleration in Chrome via policy. Reduces GPU usage at the cost of rendering performance.",
            Tags = ["chrome", "browser", "gpu", "performance"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "HardwareAccelerationModeEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "HardwareAccelerationModeEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "HardwareAccelerationModeEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-background",
            Label = "Disable Chrome Background Apps",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Prevents Chrome background apps from running when Chrome is closed. Saves memory and CPU.",
            Tags = ["chrome", "browser", "background", "apps"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BackgroundProcessingEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BackgroundProcessingEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "BackgroundProcessingEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-signin",
            Label = "Disable Chrome Browser Sign-In Prompt",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables the Chrome sign-in prompt via policy. Prevents nagging to sign into Google.",
            Tags = ["chrome", "browser", "signin", "ux"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PromotionalTabsEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PromotionalTabsEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PromotionalTabsEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-sync",
            Label = "Disable Chrome Sync",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome data synchronization across devices via policy.",
            Tags = ["chrome", "browser", "sync", "privacy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SyncDisabled", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SyncDisabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "SyncDisabled", 1)],
        },
        new TweakDef
        {
            Id = "chrome-disable-autofill-passwords",
            Label = "Disable Chrome Password Autofill",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome built-in password manager and autofill.",
            Tags = ["chrome", "browser", "password", "autofill"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PasswordManagerEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PasswordManagerEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PasswordManagerEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-reporter",
            Label = "Disable Chrome Software Reporter",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome Software Reporter Tool (CleanUp tool) that scans for unwanted software.",
            Tags = ["chrome", "browser", "reporter", "privacy", "performance"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "ChromeCleanupEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "ChromeCleanupEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "ChromeCleanupEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-leak-detection",
            Label = "Disable Chrome Password Leak Detection",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome password leak detection that checks passwords against breach databases.",
            Tags = ["chrome", "browser", "leak", "password", "privacy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PasswordLeakDetectionEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PasswordLeakDetectionEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "PasswordLeakDetectionEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-default-browser-check",
            Label = "Disable Chrome Default Browser Check",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Prevents Chrome from checking/prompting to be the default browser.",
            Tags = ["chrome", "browser", "default", "ux"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DefaultBrowserSettingEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DefaultBrowserSettingEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DefaultBrowserSettingEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-media-recommendations",
            Label = "Disable Chrome Media Recommendations",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome media recommendations on the new tab page.",
            Tags = ["chrome", "browser", "media", "recommendations"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "MediaRecommendationsEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "MediaRecommendationsEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "MediaRecommendationsEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-disable-hardware-accel-policy",
            Label = "Disable Chrome GPU Acceleration Policy",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Chrome GPU hardware acceleration at policy level.",
            Tags = ["chrome", "browser", "gpu", "acceleration", "policy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "HardwareAccelerationModeEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "HardwareAccelerationModeEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "HardwareAccelerationModeEnabled", 0)],
        },
        new TweakDef
        {
            Id = "chrome-enforce-3p-cookie-block",
            Label = "Enforce Third-Party Cookie Block in Chrome",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Sets Chrome default cookie setting to block third-party cookies (value 1=allow all, 2=block 3p, 4=block all).",
            Tags = ["chrome", "browser", "cookies", "policy"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DefaultCookiesSetting", 2)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DefaultCookiesSetting")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DefaultCookiesSetting", 2)],
        },
        new TweakDef
        {
            Id = "chrome-secure-dns",
            Label = "Enable Chrome Secure DNS",
            Category = "Chrome",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Forces Chrome DNS-over-HTTPS in secure mode with Cloudflare as provider.",
            Tags = ["chrome", "browser", "dns", "security"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome"],
            ApplyOps =
            [
                RegOp.SetString(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DnsOverHttpsMode", "secure"),
                RegOp.SetString(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DnsOverHttpsTemplates", "https://cloudflare-dns.com/dns-query"),
            ],
            RemoveOps =
            [
                RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DnsOverHttpsMode"),
                RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DnsOverHttpsTemplates"),
            ],
            DetectOps = [RegOp.CheckString(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome", "DnsOverHttpsMode", "secure")],
        },
    ];
}
