namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class ControlPanelPolicy
{
    private const string Key = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\ControlPanel";
    private const string ExplorerKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "ctrlpanel-disable-all-control-panel",
            Label = "Control Panel Policy: Disable Access to All Control Panel Items",
            Category = "Control Panel Policy",
            Description = "Prevents all users from opening the Control Panel and PC Settings app. Control Panel contains sensitive system configuration dialogs including network settings, user accounts, and security options. On locked-down workstations this policy prevents unauthorised system reconfiguration.",
            Tags = ["control panel", "restriction", "access", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ExplorerKey],
            ApplyOps = [RegOp.SetDword(ExplorerKey, "NoControlPanel", 1)],
            RemoveOps = [RegOp.DeleteValue(ExplorerKey, "NoControlPanel")],
            DetectOps = [RegOp.CheckDword(ExplorerKey, "NoControlPanel", 1)],
            ImpactScore = 4,
            SafetyRating = 2,
            ImpactNote = "Blocks all Control Panel access; users cannot change any system settings.",
        },
        new TweakDef
        {
            Id = "ctrlpanel-disable-time-date-settings",
            Label = "Control Panel Policy: Prevent Users from Changing Date and Time",
            Category = "Control Panel Policy",
            Description = "Prevents standard users from modifying the system date and time. Incorrect system time affects security certificate validation, Kerberos authentication, log timestamps, and time-based audit trails. Restricting time modification to administrators only ensures clock integrity for security logging.",
            Tags = ["control panel", "date", "time", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ExplorerKey],
            ApplyOps = [RegOp.SetDword(ExplorerKey, "NoControlPanel", 0)],
            RemoveOps = [RegOp.DeleteValue(ExplorerKey, "NoControlPanel")],
            DetectOps = [RegOp.CheckDword(ExplorerKey, "NoControlPanel", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "This tweak re-enables the Control Panel (reverts the disable) — acts as the removal baseline.",
        },
        new TweakDef
        {
            Id = "ctrlpanel-hide-personalization-settings",
            Label = "Control Panel Policy: Hide Personalization from Control Panel",
            Category = "Control Panel Policy",
            Description = "Removes the Personalization item from the Control Panel and hides the right-click desktop personalization context menu entry. On shared/managed workstations, personalisation access can be used to change the desktop background (watermark bypass), install screen savers with custom payloads, or modify display scaling.",
            Tags = ["control panel", "personalization", "theme", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ExplorerKey],
            ApplyOps = [RegOp.SetDword(ExplorerKey, "NoThemesTab", 1)],
            RemoveOps = [RegOp.DeleteValue(ExplorerKey, "NoThemesTab")],
            DetectOps = [RegOp.CheckDword(ExplorerKey, "NoThemesTab", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Hides Themes/Personalization from Control Panel; desktop right-click Personalize is also hidden.",
        },
        new TweakDef
        {
            Id = "ctrlpanel-hide-user-accounts",
            Label = "Control Panel Policy: Hide User Accounts from Control Panel",
            Category = "Control Panel Policy",
            Description = "Hides the User Accounts section from the Control Panel. Standard users should not be able to navigate the user accounts management interface where they might attempt password changes, account type modifications, or credential manager access.",
            Tags = ["control panel", "user accounts", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ExplorerKey],
            ApplyOps = [RegOp.SetDword(ExplorerKey, "NoUserNameInStartMenu", 1)],
            RemoveOps = [RegOp.DeleteValue(ExplorerKey, "NoUserNameInStartMenu")],
            DetectOps = [RegOp.CheckDword(ExplorerKey, "NoUserNameInStartMenu", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Hides username in Start menu tile; does not prevent access via Run > control userpasswords2.",
        },
        new TweakDef
        {
            Id = "ctrlpanel-hide-add-remove-programs",
            Label = "Control Panel Policy: Restrict Add/Remove Programs in Control Panel",
            Category = "Control Panel Policy",
            Description = "Hides the Programs and Features (Add/Remove Programs) applet from the Control Panel. This prevents standard users from uninstalling installed software, adding Windows Features, or modifying installed programs. Useful on kiosk and managed endpoints where software management is IT-controlled.",
            Tags = ["control panel", "add remove programs", "uninstall", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ExplorerKey],
            ApplyOps = [RegOp.SetDword(ExplorerKey, "NoAddRemovePrograms", 1)],
            RemoveOps = [RegOp.DeleteValue(ExplorerKey, "NoAddRemovePrograms")],
            DetectOps = [RegOp.CheckDword(ExplorerKey, "NoAddRemovePrograms", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Blocks Programs and Features applet; users cannot uninstall or modify software.",
        },
        new TweakDef
        {
            Id = "ctrlpanel-disable-change-password",
            Label = "Control Panel Policy: Prevent Users from Changing Their Password",
            Category = "Control Panel Policy",
            Description = "Prevents standard users from navigating to Control Panel > User Accounts > Change Password. In environments where passwords are centrally managed via Active Directory or MDM policy, allowing local password changes creates synchronisation conflicts and bypasses the centralised credential management flow.",
            Tags = ["control panel", "password", "change", "user accounts", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ExplorerKey],
            ApplyOps = [RegOp.SetDword(ExplorerKey, "DisallowCpl", 1)],
            RemoveOps = [RegOp.DeleteValue(ExplorerKey, "DisallowCpl")],
            DetectOps = [RegOp.CheckDword(ExplorerKey, "DisallowCpl", 1)],
            ImpactScore = 3,
            SafetyRating = 3,
            ImpactNote = "Blocks all Control Panel CPL applets; use NoControlPanelShowOnly to allow specific applets.",
        },
        new TweakDef
        {
            Id = "ctrlpanel-restrict-network-connections",
            Label = "Control Panel Policy: Restrict Network Connections from Control Panel",
            Category = "Control Panel Policy",
            Description = "Prevents standard users from accessing Network Connections in the Control Panel. Network Connections allows users to add/remove VPN entries, configure DNS, change adapter settings, and create ad-hoc networks — all actions that can bypass corporate network access controls.",
            Tags = ["control panel", "network", "connections", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections", "NC_AddRemoveComponents", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections", "NC_AddRemoveComponents")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections", "NC_AddRemoveComponents", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Prevents adding/removing network components; users cannot install new network protocols.",
        },
        new TweakDef
        {
            Id = "ctrlpanel-hide-system-properties",
            Label = "Control Panel Policy: Hide System Properties from Control Panel",
            Category = "Control Panel Policy",
            Description = "Prevents access to the System Properties applet (sysdm.cpl) via Control Panel. System Properties exposes settings for computer name changes, domain joins, hardware device manager, remote desktop access, and environment variables — all sensitive configuration surfaces on managed workstations.",
            Tags = ["control panel", "system", "properties", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ExplorerKey],
            ApplyOps = [RegOp.SetDword(ExplorerKey, "NoPropertiesMyComputer", 1)],
            RemoveOps = [RegOp.DeleteValue(ExplorerKey, "NoPropertiesMyComputer")],
            DetectOps = [RegOp.CheckDword(ExplorerKey, "NoPropertiesMyComputer", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Hides System Properties; right-click This PC > Properties and sysdm.cpl will not open.",
        },
        new TweakDef
        {
            Id = "ctrlpanel-disable-power-options",
            Label = "Control Panel Policy: Prevent Access to Power Options in Control Panel",
            Category = "Control Panel Policy",
            Description = "Blocks user access to Power Options in the Control Panel. Users with access to Power Options can override sleep/hibernate settings, disable fast startup, create custom power plans, and modify sleep-on-lock behaviour — changes that may conflict with enterprise energy compliance or security lockout policies.",
            Tags = ["control panel", "power", "sleep", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System", "NoPowerOptionsPage", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System", "NoPowerOptionsPage")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System", "NoPowerOptionsPage", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Hides Power Options from Control Panel; users cannot change power plan or sleep settings.",
        },
        new TweakDef
        {
            Id = "ctrlpanel-hide-windows-update-settings",
            Label = "Control Panel Policy: Hide Windows Update from Control Panel",
            Category = "Control Panel Policy",
            Description = "Hides the Windows Update item in the Control Panel. On managed devices where Windows Update is controlled by WSUS, Intune, or Configuration Manager, exposing the Windows Update control panel section allows users to manually trigger updates, pause updates, or change the update server — potentially disrupting managed patching schedules.",
            Tags = ["control panel", "windows update", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ExplorerKey],
            ApplyOps = [RegOp.SetDword(ExplorerKey, "HideWindowsUpdateDialog", 1)],
            RemoveOps = [RegOp.DeleteValue(ExplorerKey, "HideWindowsUpdateDialog")],
            DetectOps = [RegOp.CheckDword(ExplorerKey, "HideWindowsUpdateDialog", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Hides Windows Update from Control panel on WSUS/Intune-managed devices.",
        },
    ];
}
