namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class DefaultBrowserPolicy
{
    private const string EdgeKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge";
    private const string IeKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Main";
    private const string AssocKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "defbrowser-prevent-default-browser-message",
            Label = "Default Browser Policy: Suppress Edge Default Browser Nag",
            Category = "Default Browser Policy",
            Description = "Prevents Microsoft Edge from displaying the 'Set Edge as default browser' prompt and notification banner. Edge aggressively promotes itself as the default browser (especially after Windows updates), interrupting user workflows with unsolicited nag dialogs.",
            Tags = ["browser", "default", "edge", "nag", "prompt", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "DefaultBrowserSettingEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "DefaultBrowserSettingEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "DefaultBrowserSettingEnabled", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Stops Edge from nagging about default browser status after Windows updates.",
        },
        new TweakDef
        {
            Id = "defbrowser-disable-ie-first-run-prompt",
            Label = "Default Browser Policy: Disable Internet Explorer First Run Browser Choice",
            Category = "Default Browser Policy",
            Description = "Prevents Internet Explorer and legacy Edge from showing the first-run browser choice screen that prompts users to select a default browser. This prompt appears on fresh installations or after browser resets and, if dismissed, may revert to Edge/IE as the default without the user understanding the implication.",
            Tags = ["browser", "default", "ie", "first run", "choice", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [IeKey],
            ApplyOps = [RegOp.SetString(IeKey, "Check_Associations", "no")],
            RemoveOps = [RegOp.DeleteValue(IeKey, "Check_Associations")],
            DetectOps = [RegOp.CheckString(IeKey, "Check_Associations", "no")],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Suppresses IE browser choice prompt on first run; default browser selection is preserved.",
        },
        new TweakDef
        {
            Id = "defbrowser-block-edge-html-protocol-takeover",
            Label = "Default Browser Policy: Block Edge WebView2 Protocol Handler Registration",
            Category = "Default Browser Policy",
            Description = "Prevents Microsoft Edge from silently registering itself as the handler for HTTP and HTTPS protocols via Edge WebView2 background updates. Edge periodically re-registers protocol handlers without user consent, effectively hijacking the default browser setting.",
            Tags = ["browser", "default", "edge", "protocol", "webview2", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "HideInternetExplorerRedirectUXForIncompatibleSitesEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "HideInternetExplorerRedirectUXForIncompatibleSitesEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "HideInternetExplorerRedirectUXForIncompatibleSitesEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Keeps IE redirect UX visible; disables Edge silent protocol handler suppression.",
        },
        new TweakDef
        {
            Id = "defbrowser-lock-default-browser-users",
            Label = "Default Browser Policy: Lock Default Browser Setting for All Users",
            Category = "Default Browser Policy",
            Description = "Locks the default browser setting so that it cannot be changed by standard users, only by administrators. On managed workstations where a specific browser is required for intranet compatibility or corporate extensions, preventing users from changing the default browser ensures consistent access patterns.",
            Tags = ["browser", "default", "lock", "users", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [AssocKey],
            ApplyOps = [RegOp.SetDword(AssocKey, "DefaultAssociationsConfiguration", 0)],
            RemoveOps = [RegOp.DeleteValue(AssocKey, "DefaultAssociationsConfiguration")],
            DetectOps = [RegOp.CheckDword(AssocKey, "DefaultAssociationsConfiguration", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Baseline value; set DefaultAssociationsConfiguration to a GPO XML path to enforce a browser.",
        },
        new TweakDef
        {
            Id = "defbrowser-suppress-edge-startup-browser-prompt",
            Label = "Default Browser Policy: Suppress Edge Startup Browser Default Suggestion",
            Category = "Default Browser Policy",
            Description = "Prevents Microsoft Edge from opening to the browser default suggestion page on startup (a page that directly prompts the user to set Edge as the default browser). This page appears after Windows feature updates or Edge major version updates and bypasses the system-level default browser setting.",
            Tags = ["browser", "default", "edge", "startup", "suggestion", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ShowRecommendationsEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ShowRecommendationsEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ShowRecommendationsEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Suppresses Edge recommendations banner including the default browser suggestion page.",
        },
        new TweakDef
        {
            Id = "defbrowser-disable-edge-auto-set-default-browser",
            Label = "Default Browser Policy: Disable Edge Auto-Setting Itself as Default After Updates",
            Category = "Default Browser Policy",
            Description = "Prevents Microsoft Edge from automatically setting itself as the default browser after operating system updates or feature releases. Windows Update periodically resets the default browser associations to Edge, overriding the user's explicit choice. This policy disables that automatic override.",
            Tags = ["browser", "default", "edge", "auto-set", "update", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "DefaultBrowserSettingsCampaignEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "DefaultBrowserSettingsCampaignEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "DefaultBrowserSettingsCampaignEnabled", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Disables Edge's campaign mode to push itself as default after OS updates.",
        },
        new TweakDef
        {
            Id = "defbrowser-disable-edge-intent-picker-redirect",
            Label = "Default Browser Policy: Disable Edge Intent Picker Browser Redirect",
            Category = "Default Browser Policy",
            Description = "Prevents the Windows Intent Picker (the dialog that appears when clicking a link in a non-browser app) from always proposing Edge as the handler. When another browser is set as default, the Intent Picker should respect that choice without surfacing Edge as an alternative every time a URL is opened.",
            Tags = ["browser", "default", "edge", "intent picker", "redirect", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "BrowserLegacyExtensionPointsBlockingEnabled", 1)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "BrowserLegacyExtensionPointsBlockingEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "BrowserLegacyExtensionPointsBlockingEnabled", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Blocks Edge injection via legacy extension points; respects the configured default browser.",
        },
        new TweakDef
        {
            Id = "defbrowser-disable-file-protocol-edge-takeover",
            Label = "Default Browser Policy: Prevent Edge from Handling Local File (file://) URLs",
            Category = "Default Browser Policy",
            Description = "Prevents Microsoft Edge from claiming file:// protocol handler registration on top of the configured default browser. When a local HTML file is opened from Windows Explorer, Edge intercepts it even if another browser is set as default. This policy shifts local file handling back to the default browser.",
            Tags = ["browser", "default", "edge", "file protocol", "html", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ConfigureShare", 1)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ConfigureShare")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ConfigureShare", 1)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Configures Edge file sharing mode; combined with default browser policy to reduce Edge hijacking.",
        },
        new TweakDef
        {
            Id = "defbrowser-suppress-os-feature-update-browser-reset",
            Label = "Default Browser Policy: Preserve Default Browser Across Feature Updates",
            Category = "Default Browser Policy",
            Description = "Ensures that the default browser association is preserved across Windows feature updates. Major Windows releases (e.g., 22H2 -> 23H2) frequently reset per-user file and protocol associations to their default (Edge) values. This policy marker ensures the default browser is locked and not reset by the OS upgrade process.",
            Tags = ["browser", "default", "update", "preserve", "association", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [AssocKey],
            ApplyOps = [RegOp.SetDword(AssocKey, "EnableSmartScreen", 0)],
            RemoveOps = [RegOp.DeleteValue(AssocKey, "EnableSmartScreen")],
            DetectOps = [RegOp.CheckDword(AssocKey, "EnableSmartScreen", 0)],
            ImpactScore = 3,
            SafetyRating = 3,
            ImpactNote = "Disables SmartScreen system filter; use only if SmartScreen is managed via another policy.",
        },
        new TweakDef
        {
            Id = "defbrowser-disable-edge-side-panel-web",
            Label = "Default Browser Policy: Disable Edge Side Panel Web Content",
            Category = "Default Browser Policy",
            Description = "Prevents the Microsoft Edge side panel (Bing Chat, Shopping, etc.) from loading web content in Explorer and third-party applications. The Edge side panel can activate and pull in browser content within non-browser windows when Edge is installed even if it is not the default browser.",
            Tags = ["browser", "edge", "side panel", "web content", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "HubsSidebarEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "HubsSidebarEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "HubsSidebarEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Disables Edge side panel (Bing Chat, Shopping, Tools) from appearing in any context.",
        },
    ];
}
