namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class DeviceLockGpoPolicy
{
    private const string PassportKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\PassportForWork";
    private const string DesktopKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop";
    private const string SystemKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "devlockgpo-disable-windows-hello-business",
            Label = "Device Lock GPO: Disable Windows Hello for Business Enrollment",
            Category = "Device Lock GPO Policy",
            Description = "Prevents users and devices from enrolling in Windows Hello for Business (WHfB), the enterprise PIN-based authentication system that replaces passwords with asymmetric-key credentials tied to the device TPM. In environments where smart cards or alternative MFA tokens are used instead of WHfB, disabling enrollment prevents credential proliferation.",
            Tags = ["windows hello", "pin", "mfa", "enrollment", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [PassportKey],
            ApplyOps = [RegOp.SetDword(PassportKey, "Enabled", 0)],
            RemoveOps = [RegOp.DeleteValue(PassportKey, "Enabled")],
            DetectOps = [RegOp.CheckDword(PassportKey, "Enabled", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Disables Windows Hello for Business on the device; standard Windows Hello (local PIN) is unaffected.",
        },
        new TweakDef
        {
            Id = "devlockgpo-disable-hello-post-logon-provisioning",
            Label = "Device Lock GPO: Disable Windows Hello Post-Logon Provisioning Prompt",
            Category = "Device Lock GPO Policy",
            Description = "Prevents Windows from launching the Windows Hello for Business provisioning wizard immediately after the first interactive logon. By default, Windows shows the WHfB setup screen right after AD/Azure AD join and logon. This policy suppresses that prompt so administrators can provision Windows Hello on a controlled schedule.",
            Tags = ["windows hello", "pin", "provisioning", "logon", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [PassportKey],
            ApplyOps = [RegOp.SetDword(PassportKey, "DisablePostLogonProvisioning", 1)],
            RemoveOps = [RegOp.DeleteValue(PassportKey, "DisablePostLogonProvisioning")],
            DetectOps = [RegOp.CheckDword(PassportKey, "DisablePostLogonProvisioning", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Suppresses the Windows Hello provisioning screen shown after first logon on new machines.",
        },
        new TweakDef
        {
            Id = "devlockgpo-disable-hello-pin-recovery",
            Label = "Device Lock GPO: Disable Windows Hello PIN Recovery Service",
            Category = "Device Lock GPO Policy",
            Description = "Disables the cloud-based Windows Hello PIN recovery service that allows users to reset their device PIN via their Microsoft account or Azure AD credentials. The PIN recovery service sends encrypted PIN reset data to Microsoft cloud servers. In high-security environments where no cloud dependencies are allowed, this service should be disabled.",
            Tags = ["windows hello", "pin", "recovery", "cloud", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [PassportKey],
            ApplyOps = [RegOp.SetDword(PassportKey, "DisablePinRecovery", 1)],
            RemoveOps = [RegOp.DeleteValue(PassportKey, "DisablePinRecovery")],
            DetectOps = [RegOp.CheckDword(PassportKey, "DisablePinRecovery", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Disables cloud PIN reset; users must reset via IT admin if they forget their PIN.",
        },
        new TweakDef
        {
            Id = "devlockgpo-require-tpm-for-hello",
            Label = "Device Lock GPO: Require TPM Chip for Windows Hello Credential Storage",
            Category = "Device Lock GPO Policy",
            Description = "Requires that Windows Hello for Business private keys be stored in the device's Trusted Platform Module (TPM) hardware security chip, not in software-only storage. Without a TPM requirement, WHfB keys are stored in software, making them vulnerable to extraction from disk. TPM binding ensures that private keys never leave the secure chip.",
            Tags = ["windows hello", "tpm", "security", "key storage", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [PassportKey],
            ApplyOps = [RegOp.SetDword(PassportKey, "RequireSecurityDevice", 1)],
            RemoveOps = [RegOp.DeleteValue(PassportKey, "RequireSecurityDevice")],
            DetectOps = [RegOp.CheckDword(PassportKey, "RequireSecurityDevice", 1)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Enforces TPM-based key storage; devices without a TPM cannot use Windows Hello for Business.",
        },
        new TweakDef
        {
            Id = "devlockgpo-require-screensaver-password",
            Label = "Device Lock GPO: Require Password When Resuming from Screen Saver",
            Category = "Device Lock GPO Policy",
            Description = "Forces Windows to require the user's password (or PIN) when resuming from a screen saver or after a period of inactivity. This is a foundational physical security control that prevents unauthorized access to unattended workstations. Without this policy, an unlocked workstation can be accessed by anyone who sits down at the keyboard.",
            Tags = ["screen saver", "lock", "password", "unattended", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DesktopKey],
            ApplyOps = [RegOp.SetString(DesktopKey, "ScreenSaverIsSecure", "1")],
            RemoveOps = [RegOp.DeleteValue(DesktopKey, "ScreenSaverIsSecure")],
            DetectOps = [RegOp.CheckString(DesktopKey, "ScreenSaverIsSecure", "1")],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Prevents access to unattended workstations after screen saver activates.",
        },
        new TweakDef
        {
            Id = "devlockgpo-enable-screensaver",
            Label = "Device Lock GPO: Enable Screen Saver (Enforce Lock on Idle)",
            Category = "Device Lock GPO Policy",
            Description = "Enables and enforces the screen saver policy on the workstation, ensuring that it activates after a configurable period of user inactivity. When combined with the ScreenSaverIsSecure policy, this guarantees all unattended workstations will automatically lock. Without this policy, users can disable the screen saver entirely, defeating the auto-lock mechanism.",
            Tags = ["screen saver", "enable", "idle", "lock", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DesktopKey],
            ApplyOps = [RegOp.SetString(DesktopKey, "ScreenSaveActive", "1")],
            RemoveOps = [RegOp.DeleteValue(DesktopKey, "ScreenSaveActive")],
            DetectOps = [RegOp.CheckString(DesktopKey, "ScreenSaveActive", "1")],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Enforces screen saver activation; prevents users from disabling the auto-lock mechanism.",
        },
        new TweakDef
        {
            Id = "devlockgpo-set-screensaver-timeout-600",
            Label = "Device Lock GPO: Set Screen Saver Timeout to 10 Minutes (600 s)",
            Category = "Device Lock GPO Policy",
            Description = "Sets the screen saver / auto-lock timeout to 600 seconds (10 minutes). Industry security frameworks (CIS, NIST SP 800-53, PCI DSS) recommend an idle timeout of 10–15 minutes for standard workstations. A 10-minute timeout balances security with productivity, locking unattended machines before a brief absence creates risk.",
            Tags = ["screen saver", "timeout", "idle", "lock", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DesktopKey],
            ApplyOps = [RegOp.SetString(DesktopKey, "ScreenSaveTimeOut", "600")],
            RemoveOps = [RegOp.DeleteValue(DesktopKey, "ScreenSaveTimeOut")],
            DetectOps = [RegOp.CheckString(DesktopKey, "ScreenSaveTimeOut", "600")],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "10-minute idle lock; CIS Benchmark recommended value for standard workstations.",
        },
        new TweakDef
        {
            Id = "devlockgpo-disable-lock-screen-notifications",
            Label = "Device Lock GPO: Disable Notifications on Lock Screen",
            Category = "Device Lock GPO Policy",
            Description = "Prevents Windows from displaying app notifications (toast notifications) on the lock screen. Lock-screen notifications can expose sensitive information to passersby — email previews, chat messages, calendar events — without requiring authentication. This policy disables all notification content from appearing while the screen is locked.",
            Tags = ["lock screen", "notifications", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "NoLockScreenNotificationsTitle", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "NoLockScreenNotificationsTitle")],
            DetectOps = [RegOp.CheckDword(SystemKey, "NoLockScreenNotificationsTitle", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Hides notification content on the lock screen; prevents data exposure to unauthenticated viewers.",
        },
        new TweakDef
        {
            Id = "devlockgpo-disable-camera-on-lockscreen",
            Label = "Device Lock GPO: Disable Camera Access on Lock Screen",
            Category = "Device Lock GPO Policy",
            Description = "Prevents cameras (webcams, built-in laptop cameras) from being activated while the workstation is locked. Some Windows Hello facial recognition implementations allow the camera to be used on the lock screen, but malicious code or physical manipulation could trigger unauthorized image capture. Disabling the camera on the lock screen closes this attack surface.",
            Tags = ["lock screen", "camera", "privacy", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "NoLockScreenCamera", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "NoLockScreenCamera")],
            DetectOps = [RegOp.CheckDword(SystemKey, "NoLockScreenCamera", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Disables camera hardware access from the lock screen; Windows Hello face recognition still works at login.",
        },
        new TweakDef
        {
            Id = "devlockgpo-disable-ease-access-on-lockscreen",
            Label = "Device Lock GPO: Disable Ease of Access Menu on Lock Screen",
            Category = "Device Lock GPO Policy",
            Description = "Removes the Ease of Access (accessibility) button from the Windows lock screen. The Ease of Access menu on the lock screen provides access to Narrator, Magnifier, and On-Screen Keyboard before authentication, which has historically been exploited to gain SYSTEM-level access through sticky-key and narrator command injection techniques on older Windows versions.",
            Tags = ["lock screen", "ease of access", "security", "accessibility", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "DisableLockScreenAppNotifications", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "DisableLockScreenAppNotifications")],
            DetectOps = [RegOp.CheckDword(SystemKey, "DisableLockScreenAppNotifications", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Removes app notifications from lock screen; does not affect standard accessibility tools at login.",
        },
    ];
}
