#nullable enable
using RegiLattice.Core.Models;

namespace RegiLattice.Core.Tweaks;

internal static class DeviceGuardPolicy
{
    private const string DgKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\DeviceGuard";

    public static IReadOnlyList<TweakDef> Tweaks =>
    [
        new TweakDef
        {
            Id = "devguard-enable-vbs",
            Label = "Enable Virtualization-Based Security (VBS)",
            Category = "Device Guard Policy",
            Description = "Enables Virtualization-Based Security, which uses the hypervisor to isolate critical security processes.",
            Tags = ["vbs", "device-guard", "virtualization", "security", "hyperv"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 5,
            SafetyRating = 3,
            ImpactNote = "Requires Hyper-V, UEFI, and Secure Boot; significant performance impact on systems without HVCI-capable hardware.",
            ApplyOps = [RegOp.SetDword(DgKey, "EnableVirtualizationBasedSecurity", 1)],
            RemoveOps = [RegOp.DeleteValue(DgKey, "EnableVirtualizationBasedSecurity")],
            DetectOps = [RegOp.CheckDword(DgKey, "EnableVirtualizationBasedSecurity", 1)],
        },
        new TweakDef
        {
            Id = "devguard-require-secure-boot-dma",
            Label = "Require Secure Boot and DMA Protection for VBS",
            Category = "Device Guard Policy",
            Description = "Requires Secure Boot and hardware DMA protection as platform security features for VBS to run.",
            Tags = ["vbs", "device-guard", "secure-boot", "dma", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 5,
            SafetyRating = 3,
            ImpactNote = "Value 3 = Secure Boot + DMA; requires appropriate firmware/hardware; VBS disabled without both features.",
            ApplyOps = [RegOp.SetDword(DgKey, "RequirePlatformSecurityFeatures", 3)],
            RemoveOps = [RegOp.DeleteValue(DgKey, "RequirePlatformSecurityFeatures")],
            DetectOps = [RegOp.CheckDword(DgKey, "RequirePlatformSecurityFeatures", 3)],
        },
        new TweakDef
        {
            Id = "devguard-enable-hvci",
            Label = "Enable Hypervisor-Enforced Code Integrity (HVCI)",
            Category = "Device Guard Policy",
            Description = "Enables Memory Integrity (HVCI) which uses the hypervisor to validate kernel code before execution.",
            Tags = ["hvci", "memory-integrity", "device-guard", "kernel", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 5,
            SafetyRating = 3,
            ImpactNote = "Value 2 = on without UEFI lock; blocks unsigned kernel drivers; may cause incompatibilities with legacy drivers.",
            ApplyOps = [RegOp.SetDword(DgKey, "HypervisorEnforcedCodeIntegrity", 2)],
            RemoveOps = [RegOp.DeleteValue(DgKey, "HypervisorEnforcedCodeIntegrity")],
            DetectOps = [RegOp.CheckDword(DgKey, "HypervisorEnforcedCodeIntegrity", 2)],
        },
        new TweakDef
        {
            Id = "devguard-require-uefi-mat",
            Label = "Require UEFI Memory Attributes Table for HVCI",
            Category = "Device Guard Policy",
            Description = "Requires the firmware to expose a UEFI Memory Attributes Table, enabling stricter HVCI enforcement.",
            Tags = ["hvci", "uefi", "mat", "device-guard", "firmware", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Ensures UEFI properly marks regions; old firmware without UEFI MAT will fail HVCI initialisation.",
            ApplyOps = [RegOp.SetDword(DgKey, "HVCIMATRequired", 1)],
            RemoveOps = [RegOp.DeleteValue(DgKey, "HVCIMATRequired")],
            DetectOps = [RegOp.CheckDword(DgKey, "HVCIMATRequired", 1)],
        },
        new TweakDef
        {
            Id = "devguard-enable-credential-guard",
            Label = "Enable Credential Guard",
            Category = "Device Guard Policy",
            Description = "Isolates NTLM hashes and Kerberos tickets inside a VBS-protected virtual machine to prevent Pass-the-Hash attacks.",
            Tags = ["credential-guard", "device-guard", "vbs", "lsa", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 5,
            SafetyRating = 3,
            ImpactNote = "Value 2 = enabled without UEFI lock (removable); requires VBS; breaks smart-card-only environments in some configs.",
            ApplyOps = [RegOp.SetDword(DgKey, "LsaCfgFlags", 2)],
            RemoveOps = [RegOp.DeleteValue(DgKey, "LsaCfgFlags")],
            DetectOps = [RegOp.CheckDword(DgKey, "LsaCfgFlags", 2)],
        },
        new TweakDef
        {
            Id = "devguard-enable-system-guard",
            Label = "Enable System Guard Secure Launch",
            Category = "Device Guard Policy",
            Description = "Enables System Guard Secure Launch to verify platform integrity at boot using Dynamic Root of Trust (DRTM).",
            Tags = ["system-guard", "drtm", "secure-launch", "device-guard", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Requires Intel TXT or AMD SKINIT; boot verified via secure measurement; no effect on unsupported hardware.",
            ApplyOps = [RegOp.SetDword(DgKey, "ConfigureSystemGuardLaunch", 1)],
            RemoveOps = [RegOp.DeleteValue(DgKey, "ConfigureSystemGuardLaunch")],
            DetectOps = [RegOp.CheckDword(DgKey, "ConfigureSystemGuardLaunch", 1)],
        },
        new TweakDef
        {
            Id = "devguard-enable-kernel-shadow-stack",
            Label = "Enable Kernel Mode Hardware-Enforced Stack Protection",
            Category = "Device Guard Policy",
            Description = "Activates Hardware-Enforced Call Stack Protection (CET Shadow Stack) for kernel mode to resist ROP attacks.",
            Tags = ["cet", "shadow-stack", "device-guard", "kernel", "security", "rop"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Requires Intel CET (Tiger Lake+) or AMD equivalent; blocks ROP/JOP exploits in kernel; may conflict with old drivers.",
            ApplyOps = [RegOp.SetDword(DgKey, "ConfigureKernelShadowStacksLaunchControl", 1)],
            RemoveOps = [RegOp.DeleteValue(DgKey, "ConfigureKernelShadowStacksLaunchControl")],
            DetectOps = [RegOp.CheckDword(DgKey, "ConfigureKernelShadowStacksLaunchControl", 1)],
        },
        new TweakDef
        {
            Id = "devguard-enable-hvci-audit-mode",
            Label = "Disable HVCI Audit Mode (Enforce Mode)",
            Category = "Device Guard Policy",
            Description = "Ensures HVCI operates in enforcement mode rather than audit-only mode for active code integrity protection.",
            Tags = ["hvci", "audit-mode", "device-guard", "enforce", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Audit mode only logs violations; enforce mode blocks them. Disabling audit ensures active protection.",
            ApplyOps = [RegOp.SetDword(DgKey, "HypervisorEnforcedCodeIntegrityAuditModeEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(DgKey, "HypervisorEnforcedCodeIntegrityAuditModeEnabled")],
            DetectOps = [RegOp.CheckDword(DgKey, "HypervisorEnforcedCodeIntegrityAuditModeEnabled", 0)],
        },
        new TweakDef
        {
            Id = "devguard-block-unsigned-drivers",
            Label = "Block Unsigned Kernel Drivers via Policy",
            Category = "Device Guard Policy",
            Description = "Prevents loading of unsigned kernel-mode drivers, supplementing HVCI at the policy layer.",
            Tags = ["device-guard", "drivers", "signing", "kernel", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Blocks unsigned drivers; WHQL or Microsoft signing required; may break niche hardware with unsigned drivers.",
            ApplyOps = [RegOp.SetDword(DgKey, "RequireDriverSignature", 1)],
            RemoveOps = [RegOp.DeleteValue(DgKey, "RequireDriverSignature")],
            DetectOps = [RegOp.CheckDword(DgKey, "RequireDriverSignature", 1)],
        },
        new TweakDef
        {
            Id = "devguard-audit-device-guard-status",
            Label = "Enable Device Guard Status Auditing",
            Category = "Device Guard Policy",
            Description = "Logs Device Guard and Credential Guard startup status to the event log for compliance monitoring.",
            Tags = ["device-guard", "audit", "logging", "compliance", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Writes Device Guard status events at boot; purely informational, no security side effects.",
            ApplyOps = [RegOp.SetDword(DgKey, "AuditDeviceGuardStatus", 1)],
            RemoveOps = [RegOp.DeleteValue(DgKey, "AuditDeviceGuardStatus")],
            DetectOps = [RegOp.CheckDword(DgKey, "AuditDeviceGuardStatus", 1)],
        },
    ];
}
