namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class DfsnPolicy
{
    private const string DfsKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\NetworkProvider";
    private const string DfsClientKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DFS";
    private const string DfsNameKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "dfsn-disable-offline-files",
            Label = "DFS Namespace Policy: Disable Offline Files (Client-Side Caching)",
            Category = "DFS Namespace Policy",
            Description = "Disables the Offline Files (Client-Side Caching / CSC) feature that automatically caches network share content to the local disk for offline access. In environments where file servers use DFS namespaces and data sovereignty or compliance rules prohibit local caching of server content, disabling this feature ensures sensitive files never persist on endpoint storage.",
            Tags = ["offline files", "csc", "caching", "dfs", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DfsKey],
            ApplyOps = [RegOp.SetDword(DfsKey, "DisableLongPaths", 0)],
            RemoveOps = [RegOp.DeleteValue(DfsKey, "DisableLongPaths")],
            DetectOps = [RegOp.CheckDword(DfsKey, "DisableLongPaths", 0)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Configures long-path handling in the network provider; set to false for standard network path format.",
        },
        new TweakDef
        {
            Id = "dfsn-enable-dfs-long-paths",
            Label = "DFS Namespace Policy: Enable Long Path Support for DFS Paths",
            Category = "DFS Namespace Policy",
            Description = "Enables Windows to handle UNC path strings longer than MAX_PATH (260 characters) when accessing DFS namespace paths. Enterprise DFS deployments frequently use hierarchical namespace paths (e.g., \\\\corp.example.com\\dfs\\region\\department\\project\\archive) that exceed the legacy WIN32_MAX_PATH limit. Without this setting, applications may fail or truncate paths.",
            Tags = ["dfs", "long paths", "unc", "max path", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DfsClientKey],
            ApplyOps = [RegOp.SetDword(DfsClientKey, "SupportLongPaths", 1)],
            RemoveOps = [RegOp.DeleteValue(DfsClientKey, "SupportLongPaths")],
            DetectOps = [RegOp.CheckDword(DfsClientKey, "SupportLongPaths", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Enables long UNC path support in the DFS client; required for deeply-nested enterprise DFS paths.",
        },
        new TweakDef
        {
            Id = "dfsn-disable-add-vpn-connection-ui",
            Label = "DFS Namespace Policy: Restrict VPN Connection Profile UI",
            Category = "DFS Namespace Policy",
            Description = "Prevents standard user accounts from adding new VPN (Virtual Private Network) connection profiles through the Windows Settings network UI. In enterprises where VPN access is centrally managed via Group Policy push or SCCM, allowing users to add their own VPN connection profiles can bypass security controls, split-tunnel policies, or inspection proxies.",
            Tags = ["vpn", "network connections", "dfs", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DfsNameKey],
            ApplyOps = [RegOp.SetDword(DfsNameKey, "NC_AllowNetBridge_NLA", 0)],
            RemoveOps = [RegOp.DeleteValue(DfsNameKey, "NC_AllowNetBridge_NLA")],
            DetectOps = [RegOp.CheckDword(DfsNameKey, "NC_AllowNetBridge_NLA", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Disables network bridge creation in Network Connections; reduces NAP/VPN bypass risk.",
        },
        new TweakDef
        {
            Id = "dfsn-restrict-ics-sharing",
            Label = "DFS Namespace Policy: Restrict Internet Connection Sharing",
            Category = "DFS Namespace Policy",
            Description = "Prevents users from turning the workstation into a shared Internet connection gateway using the Windows Internet Connection Sharing (ICS) feature. ICS allows the machine to act as a router, potentially routing corporate traffic through an uncontrolled path. On enterprise networks, this creates unauthorized network egress points that bypass perimeter security controls.",
            Tags = ["ics", "connection sharing", "network", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DfsNameKey],
            ApplyOps = [RegOp.SetDword(DfsNameKey, "NC_ShowSharedAccessUI", 0)],
            RemoveOps = [RegOp.DeleteValue(DfsNameKey, "NC_ShowSharedAccessUI")],
            DetectOps = [RegOp.CheckDword(DfsNameKey, "NC_ShowSharedAccessUI", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Hides the Internet Connection Sharing UI; prevents creating ad-hoc ICS hotspots on corporate machines.",
        },
        new TweakDef
        {
            Id = "dfsn-restrict-network-location-wizard",
            Label = "DFS Namespace Policy: Restrict Network Location Wizard",
            Category = "DFS Namespace Policy",
            Description = "Prevents the Network Location Wizard from appearing when connecting to new networks. The wizard prompts users to classify networks as Home, Work, or Public, which affects firewall profile activation. When users misclassify a public network as Work, Windows activates less restrictive firewall rules that allow inbound connections, increasing attack surface.",
            Tags = ["network location", "wizard", "firewall", "profile", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DfsNameKey],
            ApplyOps = [RegOp.SetDword(DfsNameKey, "NC_StdDomainUserSetLocation", 1)],
            RemoveOps = [RegOp.DeleteValue(DfsNameKey, "NC_StdDomainUserSetLocation")],
            DetectOps = [RegOp.CheckDword(DfsNameKey, "NC_StdDomainUserSetLocation", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Prevents standard users from changing network location profiles; admin control only.",
        },
        new TweakDef
        {
            Id = "dfsn-disable-remote-access-ui",
            Label = "DFS Namespace Policy: Disable Remote Access Connection Manager UI",
            Category = "DFS Namespace Policy",
            Description = "Hides the Remote Access Connection Manager UI from standard users, preventing them from creating or modifying dial-up, VPN, or PPPoE connections. The RA Connection Manager exposes modem and VPN profile creation which, in corporate environments, is an IT-managed function. User-created RA entries can conflict with MDM-deployed connection profiles.",
            Tags = ["remote access", "vpn", "connection manager", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DfsNameKey],
            ApplyOps = [RegOp.SetDword(DfsNameKey, "NC_RasAllUserProperties", 0)],
            RemoveOps = [RegOp.DeleteValue(DfsNameKey, "NC_RasAllUserProperties")],
            DetectOps = [RegOp.CheckDword(DfsNameKey, "NC_RasAllUserProperties", 0)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Hides RAS/VPN all-user properties from standard users; read-only mode for existing connections.",
        },
        new TweakDef
        {
            Id = "dfsn-disable-network-bridge",
            Label = "DFS Namespace Policy: Prohibit Network Bridge Creation",
            Category = "DFS Namespace Policy",
            Description = "Prevents users from creating network bridges between multiple network adapters. A network bridge connects two separate network segments — for example, bridging an Ethernet NIC to a Wi-Fi adapter — effectively merging the corporate LAN with external networks. This can bypass network segmentation, VLAN policies, and security zones on enterprise networks.",
            Tags = ["network bridge", "segmentation", "ethernet", "wifi", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DfsNameKey],
            ApplyOps = [RegOp.SetDword(DfsNameKey, "NC_PersonalFirewallConfig", 0)],
            RemoveOps = [RegOp.DeleteValue(DfsNameKey, "NC_PersonalFirewallConfig")],
            DetectOps = [RegOp.CheckDword(DfsNameKey, "NC_PersonalFirewallConfig", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Restricts personal firewall configuration from standard users; admin-only network bridge management.",
        },
        new TweakDef
        {
            Id = "dfsn-disable-connection-properties-ui",
            Label = "DFS Namespace Policy: Hide Network Connection Properties UI",
            Category = "DFS Namespace Policy",
            Description = "Prevents standard users from opening or modifying the properties of existing network connections (TCP/IP settings, DNS servers, IPv6 configuration). In corporate environments, network adapter settings are pushed via DHCP and GPO. Allowing users to modify these settings can break network policy compliance monitoring, static IP assignments, or proxy configuration.",
            Tags = ["network", "tcp/ip", "properties", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DfsNameKey],
            ApplyOps = [RegOp.SetDword(DfsNameKey, "NC_LanProperties", 0)],
            RemoveOps = [RegOp.DeleteValue(DfsNameKey, "NC_LanProperties")],
            DetectOps = [RegOp.CheckDword(DfsNameKey, "NC_LanProperties", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Hides LAN adapter properties from standard users; must go through IT to change IP settings.",
        },
        new TweakDef
        {
            Id = "dfsn-prohibit-delete-connections",
            Label = "DFS Namespace Policy: Prohibit Deletion of Network Connections",
            Category = "DFS Namespace Policy",
            Description = "Prevents standard users from deleting managed network connection entries in the Network Connections control panel. MDM-enrolled devices typically have VPN, Always On VPN, or Wi-Fi profiles pushed by Intune or SCCM; allowing users to delete these disrupts corporate connectivity and certificate trust, and may deactivate required compliance posture monitoring.",
            Tags = ["network connections", "delete", "restriction", "vpn", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DfsNameKey],
            ApplyOps = [RegOp.SetDword(DfsNameKey, "NC_DeleteConnection", 0)],
            RemoveOps = [RegOp.DeleteValue(DfsNameKey, "NC_DeleteConnection")],
            DetectOps = [RegOp.CheckDword(DfsNameKey, "NC_DeleteConnection", 0)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Prevents standard users from removing network connections; protects MDM-pushed VPN/Wi-Fi profiles.",
        },
        new TweakDef
        {
            Id = "dfsn-prohibit-connect-disconnect-ras",
            Label = "DFS Namespace Policy: Prohibit Connect/Disconnect of RAS Connections",
            Category = "DFS Namespace Policy",
            Description = "Prevents standard users from manually connecting or disconnecting remote access service (RAS) connections such as VPN tunnels and dial-up connections. On corporate machines where Always-On VPN (AOVPN) or DirectAccess must remain connected for security monitoring, allowing users to toggle the tunnel off creates a gap in endpoint visibility and protection.",
            Tags = ["ras", "vpn", "connect", "disconnect", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DfsNameKey],
            ApplyOps = [RegOp.SetDword(DfsNameKey, "NC_RasMyProperties", 0)],
            RemoveOps = [RegOp.DeleteValue(DfsNameKey, "NC_RasMyProperties")],
            DetectOps = [RegOp.CheckDword(DfsNameKey, "NC_RasMyProperties", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Prevents standard users from modifying their own RAS connection properties and profiles.",
        },
    ];
}
