namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class Display
{
    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "display-disable-dpi-scaling",
            Label = "Disable DPI Scaling Override",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Enables the Windows 8-style DPI scaling override, forcing the system DPI setting for all applications.",
            Tags = ["display", "dpi", "scaling"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "Win8DpiScaling", 1)],
            RemoveOps =
            [
                RegOp.DeleteValue(@"HKEY_CURRENT_USER\Control Panel\Desktop", "DpiScalingVer"),
                RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "Win8DpiScaling", 0),
            ],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "Win8DpiScaling", 1)],
        },
        new TweakDef
        {
            Id = "display-enable-cleartype",
            Label = "Enable ClearType Font Smoothing",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Enables ClearType sub-pixel font rendering for sharper text on LCD screens.",
            Tags = ["display", "cleartype", "font", "smoothing"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps =
            [
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "FontSmoothing", "2"),
                RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "FontSmoothingType", 2),
            ],
            RemoveOps =
            [
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "FontSmoothing", "0"),
                RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "FontSmoothingType", 0),
            ],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "FontSmoothingType", 2)],
        },
        new TweakDef
        {
            Id = "display-force-96dpi",
            Label = "Force 96 DPI (100% Scaling)",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Forces the display to use 96 DPI (100% scaling), disabling any high-DPI scaling that Windows may apply.",
            Tags = ["display", "dpi", "scaling", "96dpi"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "LogPixels", 96)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Control Panel\Desktop", "LogPixels")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "LogPixels", 96)],
        },
        new TweakDef
        {
            Id = "display-dark-mode-apps",
            Label = "Dark Mode for Apps",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Switches UWP and modern apps to their dark colour scheme.",
            Tags = ["display", "dark", "theme", "apps"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "AppsUseLightTheme", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "AppsUseLightTheme", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "AppsUseLightTheme", 0)],
        },
        new TweakDef
        {
            Id = "display-dark-mode-system",
            Label = "Dark Mode for System",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Switches the Windows system theme (taskbar, Start menu, Action Center) to dark mode.",
            Tags = ["display", "dark", "theme", "system"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "SystemUsesLightTheme", 0)],
            RemoveOps =
            [
                RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "SystemUsesLightTheme", 1),
            ],
            DetectOps =
            [
                RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "SystemUsesLightTheme", 0),
            ],
        },
        new TweakDef
        {
            Id = "display-disable-transparency",
            Label = "Disable Transparency Effects",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables the acrylic/blur transparency effects on the taskbar, Start menu, and window backgrounds.",
            Tags = ["display", "transparency", "performance", "visual"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "EnableTransparency", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "EnableTransparency", 1)],
            DetectOps =
            [
                RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "EnableTransparency", 0),
            ],
        },
        new TweakDef
        {
            Id = "display-disable-animations",
            Label = "Disable Window Animations",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables minimize and maximize window animations for snappier window management.",
            Tags = ["display", "animation", "performance", "visual"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "MinAnimate", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "MinAnimate", "1")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "MinAnimate", "0")],
        },
        new TweakDef
        {
            Id = "display-disable-wallpaper-compression",
            Label = "Disable Wallpaper JPEG Compression",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets wallpaper JPEG import quality to 100%, preventing Windows from compressing desktop wallpapers.",
            Tags = ["display", "wallpaper", "quality", "compression"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "JPEGImportQuality", 100)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Control Panel\Desktop", "JPEGImportQuality")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "JPEGImportQuality", 100)],
        },
        new TweakDef
        {
            Id = "display-accent-title-bars",
            Label = "Accent Color on Title Bars",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Shows the Windows accent colour on title bars and window borders.",
            Tags = ["display", "accent", "color", "titlebar", "dwm"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "ColorPrevalence", 1)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "ColorPrevalence", 0)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "ColorPrevalence", 1)],
        },
        new TweakDef
        {
            Id = "display-disable-edge-swipe",
            Label = "Disable Screen Edge Swipe",
            Category = "Display",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables the screen edge swipe gesture that opens the Charms bar or Action Center on touch devices.",
            Tags = ["display", "edge", "swipe", "gesture", "touch"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EdgeUI"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EdgeUI", "AllowEdgeSwipe", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EdgeUI", "AllowEdgeSwipe")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\EdgeUI", "AllowEdgeSwipe", 0)],
        },
        new TweakDef
        {
            Id = "display-disable-adaptive-brightness",
            Label = "Disable Adaptive Brightness",
            Category = "Display",
            NeedsAdmin = true,
            CorpSafe = true,
            Description =
                "Disables the Adaptive Brightness sensor service. Prevents automatic screen brightness changes based on ambient light. Default: Enabled (3=Manual). Recommended: Disabled (4).",
            Tags = ["display", "brightness", "adaptive", "performance"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SensrSvc"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SensrSvc", "Start", 4)],
            RemoveOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SensrSvc", "Start", 3)],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SensrSvc", "Start", 4)],
        },
        new TweakDef
        {
            Id = "display-dpi-override",
            Label = "Set Display Scaling DPI Override",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Forces display scaling to 100% (96 DPI) using the legacy DPI override. Disables DPI virtualization for crisp rendering. Default: System-managed. Recommended: 96 DPI for external monitors.",
            Tags = ["display", "dpi", "scaling", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps =
            [
                RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "Win8DpiScaling", 1),
                RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "LogPixels", 96),
            ],
            RemoveOps =
            [
                RegOp.DeleteValue(@"HKEY_CURRENT_USER\Control Panel\Desktop", "Win8DpiScaling"),
                RegOp.DeleteValue(@"HKEY_CURRENT_USER\Control Panel\Desktop", "LogPixels"),
            ],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "Win8DpiScaling", 1)],
        },
        new TweakDef
        {
            Id = "display-disable-adaptive-brightness-icm",
            Label = "Disable Adaptive Brightness (ICM)",
            Category = "Display",
            NeedsAdmin = true,
            CorpSafe = true,
            Description =
                "Disables adaptive brightness via ICM display calibration. Prevents automatic brightness adjustments based on content. Default: Enabled. Recommended: Disabled for consistent brightness.",
            Tags = ["display", "brightness", "icm", "calibration"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ICM\Calibration"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SensrSvc", "Start", 4)],
            RemoveOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SensrSvc", "Start", 3)],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SensrSvc", "Start", 4)],
        },
        new TweakDef
        {
            Id = "display-hardware-cursor",
            Label = "Force Hardware Cursor",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Forces hardware cursor rendering and disables smooth scrolling. Reduces input lag and cursor rendering overhead. Default: Smooth scrolling on. Recommended: Hardware cursor for gaming.",
            Tags = ["display", "cursor", "hardware", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "SmoothScroll", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "SmoothScroll", "1")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "SmoothScroll", "0")],
        },
        new TweakDef
        {
            Id = "display-disable-transparency-effect",
            Label = "Disable Window Transparency Effect",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables window transparency and acrylic blur effects. Improves rendering performance on integrated GPUs. Default: Enabled. Recommended: Disabled for performance.",
            Tags = ["display", "transparency", "acrylic", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "EnableTransparency", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "EnableTransparency", 1)],
            DetectOps =
            [
                RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "EnableTransparency", 0),
            ],
        },
        new TweakDef
        {
            Id = "display-force-gpu-scaling",
            Label = "Force GPU Scaling Mode",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Enables GPU-based DPI scaling (Win8DpiScaling) for sharper rendering on non-native resolutions. Default: Disabled. Recommended: Enabled for high-DPI displays.",
            Tags = ["display", "gpu", "scaling", "dpi", "rendering"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "Win8DpiScaling", 1)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "Win8DpiScaling", 0)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "Win8DpiScaling", 1)],
        },
        new TweakDef
        {
            Id = "display-disable-auto-color-mgmt",
            Label = "Disable Auto Color Management",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables Windows Desktop Window Manager automatic color management for manual ICC profile control. Default: Enabled. Recommended: Disabled for color-critical work.",
            Tags = ["display", "color", "management", "dwm", "icc"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "EnableAutoColorManagement", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "EnableAutoColorManagement")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "EnableAutoColorManagement", 0)],
        },
        new TweakDef
        {
            Id = "display-disable-cursor-shadow",
            Label = "Disable Cursor Drop Shadow",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Removes the drop shadow rendered under the mouse cursor. Very slightly reduces compositor workload. Default: Enabled.",
            Tags = ["display", "cursor", "shadow", "performance", "rendering"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CursorShadow", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CursorShadow", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CursorShadow", 0)],
        },
        new TweakDef
        {
            Id = "display-reduce-blur-intensity",
            Label = "Reduce DWM Blur Intensity (50%)",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Sets the DWM blur-behind intensity to 50. Reduces the visual weight of frosted-glass Mica/Acrylic effects. Default: Not set (OS default full blur).",
            Tags = ["display", "dwm", "blur", "aero", "visual"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "BlurIntensity", 50)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "BlurIntensity")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "BlurIntensity", 50)],
        },
        new TweakDef
        {
            Id = "display-force-aero-composition",
            Label = "Force Desktop Composition (Aero)",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Explicitly enables Desktop Window Manager composition (Aero). Ensures DWM is active even on systems where it was manually disabled. Default: Enabled.",
            Tags = ["display", "dwm", "aero", "composition", "visual"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "Composition", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "Composition")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "Composition", 1)],
        },
        new TweakDef
        {
            Id = "display-disable-hdr-streaming",
            Label = "Disable HDR Streaming",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables HDR video streaming. Prevents auto-HDR tone mapping for streaming content. Default: enabled if HDR supported.",
            Tags = ["display", "hdr", "streaming", "video"],
            RegistryKeys = [@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\VideoSettings"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\VideoSettings", "EnableHDRForPlayback", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\VideoSettings", "EnableHDRForPlayback")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\VideoSettings", "EnableHDRForPlayback", 0)],
        },
        new TweakDef
        {
            Id = "display-disable-auto-color-management",
            Label = "Disable Auto Color Management",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables Windows auto color management. Use when accurate colors are managed by a dedicated ICC profile. Default: enabled.",
            Tags = ["display", "color", "management", "icc"],
            RegistryKeys = [@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\AutoColorManagement"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\AutoColorManagement", "Enable", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\AutoColorManagement", "Enable")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\AutoColorManagement", "Enable", 0)],
        },
        new TweakDef
        {
            Id = "display-disable-window-animations",
            Label = "Disable Window Animations",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables minimize/maximize window animations. Makes window transitions instant. Default: animated.",
            Tags = ["display", "animation", "window", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "MinAnimate", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "MinAnimate", "1")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "MinAnimate", "0")],
        },
        new TweakDef
        {
            Id = "display-disable-cursor-blink",
            Label = "Disable Cursor Blink",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets the cursor blink rate to infinite (non-blinking). Reduces minor CPU/GPU load. Default: 530ms blink.",
            Tags = ["display", "cursor", "blink", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CursorBlinkRate", "-1")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CursorBlinkRate", "530")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CursorBlinkRate", "-1")],
        },
        new TweakDef
        {
            Id = "display-set-dpi-scaling-override",
            Label = "Force Per-Monitor DPI Awareness",
            Category = "Display",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Forces per-monitor DPI awareness for legacy applications system-wide. Reduces blurry scaling. Default: system-aware.",
            Tags = ["display", "dpi", "scaling", "per-monitor"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\SideBySide", "PreferExternalManifest", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\SideBySide", "PreferExternalManifest")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\SideBySide", "PreferExternalManifest", 1)],
        },
        new TweakDef
        {
            Id = "display-disable-animation-effects",
            Label = "Disable Window Animation Effects",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables window minimize/maximize and transition animation effects. Snappier window management. Default: animated.",
            Tags = ["display", "animation", "effects", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "MinAnimate", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "MinAnimate", "1")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "MinAnimate", "0")],
        },
        new TweakDef
        {
            Id = "display-disable-screensaver-policy",
            Label = "Disable Screen Saver via Policy",
            Category = "Display",
            NeedsAdmin = true,
            CorpSafe = true,
            Description =
                "Disables screen saver activation via Group Policy. Prevents screen saver from interrupting work. Default: user-controlled.",
            Tags = ["display", "screensaver", "policy", "disable"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetString(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop", "ScreenSaveActive", "0")],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop", "ScreenSaveActive")],
            DetectOps = [RegOp.CheckString(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop", "ScreenSaveActive", "0")],
        },
        new TweakDef
        {
            Id = "display-set-font-smoothing-gamma",
            Label = "Set Font Smoothing Gamma",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Sets the ClearType font smoothing gamma correction to optimal value. Improves text rendering contrast on LCD displays. Default: system default.",
            Tags = ["display", "font", "gamma", "cleartype"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "FontSmoothingGamma", 1400)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Control Panel\Desktop", "FontSmoothingGamma")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "FontSmoothingGamma", 1400)],
        },
        new TweakDef
        {
            Id = "display-increase-icon-spacing-horizontal",
            Label = "Increase Horizontal Icon Spacing",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Increases horizontal icon spacing on the desktop from the default -1125 to -1500 twips. Reduces icon overlap on high-DPI displays.",
            Tags = ["display", "icons", "spacing", "desktop"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "IconSpacing", "-1500")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "IconSpacing", "-1125")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "IconSpacing", "-1500")],
        },
        new TweakDef
        {
            Id = "display-increase-icon-spacing-vertical",
            Label = "Increase Vertical Icon Spacing",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Increases vertical icon spacing on the desktop from the default -1125 to -1500 twips. Reduces icon overlap on high-DPI displays.",
            Tags = ["display", "icons", "spacing", "desktop"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "IconVerticalSpacing", "-1500")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "IconVerticalSpacing", "-1125")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "IconVerticalSpacing", "-1500")],
        },
        new TweakDef
        {
            Id = "display-set-scrollbar-width",
            Label = "Set Narrow Scrollbar Width",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Reduces the scrollbar width from the default -255 to -200 twips. Gives more screen real estate for content. Requires logoff.",
            Tags = ["display", "scrollbar", "width", "compact"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "ScrollWidth", "-200")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "ScrollWidth", "-255")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "ScrollWidth", "-200")],
        },
        new TweakDef
        {
            Id = "display-set-scrollbar-height",
            Label = "Set Narrow Scrollbar Height",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces the horizontal scrollbar height from the default -255 to -200 twips. More compact UI. Requires logoff.",
            Tags = ["display", "scrollbar", "height", "compact"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "ScrollHeight", "-200")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "ScrollHeight", "-255")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "ScrollHeight", "-200")],
        },
        new TweakDef
        {
            Id = "display-set-border-width",
            Label = "Set Thin Window Border",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces the window border width from the default -15 to -1 twips for a thinner, modern look. Requires logoff.",
            Tags = ["display", "border", "width", "thin"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "BorderWidth", "-1")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "BorderWidth", "-15")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "BorderWidth", "-1")],
        },
        new TweakDef
        {
            Id = "display-disable-window-shake",
            Label = "Disable Aero Shake (Minimize All)",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables the Aero Shake feature that minimizes all other windows when shaking a title bar. Prevents accidental minimization.",
            Tags = ["display", "aero", "shake", "minimize"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisallowShaking", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisallowShaking")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced", "DisallowShaking", 1)],
        },
        new TweakDef
        {
            Id = "display-set-menu-show-delay",
            Label = "Reduce Menu Show Delay to 50ms",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces the submenu popup delay from 400ms to 50ms. Makes menus feel more responsive.",
            Tags = ["display", "menu", "delay", "speed"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "MenuShowDelay", "50")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "MenuShowDelay", "400")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "MenuShowDelay", "50")],
        },
        new TweakDef
        {
            Id = "display-enable-text-cursor-indicator",
            Label = "Enable Text Cursor Indicator",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Enables a coloured visual indicator at the text cursor position. Improves cursor visibility in dense text.",
            Tags = ["display", "cursor", "indicator", "accessibility"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Accessibility"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Accessibility", "Configuration", 1)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Accessibility", "Configuration")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Accessibility", "Configuration", 1)],
        },
        new TweakDef
        {
            Id = "display-set-tooltip-initial-delay",
            Label = "Reduce Tooltip Initial Delay",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces the initial tooltip popup delay from 400ms to 100ms. Shows hover info faster.",
            Tags = ["display", "tooltip", "delay", "speed"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverTime", "100")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverTime", "400")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverTime", "100")],
        },
        new TweakDef
        {
            Id = "display-enable-dark-mode-system",
            Label = "Force System Dark Mode",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Forces system-wide dark mode for the Windows shell (taskbar, Start menu, Action Center). Default: follows user preference.",
            Tags = ["display", "dark", "mode", "theme"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "SystemUsesLightTheme", 0)],
            RemoveOps =
            [
                RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "SystemUsesLightTheme", 1),
            ],
            DetectOps =
            [
                RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize", "SystemUsesLightTheme", 0),
            ],
        },
        // ── Sprint 19 additions ────────────────────────────────────────────
        new TweakDef
        {
            Id = "display-disable-windows-ink-workspace",
            Label = "Disable Windows Ink Workspace",
            Category = "Display",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables the Windows Ink Workspace overlay. Removes the pen/ink button from the taskbar area. Default: enabled.",
            Tags = ["display", "ink", "workspace", "disable"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace", "AllowWindowsInkWorkspace", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace", "AllowWindowsInkWorkspace")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace", "AllowWindowsInkWorkspace", 0)],
        },
        new TweakDef
        {
            Id = "display-force-disable-hdr",
            Label = "Force Disable HDR",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Forces HDR to be disabled system-wide. Useful for monitors that don't support HDR properly. Default: auto-detect.",
            Tags = ["display", "hdr", "disable"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\VideoSettings"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\VideoSettings", "EnableHDRForPlayback", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\VideoSettings", "EnableHDRForPlayback")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\VideoSettings", "EnableHDRForPlayback", 0)],
        },
        new TweakDef
        {
            Id = "display-enable-high-contrast-mode",
            Label = "Enable High Contrast Mode",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Enables Windows High Contrast accessibility mode for better visibility. Default: disabled.",
            Tags = ["display", "accessibility", "high-contrast"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Accessibility\HighContrast"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\HighContrast", "Flags", "127")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\HighContrast", "Flags", "0")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\HighContrast", "Flags", "127")],
        },
        new TweakDef
        {
            Id = "display-set-color-depth-32bit",
            Label = "Force 32-bit Color Depth",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets the desktop color depth to 32-bit (True Color). Ensures maximum color quality. Default: 32-bit on most systems.",
            Tags = ["display", "color", "depth", "32bit"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "ShellIconBPP", "32")],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "ShellIconBPP")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "ShellIconBPP", "32")],
        },
        new TweakDef
        {
            Id = "display-disable-auto-rotation",
            Label = "Disable Auto-Rotation",
            Category = "Display",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables automatic screen rotation on tablets and convertible laptops. Default: enabled on tablets.",
            Tags = ["display", "rotation", "tablet", "disable"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AutoRotation"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AutoRotation", "Enable", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AutoRotation", "Enable", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AutoRotation", "Enable", 0)],
        },
        new TweakDef
        {
            Id = "display-set-caption-button-height",
            Label = "Increase Title Bar Button Height",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Increases the height of window title bar caption buttons (minimize/maximize/close) for easier targeting. Default: -270.",
            Tags = ["display", "titlebar", "caption", "height"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "CaptionHeight", "-330")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "CaptionHeight", "-270")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics", "CaptionHeight", "-330")],
        },
        new TweakDef
        {
            Id = "display-disable-mouse-hover-select",
            Label = "Disable Mouse Hover Window Activation",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Prevents windows from activating when the mouse hovers over them (X-Mouse behaviour). Default: disabled.",
            Tags = ["display", "mouse", "hover", "activation"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "ActiveWndTrkMouse", "0")],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Control Panel\Desktop", "ActiveWndTrkMouse")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "ActiveWndTrkMouse", "0")],
        },
        new TweakDef
        {
            Id = "display-force-full-screen-optimize",
            Label = "Disable Fullscreen Optimizations Globally",
            Category = "Display",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables Windows fullscreen optimizations system-wide. Can improve performance in legacy games. Default: enabled.",
            Tags = ["display", "fullscreen", "optimization", "gaming"],
            RegistryKeys = [@"HKEY_CURRENT_USER\System\GameConfigStore"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\System\GameConfigStore", "GameDVR_FSEBehaviorMode", 2)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\System\GameConfigStore", "GameDVR_FSEBehaviorMode")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\System\GameConfigStore", "GameDVR_FSEBehaviorMode", 2)],
        },
        new TweakDef
        {
            Id = "display-set-menu-animation-fade",
            Label = "Set Menu Animation to Fade",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets menu animation style to fade instead of scroll. Feels smoother on modern hardware. Default: scroll.",
            Tags = ["display", "menu", "animation", "fade"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "MenuAnimation", "1")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "MenuAnimation", "0")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "MenuAnimation", "1")],
        },
        new TweakDef
        {
            Id = "display-disable-peek-desktop",
            Label = "Disable Aero Peek at Desktop",
            Category = "Display",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables the Aero Peek feature that shows the desktop when hovering over the Show Desktop button. Default: enabled.",
            Tags = ["display", "peek", "desktop", "aero"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "EnableAeroPeek", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "EnableAeroPeek", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM", "EnableAeroPeek", 0)],
        },
    ];
}
