namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class DotNetFrameworkPolicy
{
    private const string DotNetKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\.NETFramework";
    private const string DotNetUserKey = @"HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\.NETFramework";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "dotnet-disable-authenticode-publisher-prompt",
            Label = ".NET Framework Policy: Disable Authenticode Publisher Trust Prompt",
            Category = ".NET Framework Policy",
            Description = "Prevents the Authenticode publisher trust dialog from appearing when running .NET applications that are not signed by a trusted publisher. The dialog asks users whether to trust the publisher; allowing untrained users to click through this prompt grants blanket trust to potentially malicious assemblies signed by unknown or compromised certificates.",
            Tags = [".net", "authenticode", "trust", "publisher", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DotNetKey],
            ApplyOps = [RegOp.SetDword(DotNetKey, "AllPublishers", 0)],
            RemoveOps = [RegOp.DeleteValue(DotNetKey, "AllPublishers")],
            DetectOps = [RegOp.CheckDword(DotNetKey, "AllPublishers", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Prevents broad publisher trust grants; untrusted .NET apps will be blocked rather than prompted.",
        },
        new TweakDef
        {
            Id = "dotnet-disable-clickonce-publisher-prompt",
            Label = ".NET Framework Policy: Disable ClickOnce Untrusted Publisher Prompt",
            Category = ".NET Framework Policy",
            Description = "Prevents ClickOnce deployment applications from showing a trust elevation prompt when the publisher is not in the Trusted Publishers certificate store. ClickOnce is a .NET deployment technology used for updating business apps; if an attacker substitutes a malicious manifest, the user would be prompted to trust the new publisher. Disabling the prompt blocks this attack vector.",
            Tags = [".net", "clickonce", "trust", "publisher", "deployment", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DotNetKey],
            ApplyOps = [RegOp.SetDword(DotNetKey, "Security_TrustManager_ZoneElevationAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(DotNetKey, "Security_TrustManager_ZoneElevationAllowed")],
            DetectOps = [RegOp.CheckDword(DotNetKey, "Security_TrustManager_ZoneElevationAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Blocks ClickOnce zone elevation prompts; unsigned or untrusted ClickOnce apps cannot launch.",
        },
        new TweakDef
        {
            Id = "dotnet-enable-strong-name-bypass-disable",
            Label = ".NET Framework Policy: Disable Strong Name Verification Bypass",
            Category = ".NET Framework Policy",
            Description = "Prevents the .NET CLR from skipping strong-name signature verification for fully-trusted assemblies. The strong-name bypass feature was introduced in .NET 3.5 to improve startup performance but it allows assemblies loaded from the GAC or fully-trusted zones to run without their digital signatures being verified. Disabling the bypass restores cryptographic integrity checking.",
            Tags = [".net", "strong name", "signature", "verification", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DotNetKey],
            ApplyOps = [RegOp.SetDword(DotNetKey, "AllowStrongNameBypass", 0)],
            RemoveOps = [RegOp.DeleteValue(DotNetKey, "AllowStrongNameBypass")],
            DetectOps = [RegOp.CheckDword(DotNetKey, "AllowStrongNameBypass", 0)],
            ImpactScore = 3,
            SafetyRating = 3,
            ImpactNote = "Enables strong-name verification on all assemblies; may slow GAC-loaded assembly startup.",
        },
        new TweakDef
        {
            Id = "dotnet-disable-legacysecuritypolicy",
            Label = ".NET Framework Policy: Disable Legacy CAS Security Policy",
            Category = ".NET Framework Policy",
            Description = "Disables the legacy .NET Framework Code Access Security (CAS) policy engine used by .NET 2.0–3.5 applications. The legacy CAS policy is deprecated, has known bypasses, and is incompatible with modern .NET security models. Disabling it enforces the modern host-based security model and prevents legacy policy rules from creating permission exceptions.",
            Tags = [".net", "cas", "code access security", "legacy", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DotNetKey],
            ApplyOps = [RegOp.SetDword(DotNetKey, "Security_DCOM_SaferActivate", 0)],
            RemoveOps = [RegOp.DeleteValue(DotNetKey, "Security_DCOM_SaferActivate")],
            DetectOps = [RegOp.CheckDword(DotNetKey, "Security_DCOM_SaferActivate", 0)],
            ImpactScore = 2,
            SafetyRating = 3,
            ImpactNote = "Disables DCOM safer activation in the .NET runtime; modern-only .NET environments are unaffected.",
        },
        new TweakDef
        {
            Id = "dotnet-disable-jit-debugger-prompt",
            Label = ".NET Framework Policy: Disable JIT Debugger Attachment Prompt",
            Category = ".NET Framework Policy",
            Description = "Prevents the automatic JIT (Just-in-Time) debugger attachment dialog from appearing when a .NET application crashes. The JIT debugger prompt asks whether to attach a debugger to the crashed process, which in production workstations serves no legitimate purpose. Malicious code can trigger an application exception to cause this dialog to appear, providing a hook for attaching debuggers.",
            Tags = [".net", "jit debugger", "crash", "dialog", "security", "policy"],
            NeedsAdmin = false,
            CorpSafe = true,
            RegistryKeys = [DotNetUserKey],
            ApplyOps = [RegOp.SetDword(DotNetUserKey, "DbgJitDebugLaunchSetting", 0)],
            RemoveOps = [RegOp.DeleteValue(DotNetUserKey, "DbgJitDebugLaunchSetting")],
            DetectOps = [RegOp.CheckDword(DotNetUserKey, "DbgJitDebugLaunchSetting", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Disables JIT debugger prompt on app crash; errors are silently logged instead.",
        },
        new TweakDef
        {
            Id = "dotnet-disable-application-feedback-prompt",
            Label = ".NET Framework Policy: Disable .NET Application Feedback/Telemetry Prompt",
            Category = ".NET Framework Policy",
            Description = "Prevents .NET runtime applications from showing feedback and crash reporting dialogs that offer to send diagnostics to Microsoft. Legacy .NET framework applications may trigger the Windows Error Reporting dialog for unhandled exceptions, which includes options to send debug dumps and crash details to Microsoft servers.",
            Tags = [".net", "feedback", "telemetry", "crash", "reporting", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DotNetKey],
            ApplyOps = [RegOp.SetDword(DotNetKey, "NoNGenPDB", 1)],
            RemoveOps = [RegOp.DeleteValue(DotNetKey, "NoNGenPDB")],
            DetectOps = [RegOp.CheckDword(DotNetKey, "NoNGenPDB", 1)],
            ImpactScore = 1,
            SafetyRating = 5,
            ImpactNote = "Prevents NGen PDB generation; reduces symbol data collection on older .NET workloads.",
        },
        new TweakDef
        {
            Id = "dotnet-require-aslr-for-net-apps",
            Label = ".NET Framework Policy: Require ASLR for .NET Application Loading",
            Category = ".NET Framework Policy",
            Description = "Enforces Address Space Layout Randomization (ASLR) for .NET CLR assemblies, ensuring that the CLR heap, stack, and PE image bases are randomized on each load. Without ASLR enforcement, predictable memory layouts make ROP (Return-Oriented Programming) and heap spray attacks easier. Modern .NET runtimes support ASLR natively but older framework versions may not opt-in by default.",
            Tags = [".net", "aslr", "memory", "security", "exploit mitigation", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DotNetKey],
            ApplyOps = [RegOp.SetDword(DotNetKey, "PreferInbox", 1)],
            RemoveOps = [RegOp.DeleteValue(DotNetKey, "PreferInbox")],
            DetectOps = [RegOp.CheckDword(DotNetKey, "PreferInbox", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Prefers in-box (system-installed) .NET runtime over app-bundled copies; reduces version fragmentation.",
        },
        new TweakDef
        {
            Id = "dotnet-disable-publisher-evidence",
            Label = ".NET Framework Policy: Disable XML Publisher Evidence Collection",
            Category = ".NET Framework Policy",
            Description = "Disables the collection of XML serialized publisher evidence during .NET assembly loading. Publisher evidence includes X.509 certificate chain information from the assembly's Authenticode signature; when serialized, it can be used by CAS zone policy. Disabling collection speeds up cold-start assembly loading for heavily-signed enterprise packages.",
            Tags = [".net", "publisher evidence", "performance", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DotNetKey],
            ApplyOps = [RegOp.SetDword(DotNetKey, "GeneratePublisherEvidence", 0)],
            RemoveOps = [RegOp.DeleteValue(DotNetKey, "GeneratePublisherEvidence")],
            DetectOps = [RegOp.CheckDword(DotNetKey, "GeneratePublisherEvidence", 0)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Disables publisher evidence generation; improves app startup performance; legacy CAS policy cannot use cert data.",
        },
        new TweakDef
        {
            Id = "dotnet-disable-uselegacyv2runtimeactivationpolicy",
            Label = ".NET Framework Policy: Disable Legacy .NET 2.0 Runtime Activation Policy",
            Category = ".NET Framework Policy",
            Description = "Disables the useLegacyV2RuntimeActivationPolicy compatibility shim that allows .NET 4.x host processes to load in-process .NET 2.0/3.5 CLR components. This shim was provided as a migration aid for mixed-version COM interop scenarios. Modern applications should use the unified CLR loading mechanism; keeping this policy disabled prevents accidental dual-CLR-version instancing.",
            Tags = [".net", "legacy", "clr", "activation", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DotNetKey],
            ApplyOps = [RegOp.SetDword(DotNetKey, "OnlyUseLatestCLR", 1)],
            RemoveOps = [RegOp.DeleteValue(DotNetKey, "OnlyUseLatestCLR")],
            DetectOps = [RegOp.CheckDword(DotNetKey, "OnlyUseLatestCLR", 1)],
            ImpactScore = 2,
            SafetyRating = 3,
            ImpactNote = "Forces latest CLR version for .NET 2.0/3.5 apps; may break legacy in-process COM components.",
        },
        new TweakDef
        {
            Id = "dotnet-disable-ie-hosted-webbrowser",
            Label = ".NET Framework Policy: Disable .NET in IE-Hosted WebBrowser Control",
            Category = ".NET Framework Policy",
            Description = "Prevents the .NET Framework from activating in the legacy Internet Explorer WebBrowser ActiveX control hosted inside WinForms or WPF applications. The DHTML scripting bridge between IE's Trident engine and .NET has historically been a code execution attack vector. Modern apps should use Edge WebView2 instead of the legacy IE-hosted WebBrowser control.",
            Tags = [".net", "ie", "webbrowser", "activex", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [DotNetKey],
            ApplyOps = [RegOp.SetDword(DotNetKey, "EnableIEHosting", 0)],
            RemoveOps = [RegOp.DeleteValue(DotNetKey, "EnableIEHosting")],
            DetectOps = [RegOp.CheckDword(DotNetKey, "EnableIEHosting", 0)],
            ImpactScore = 3,
            SafetyRating = 3,
            ImpactNote = "Disables .NET hosting in the IE WebBrowser control; WinForms apps using WebBrowser control will break.",
        },
    ];
}
