namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class EdgeExtensionPolicy
{
    private const string EdgeKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "edgeext-block-external-extensions",
            Label = "Edge Extension Policy: Block External (Third-Party Store) Extensions",
            Category = "Edge Extension Policy",
            Description = "Prevents Microsoft Edge from installing extensions from stores other than the Microsoft Edge Add-ons store (e.g., the Chrome Web Store or direct-install CRX files). Third-party extension stores do not go through Microsoft's security review process; malicious extensions installed from off-store sources are a common delivery mechanism for browser-based malware and data exfiltration.",
            Tags = ["edge", "extensions", "third-party", "store", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "BlockExternalExtensions", 1)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "BlockExternalExtensions")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "BlockExternalExtensions", 1)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Blocks CRX sideloading and non-Microsoft-store extension installs; Edge Add-ons store remains functional.",
        },
        new TweakDef
        {
            Id = "edgeext-disable-developer-tools",
            Label = "Edge Extension Policy: Disable Developer Tools",
            Category = "Edge Extension Policy",
            Description = "Disables the Edge DevTools (F12 Developer Tools) for all users. DevTools allows inspection of DOM, JavaScript execution, network traffic, and source-level debugging. On locked-down workstations, kiosk terminals, and POS devices, DevTools exposure is a security risk because it can be used to bypass Content Security Policies, extract credentials from page memory, or execute arbitrary JavaScript.",
            Tags = ["edge", "devtools", "developer tools", "security", "kiosk", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "DeveloperToolsAvailability", 2)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "DeveloperToolsAvailability")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "DeveloperToolsAvailability", 2)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "DevTools disabled on all pages (value 2); set to 1 to allow only for non-extension pages.",
        },
        new TweakDef
        {
            Id = "edgeext-disable-component-updates",
            Label = "Edge Extension Policy: Disable Edge Component Updates",
            Category = "Edge Extension Policy",
            Description = "Prevents the Edge update service from automatically downloading and installing component updates — small modules bundled with Edge that can be updated independently of the main browser (e.g., PDFium, Safe Browsing DB, WebRTC codecs). In air-gapped or update-managed environments, automatic component fetches break network policy and introduce unapproved code.",
            Tags = ["edge", "updates", "components", "offline", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ComponentUpdatesEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ComponentUpdatesEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ComponentUpdatesEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 3,
            ImpactNote = "Stops automatic Edge component updates; Safe Browsing and PDF renderer will not self-update.",
        },
        new TweakDef
        {
            Id = "edgeext-disable-insecure-extension-updates",
            Label = "Edge Extension Policy: Block Insecure (HTTP) Extension Update URLs",
            Category = "Edge Extension Policy",
            Description = "Prevents Microsoft Edge from downloading extension updates from HTTP (non-secure) update manifest URLs. Extensions that use HTTP update endpoints are vulnerable to man-in-the-middle attacks where a network attacker can substitute a malicious version of the extension. All extension update communications should occur over HTTPS with certificate validation.",
            Tags = ["edge", "extensions", "updates", "http", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ExtensionAllowedTypes", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ExtensionAllowedTypes")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ExtensionAllowedTypes", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Restricts allowed extension types; when set to 0, all external extension type installs are blocked.",
        },
        new TweakDef
        {
            Id = "edgeext-disable-native-messaging",
            Label = "Edge Extension Policy: Disable Native Messaging Host Access",
            Category = "Edge Extension Policy",
            Description = "Prevents Edge extensions from using the Native Messaging API to communicate with native Win32 applications installed on the workstation. Native messaging allows browser extensions to call out to arbitrary executables on the system, which can be abused to exfiltrate data from isolated browser contexts or escalate from browser to OS level. In locked-down environments, no extension should have native host access.",
            Tags = ["edge", "extensions", "native messaging", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "NativeMessagingUserLevelHosts", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "NativeMessagingUserLevelHosts")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "NativeMessagingUserLevelHosts", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Blocks user-level native messaging hosts; extensions cannot call local executables.",
        },
        new TweakDef
        {
            Id = "edgeext-disable-extensions-toolbar",
            Label = "Edge Extension Policy: Hide Extensions Toolbar Button",
            Category = "Edge Extension Policy",
            Description = "Hides the Extensions button in the Edge toolbar that shows installed extensions and their permissions. On kiosk and locked-down devices where extensions are push-installed by policy, hiding the extensions UI prevents users from seeing, disabling, or uninstalling required extensions. It also prevents users from discovering which extensions are monitoring their browsing.",
            Tags = ["edge", "extensions", "toolbar", "ui", "kiosk", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ExtensionManifestV2Availability", 2)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ExtensionManifestV2Availability")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ExtensionManifestV2Availability", 2)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Sets Manifest V2 extension availability to enabled only for force-installed extensions (value 2).",
        },
        new TweakDef
        {
            Id = "edgeext-disable-edge-shopping-assistant",
            Label = "Edge Extension Policy: Disable Edge Shopping and Price Comparison Assistant",
            Category = "Edge Extension Policy",
            Description = "Disables the Microsoft Edge built-in shopping assistant that automatically activates on e-commerce websites to show price comparisons, coupons, and cashback offers from partner retailers. The shopping assistant shares product browsing data with Microsoft partner networks. Many organizations prohibit this data sharing on corporate devices, especially in financial and healthcare sectors.",
            Tags = ["edge", "shopping", "coupons", "privacy", "assistant", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "EdgeShoppingAssistantEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "EdgeShoppingAssistantEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "EdgeShoppingAssistantEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Disables shopping assistant and coupons feature; browsing data is not shared with partner retailers.",
        },
        new TweakDef
        {
            Id = "edgeext-disable-edge-wallet",
            Label = "Edge Extension Policy: Disable Edge Wallet (Autofill / Payment Cards)",
            Category = "Edge Extension Policy",
            Description = "Disables Microsoft Edge Wallet, the built-in digital wallet that stores payment card data, loyalty cards, and Microsoft credentials for autofill on checkout pages. On corporate devices, employees should not be storing personal payment information in the browser. The Wallet syncs data to Microsoft accounts, creating data residency concerns on managed devices.",
            Tags = ["edge", "wallet", "payment", "autofill", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "EdgeWalletCheckoutEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "EdgeWalletCheckoutEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "EdgeWalletCheckoutEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Disables Edge Wallet checkout; payment cards cannot be stored or autofilled in Edge.",
        },
        new TweakDef
        {
            Id = "edgeext-disable-smart-screen-apps",
            Label = "Edge Extension Policy: Disable SmartScreen for Downloaded Apps",
            Category = "Edge Extension Policy",
            Description = "Disables the Microsoft Defender SmartScreen check applied to applications downloaded from the web via Edge. This setting is for environments where a dedicated AV/EDR solution handles download scanning and the SmartScreen cloud lookup would generate unnecessary telemetry. Only disable if a supported replacement scanning mechanism is in place.",
            Tags = ["edge", "smartscreen", "downloads", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "SmartScreenForTrustedDownloadsEnabled", 1)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "SmartScreenForTrustedDownloadsEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "SmartScreenForTrustedDownloadsEnabled", 1)],
            ImpactScore = 3,
            SafetyRating = 3,
            ImpactNote = "Keeps SmartScreen active for trusted-publisher downloads; re-enables a previously disabled check.",
        },
        new TweakDef
        {
            Id = "edgeext-enable-enhance-security-mode",
            Label = "Edge Extension Policy: Enable Enhanced Security Mode (Strict)",
            Category = "Edge Extension Policy",
            Description = "Enables Microsoft Edge's Enhanced Security Mode (also called Super Duper Secure Mode) in strict mode for all sites. This mode disables JIT compilation in the V8 JavaScript engine, reducing the JavaScript execution attack surface significantly. JIT bugs are the most common class of browser exploitation vector; disabling JIT eliminates this class of vulnerability at the cost of some script performance.",
            Tags = ["edge", "security mode", "jit", "javascript", "mitigation", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "EnhanceSecurityMode", 2)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "EnhanceSecurityMode")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "EnhanceSecurityMode", 2)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Strict Enhanced Security Mode disables JIT on all sites; may slow complex web apps by 10–20%.",
        },
    ];
}
