// RegiLattice.Core — Tweaks/EdgeNewTabPagePolicy.cs
// Microsoft Edge New Tab Page layout, content, and enterprise customisation Group Policy controls (Sprint 614).
// Category: "Edge New Tab Page Policy" | Slug: edgentp
// Key: HKLM\SOFTWARE\Policies\Microsoft\Edge

namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class EdgeNewTabPagePolicy
{
    private const string Key = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge";

    public static IReadOnlyList<TweakDef> Tweaks =>
    [
        new TweakDef
        {
            Id = "edgentp-disable-news-feed-on-new-tab",
            Label = "Edge New Tab Page: Disable Microsoft News Feed and Sponsored Content",
            Category = "Edge New Tab Page Policy",
            Description = "Sets NewTabPageContentEnabled=0 in Edge policy. Removes the news feed, sponsored content tiles, and 'Microsoft Start' MSN content from the Edge New Tab Page, leaving only the search bar and customisable quick-access shortcuts. " +
                "The Microsoft News feed on the Edge New Tab Page makes network requests to news CDN endpoints on every new tab open, sending the user's browsing context and telemetry to the MSN/Microsoft Start advertising network. Every new tab opened invites a network round-trip that may be captured by enterprise proxy logs as an apparent outbound data transfer. Removing the feed eliminates this unwanted telemetry and reduces browser startup time.",
            Tags = ["edge", "new-tab", "news-feed", "telemetry", "msn"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Edge New Tab news feed disabled; no MSN/Microsoft Start content requests on new tab open.",
            ApplyOps = [RegOp.SetDword(Key, "NewTabPageContentEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "NewTabPageContentEnabled")],
            DetectOps = [RegOp.CheckDword(Key, "NewTabPageContentEnabled", 0)],
        },
        new TweakDef
        {
            Id = "edgentp-set-new-tab-layout-focused-mode",
            Label = "Edge New Tab Page: Set New Tab Page to Focused Layout (Search Only)",
            Category = "Edge New Tab Page Policy",
            Description = "Sets NewTabPageLayout=2 in Edge policy (value 2 = Focused). Configures the Edge New Tab Page to display in 'Focused' layout, which shows only the search bar and removes the news grid, quick-access tiles, and Microsoft promoted content from the default new tab experience. " +
                "Focused layout reduces the cognitive load introduced by the news grid on the New Tab Page, provides a distraction-free default browser state, and prevents accidental clicks on promoted content that may navigate to external news sites during a work browsing session. It also reduces the amount of outbound advertising telemetry generated by the default 'Inspirational' or 'Informational' layouts.",
            Tags = ["edge", "new-tab", "focused", "distraction", "layout"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Edge New Tab Page shows focused layout (search bar only); no news grid or promotional tiles.",
            ApplyOps = [RegOp.SetDword(Key, "NewTabPageLayout", 2)],
            RemoveOps = [RegOp.DeleteValue(Key, "NewTabPageLayout")],
            DetectOps = [RegOp.CheckDword(Key, "NewTabPageLayout", 2)],
        },
        new TweakDef
        {
            Id = "edgentp-disable-quick-search-bar",
            Label = "Edge New Tab Page: Disable Bing Quick Search Suggestions on New Tab",
            Category = "Edge New Tab Page Policy",
            Description = "Sets NewTabPageSearchBoxEnabled=0 in Edge policy. Disables the Bing-powered search suggestions that appear as the user types in the New Tab Page search bar, preventing keystroke telemetry from being sent to Bing suggestion endpoints before the user submits a search. " +
                "Typeahead search suggestions on the New Tab Page send partial keystrokes to Bing's autocomplete API as the user types, even for searches that may include sensitive internal terms, IP addresses, or hostnames. In high-security environments where employees should not be inadvertently leaking internal hostname patterns to external search engines, disabling typeahead prevents pre-submission data transmission.",
            Tags = ["edge", "new-tab", "search-suggestions", "typeahead", "telemetry"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Bing typeahead suggestions disabled on NTP search bar; keystrokes not sent to Bing until search is submitted.",
            ApplyOps = [RegOp.SetDword(Key, "NewTabPageSearchBoxEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "NewTabPageSearchBoxEnabled")],
            DetectOps = [RegOp.CheckDword(Key, "NewTabPageSearchBoxEnabled", 0)],
        },
        new TweakDef
        {
            Id = "edgentp-disable-context-personalization",
            Label = "Edge New Tab Page: Disable Personalised Content Based on Browsing Context",
            Category = "Edge New Tab Page Policy",
            Description = "Sets NewTabPagePersonalizedContentEnabled=0 in Edge policy. Prevents Edge from using the user's browsing history, saved sites, and M365 activity signals to personalise the content displayed on the New Tab Page with customised news topics, trending articles, and personalised ad tiles. " +
                "Personalised New Tab content is built from browsing telemetry that is uploaded to and processed by Microsoft's Personalisation service. This telemetry includes categories of pages visited, search terms, and time-on-page signals derived from the user's on-device browsing data. In privacy-conscious organisations, this upstream browsing telemetry transmission may conflict with internal data handling policies or employee monitoring regulations.",
            Tags = ["edge", "new-tab", "personalisation", "telemetry", "privacy"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "NTP personalisation disabled; no browsing telemetry used to customise Edge New Tab contents.",
            ApplyOps = [RegOp.SetDword(Key, "NewTabPagePersonalizedContentEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "NewTabPagePersonalizedContentEnabled")],
            DetectOps = [RegOp.CheckDword(Key, "NewTabPagePersonalizedContentEnabled", 0)],
        },
        new TweakDef
        {
            Id = "edgentp-disable-background-image-download",
            Label = "Edge New Tab Page: Disable Daily Background Image Download (Bing Wallpaper)",
            Category = "Edge New Tab Page Policy",
            Description = "Sets NewTabPageBingChatDefaultEnabled=0 in Edge policy. Prevents Edge from downloading the daily Bing Image of the Day wallpaper for the New Tab Page background, eliminating an outbound network request to Bing's image CDN that occurs on every new browser session or when the browser starts cold. " +
                "The Bing Image of the Day download sends a request to Bing's CDN infrastructure that includes the user's locale, Edge client ID, and a timestamp. This request is made unconditionally on every new tab open (when local cache is expired), creating a persistent outbound C&C-style beacon pattern in enterprise proxy logs that security monitoring may flag. Disabling the background image download eliminates this regular network telemetry.",
            Tags = ["edge", "new-tab", "background-image", "bing", "network-beacon"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Daily Bing wallpaper download disabled for NTP; no periodic Bing CDN image request on new tab open.",
            ApplyOps = [RegOp.SetDword(Key, "NewTabPageBingChatDefaultEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "NewTabPageBingChatDefaultEnabled")],
            DetectOps = [RegOp.CheckDword(Key, "NewTabPageBingChatDefaultEnabled", 0)],
        },
        new TweakDef
        {
            Id = "edgentp-block-quick-links-modification",
            Label = "Edge New Tab Page: Lock Quick Links and Prevent User Modification",
            Category = "Edge New Tab Page Policy",
            Description = "Sets NewTabPageQuickLinksEnabled=1 in Edge policy. Enables Quick Links on the New Tab Page but combined with enterprise link configuration policies, locks the quick links to IT-defined shortcuts for internal portals and blocks users from adding, removing, or reordering quick link tiles. " +
                "Quick links on the Edge NTP serve as one-click navigation to frequently used sites. Without enterprise control, users populate these with personal shortcuts including personal social media, webmail, and personal banking portals. By locking quick links to enterprise-defined values (helpdesk portal, internal SharePoint, timesheet system), the NTP becomes a managed productivity tool instead of a consumer browsing shortcut bar.",
            Tags = ["edge", "new-tab", "quick-links", "enterprise", "managed"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "NTP quick links locked to enterprise configuration; users cannot add or remove personal shortcuts.",
            ApplyOps = [RegOp.SetDword(Key, "NewTabPageQuickLinksEnabled", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "NewTabPageQuickLinksEnabled")],
            DetectOps = [RegOp.CheckDword(Key, "NewTabPageQuickLinksEnabled", 1)],
        },
        new TweakDef
        {
            Id = "edgentp-disable-weather-widget",
            Label = "Edge New Tab Page: Disable Weather Widget on New Tab Page",
            Category = "Edge New Tab Page Policy",
            Description = "Sets NewTabPageWeatherEnabled=0 in Edge policy. Removes the weather information widget from the Edge New Tab Page, preventing the weather service from sending a geolocation lookup request or IP-based location inference request to the MSN weather API each time a new tab is opened. " +
                "The Edge NTP weather widget resolves user location by sending a location signal (either GPS coordinates if location permission is granted, or IP-based geolocation as a fallback) to the MSN weather API. This is a low-bandwidth but persistent telemetry channel that transmits the user's approximate location to Microsoft's advertising backend. On devices used in sensitive facility locations, this geolocation signal may disclose site location to external services.",
            Tags = ["edge", "new-tab", "weather", "geolocation", "telemetry"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Weather widget removed from Edge NTP; no IP-based geolocation request sent to MSN weather API.",
            ApplyOps = [RegOp.SetDword(Key, "NewTabPageWeatherEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "NewTabPageWeatherEnabled")],
            DetectOps = [RegOp.CheckDword(Key, "NewTabPageWeatherEnabled", 0)],
        },
        new TweakDef
        {
            Id = "edgentp-disable-microsoft-365-feed",
            Label = "Edge New Tab Page: Disable M365 Office Feed on New Tab Page",
            Category = "Edge New Tab Page Policy",
            Description = "Sets NewTabPageAppLauncherEnabled=0 in Edge policy. Removes the Microsoft 365 app launcher grid and recent Office documents feed from the Edge New Tab Page, which would otherwise display the user's recently modified SharePoint, OneDrive, and Teams files in a list visible to anyone viewing the screen while a new tab is open. " +
                "The recent Office documents displayed in the Edge M365 feed are loaded from the Microsoft Graph API using the user's current access token on every new tab open. The document titles and URLs visible in the feed constitute a real-time disclosure of what the user is working on. In screen-sharing sessions or when colleagues can see the screen background, this information can be inadvertently disclosed.",
            Tags = ["edge", "new-tab", "m365", "office-feed", "document-titles"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "M365 recent documents feed removed from Edge NTP; recent file titles not displayed on new tab open.",
            ApplyOps = [RegOp.SetDword(Key, "NewTabPageAppLauncherEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "NewTabPageAppLauncherEnabled")],
            DetectOps = [RegOp.CheckDword(Key, "NewTabPageAppLauncherEnabled", 0)],
        },
        new TweakDef
        {
            Id = "edgentp-disable-trending-topics-on-new-tab",
            Label = "Edge New Tab Page: Disable Trending / Trending News on New Tab Page",
            Category = "Edge New Tab Page Policy",
            Description = "Sets NewTabPageManagedNewTabMicrosoftNews=0 in Edge policy. Removes the trending news stories and 'Trending' section from the Edge New Tab Page, preventing distraction from trending social media and news content during working hours. " +
                "Trending news on the Edge NTP is curated by MSN's editorial and algorithmic pipeline and includes entertainment news, viral social media topics, and politically engaging content. Exposure to trending topics during work hours contributes to context switching and reduced focus. Enterprise productivity studies have associated news feed interruptions on browser tabs with significant attention cost per-interruption. Removing trending content from the NTP reduces this distraction vector.",
            Tags = ["edge", "new-tab", "trending", "distraction", "productivity"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Trending news section removed from Edge NTP; no viral/entertainment content on new tab opens.",
            ApplyOps = [RegOp.SetDword(Key, "NewTabPageManagedNewTabMicrosoftNews", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "NewTabPageManagedNewTabMicrosoftNews")],
            DetectOps = [RegOp.CheckDword(Key, "NewTabPageManagedNewTabMicrosoftNews", 0)],
        },
        new TweakDef
        {
            Id = "edgentp-hide-new-tab-logo",
            Label = "Edge New Tab Page: Hide Microsoft and Bing Branding from New Tab Page",
            Category = "Edge New Tab Page Policy",
            Description = "Sets NewTabPageHideDefaultTopSites=1 in Edge policy. Hides the default Microsoft/Bing promotional top sites tiles that appear on a fresh Edge installation's New Tab Page before the user has browsed enough to populate personal top sites, replacing them with blank slots. " +
                "On managed enterprise deployments where Edge is pre-configured, Bing promotional top site tiles (Bing homepage, Bing Shopping, MSN) appear as prominent quick-access shortcuts that direct traffic to Microsoft's advertising properties. These pre-seeded sites serve no legitimate enterprise workflow purpose and consume quick link slot positions that could be used for IT-defined enterprise shortcuts.",
            Tags = ["edge", "new-tab", "top-sites", "bing", "branding"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 1,
            SafetyRating = 5,
            ImpactNote = "Default Bing/Microsoft promoted top site tiles hidden from Edge NTP; slots replaced with blank positions.",
            ApplyOps = [RegOp.SetDword(Key, "NewTabPageHideDefaultTopSites", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "NewTabPageHideDefaultTopSites")],
            DetectOps = [RegOp.CheckDword(Key, "NewTabPageHideDefaultTopSites", 1)],
        },
    ];
}
