namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class EdgeStartupPolicy
{
    private const string EdgeKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "edgestart-set-startup-to-new-tab",
            Label = "Edge Startup Policy: Set Startup Action to Open New Tab Page",
            Category = "Edge Startup Policy",
            Description = "Configures Microsoft Edge to always open the New Tab Page on startup, discarding any previously open tabs and ignoring the 'Continue where you left off' option. This ensures a clean browser state on every launch, which is important for shared workstations, kiosk deployments, and compliance environments where session continuity between logins must not occur.",
            Tags = ["edge", "startup", "new tab", "session", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "RestoreOnStartup", 5)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "RestoreOnStartup")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "RestoreOnStartup", 5)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "RestoreOnStartup=5 opens New Tab Page; Edge discards previous session on every launch.",
        },
        new TweakDef
        {
            Id = "edgestart-disable-preload-home-page",
            Label = "Edge Startup Policy: Disable Preloading of Home Page on Startup",
            Category = "Edge Startup Policy",
            Description = "Prevents Microsoft Edge from preloading the home page or startup pages in the background during Windows startup or user logon. Edge aggressively preloads its startup page to shorten the perceived time-to-interactive, but this consumes RAM and CPU on logon, delays desktop readiness, and causes unnecessary network activity even when the user does not intend to open Edge.",
            Tags = ["edge", "startup", "preload", "performance", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "StartupBoostEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "StartupBoostEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "StartupBoostEnabled", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Disables Edge startup boost; eliminates Edge background preloading from Windows logon sequence.",
        },
        new TweakDef
        {
            Id = "edgestart-disable-sleeping-tabs",
            Label = "Edge Startup Policy: Disable Sleeping Tabs Background CPU Throttle",
            Category = "Edge Startup Policy",
            Description = "Disables the Edge Sleeping Tabs feature that automatically sends unused background tabs into a low-power throttled state after a period of inactivity. While intended to reduce CPU and memory usage, the Sleeping Tabs feature sometimes causes web applications (dashboards, real-time monitoring tools, auto-paging enterprise apps) to lose their session state unexpectedly.",
            Tags = ["edge", "sleeping tabs", "performance", "tabs", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "SleepingTabsEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "SleepingTabsEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "SleepingTabsEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Prevents background tabs from being throttled; live web dashboards stay active.",
        },
        new TweakDef
        {
            Id = "edgestart-disable-performance-detector",
            Label = "Edge Startup Policy: Disable Edge Performance Detector",
            Category = "Edge Startup Policy",
            Description = "Disables the Edge Performance Detector, which monitors browser and system performance to advise users about slow extensions, resource-heavy tabs, and memory pressure. While informational, the Performance Detector runs a background profiling service and generates telemetry reports sent to Microsoft. In managed environments where performance baselines are set by IT, this unsolicited advisor is unnecessary.",
            Tags = ["edge", "performance detector", "telemetry", "profiling", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "PerformanceDetectorEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "PerformanceDetectorEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "PerformanceDetectorEnabled", 0)],
            ImpactScore = 1,
            SafetyRating = 5,
            ImpactNote = "Disables Edge Performance Detector; no impact on actual browser performance.",
        },
        new TweakDef
        {
            Id = "edgestart-disable-new-tab-prerender",
            Label = "Edge Startup Policy: Disable New Tab Page Prerendering",
            Category = "Edge Startup Policy",
            Description = "Prevents Edge from pre-rendering the New Tab Page (NTP) before the user explicitly opens a new tab. The NTP prerender fetches background images, news feed content, and Bing search suggestions in advance. Disabling prerendering reduces background network activity, decreases memory usage, and prevents prefetch requests from appearing in corporate network monitoring tools.",
            Tags = ["edge", "new tab", "prerender", "performance", "network", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "NewTabPagePrerenderEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "NewTabPagePrerenderEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "NewTabPagePrerenderEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Disables NTP preload; reduces background network calls triggered by opening a new Edge tab.",
        },
        new TweakDef
        {
            Id = "edgestart-force-bing-search-on-ntp",
            Label = "Edge Startup Policy: Lock New Tab Page Search Box to Bing (Prevent Override)",
            Category = "Edge Startup Policy",
            Description = "Configures the New Tab Page search box type to Bing and prevents users from changing it to a third-party or intranet search engine. In enterprise deployments where Bing is the approved search provider (or where the Enterprise New Tab Page is set to a corporate portal), this prevents inconsistency in the search experience and avoids accidental data submission to unapproved search services.",
            Tags = ["edge", "new tab", "search box", "bing", "search engine", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "NewTabPageSearchBox", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "NewTabPageSearchBox")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "NewTabPageSearchBox", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "NTP search box set to Bing (value 0); set to 1 to use Edge URL bar search provider instead.",
        },
        new TweakDef
        {
            Id = "edgestart-set-homepage-to-new-tab",
            Label = "Edge Startup Policy: Set Home Page to New Tab Page",
            Category = "Edge Startup Policy",
            Description = "Configures the Edge home page button to navigate to the New Tab Page rather than a custom URL. This ensures the home button is functional and consistent on all managed devices. When combined with the startup action policy, the home button and startup both go to the NTP, providing a consistent entry point across all managed Edge profiles.",
            Tags = ["edge", "homepage", "new tab", "startup", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "HomepageIsNewTabPage", 1)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "HomepageIsNewTabPage")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "HomepageIsNewTabPage", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Home button always navigates to the New Tab Page; custom HomepageLocation URLs are ignored.",
        },
        new TweakDef
        {
            Id = "edgestart-disable-experimentation-service",
            Label = "Edge Startup Policy: Disable Edge Experimentation and A/B Testing Service",
            Category = "Edge Startup Policy",
            Description = "Prevents Microsoft Edge from contacting the Experimentation and Configuration Service (ECS) that enrolls the browser in A/B feature experiments and delivers remote feature flag overrides. ECS can silently enable or disable browser features without a version update. In enterprise environments, uncontrolled feature experiments can change behaviour, break web app compatibility, or activate preview features not approved by IT.",
            Tags = ["edge", "experimentation", "ab testing", "feature flags", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ExperimentationAndConfigurationServiceControl", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ExperimentationAndConfigurationServiceControl")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ExperimentationAndConfigurationServiceControl", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Disables ECS; Edge feature experiments are turned off; browser behavior is determined by installed version only.",
        },
        new TweakDef
        {
            Id = "edgestart-disable-tab-groups",
            Label = "Edge Startup Policy: Disable Edge Tab Groups",
            Category = "Edge Startup Policy",
            Description = "Disables the Edge Tab Groups feature that lets users organize browser tabs into named, colored groups. On kiosk and locked-down devices where the number of open tabs is restricted by policy, and where session restoration of tab groups between logins would create persistent state, disabling tab groups simplifies the browser UX and prevents group state from persisting across logons.",
            Tags = ["edge", "tab groups", "kiosk", "simplification", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "TabServicesEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "TabServicesEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "TabServicesEnabled", 0)],
            ImpactScore = 1,
            SafetyRating = 5,
            ImpactNote = "Disables Edge tab services and tab groups; only affects tab organization UI.",
        },
        new TweakDef
        {
            Id = "edgestart-disable-edge-workspaces",
            Label = "Edge Startup Policy: Disable Edge Workspaces",
            Category = "Edge Startup Policy",
            Description = "Disables Microsoft Edge Workspaces, the collaborative tab-sharing feature that allows users to share a live set of browser tabs with colleagues via a shared link. Workspaces sync tab lists to Microsoft cloud services and allow external parties to view or join an active workspace. In corporate environments with data-classification or DLP requirements, this feature could inadvertently expose internal URLs to unauthorized users.",
            Tags = ["edge", "workspaces", "sharing", "collaboration", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "EdgeWorkspacesEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "EdgeWorkspacesEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "EdgeWorkspacesEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Disables Edge Workspaces tab sharing; prevents internal URLs from being shared via workspace links.",
        },
    ];
}
