namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;
using System.Collections.Generic;

internal static class EdgeMediaCapturePolicy
{
    private const string EdgeKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "edgemedia-block-camera",
            Label = "Edge Media Capture Policy: Block Camera Access from Browser",
            Category = "Edge Media Capture Policy",
            Description = "Blocks all camera and video capture access from within Microsoft Edge for all sites by default. When VideoCaptureAllowed is set to 0, no website may request or use the system camera through the browser, regardless of site permissions previously granted. This is appropriate for locked-down workstations, reception terminals, kiosk deployments, and any environment where webcam access from a browser constitutes a privacy or security risk.",
            Tags = ["edge", "camera", "video capture", "privacy", "kiosk", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "VideoCaptureAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "VideoCaptureAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "VideoCaptureAllowed", 0)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "All websites denied camera access; video conferencing via browser will not function.",
        },
        new TweakDef
        {
            Id = "edgemedia-block-microphone",
            Label = "Edge Media Capture Policy: Block Microphone Access from Browser",
            Category = "Edge Media Capture Policy",
            Description = "Blocks all microphone and audio capture access from within Microsoft Edge for all sites by default. Setting AudioCaptureAllowed to 0 prevents any website from recording audio through the system microphone, regardless of previously granted browser permissions. Use in call-center environments where only approved communication apps may use the microphone, or in high-security areas where audio capture from a browser session is prohibited.",
            Tags = ["edge", "microphone", "audio capture", "privacy", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "AudioCaptureAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "AudioCaptureAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "AudioCaptureAllowed", 0)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "All websites denied microphone access; browser-based voice/audio applications will not function.",
        },
        new TweakDef
        {
            Id = "edgemedia-block-screen-capture",
            Label = "Edge Media Capture Policy: Block Screen Capture from Browser",
            Category = "Edge Media Capture Policy",
            Description = "Blocks screen capture and screen recording APIs within Microsoft Edge by default for all sites. Setting ScreenCaptureAllowed to 0 prevents websites from calling getDisplayMedia() to share or record the screen, individual application windows, or browser tabs. This is critical in environments where DLP (Data Loss Prevention) policy prohibits screen recording by web applications, or where sensitive information displayed on screen must not be programmatically captured.",
            Tags = ["edge", "screen capture", "recording", "dlp", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ScreenCaptureAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ScreenCaptureAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ScreenCaptureAllowed", 0)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Browser screen-share and screen recording APIs blocked; web-based meeting tools that share screens will not function.",
        },
        new TweakDef
        {
            Id = "edgemedia-disable-cast",
            Label = "Edge Media Capture Policy: Disable Google Cast Media Streaming",
            Category = "Edge Media Capture Policy",
            Description = "Disables the Google Cast feature integrated into Microsoft Edge, which allows casting browser tab content or entire screen to Chromecast-compatible devices on the local network. Cast operates by scanning the local network for cast-compatible receivers and establishing a peer-to-peer media stream. In corporate environments, Cast may expose browser content to unauthorized receivers or allow users to bypass screen-mirroring controls.",
            Tags = ["edge", "cast", "chromecast", "streaming", "network", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "CastEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "CastEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "CastEnabled", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Cast icon removed from Edge toolbar; browser-to-Chromecast streaming disabled.",
        },
        new TweakDef
        {
            Id = "edgemedia-block-web-bluetooth",
            Label = "Edge Media Capture Policy: Block Web Bluetooth API",
            Category = "Edge Media Capture Policy",
            Description = "Blocks the Web Bluetooth API in Microsoft Edge, preventing websites from discovering, pairing with, or communicating with Bluetooth devices. The Web Bluetooth specification exposes device capabilities including model, manufacturer, and sensor data to websites. In corporate environments with Bluetooth-enabled medical devices, payment terminals, or security tokens, browser-level Bluetooth access creates an unauthorized channel for device enumeration and data exfiltration.",
            Tags = ["edge", "bluetooth", "web bluetooth", "api", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "WebBluetoothAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "WebBluetoothAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "WebBluetoothAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Websites cannot access Bluetooth devices; Web Bluetooth API calls are rejected.",
        },
        new TweakDef
        {
            Id = "edgemedia-block-web-hid",
            Label = "Edge Media Capture Policy: Block WebHID API Access",
            Category = "Edge Media Capture Policy",
            Description = "Blocks the WebHID (Human Interface Device) API in Microsoft Edge, preventing websites from accessing HID devices such as gamepads, custom input devices, and specialty hardware directly through the browser. WebHID allows arbitrary device I/O from a web page. On corporate workstations connected to HID-based security tokens, smart card readers, or biometric devices, browser HID access provides an unapproved communication channel to sensitive hardware.",
            Tags = ["edge", "hid", "webhid", "api", "hardware", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "WebHidAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "WebHidAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "WebHidAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Websites cannot enumerate or communicate with HID devices; gamepad and specialty input APIs are rejected.",
        },
        new TweakDef
        {
            Id = "edgemedia-block-web-usb",
            Label = "Edge Media Capture Policy: Block WebUSB API Access",
            Category = "Edge Media Capture Policy",
            Description = "Blocks the WebUSB API in Microsoft Edge, preventing websites from accessing USB devices connected to the system directly through the browser. WebUSB allows websites to communicate with any USB device — including USB drives, hardware security tokens, programmers, and devices with proprietary protocols. This creates a browser-level bypass of OS-enforced USB device policies and DLP controls.",
            Tags = ["edge", "usb", "webusb", "api", "hardware", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "WebUsbAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "WebUsbAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "WebUsbAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Websites cannot request access to USB devices; WebUSB API calls are rejected by the browser.",
        },
        new TweakDef
        {
            Id = "edgemedia-block-serial-api",
            Label = "Edge Media Capture Policy: Block Serial Port API Access",
            Category = "Edge Media Capture Policy",
            Description = "Blocks the Web Serial API in Microsoft Edge, preventing websites from communicating with serial port devices (RS-232, COM port, USB-to-serial adapters). The Serial API gives a web page direct read/write access to any serial device without requiring a native application. On industrial control PCs, medical workstations, and environments with serial-connected PLCs or measurement instruments, this browser API provides unauthorized low-level hardware access.",
            Tags = ["edge", "serial api", "com port", "hardware", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "SerialApiAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "SerialApiAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "SerialApiAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Websites cannot access serial port devices; Web Serial API calls are rejected.",
        },
        new TweakDef
        {
            Id = "edgemedia-disable-gamepad-api",
            Label = "Edge Media Capture Policy: Disable Gamepad API in Browser",
            Category = "Edge Media Capture Policy",
            Description = "Disables the Gamepad API in Microsoft Edge, preventing websites from reading input state from gamepads, joysticks, and other game controllers connected to the system. The Gamepad API exposes button and axis state from all connected controllers to any web page. On corporate workstations, this API is unnecessary and can be used to fingerprint users (identifying specific controller hardware) or read input from controllers repurposed as input devices.",
            Tags = ["edge", "gamepad", "gamepad api", "input", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "GamepadApiEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "GamepadApiEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "GamepadApiEnabled", 0)],
            ImpactScore = 1,
            SafetyRating = 5,
            ImpactNote = "Gamepad API unavailable in browser; controller-based web games will not detect input.",
        },
        new TweakDef
        {
            Id = "edgemedia-disable-math-solver",
            Label = "Edge Media Capture Policy: Disable AI Math Solver in Edge",
            Category = "Edge Media Capture Policy",
            Description = "Disables the Edge Math Solver feature, which adds a Math Solver button to the Edge toolbar and context menu. When activated, the feature captures the selected math expression or equation from the page and submits it to a Microsoft AI cloud service that returns step-by-step solution guidance. In academic and testing environments where students use controlled browser sessions for exams, the Math Solver creates an unauthorized AI assistance channel.",
            Tags = ["edge", "math solver", "ai", "academic", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "MathSolverEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "MathSolverEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "MathSolverEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Math Solver button removed from Edge; AI math assistance feature disabled on all pages.",
        },
    ];
}
