namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;
using System.Collections.Generic;

internal static class EdgePrintAndPdfPolicy
{
    private const string EdgeKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "edgepdp-disable-printing",
            Label = "Edge Print & PDF Policy: Disable Printing from Edge",
            Category = "Edge Print & PDF Policy",
            Description = "Disables all printing from within Microsoft Edge via enterprise policy. When PrintingEnabled is set to 0, the Print option, Ctrl+P hotkey, and right-click Print are all suppressed. Use in environments where printed output from the browser must be controlled or logged through dedicated print servers, or in kiosk/terminal deployments where printing is prohibited.",
            Tags = ["edge", "printing", "kiosk", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "PrintingEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "PrintingEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "PrintingEnabled", 0)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Completely disables the browser's print functionality; affects Ctrl+P and print dialogs.",
        },
        new TweakDef
        {
            Id = "edgepdp-disable-print-header-footer",
            Label = "Edge Print & PDF Policy: Remove Headers and Footers from Print Output",
            Category = "Edge Print & PDF Policy",
            Description = "Configures Microsoft Edge to omit headers and footers from all print output via Group Policy. Normally Edge includes the page title, URL, date, and page numbers in printing headers and footers. This is useful in environments where printed documents should not expose internal URLs or timestamps, or where clean output without browser-added metadata is required for official documents.",
            Tags = ["edge", "printing", "header", "footer", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "PrintHeaderFooter", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "PrintHeaderFooter")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "PrintHeaderFooter", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Strips page URL, date, and page number header/footer annotations from all Edge print output.",
        },
        new TweakDef
        {
            Id = "edgepdp-use-system-default-printer",
            Label = "Edge Print & PDF Policy: Default to System Default Printer in Print Dialog",
            Category = "Edge Print & PDF Policy",
            Description = "Configures the Edge print preview to preselect the system default printer instead of the last printer used in Edge. In managed environments, the system default printer is set by IT policy. This prevents users from accidentally printing to the last used printer (which may be a home or personal printer on a previous session) and ensures all output defaults to the approved enterprise printer.",
            Tags = ["edge", "printing", "printer", "default", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "PrintPreviewUseSystemDefaultPrinter", 1)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "PrintPreviewUseSystemDefaultPrinter")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "PrintPreviewUseSystemDefaultPrinter", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Print dialog opens with the OS default printer pre-selected instead of the last used Edge printer.",
        },
        new TweakDef
        {
            Id = "edgepdp-disable-cloud-print",
            Label = "Edge Print & PDF Policy: Disable Google Cloud Print Submission",
            Category = "Edge Print & PDF Policy",
            Description = "Prevents Microsoft Edge from submitting print jobs via Google Cloud Print. Cloud Print routes documents through external cloud infrastructure, which may violate data-residency requirements or introduce uncontrolled data egress in corporate environments. Disabling this forces all print jobs to use local or network printers managed by IT.",
            Tags = ["edge", "printing", "cloud print", "policy", "data-loss"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "CloudPrintSubmitEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "CloudPrintSubmitEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "CloudPrintSubmitEnabled", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Cloud Print option removed from Edge print dialog; only local and network printers available.",
        },
        new TweakDef
        {
            Id = "edgepdp-block-legacy-printer-drivers",
            Label = "Edge Print & PDF Policy: Block Legacy Printer Drivers from Edge Printing",
            Category = "Edge Print & PDF Policy",
            Description = "Prevents Microsoft Edge from sending print jobs through legacy (non-IPP) printer drivers. Legacy printer drivers were removed from the Windows print subsystem as part of PrintNightmare remediation. When this policy is set to 0, Edge's printing stack will only use modern IPP print drivers and will refuse to enumerate or use legacy kernel-mode printer drivers, reducing attack surface.",
            Tags = ["edge", "printing", "drivers", "security", "printnightmare", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "LegacyPrinterDriversAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "LegacyPrinterDriversAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "LegacyPrinterDriversAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Blocks legacy kernel-mode printer drivers in Edge; older printers without IPP support may be unavailable.",
        },
        new TweakDef
        {
            Id = "edgepdp-open-pdf-externally",
            Label = "Edge Print & PDF Policy: Open PDF Files with External Application",
            Category = "Edge Print & PDF Policy",
            Description = "Forces Microsoft Edge to open PDF files using the operating system's default PDF application (e.g., Adobe Acrobat Reader, Foxit) instead of the built-in Edge PDF viewer. This is useful in environments where the standard PDF tool provides additional features such as digital signature validation, form filling, or DRM support that the browser's viewer does not provide.",
            Tags = ["edge", "pdf", "viewer", "external", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "AlwaysOpenPdfExternally", 1)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "AlwaysOpenPdfExternally")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "AlwaysOpenPdfExternally", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "PDF files downloaded via Edge are opened with the OS default PDF app instead of the built-in viewer.",
        },
        new TweakDef
        {
            Id = "edgepdp-disable-pdf-annotations",
            Label = "Edge Print & PDF Policy: Disable PDF Annotation Tools in Edge Viewer",
            Category = "Edge Print & PDF Policy",
            Description = "Disables annotation tools in the Microsoft Edge built-in PDF viewer. Annotations allow users to add highlights, underlines, and free-form text comments to PDFs and save the annotated file. In environments where PDFs are read-only compliance documents, legal filings, or audit reports, preventing browser-level annotation preserves document integrity and prevents accidental modification.",
            Tags = ["edge", "pdf", "annotations", "viewer", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "PdfAnnotationsEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "PdfAnnotationsEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "PdfAnnotationsEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Removes annotation toolbar from Edge PDF viewer; PDFs are read-only in the browser.",
        },
        new TweakDef
        {
            Id = "edgepdp-disable-pdf-xfa-forms",
            Label = "Edge Print & PDF Policy: Disable XFA Form Support in Edge PDF Viewer",
            Category = "Edge Print & PDF Policy",
            Description = "Disables XFA (XML Forms Architecture) form support in the Microsoft Edge PDF viewer. XFA is a legacy Adobe-proprietary format for dynamic PDF forms. Modern PDFs use AcroForm instead. XFA forms require a JavaScript engine running inside the PDF reader, which significantly expands the attack surface. Disabling XFA prevents this JavaScript engine from activating for PDFs with embedded XFA content.",
            Tags = ["edge", "pdf", "xfa", "forms", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "PdfXFAEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "PdfXFAEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "PdfXFAEnabled", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "XFA-based PDF forms will not render in Edge viewer; PDF opens as a non-interactive document.",
        },
        new TweakDef
        {
            Id = "edgepdp-set-pdf-rasterize-dpi",
            Label = "Edge Print & PDF Policy: Enable PDF Rasterization for Printing at 150 DPI",
            Category = "Edge Print & PDF Policy",
            Description = "Configures Microsoft Edge to rasterize PDF documents at 150 DPI when printing them. Rasterization converts vector and text content in the PDF to a bitmap image before sending to the printer driver. This avoids font-rendering issues with PostScript printers, resolves transparency layer conflicts with some corporate printer drivers, and produces consistent output on printers that have limited PDF pass-through support.",
            Tags = ["edge", "pdf", "printing", "rasterize", "dpi", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "PrintRasterizePdfDpi", 150)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "PrintRasterizePdfDpi")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "PrintRasterizePdfDpi", 150)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "PDFs printed from Edge are rendered to 150-DPI bitmaps; avoids font/transparency driver conflicts.",
        },
        new TweakDef
        {
            Id = "edgepdp-disable-pdf-default-recommendation",
            Label = "Edge Print & PDF Policy: Suppress Recommendation to Set Edge as Default PDF Viewer",
            Category = "Edge Print & PDF Policy",
            Description = "Prevents Microsoft Edge from showing recommendations or prompts asking the user to set Edge as the default PDF application. In environments where a specific PDF tool (Adobe Acrobat, Foxit, Nitro) is the approved standard for PDF handling, Edge's persistent recommendation to override the default association creates user confusion and non-compliance with the approved software stack.",
            Tags = ["edge", "pdf", "default app", "recommendation", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ShowPDFDefaultRecommendationsEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ShowPDFDefaultRecommendationsEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ShowPDFDefaultRecommendationsEnabled", 0)],
            ImpactScore = 1,
            SafetyRating = 5,
            ImpactNote = "Suppresses Edge prompt to become default PDF viewer; OS default PDF handler remains unchanged.",
        },
    ];
}
