namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;
using System.Collections.Generic;

internal static class EdgeTrackingProtectionPolicy
{
    private const string EdgeKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "edgetrack-strict-tracking-prevention",
            Label = "Edge Tracking Protection Policy: Enforce Strict Tracking Prevention",
            Category = "Edge Tracking Protection Policy",
            Description = "Forces Microsoft Edge to use Strict tracking prevention mode, which blocks all known trackers regardless of whether they are from sites the user has previously visited. Strict mode blocks trackers that cause compatibility issues and prevents tracking from any source — including cross-site embedded trackers, fingerprinting scripts, and crypto mining scripts. In privacy-focused corporate environments, strict mode reduces enterprise data leakage to advertising networks.",
            Tags = ["edge", "tracking prevention", "strict", "privacy", "telemetry", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "TrackingPrevention", 3)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "TrackingPrevention")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "TrackingPrevention", 3)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Strict tracking prevention (value 3) blocks all known trackers; some web apps with third-party embedded content may break.",
        },
        new TweakDef
        {
            Id = "edgetrack-clear-cache-on-exit",
            Label = "Edge Tracking Protection Policy: Clear Cached Images and Files on Exit",
            Category = "Edge Tracking Protection Policy",
            Description = "Configures Microsoft Edge to automatically delete all cached images and files from the browser cache when the browser closes. The disk cache is a persistent storage mechanism that survives browser restarts and can be used as a covert channel for tracking users across sessions (cache timing attacks, ETag tracking, and cache element counting). Clearing the cache on exit prevents this class of cross-session tracking.",
            Tags = ["edge", "cache", "privacy", "exit", "tracking", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ClearCachedImagesAndFilesOnExit", 1)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ClearCachedImagesAndFilesOnExit")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ClearCachedImagesAndFilesOnExit", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "All cached media cleared at browser close; subsequent page loads will re-download previously cached resources.",
        },
        new TweakDef
        {
            Id = "edgetrack-disable-user-feedback",
            Label = "Edge Tracking Protection Policy: Disable User Feedback and Error Reporting",
            Category = "Edge Tracking Protection Policy",
            Description = "Blocks the built-in Edge user feedback mechanism and telemetric crash/error reporting. When UserFeedbackAllowed is set to 0, the Help > Send Feedback option is removed and Edge will not submit user-generated feedback reports or automatic crash diagnostics to Microsoft. Crash reports may contain browser session state, visited URL data, and clipboard content captured at the time of the crash.",
            Tags = ["edge", "feedback", "telemetry", "crash reporting", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "UserFeedbackAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "UserFeedbackAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "UserFeedbackAllowed", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Feedback menu entry removed and automatic crash reporting disabled; no browser session data sent in feedback reports.",
        },
        new TweakDef
        {
            Id = "edgetrack-disable-signed-http-exchange",
            Label = "Edge Tracking Protection Policy: Disable Signed HTTP Exchange Support",
            Category = "Edge Tracking Protection Policy",
            Description = "Disables Signed HTTP Exchange (SXG) support in Microsoft Edge. SXG is a web packaging format that allows content to be pre-signed by the original publisher and served from a CDN or cache while appearing to originate from the publisher's domain. While this improves performance for AMP and pre-fetched content, it can break referrer-origin alignment, complicate certificate revocation for distributed content, and interfere with corporate content inspection proxies.",
            Tags = ["edge", "signed http exchange", "sxg", "security", "proxy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "SignedHTTPExchangeEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "SignedHTTPExchangeEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "SignedHTTPExchangeEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "SXG pre-signed content disabled; some AMP and pre-cached pages may fall back to regular HTTP fetching.",
        },
        new TweakDef
        {
            Id = "edgetrack-disable-shared-array-buffer-unrestricted",
            Label = "Edge Tracking Protection Policy: Enforce Cross-Origin Isolation for SharedArrayBuffer",
            Category = "Edge Tracking Protection Policy",
            Description = "Prevents websites from using the SharedArrayBuffer (SAB) API without proper cross-origin isolation headers (COOP/COEP). SharedArrayBuffer enables high-resolution timer attacks and Spectre-class side-channel exploits when used from pages that are not properly isolated. Disabling unrestricted SAB access forces all websites that require SharedArrayBuffer to declare cross-origin isolation, which significantly reduces Spectre exploitation potential.",
            Tags = ["edge", "sharedarraybuffer", "spectre", "security", "cross-origin", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "SharedArrayBufferUnrestrictedAccessAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "SharedArrayBufferUnrestrictedAccessAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "SharedArrayBufferUnrestrictedAccessAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "SAB usage requires COOP/COEP headers; sites lacking cross-origin isolation will lose SAB access.",
        },
        new TweakDef
        {
            Id = "edgetrack-disable-surf-game",
            Label = "Edge Tracking Protection Policy: Disable Surf Easter Egg Game on Error Pages",
            Category = "Edge Tracking Protection Policy",
            Description = "Disables the Surf easter egg game that appears on Edge error pages (similar to Chrome's T-Rex game). When AllowSurfGame is set to 0, the game cannot be activated on the no-internet or ERR_CONNECTION_REFUSED error page. In managed enterprise environments and kiosk deployments, the hidden game represents an uncontrolled interactive application running within the browser, which may distract users or enable unintended browser activity on locked-down systems.",
            Tags = ["edge", "surf game", "easter egg", "error page", "kiosk", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "AllowSurfGame", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "AllowSurfGame")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "AllowSurfGame", 0)],
            ImpactScore = 1,
            SafetyRating = 5,
            ImpactNote = "Surf easter egg disabled on Edge error pages; no impact on normal browser behavior.",
        },
        new TweakDef
        {
            Id = "edgetrack-disable-immersive-reader-grammar",
            Label = "Edge Tracking Protection Policy: Disable Immersive Reader Grammar Tools",
            Category = "Edge Tracking Protection Policy",
            Description = "Disables the Grammar Tools option within the Edge Immersive Reader panel. When Immersive Reader is opened, Grammar Tools provides syllable highlighting, part-of-speech color-coding, and text analysis powered by Microsoft language services. The grammar analysis requires sending page text content to Microsoft cloud language endpoints. Disabling this feature prevents reading-mode content from being transmitted to external language processing services.",
            Tags = ["edge", "immersive reader", "grammar tools", "privacy", "cloud", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ImmersiveReaderGrammarToolsEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ImmersiveReaderGrammarToolsEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ImmersiveReaderGrammarToolsEnabled", 0)],
            ImpactScore = 1,
            SafetyRating = 5,
            ImpactNote = "Grammar analysis panel removed from Immersive Reader; syllable and part-of-speech highlighting unavailable.",
        },
        new TweakDef
        {
            Id = "edgetrack-block-intrusive-ads",
            Label = "Edge Tracking Protection Policy: Block Ads on Sites with Intrusive Ad Experiences",
            Category = "Edge Tracking Protection Policy",
            Description = "Configures Microsoft Edge to block all ads on websites that have been flagged by the Better Ads Standards initiative for running intrusive ad experiences (auto-playing video with sound, countdown interstitials, prestitial ads with countdown). Setting AdsSettingForIntrusiveAdsSites to 2 activates the integrated ad-blocking on flagged domains. This reduces the number of ad trackers loaded, improves page load performance, and removes disruptive content on violating sites.",
            Tags = ["edge", "ads", "intrusive ads", "better ads", "tracking", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "AdsSettingForIntrusiveAdsSites", 2)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "AdsSettingForIntrusiveAdsSites")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "AdsSettingForIntrusiveAdsSites", 2)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Ads blocked on Better Ads violating sites (value 2); only affects flagged sites, not all advertising.",
        },
        new TweakDef
        {
            Id = "edgetrack-disable-builtin-dns-client",
            Label = "Edge Tracking Protection Policy: Disable Edge Built-In DNS Client (Use OS DNS)",
            Category = "Edge Tracking Protection Policy",
            Description = "Disables the built-in DNS client in Microsoft Edge and forces the browser to use the operating system's DNS resolver for all name resolution. Edge's built-in DNS client can use different DNS servers, timeout settings, and resolution strategies than the OS-configured DNS — potentially bypassing corporate DNS policies, split-horizon DNS configurations, and DNS-based filtering. Using the OS DNS ensures Edge resolution goes through the same monitored and filtered DNS path as all other applications.",
            Tags = ["edge", "dns", "built-in dns", "network", "corporate", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "BuiltInDnsClientEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "BuiltInDnsClientEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "BuiltInDnsClientEnabled", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Edge uses OS DNS resolver; browser DNS queries follow corporate DNS policy and filtering rules.",
        },
        new TweakDef
        {
            Id = "edgetrack-disable-lens-search",
            Label = "Edge Tracking Protection Policy: Disable Image Lens Region Search",
            Category = "Edge Tracking Protection Policy",
            Description = "Disables the Lens Region Search feature in Microsoft Edge, which adds a camera/Bing icon to the browser toolbar and context menu allowing users to select a region of any web page and submit it as an image search query to Bing. Lens Region Search uploads a screenshot of the selected page region to Microsoft Bing's image search service. This creates an implicit image-based data exfiltration path for sensitive content displayed on internal corporate web pages or classified documents.",
            Tags = ["edge", "lens search", "bing", "image search", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "LensRegionSearchEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "LensRegionSearchEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "LensRegionSearchEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Lens/image region search removed from Edge context menu; no page screenshots sent to Bing image search.",
        },
    ];
}
