namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;
using System.Collections.Generic;

internal static class EdgeInternetExplorerModePolicy
{
    private const string EdgeKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "iemode-disable-ie-integration",
            Label = "Edge IE Mode Policy: Disable Internet Explorer Integration Mode",
            Category = "Edge IE Mode Policy",
            Description = "Configures Microsoft Edge to disable Internet Explorer integration mode entirely. Setting InternetExplorerIntegrationLevel to 0 means Edge will not render any pages in the Internet Explorer rendering engine (Trident/MSHTML), even if those pages match an Enterprise Mode Site List. IE mode is a legacy compatibility shunt that activates the deprecated IE11 engine inside Edge. Disabling it forces all web content through the modern Chromium renderer and eliminates the IE11 attack surface.",
            Tags = ["edge", "internet explorer", "ie mode", "legacy", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "InternetExplorerIntegrationLevel", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "InternetExplorerIntegrationLevel")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "InternetExplorerIntegrationLevel", 0)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "IE mode tab rendering disabled; legacy intranet apps requiring Trident/MSHTML will no longer render in Edge.",
        },
        new TweakDef
        {
            Id = "iemode-block-reload-in-ie",
            Label = "Edge IE Mode Policy: Block User Reload in IE Mode for Standard Pages",
            Category = "Edge IE Mode Policy",
            Description = "Prevents users from manually reloading non-IE-mode pages in Internet Explorer mode via the Edge context menu or address bar action. Without this policy, users can force any arbitrary web page into the IE rendering engine by right-clicking and selecting 'Reload tab in Internet Explorer mode'. This bypasses IT-controlled site lists and allows uncontrolled Trident-rendered browsing, which may expose older, less patched code paths to malicious content.",
            Tags = ["edge", "internet explorer", "ie mode", "reload", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "InternetExplorerIntegrationReloadInIEModeAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "InternetExplorerIntegrationReloadInIEModeAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "InternetExplorerIntegrationReloadInIEModeAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Users cannot force arbitrary pages into IE mode via context menu; only IT-configured site list entries render in IE mode.",
        },
        new TweakDef
        {
            Id = "iemode-block-ie-mode-tab-in-edge",
            Label = "Edge IE Mode Policy: Block IE Mode Tabs from Returning to Edge Mode",
            Category = "Edge IE Mode Policy",
            Description = "Prevents Internet Explorer mode tabs from navigating back to Microsoft Edge mode (Chromium rendering) for pages that are not in the Enterprise Mode Site List. When a user navigates from an IE mode tab to a page not on the site list, the default behavior opens the new page in a separate Edge tab. Blocking this prevents session mixing between Trident and Chromium rendering contexts, which is important for maintaining consistent security isolation.",
            Tags = ["edge", "internet explorer", "ie mode", "tab", "isolation", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "InternetExplorerModeTabInEdgeModeAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "InternetExplorerModeTabInEdgeModeAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "InternetExplorerModeTabInEdgeModeAllowed", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "IE mode tabs cannot switch to Edge mode for off-list pages; rendering context is locked per tab.",
        },
        new TweakDef
        {
            Id = "iemode-block-local-file-in-ie",
            Label = "Edge IE Mode Policy: Block Local Files from Opening in IE Mode",
            Category = "Edge IE Mode Policy",
            Description = "Prevents local file:// protocol pages from being loaded in Internet Explorer mode within Edge. Without this restriction, local HTML files and intranet file shares accessed via UNC paths can be forced into IE mode, where ActiveX controls, VBScript, and other legacy technologies are available. Local files rendered in the IE engine can access the local file system with fewer restrictions than Chromium-hosted content.",
            Tags = ["edge", "internet explorer", "ie mode", "local files", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "InternetExplorerIntegrationLocalFileAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "InternetExplorerIntegrationLocalFileAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "InternetExplorerIntegrationLocalFileAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Local HTML files cannot be rendered using the IE engine; file:// URLs always use Chromium.",
        },
        new TweakDef
        {
            Id = "iemode-block-local-page-in-ie",
            Label = "Edge IE Mode Policy: Block Local Pages from Being Loaded in IE Mode",
            Category = "Edge IE Mode Policy",
            Description = "Prevents local intranet pages (those resolved via the Local intranet zone in Internet Explorer, including short hostnames and *.local domains) from being automatically elevated into Internet Explorer mode within Edge. Without this control, legacy intranet pages that IE mode site lists or automatic zone detection would route to Trident can activate legacy ActiveX controls and scripts that are unavailable in Chromium.",
            Tags = ["edge", "internet explorer", "ie mode", "intranet", "local page", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "InternetExplorerIntegrationLocalPageAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "InternetExplorerIntegrationLocalPageAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "InternetExplorerIntegrationLocalPageAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Intranet local pages not rendered in IE mode; short hostname intranet sites use Chromium rendering.",
        },
        new TweakDef
        {
            Id = "iemode-dont-send-intranet-to-ie",
            Label = "Edge IE Mode Policy: Disable Automatic Redirect of Intranet to Internet Explorer Mode",
            Category = "Edge IE Mode Policy",
            Description = "Prevents Microsoft Edge from automatically redirecting intranet zone URLs to Internet Explorer mode or the standalone Internet Explorer process. In default configurations, Edge may auto-detect intranet sites via the IE Intranet zone heuristic and silently open them in IE. Setting SendIntranetToInternetExplorer to 0 disables this behavior, ensuring intranet content is always rendered in the Chromium engine unless explicitly listed in an Enterprise Mode Site List.",
            Tags = ["edge", "internet explorer", "intranet", "auto-redirect", "ie mode", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "SendIntranetToInternetExplorer", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "SendIntranetToInternetExplorer")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "SendIntranetToInternetExplorer", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Intranet sites not automatically opened in IE; all intranet navigation uses Edge Chromium engine.",
        },
        new TweakDef
        {
            Id = "iemode-enhanced-hang-detection",
            Label = "Edge IE Mode Policy: Enable Enhanced Hang Detection for IE Mode Tabs",
            Category = "Edge IE Mode Policy",
            Description = "Enables enhanced hang detection for Internet Explorer mode tabs within Microsoft Edge. When InternetExplorerIntegrationEnhancedHangDetection is set to 1, Edge applies a shorter hang timeout to IE mode tabs and surfaces a 'This page is not responding' dialog more quickly when an IE mode tab stops responding. In managed environments where IE mode is used for legacy line-of-business apps, enhanced hang detection prevents a single frozen IE component from blocking the entire Edge process.",
            Tags = ["edge", "internet explorer", "ie mode", "hang detection", "reliability", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "InternetExplorerIntegrationEnhancedHangDetection", 1)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "InternetExplorerIntegrationEnhancedHangDetection")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "InternetExplorerIntegrationEnhancedHangDetection", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Enhanced hang detection enabled; frozen IE mode tabs surface recovery dialog faster.",
        },
        new TweakDef
        {
            Id = "iemode-block-zone-id-mht-files",
            Label = "Edge IE Mode Policy: Block Zone-Identifier MHT Files from IE Mode",
            Category = "Edge IE Mode Policy",
            Description = "Prevents MHTML (.mht, .mhtml) files that carry a Zone.Identifier Alternate Data Stream (Mark of the Web) from being opened in Internet Explorer mode. MHT files downloaded from the internet carry a Zone.Identifier ADS marking them as untrusted. Without this policy, Edge may open such files in IE mode where legacy MSHTML parsing applies. Blocking zone-marked MHT files from IE mode forces them to open in the Chromium renderer with modern sandboxing.",
            Tags = ["edge", "internet explorer", "ie mode", "mht", "zone identifier", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "InternetExplorerIntegrationZoneIdentifierMhtFileAllowed", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "InternetExplorerIntegrationZoneIdentifierMhtFileAllowed")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "InternetExplorerIntegrationZoneIdentifierMhtFileAllowed", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Zone-marked MHT files open in Chromium renderer instead of IE mode; reduces MSHTML parsing of untrusted web archives.",
        },
        new TweakDef
        {
            Id = "iemode-set-window-open-threshold",
            Label = "Edge IE Mode Policy: Set window.open Navigation Threshold for IE Mode Tabs",
            Category = "Edge IE Mode Policy",
            Description = "Controls the pixel-width threshold above which new windows opened via window.open() from IE mode tabs are rendered in Edge mode rather than IE mode. When InternetExplorerIntegrationWindowOpenWidthThreshold is set to 0, all new windows opened by IE mode tabs will open in Edge (Chromium) mode regardless of their dimensions. This prevents IE mode tabs from spawning new windows that also use the Trident rendering engine, containing the legacy engine to only specifically configured tabs.",
            Tags = ["edge", "internet explorer", "ie mode", "window.open", "rendering", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "InternetExplorerIntegrationWindowOpenWidthThreshold", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "InternetExplorerIntegrationWindowOpenWidthThreshold")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "InternetExplorerIntegrationWindowOpenWidthThreshold", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "All window.open() calls from IE mode tabs open as Edge Chromium tabs (value 0); no new IE mode windows spawned.",
        },
        new TweakDef
        {
            Id = "iemode-disable-cloud-site-list-management",
            Label = "Edge IE Mode Policy: Disable Cloud-Managed IE Mode Site List",
            Category = "Edge IE Mode Policy",
            Description = "Disables the Cloud Site List Management feature in Microsoft Edge, which allows IT administrators to publish and update the Enterprise Mode Site List via Microsoft 365 Admin Center (Microsoft Entra ID / Intune cloud) without requiring on-premises GPO or file share deployment. When CloudSiteListManagementEnabled is set to 0, Edge only reads the site list from the locally configured URL or GPO path. This maintains site list control within the organization's on-premises infrastructure and prevents cloud-based overrides.",
            Tags = ["edge", "internet explorer", "ie mode", "site list", "cloud", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "CloudSiteListManagementEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "CloudSiteListManagementEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "CloudSiteListManagementEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Cloud-based IE mode site list management disabled; site list is sourced from on-premises GPO or file share only.",
        },
    ];
}
