namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;
using System.Collections.Generic;

internal static class EdgeSearchAddressBarPolicy
{
    private const string EdgeKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "edgesrch-disable-search-suggest",
            Label = "Edge Search & Address Bar Policy: Disable Address Bar Search Suggestions",
            Category = "Edge Search & Address Bar Policy",
            Description = "Prevents Microsoft Edge from displaying predictive search suggestions in the address bar as the user types. Search suggestions are sent keystroke-by-keystroke to the configured search provider (typically Bing). Disabling this eliminates real-time data leakage of partially typed URLs and search queries to Microsoft or third-party search engines over the network.",
            Tags = ["edge", "search", "suggestions", "address bar", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "SearchSuggestEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "SearchSuggestEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "SearchSuggestEnabled", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "No search suggestions appear in the address bar; each search is only submitted when Enter is pressed.",
        },
        new TweakDef
        {
            Id = "edgesrch-disable-bing-address-bar-provider",
            Label = "Edge Search & Address Bar Policy: Remove Microsoft Search in Bing from Address Bar",
            Category = "Edge Search & Address Bar Policy",
            Description = "Removes the Microsoft Search in Bing suggestion provider from the Microsoft Edge address bar. When enabled, this provider queries the Microsoft Search enterprise index and Bing whenever the user types in the address bar, even for single words or partial terms. In environments where all internet search is routed through an approved proxy or where Bing query telemetry is unwanted, removing this provider reduces unsolicited outbound traffic.",
            Tags = ["edge", "search", "bing", "address bar", "microsoft search", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "AddressBarMicrosoftSearchInBingProviderEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "AddressBarMicrosoftSearchInBingProviderEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "AddressBarMicrosoftSearchInBingProviderEnabled", 0)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Removes Bing suggestion provider from address bar; reduces background search queries to Microsoft.",
        },
        new TweakDef
        {
            Id = "edgesrch-disable-local-providers",
            Label = "Edge Search & Address Bar Policy: Disable Local and Intranet Search Suggestions",
            Category = "Edge Search & Address Bar Policy",
            Description = "Disables local suggestion providers in the Microsoft Edge address bar, including previously visited intranet URLs, bookmarks from the managed profile, and file:// path completions. On shared workstations, browser kiosk sessions, and temporary accounts, address bar history exposure (even of intranet URLs) could reveal which internal systems and resources the previous user visited.",
            Tags = ["edge", "search", "local providers", "intranet", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "LocalProvidersEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "LocalProvidersEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "LocalProvidersEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Intranet URL completions and local history suggestions no longer appear in the Edge address bar.",
        },
        new TweakDef
        {
            Id = "edgesrch-disable-network-prediction",
            Label = "Edge Search & Address Bar Policy: Disable Network Prediction and Prefetch",
            Category = "Edge Search & Address Bar Policy",
            Description = "Disables all network prediction and DNS prefetching in Microsoft Edge. With prediction enabled (the default), Edge pre-resolves DNS and pre-connects to the likely destinations of links visible on the page and the current address bar entry, even before the user clicks. This pre-warming creates network connections to destinations the user has never explicitly visited, which violates strict outbound traffic controls and generates noise in network monitoring.",
            Tags = ["edge", "network prediction", "prefetch", "dns", "performance", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "NetworkPredictionOptions", 2)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "NetworkPredictionOptions")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "NetworkPredictionOptions", 2)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Value 2 disables DNS prefetch and TCP preconnect; may slightly increase navigation time on first-visit pages.",
        },
        new TweakDef
        {
            Id = "edgesrch-disable-dns-interception-check",
            Label = "Edge Search & Address Bar Policy: Disable DNS Interception Detection",
            Category = "Edge Search & Address Bar Policy",
            Description = "Disables the DNS interception detection feature in Microsoft Edge. When enabled, Edge periodically sends probe DNS requests to non-existent hostnames and checks whether the DNS resolver returns NXDOMAIN (expected) or a real IP address (indicating intercepting DNS). In enterprise environments with transparent DNS proxies, split-horizon DNS, or captive portal infrastructure, this probe generates false positives and triggers browser warnings that confuse users.",
            Tags = ["edge", "dns", "interception", "detection", "network", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "DNSInterceptionChecksEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "DNSInterceptionChecksEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "DNSInterceptionChecksEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "DNS interception probe requests are suppressed; no false-positive warnings from split-horizon DNS environments.",
        },
        new TweakDef
        {
            Id = "edgesrch-disable-error-page-web-service",
            Label = "Edge Search & Address Bar Policy: Disable Web Service for Navigation Error Pages",
            Category = "Edge Search & Address Bar Policy",
            Description = "Prevents Microsoft Edge from using a Microsoft-hosted web service to generate alternative navigation error pages when a site is unreachable. When this policy is enabled, Edge sends the unreachable URL to Microsoft's servers to retrieve a custom error page with suggestions. Disabling it keeps Edge using its built-in static error page and prevents the URL of failed navigation attempts from being submitted to Microsoft.",
            Tags = ["edge", "error page", "navigation", "web service", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "ResolveNavigationErrorsUseWebService", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "ResolveNavigationErrorsUseWebService")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "ResolveNavigationErrorsUseWebService", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Failed navigation attempts show Edge's built-in error page; failed URLs are not sent to Microsoft.",
        },
        new TweakDef
        {
            Id = "edgesrch-disable-alternate-error-pages",
            Label = "Edge Search & Address Bar Policy: Disable Alternate Error Page Web Service",
            Category = "Edge Search & Address Bar Policy",
            Description = "Disables the alternate error page feature in Microsoft Edge, which contacts a Microsoft web service to display rich error pages with suggestions, links, and diagnostics for unreachable URLs. The alternate error page service sends the unreachable hostname to Microsoft even if the hostname is a private intranet address. Disabling it keeps failed navigations private and uses only Edge's built-in static error content.",
            Tags = ["edge", "error page", "alternate", "web service", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "AlternateErrorPagesEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "AlternateErrorPagesEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "AlternateErrorPagesEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "No Microsoft-hosted error page content; Edge shows its own static error page for unreachable sites.",
        },
        new TweakDef
        {
            Id = "edgesrch-disable-cloud-related-matches",
            Label = "Edge Search & Address Bar Policy: Disable Cloud-Based Related Matches in Address Bar",
            Category = "Edge Search & Address Bar Policy",
            Description = "Disables the cloud-based Related Matches provider in the Microsoft Edge address bar. Related Matches is a Microsoft service that offers AI-enhanced cross-domain URL completions based on browsing behavior, intent signals, and trending content signals from the Bing cloud index. Unlike local completions, Related Matches sends real-time query data to Microsoft cloud even for partial input.",
            Tags = ["edge", "search", "cloud", "related matches", "ai", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "RelatedMatchesCloudServiceEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "RelatedMatchesCloudServiceEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "RelatedMatchesCloudServiceEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Related Matches AI cloud provider disabled; address bar suggestions come only from local history and bookmarks.",
        },
        new TweakDef
        {
            Id = "edgesrch-disable-sidebar-search",
            Label = "Edge Search & Address Bar Policy: Disable Search in Sidebar Panel",
            Category = "Edge Search & Address Bar Policy",
            Description = "Disables the Edge Search in Sidebar feature, which opens a search panel on the right side of the browser when the user right-clicks and selects 'Search using web side panel', or when the user selects text and triggers a sidebar search action. This feature creates a split-screen search experience that shares the selected text with Microsoft's search service.",
            Tags = ["edge", "sidebar", "search", "side panel", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "SearchInSidebarEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "SearchInSidebarEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "SearchInSidebarEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Right-click 'Search web side panel' option removed; selected text no longer sent to Edge sidebar search.",
        },
        new TweakDef
        {
            Id = "edgesrch-disable-typosquatting-checker",
            Label = "Edge Search & Address Bar Policy: Disable URL Typosquatting Checker",
            Category = "Edge Search & Address Bar Policy",
            Description = "Disables the Edge typosquatting checker that compares navigated URLs against a list of commonly mistyped domain names to warn the user when they may have typed a typosquatting site. While the checker improves user safety, it performs cloud lookups for URLs navigated via the address bar and sends the navigated hostname to Microsoft for comparison, creating outbound communication for every navigation.",
            Tags = ["edge", "typosquatting", "url", "safety", "network", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [EdgeKey],
            ApplyOps = [RegOp.SetDword(EdgeKey, "TyposquattingCheckerEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(EdgeKey, "TyposquattingCheckerEnabled")],
            DetectOps = [RegOp.CheckDword(EdgeKey, "TyposquattingCheckerEnabled", 0)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Typosquatting URL warnings disabled; users will not be warned about similar-looking domains.",
        },
    ];
}
