namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class EnterpriseStateRoamingPolicy
{
    private const string SyncKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\SettingSync";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "esroam-disable-app-setting-sync",
            Label = "Enterprise State Roaming: Disable Application Settings Sync",
            Category = "Enterprise State Roaming Policy",
            Description = "Prevents Windows from syncing application settings (e.g., browser preferences, UWP app configuration) to Azure AD / Microsoft account cloud storage via Enterprise State Roaming. Application settings often contain business-critical customizations; roaming them to cloud storage creates data residency concerns and can cause settings to propagate to personal devices using the same account.",
            Tags = ["state roaming", "sync", "app settings", "azure ad", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SyncKey],
            ApplyOps = [RegOp.SetDword(SyncKey, "DisableApplicationSettingSync", 2)],
            RemoveOps = [RegOp.DeleteValue(SyncKey, "DisableApplicationSettingSync")],
            DetectOps = [RegOp.CheckDword(SyncKey, "DisableApplicationSettingSync", 2)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Disables app settings sync to cloud; settings remain device-local only.",
        },
        new TweakDef
        {
            Id = "esroam-disable-start-layout-sync",
            Label = "Enterprise State Roaming: Disable Start Menu Layout Sync",
            Category = "Enterprise State Roaming Policy",
            Description = "Disables synchronization of the Windows Start layout (Start screen tile arrangement, pinned apps, size configuration) across devices enrolled in Enterprise State Roaming. In managed environments where Start menus are deployed via Group Policy or provisioning packages, cloud roaming of Start layout can overwrite the IT-managed layout, creating inconsistency across machines.",
            Tags = ["state roaming", "sync", "start menu", "layout", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SyncKey],
            ApplyOps = [RegOp.SetDword(SyncKey, "DisableStartLayoutSettingSync", 2)],
            RemoveOps = [RegOp.DeleteValue(SyncKey, "DisableStartLayoutSettingSync")],
            DetectOps = [RegOp.CheckDword(SyncKey, "DisableStartLayoutSettingSync", 2)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Stops Start menu layout from roaming; each device keeps its own IT-deployed or user-configured layout.",
        },
        new TweakDef
        {
            Id = "esroam-disable-desktop-theme-sync",
            Label = "Enterprise State Roaming: Disable Desktop Theme Sync",
            Category = "Enterprise State Roaming Policy",
            Description = "Prevents Windows desktop themes (wallpaper, accent color, visual effects, window transparency) from synchronizing across devices. While cosmetic, theme sync can override corporate branding standards (desktop wallpapers, accent colors mandated by IT) when the same account logs in on different managed computers or when personal account themes overwrite work account settings.",
            Tags = ["state roaming", "sync", "theme", "desktop", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SyncKey],
            ApplyOps = [RegOp.SetDword(SyncKey, "DisableDesktopThemeSettingSync", 2)],
            RemoveOps = [RegOp.DeleteValue(SyncKey, "DisableDesktopThemeSettingSync")],
            DetectOps = [RegOp.CheckDword(SyncKey, "DisableDesktopThemeSettingSync", 2)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Prevents theme roaming; no functional impact — wallpaper and accent color stay per-device.",
        },
        new TweakDef
        {
            Id = "esroam-disable-browser-setting-sync",
            Label = "Enterprise State Roaming: Disable Web Browser Settings Sync",
            Category = "Enterprise State Roaming Policy",
            Description = "Stops the Windows Settings Sync provider from roaming browser-related settings (favorites, history sync pointers) through the ESR (Enterprise State Roaming) channel. Note: this controls the Windows-level sync channel, not the browser's own sync channel. Browser favorites should be managed via browser-specific policies (see Edge/Chrome policy modules).",
            Tags = ["state roaming", "sync", "browser", "favorites", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SyncKey],
            ApplyOps = [RegOp.SetDword(SyncKey, "DisableWebBrowserSettingSync", 2)],
            RemoveOps = [RegOp.DeleteValue(SyncKey, "DisableWebBrowserSettingSync")],
            DetectOps = [RegOp.CheckDword(SyncKey, "DisableWebBrowserSettingSync", 2)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Blocks ESR-level browser sync; browser-native sync (Edge profile sync) requires a separate policy.",
        },
        new TweakDef
        {
            Id = "esroam-disable-password-sync",
            Label = "Enterprise State Roaming: Disable Password Settings Sync",
            Category = "Enterprise State Roaming Policy",
            Description = "Prevents Windows credential and password hashes from being synchronized through the Enterprise State Roaming channel to Azure AD cloud storage. Password roaming via ESR is distinct from Azure AD seamless SSO and may involve credential material being persisted in a cloud-accessible store. In high-security environments, all credential handling must be on-premises only.",
            Tags = ["state roaming", "sync", "password", "credentials", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SyncKey],
            ApplyOps = [RegOp.SetDword(SyncKey, "DisablePasswordSettingSync", 2)],
            RemoveOps = [RegOp.DeleteValue(SyncKey, "DisablePasswordSettingSync")],
            DetectOps = [RegOp.CheckDword(SyncKey, "DisablePasswordSettingSync", 2)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Prevents credential data from roaming via ESR; complements Azure AD SSPR policy.",
        },
        new TweakDef
        {
            Id = "esroam-disable-app-sync-setting",
            Label = "Enterprise State Roaming: Disable App Sync via ESR Channel",
            Category = "Enterprise State Roaming Policy",
            Description = "Disables the specific ESR sync provider for application data packages (UWP AppX app state, configuration blobs stored in the cloud). App sync allows UWP apps to restore their last-used state—including user-typed data—when the same account signs in on another device. For apps that handle sensitive data (forms, documents), roaming this state creates residual data in Azure.",
            Tags = ["state roaming", "sync", "app data", "uwp", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SyncKey],
            ApplyOps = [RegOp.SetDword(SyncKey, "DisableAppSyncSettingSync", 2)],
            RemoveOps = [RegOp.DeleteValue(SyncKey, "DisableAppSyncSettingSync")],
            DetectOps = [RegOp.CheckDword(SyncKey, "DisableAppSyncSettingSync", 2)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Stops UWP app state from syncing across devices; each device retains independent app state.",
        },
        new TweakDef
        {
            Id = "esroam-block-user-override-setting-sync",
            Label = "Enterprise State Roaming: Block User Override of Settings Sync Policy",
            Category = "Enterprise State Roaming Policy",
            Description = "Prevents users from re-enabling settings synchronization that has been disabled by Group Policy. Without this policy, a standard user can navigate to Windows Settings → Accounts → Sync your settings and re-enable options that the admin has turned off. This policy ensures sync restrictions are permanent and cannot be overridden by end users.",
            Tags = ["state roaming", "sync", "user override", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SyncKey],
            ApplyOps = [RegOp.SetDword(SyncKey, "DisableSettingSyncUserOverride", 1)],
            RemoveOps = [RegOp.DeleteValue(SyncKey, "DisableSettingSyncUserOverride")],
            DetectOps = [RegOp.CheckDword(SyncKey, "DisableSettingSyncUserOverride", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Locks the sync policy; users cannot re-enable disabled sync categories from Settings.",
        },
        new TweakDef
        {
            Id = "esroam-block-user-override-app-sync",
            Label = "Enterprise State Roaming: Block User Override of App Settings Sync Policy",
            Category = "Enterprise State Roaming Policy",
            Description = "Prevents users from overriding the Group Policy that disables application settings synchronization. The Windows sync settings UI allows users to individually toggle sync categories; this policy forces DisableApplicationSettingSync to be admin-enforced and uneditable, ensuring corporate devices cannot roam application configuration data regardless of user preference.",
            Tags = ["state roaming", "sync", "app settings", "user override", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SyncKey],
            ApplyOps = [RegOp.SetDword(SyncKey, "DisableApplicationSettingSyncUserOverride", 1)],
            RemoveOps = [RegOp.DeleteValue(SyncKey, "DisableApplicationSettingSyncUserOverride")],
            DetectOps = [RegOp.CheckDword(SyncKey, "DisableApplicationSettingSyncUserOverride", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Prevents user from re-enabling app sync; admin policy is the only control.",
        },
        new TweakDef
        {
            Id = "esroam-block-user-override-start-layout",
            Label = "Enterprise State Roaming: Block User Override of Start Layout Sync Policy",
            Category = "Enterprise State Roaming Policy",
            Description = "Prevents users from re-enabling Start menu layout synchronization after it has been disabled by Group Policy. In environments with GPO-deployed Start menus, users should not be able to revert to a cloud-synced layout that was potentially configured on a personal device or a different organizational unit, as this undermines the standardized desktop configuration management.",
            Tags = ["state roaming", "sync", "start menu", "user override", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SyncKey],
            ApplyOps = [RegOp.SetDword(SyncKey, "DisableStartLayoutSettingSyncUserOverride", 1)],
            RemoveOps = [RegOp.DeleteValue(SyncKey, "DisableStartLayoutSettingSyncUserOverride")],
            DetectOps = [RegOp.CheckDword(SyncKey, "DisableStartLayoutSettingSyncUserOverride", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Prevents user from re-enabling Start layout sync; enforces the IT-deployed Start menu.",
        },
        new TweakDef
        {
            Id = "esroam-disable-device-account-sync",
            Label = "Enterprise State Roaming: Disable Device Account Settings Sync",
            Category = "Enterprise State Roaming Policy",
            Description = "Disables synchronization of device account settings (Microsoft account email app state, mail account configuration, calendar sync settings) through Enterprise State Roaming. On managed corporate devices where mail clients are configured centrally via MDM profiles or Exchange Autodiscover, preventing cloud-roaming of account settings avoids conflicts between centrally-pushed and user-synced configurations.",
            Tags = ["state roaming", "sync", "device account", "email", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SyncKey],
            ApplyOps = [RegOp.SetDword(SyncKey, "DisableDeviceAccountSettingSync", 2)],
            RemoveOps = [RegOp.DeleteValue(SyncKey, "DisableDeviceAccountSettingSync")],
            DetectOps = [RegOp.CheckDword(SyncKey, "DisableDeviceAccountSettingSync", 2)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Stops device account (email/calendar config) from syncing; MDM-managed profiles are unaffected.",
        },
    ];
}
