namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class FipsCompliancePolicy
{
    private const string FipsKey = @"HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy";
    private const string CryptoKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Cryptography";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "fips-enable-fips-algorithm-policy",
            Label = "FIPS Compliance: Enable FIPS 140-2 Compliant Algorithms",
            Category = "FIPS Compliance Policy",
            Description = "Enables the FIPS 140-2 compliant algorithm policy (FipsAlgorithmPolicy\\Enabled=1), which forces Windows security subsystems including TLS, Schannel, BitLocker, and Remote Desktop to use only FIPS-approved cryptographic algorithms. Required by NIST SP 800-53, FedRAMP, DoD STIGs, and PCI-DSS environments. Note: some older COM components and third-party applications may fail when this is enforced.",
            Tags = ["fips", "cryptography", "compliance", "security", "nist"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [FipsKey],
            ApplyOps = [RegOp.SetDword(FipsKey, "Enabled", 1)],
            RemoveOps = [RegOp.SetDword(FipsKey, "Enabled", 0)],
            DetectOps = [RegOp.CheckDword(FipsKey, "Enabled", 1)],
            ImpactScore = 5,
            SafetyRating = 3,
            ImpactNote = "Enforces FIPS-approved algorithms system-wide; may break non-FIPS-compliant legacy applications.",
        },
        new TweakDef
        {
            Id = "fips-disable-machine-key-caching",
            Label = "FIPS Compliance: Disable Machine Key Caching",
            Category = "FIPS Compliance Policy",
            Description = "Disables caching of machine-level CNG (Cryptography Next Generation) private keys in memory. When enabled, machine keys can remain in memory after their first use for performance reasons, but this creates a window where a privileged attacker or malicious driver could extract cached key material. Disabling caching forces fresh key derivation on each use, aligning with zero-trust key management practices.",
            Tags = ["fips", "cryptography", "machine key", "caching", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [CryptoKey],
            ApplyOps = [RegOp.SetDword(CryptoKey, "MachineKeyCachingEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(CryptoKey, "MachineKeyCachingEnabled")],
            DetectOps = [RegOp.CheckDword(CryptoKey, "MachineKeyCachingEnabled", 0)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Removes in-memory key caching; minor performance penalty on crypto-heavy workloads.",
        },
        new TweakDef
        {
            Id = "fips-force-strong-key-protection",
            Label = "FIPS Compliance: Force Strong Key Protection for User Keys",
            Category = "FIPS Compliance Policy",
            Description = "Configures CNG to require strong key protection (ForceKeyProtection=2), which means private keys stored in the user's personal certificate store can only be accessed after the user explicitly provides their password. This prevents silent background access to private keys by automated processes, scheduled tasks, or potentially compromised processes running in the user context without the user's consent.",
            Tags = ["fips", "cryptography", "key protection", "certificates", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [CryptoKey],
            ApplyOps = [RegOp.SetDword(CryptoKey, "ForceKeyProtection", 2)],
            RemoveOps = [RegOp.DeleteValue(CryptoKey, "ForceKeyProtection")],
            DetectOps = [RegOp.CheckDword(CryptoKey, "ForceKeyProtection", 2)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Requires user password for each private key access; S/MIME signing and code signing may prompt more frequently.",
        },
        new TweakDef
        {
            Id = "fips-disable-dpapi-auto-protection",
            Label = "FIPS Compliance: Restrict DPAPI Automatic Data Protection",
            Category = "FIPS Compliance Policy",
            Description = "Restricts the Data Protection API (DPAPI) from automatically enrolling new data blobs with default key generation settings that may not be FIPS-compliant. DPAPI is used by browsers (Chrome/Edge), mail clients, and credential managers to protect saved passwords and tokens. When FIPS mode is enabled but DPAPI is not restricted, legacy blobs may still be created using non-FIPS algorithms.",
            Tags = ["fips", "cryptography", "dpapi", "data protection", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [CryptoKey],
            ApplyOps = [RegOp.SetDword(CryptoKey, "UseDPAPIForProtection", 0)],
            RemoveOps = [RegOp.DeleteValue(CryptoKey, "UseDPAPIForProtection")],
            DetectOps = [RegOp.CheckDword(CryptoKey, "UseDPAPIForProtection", 0)],
            ImpactScore = 3,
            SafetyRating = 3,
            ImpactNote = "Restricts default DPAPI auto-protection; applications that depend on DPAPI for secret storage may need reconfiguration.",
        },
        new TweakDef
        {
            Id = "fips-require-sha2-minimum",
            Label = "FIPS Compliance: Require SHA-2 Minimum for Code Integrity",
            Category = "FIPS Compliance Policy",
            Description = "Sets the minimum hash algorithm for Authenticode code signing to SHA-2 (SHA-256 or better), blocking execution of binaries signed only with SHA-1 or MD5. SHA-1 signatures have been deprecated by NIST since 2011 and are considered vulnerable to collision attacks. This policy aligns code integrity checking with FIPS 140-2 Annex A requirements.",
            Tags = ["fips", "cryptography", "sha2", "code signing", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [CryptoKey],
            ApplyOps = [RegOp.SetDword(CryptoKey, "SHA1DeprecationPolicy", 1)],
            RemoveOps = [RegOp.DeleteValue(CryptoKey, "SHA1DeprecationPolicy")],
            DetectOps = [RegOp.CheckDword(CryptoKey, "SHA1DeprecationPolicy", 1)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Blocks SHA-1 signed code from executing; older drivers or software signed before 2016 may not load.",
        },
        new TweakDef
        {
            Id = "fips-disable-rc4-tls",
            Label = "FIPS Compliance: Disable RC4 Cipher in TLS",
            Category = "FIPS Compliance Policy",
            Description = "Disables the RC4 stream cipher from the TLS negotiation cipher suite list at the Schannel policy level. RC4 is not FIPS-approved (NSA Suite B) and has been proven vulnerable to statistical attacks (BEAST, RC4NOMORE). Windows Server 2012 R2 and newer disable it by default, but this policy explicitly sets the registry value to ensure RC4 cannot be re-enabled by custom application cipher suite negotiation.",
            Tags = ["fips", "cryptography", "rc4", "tls", "schannel"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [CryptoKey],
            ApplyOps = [RegOp.SetDword(CryptoKey, "DisableRC4InTLS", 1)],
            RemoveOps = [RegOp.DeleteValue(CryptoKey, "DisableRC4InTLS")],
            DetectOps = [RegOp.CheckDword(CryptoKey, "DisableRC4InTLS", 1)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Explicitly blocks RC4 in TLS; RC4 was already deprecated in modern Windows, so no behavioral change on up-to-date systems.",
        },
        new TweakDef
        {
            Id = "fips-disable-weak-hash-algorithms",
            Label = "FIPS Compliance: Disable MD5 and MD4 Hash Algorithms",
            Category = "FIPS Compliance Policy",
            Description = "Disables MD5 and MD4 hash algorithms from being used by the Windows CNG key storage provider for new operations. MD5 and MD4 are not FIPS-approved; both have known collision vulnerabilities. While MD5 is still widely used in non-security contexts (file checksums), its use in cryptographic operations (certificate fingerprints, HMAC) must be blocked in FIPS-compliant environments.",
            Tags = ["fips", "cryptography", "md5", "hash algorithms", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [CryptoKey],
            ApplyOps = [RegOp.SetDword(CryptoKey, "DisableWeakHashAlgorithms", 1)],
            RemoveOps = [RegOp.DeleteValue(CryptoKey, "DisableWeakHashAlgorithms")],
            DetectOps = [RegOp.CheckDword(CryptoKey, "DisableWeakHashAlgorithms", 1)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Blocks MD5/MD4 in cryptographic operations; non-crypto checksums (file integrity comparison) are unaffected.",
        },
        new TweakDef
        {
            Id = "fips-disable-des-3des-cipher",
            Label = "FIPS Compliance: Restrict DES and 3DES Ciphers",
            Category = "FIPS Compliance Policy",
            Description = "Restricts use of DES (56-bit) and Triple-DES (3DES/TDEA) block ciphers in new cryptographic sessions. DES has been disallowed by NIST since 2005. 3DES (with 112-bit effective security) was deprecated by NIST SP 800-131A in 2023 for new use and is only approved through 2023 for legacy compatibility. This policy aligns the cipher suite with the requirement for AES-256 minimum.",
            Tags = ["fips", "cryptography", "des", "3des", "cipher policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [CryptoKey],
            ApplyOps = [RegOp.SetDword(CryptoKey, "RestrictDESAlgorithms", 1)],
            RemoveOps = [RegOp.DeleteValue(CryptoKey, "RestrictDESAlgorithms")],
            DetectOps = [RegOp.CheckDword(CryptoKey, "RestrictDESAlgorithms", 1)],
            ImpactScore = 3,
            SafetyRating = 3,
            ImpactNote = "Restricts DES/3DES ciphers; may break connections to legacy servers that do not support AES.",
        },
        new TweakDef
        {
            Id = "fips-require-tls-certificate-validation",
            Label = "FIPS Compliance: Require Full Certificate Chain Validation",
            Category = "FIPS Compliance Policy",
            Description = "Requires that all TLS connections validate the complete certificate chain including OCSP stapling verification and CRL distribution point checks. In FIPS environments, certificate validation must be comprehensive — weak pinning, expired status checks, or bypassed revocation checks can introduce attack vectors. This policy sets the strict validation mode for the Windows Schannel certificate validation path.",
            Tags = ["fips", "cryptography", "certificate", "tls validation", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [CryptoKey],
            ApplyOps = [RegOp.SetDword(CryptoKey, "RequireFullCertChainValidation", 1)],
            RemoveOps = [RegOp.DeleteValue(CryptoKey, "RequireFullCertChainValidation")],
            DetectOps = [RegOp.CheckDword(CryptoKey, "RequireFullCertChainValidation", 1)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Requires full OCSP/CRL chain validation; connections to servers with incomplete chains will fail.",
        },
        new TweakDef
        {
            Id = "fips-enforce-secure-channel-minimum",
            Label = "FIPS Compliance: Enforce Minimum Secure Channel Protocol Version",
            Category = "FIPS Compliance Policy",
            Description = "Enforces a minimum TLS 1.2 protocol version for all Windows Schannel connections, preventing fallback to SSL 3.0, TLS 1.0, or TLS 1.1. All three older versions have documented protocol-level vulnerabilities (POODLE, BEAST, DROWN, BEAST) that allow decryption of traffic by an active network attacker. FIPS 140-2 references NIST SP 800-52 which mandates TLS 1.2 as the minimum for federal systems.",
            Tags = ["fips", "cryptography", "tls", "secure channel", "minimum version"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [CryptoKey],
            ApplyOps = [RegOp.SetDword(CryptoKey, "EnforceMinimumTlsVersion", 1)],
            RemoveOps = [RegOp.DeleteValue(CryptoKey, "EnforceMinimumTlsVersion")],
            DetectOps = [RegOp.CheckDword(CryptoKey, "EnforceMinimumTlsVersion", 1)],
            ImpactScore = 5,
            SafetyRating = 3,
            ImpactNote = "Enforces TLS 1.2+ minimum; connections to servers that only support TLS 1.0/1.1 or SSL 3.0 will fail.",
        },
    ];
}
