// RegiLattice.Core — Tweaks/GameExplorerPolicy.cs
// Sprint 263: Game Explorer Group Policy (10 tweaks)
// Category: "Game Explorer Policy" | Slug: gex
// Registry: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\GameExplorer

namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class GameExplorerPolicy
{
    private const string Key = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\GameExplorer";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "gex-disable-all-games",
            Label = "Disable Game Explorer for All Users",
            Category = "Game Explorer Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 5,
            Description =
                "Sets DisableAll=1 in the GameExplorer policy key. Prevents users from "
                + "launching, installing, or accessing Game Explorer entirely. Removes the "
                + "Games folder from Windows Explorer and Start Menu. Default: Game Explorer "
                + "is enabled. Recommended: 1 on managed corporate or kiosk machines "
                + "where gaming is prohibited by policy.",
            Tags = ["games", "game-explorer", "group-policy", "lockdown"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "DisableAll", 1)],
            RemoveOps = [RegOp.DeleteValue(Key, "DisableAll")],
            DetectOps = [RegOp.CheckDword(Key, "DisableAll", 1)],
        },
        new TweakDef
        {
            Id = "gex-block-game-downloads",
            Label = "Block Downloading Game Ratings",
            Category = "Game Explorer Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            Description =
                "Sets AllowDownloadingRatings=0 in the GameExplorer policy key. Prevents "
                + "Windows from downloading updated game ratings (ESRB/PEGI data) over the "
                + "internet. Eliminates background network traffic generated by the Games "
                + "folder ratings update service. Default: ratings downloaded automatically. "
                + "Recommended: 0 to suppress telemetry-adjacent outbound connections.",
            Tags = ["games", "network", "ratings", "group-policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "AllowDownloadingRatings", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "AllowDownloadingRatings")],
            DetectOps = [RegOp.CheckDword(Key, "AllowDownloadingRatings", 0)],
        },
        new TweakDef
        {
            Id = "gex-hide-recommended-games",
            Label = "Hide Recommended Games in Game Explorer",
            Category = "Game Explorer Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            Description =
                "Sets ListRecommendedGames=0 in the GameExplorer policy key. Removes the "
                + "'Recommended Games' section from the Games folder that normally shows "
                + "games available to purchase or download from Microsoft. Eliminates "
                + "advertising content from the Windows shell. Default: recommended games "
                + "are shown. Recommended: 0 to suppress advertising.",
            Tags = ["games", "ads", "privacy", "game-explorer", "group-policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "ListRecommendedGames", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "ListRecommendedGames")],
            DetectOps = [RegOp.CheckDword(Key, "ListRecommendedGames", 0)],
        },
        new TweakDef
        {
            Id = "gex-block-game-launching",
            Label = "Prevent Launching Games from Game Explorer",
            Category = "Game Explorer Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 5,
            Description =
                "Sets AllowLaunchingGames=0 in the GameExplorer policy key. Prevents users "
                + "from launching games directly through the Games Explorer interface. Games "
                + "remain installed but cannot be started via the Games folder. Default: "
                + "launching games is permitted. Recommended: 0 on education or kiosk "
                + "environments where gameplay must be blocked during work hours.",
            Tags = ["games", "lockdown", "group-policy", "game-explorer"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "AllowLaunchingGames", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "AllowLaunchingGames")],
            DetectOps = [RegOp.CheckDword(Key, "AllowLaunchingGames", 0)],
        },
        new TweakDef
        {
            Id = "gex-disable-online-games",
            Label = "Hide Online Games Section",
            Category = "Game Explorer Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            Description =
                "Sets ShowOnlineGames=0 in the GameExplorer policy key. Removes the Online "
                + "Games section that links to Windows Live Games and Microsoft game services "
                + "from within Game Explorer. Reduces outbound traffic and eliminates "
                + "Microsoft storefront exposure in managed environments. Default: online "
                + "games section is visible.",
            Tags = ["games", "online", "privacy", "group-policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "ShowOnlineGames", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "ShowOnlineGames")],
            DetectOps = [RegOp.CheckDword(Key, "ShowOnlineGames", 0)],
        },
        new TweakDef
        {
            Id = "gex-disable-parental-controls",
            Label = "Disable Game Parental Controls",
            Category = "Game Explorer Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 4,
            Description =
                "Sets AllowParentalControls=0 in the GameExplorer policy key. Disables the "
                + "Windows parental control enforcement layer that restricts game access "
                + "based on ratings. On managed machines where all user accounts are "
                + "supervised by IT, the parental controls subsystem can be disabled to "
                + "reduce background service overhead. Default: parental controls available "
                + "but not enforced unless configured.",
            Tags = ["games", "parental-controls", "group-policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "AllowParentalControls", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "AllowParentalControls")],
            DetectOps = [RegOp.CheckDword(Key, "AllowParentalControls", 0)],
        },
        new TweakDef
        {
            Id = "gex-block-game-updates",
            Label = "Block Automatic Game Updates",
            Category = "Game Explorer Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            Description =
                "Sets AllowGameUpdates=0 in the GameExplorer policy key. Prevents Game "
                + "Explorer from automatically downloading and applying updates to games "
                + "managed through the Windows Games infrastructure. Gives IT control over "
                + "when game updates are deployed. Default: auto updates are permitted. "
                + "Recommended: 0 on machines where bandwidth and installed software "
                + "must be tightly managed.",
            Tags = ["games", "updates", "group-policy", "bandwidth"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "AllowGameUpdates", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "AllowGameUpdates")],
            DetectOps = [RegOp.CheckDword(Key, "AllowGameUpdates", 0)],
        },
        new TweakDef
        {
            Id = "gex-disable-game-notifications",
            Label = "Disable Game Explorer Notifications",
            Category = "Game Explorer Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            Description =
                "Sets AllowGameNotifications=0 in the GameExplorer policy key. Suppresses "
                + "balloon tips and toast notifications generated by Game Explorer, such as "
                + "news about newly available games or update alerts. Reduces notification "
                + "noise on managed workstations. Default: game notifications are shown. "
                + "Recommended: 0 for distraction-free work environments.",
            Tags = ["games", "notifications", "group-policy", "focus"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "AllowGameNotifications", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "AllowGameNotifications")],
            DetectOps = [RegOp.CheckDword(Key, "AllowGameNotifications", 0)],
        },
        new TweakDef
        {
            Id = "gex-block-game-install",
            Label = "Block Game Installation via Game Explorer",
            Category = "Game Explorer Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 5,
            Description =
                "Sets AllowInstallGames=0 in the GameExplorer policy key. Prevents users "
                + "from installing new games through the Games folder or Game Explorer "
                + "interface, including games obtained from Microsoft. Games already "
                + "installed remain accessible unless further restricted. Default: "
                + "game installation is allowed. Recommended: 0 on locked-down machines.",
            Tags = ["games", "installation", "lockdown", "group-policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "AllowInstallGames", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "AllowInstallGames")],
            DetectOps = [RegOp.CheckDword(Key, "AllowInstallGames", 0)],
        },
        new TweakDef
        {
            Id = "gex-disable-game-activity-log",
            Label = "Disable Game Activity Logging",
            Category = "Game Explorer Policy",
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            Description =
                "Sets LogGameActivity=0 in the GameExplorer policy key. Stops Windows from "
                + "logging game session activity (launch times, play duration, achievements) "
                + "in the Games Explorer database. Reduces disk I/O and eliminates locally "
                + "stored telemetry about gaming habits. Default: activity is logged. "
                + "Recommended: 0 for privacy-focused deployments.",
            Tags = ["games", "privacy", "logging", "group-policy"],
            RegistryKeys = [Key],
            ApplyOps = [RegOp.SetDword(Key, "LogGameActivity", 0)],
            RemoveOps = [RegOp.DeleteValue(Key, "LogGameActivity")],
            DetectOps = [RegOp.CheckDword(Key, "LogGameActivity", 0)],
        },
    ];
}
