namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class GpoFolderRedirPolicy
{
    private const string SystemKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System";
    private const string LogonKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Logon";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "folderredir-enable-cache-rename",
            Label = "GPO Folder Redirection: Enable Cache Rename on Redirect",
            Category = "GPO Folder Redirection Policy",
            Description = "Enables cache renaming when a redirected folder path changes. When a folder redirection target is updated via Group Policy (e.g., moving a redirected My Documents share from an old file server to a new one), Windows can seamlessly rename the local offline-files cache entry to match the new UNC path. Without this setting, the client cache may retain stale entries pointing to the old server, causing offline file sync conflicts.",
            Tags = ["folder redirection", "offline files", "gpo", "cache", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "FolderRedirectionEnableCacheRename", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "FolderRedirectionEnableCacheRename")],
            DetectOps = [RegOp.CheckDword(SystemKey, "FolderRedirectionEnableCacheRename", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Enables clean cache transitions when redirection targets change; reduces sync errors after file server migrations.",
        },
        new TweakDef
        {
            Id = "folderredir-disable-user-profile-roaming",
            Label = "GPO Folder Redirection: Disable User Profile Roaming Download",
            Category = "GPO Folder Redirection Policy",
            Description = "Prevents Windows from downloading a roaming user profile from the network during logon when the user profile server is unavailable. Without this policy, Windows waits for the roaming profile to download (up to the profile server timeout) before allowing login. Blocking this fallback download prevents slow logons when profile servers are down while ensuring that local cached profiles are used immediately.",
            Tags = ["folder redirection", "roaming profile", "logon", "performance", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "DisableRoamingProfileDownload", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "DisableRoamingProfileDownload")],
            DetectOps = [RegOp.CheckDword(SystemKey, "DisableRoamingProfileDownload", 1)],
            ImpactScore = 3,
            SafetyRating = 3,
            ImpactNote = "Skips roaming profile download when server unavailable; users get cached profile with no network wait.",
        },
        new TweakDef
        {
            Id = "folderredir-disable-roaming-profile-quota-notification",
            Label = "GPO Folder Redirection: Disable Roaming Profile Quota Warning Notification",
            Category = "GPO Folder Redirection Policy",
            Description = "Suppresses the roaming profile quota warning balloon notification that appears in the notification area when a user's roaming profile approaches its storage quota. In enterprise environments where profile size is managed through other mechanisms (e.g., folder redirection, profile monitoring tools), these notifications create user confusion and help desk calls without providing actionable guidance for end users.",
            Tags = ["folder redirection", "roaming profile", "quota", "notification", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "DisableProfileQuotaNotification", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "DisableProfileQuotaNotification")],
            DetectOps = [RegOp.CheckDword(SystemKey, "DisableProfileQuotaNotification", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Suppresses quota balloon notification; profile quota is still enforced by the file server.",
        },
        new TweakDef
        {
            Id = "folderredir-wait-for-policy-at-logon",
            Label = "GPO Folder Redirection: Wait for Group Policy at Logon (Background Sync Block)",
            Category = "GPO Folder Redirection Policy",
            Description = "Forces Windows to perform a synchronous (blocking) Group Policy application at logon rather than applying folder redirection policies in the background after the user is already logged in. Without this setting, users may briefly see their unredirected local Desktop and Documents folders before the redirection takes effect, resulting in files being saved to the wrong location. Synchronous policy application eliminates this window.",
            Tags = ["folder redirection", "group policy", "logon", "synchronous", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "WaitForPolicyToBeApplied", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "WaitForPolicyToBeApplied")],
            DetectOps = [RegOp.CheckDword(SystemKey, "WaitForPolicyToBeApplied", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Adds ~2–5 seconds to first logon on each new GPO change; prevents split-second folder location confusion.",
        },
        new TweakDef
        {
            Id = "folderredir-redirect-local-profile-to-network",
            Label = "GPO Folder Redirection: Grant User Exclusive Rights to Redirected Folder",
            Category = "GPO Folder Redirection Policy",
            Description = "Grants the user exclusive NTFS permissions on their redirected folder target when the folder redirection policy first creates it on the file server. Without this setting, the Administrators group retains access to all redirected folders, enabling administrators to read user-redirected documents. Granting exclusive user rights is a privacy and security best practice that ensures sensitive user data in redirected folders is only accessible to the owning account.",
            Tags = ["folder redirection", "permissions", "ntfs", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "GrantExclusiveRightsToFolderRedirection", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "GrantExclusiveRightsToFolderRedirection")],
            DetectOps = [RegOp.CheckDword(SystemKey, "GrantExclusiveRightsToFolderRedirection", 1)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Grants user-only NTFS permissions on their redirected share; admins must use elevated credentials to access.",
        },
        new TweakDef
        {
            Id = "folderredir-use-localized-subfolder-names",
            Label = "GPO Folder Redirection: Use Localized Subfolder Names",
            Category = "GPO Folder Redirection Policy",
            Description = "Configures folder redirection to use the localized (OS language-specific) names for redirected subfolders on the file server rather than English names. In multi-language organizations where different users log on with different Windows UI languages, the names of redirected subfolder paths (e.g., Documents vs. Documenti vs. Dokumente) can vary unless this policy standardizes them to the localized folder names per user.",
            Tags = ["folder redirection", "localization", "subfolder names", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "UseLocalizedSubfolderNames", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "UseLocalizedSubfolderNames")],
            DetectOps = [RegOp.CheckDword(SystemKey, "UseLocalizedSubfolderNames", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Changes redirected subfolder names to match the user's Windows language; no data loss, only path naming change.",
        },
        new TweakDef
        {
            Id = "folderredir-move-contents-on-redirect",
            Label = "GPO Folder Redirection: Move Contents to Redirected Path",
            Category = "GPO Folder Redirection Policy",
            Description = "Instructs Windows to automatically move the contents of a folder from its original local location to the new UNC redirect target when folder redirection is first applied. Without this policy, existing local files stay in place and only new files go to the redirect target, leaving users with data split across two locations. Enabling content migration ensures a complete transition to the managed file server path.",
            Tags = ["folder redirection", "content migration", "data move", "gpo", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "MoveContentsExistingFolders", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "MoveContentsExistingFolders")],
            DetectOps = [RegOp.CheckDword(SystemKey, "MoveContentsExistingFolders", 1)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Moves existing local files to the redirect target on first policy application; ensure the target share has sufficient space.",
        },
        new TweakDef
        {
            Id = "folderredir-disable-unc-path-hardening-bypass",
            Label = "GPO Folder Redirection: Block UNC Hardening Bypass for Redirected Paths",
            Category = "GPO Folder Redirection Policy",
            Description = "Prevents applications from bypassing UNC path hardening (SMB signing requirements) for redirected folder UNC targets. Windows allows some UNC access to bypass signing requirements for specific paths. This policy ensures that even though folder redirection targets are trusted by Windows, they are still subject to SMB signing requirements to prevent man-in-the-middle attacks on the file server connection carrying redirected folder traffic.",
            Tags = ["folder redirection", "unc hardening", "smb signing", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "DisableUNCHardeningForRedirectedPaths", 0)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "DisableUNCHardeningForRedirectedPaths")],
            DetectOps = [RegOp.CheckDword(SystemKey, "DisableUNCHardeningForRedirectedPaths", 0)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Keeps UNC hardening active for redirect paths (sets to 0 = hardening NOT disabled); SMB signing is enforced.",
        },
        new TweakDef
        {
            Id = "folderredir-configure-profile-slow-link-detection",
            Label = "GPO Folder Redirection: Configure Slow-Link Detection Threshold",
            Category = "GPO Folder Redirection Policy",
            Description = "Configures the network bandwidth threshold below which Windows considers the connection to the roaming profile server as a 'slow link', triggering use of the local cached profile instead of downloading the full remote profile. Setting this to the Microsoft-recommended value of 500 kbps ensures that even on moderate WAN links, users get fast logons while good connections still get the full roaming/redirected experience.",
            Tags = ["folder redirection", "slow link", "profile", "bandwidth", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [LogonKey],
            ApplyOps = [RegOp.SetDword(LogonKey, "SlowLinkDetect", 500)],
            RemoveOps = [RegOp.DeleteValue(LogonKey, "SlowLinkDetect")],
            DetectOps = [RegOp.CheckDword(LogonKey, "SlowLinkDetect", 500)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Sets 500 kbps as slow-link threshold; connections below this use cached profile for faster logon.",
        },
        new TweakDef
        {
            Id = "folderredir-enable-profile-migration-on-domain-join",
            Label = "GPO Folder Redirection: Enable Local Profile Migration on Domain Join",
            Category = "GPO Folder Redirection Policy",
            Description = "Permits migration of the local user profile to the roaming profile path when a user first logs in after a machine is joined to a domain. Without this policy, domain logons create a new empty profile and the user's existing local profile data (desktop files, AppData settings) is left behind in the local profile. Enabling migration ensures the first domain logon seamlessly carries over all existing local user data.",
            Tags = ["folder redirection", "profile migration", "domain join", "logon", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [LogonKey],
            ApplyOps = [RegOp.SetDword(LogonKey, "LocalProfileLoadTimeOut", 30)],
            RemoveOps = [RegOp.DeleteValue(LogonKey, "LocalProfileLoadTimeOut")],
            DetectOps = [RegOp.CheckDword(LogonKey, "LocalProfileLoadTimeOut", 30)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Sets a 30-second wait period for profile load before falling back to local cache on domain join.",
        },
    ];
}
