namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class GpoScriptsPolicy
{
    private const string SystemKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "gposcripts-run-logon-script-sync",
            Label = "GPO Scripts: Run Logon Scripts Synchronously",
            Category = "GPO Scripts Policy",
            Description = "Configures Windows to run all Group Policy logon scripts synchronously and display the desktop only after all logon scripts have completed. By default, Windows may display the desktop before all logon scripts finish, which can result in users opening applications before drive mappings, printer connections, or environment variables are established by logon scripts. Synchronous execution ensures scripts complete before the user session is accessible.",
            Tags = ["gpo scripts", "logon scripts", "synchronous", "startup", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "RunLogonScriptSync", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "RunLogonScriptSync")],
            DetectOps = [RegOp.CheckDword(SystemKey, "RunLogonScriptSync", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Delays desktop display until all logon scripts complete; increases first-logon time by the duration of all scripts.",
        },
        new TweakDef
        {
            Id = "gposcripts-run-startup-script-sync",
            Label = "GPO Scripts: Run Startup Scripts Synchronously",
            Category = "GPO Scripts Policy",
            Description = "Configures Windows to run all Computer Configuration startup scripts one at a time and sequentially before the logon prompt appears. Without this setting, startup scripts may run asynchronously in the background, meaning critical system initialization scripts (e.g., disk encryption unlock, certificate enrollment, MDM check-in) may not complete before a user logs in, potentially resulting in incomplete system state at logon.",
            Tags = ["gpo scripts", "startup scripts", "synchronous", "boot", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "RunStartupScriptSync", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "RunStartupScriptSync")],
            DetectOps = [RegOp.CheckDword(SystemKey, "RunStartupScriptSync", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Ensures each startup script finishes before the next begins and before the logon screen appears; adds boot time equal to total startup script duration.",
        },
        new TweakDef
        {
            Id = "gposcripts-run-legacy-logon-hidden",
            Label = "GPO Scripts: Run Legacy Logon Scripts Visible but Silent",
            Category = "GPO Scripts Policy",
            Description = "Forces legacy logon scripts (those defined in the user profile properties of Active Directory) to run visible to the user but without a separate CMD window. By default, legacy logon scripts (as distinct from Group Policy logon scripts) may flash console windows briefly. This policy suppresses the command prompt window while still allowing the script to run, providing a cleaner logon experience without confusing users with flashing black windows.",
            Tags = ["gpo scripts", "logon scripts", "legacy", "hidden window", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "RunLegacyLogonScriptHidden", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "RunLegacyLogonScriptHidden")],
            DetectOps = [RegOp.CheckDword(SystemKey, "RunLegacyLogonScriptHidden", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Suppresses a CMD window during legacy logon scripts; scripts still execute — purely a UX improvement.",
        },
        new TweakDef
        {
            Id = "gposcripts-set-max-script-wait-time",
            Label = "GPO Scripts: Set Maximum Script Runtime Timeout (10 minutes)",
            Category = "GPO Scripts Policy",
            Description = "Sets the maximum time Windows will wait for a Group Policy script (startup, logon, logoff, or shutdown) to complete before forcibly terminating it. The default is 600 seconds (10 minutes). Scripts that exceed this timeout are terminated without completing. Setting this explicitly prevents runaway scripts from hanging the logon/logoff sequence indefinitely, which can leave the machine in an unresponsive state.",
            Tags = ["gpo scripts", "timeout", "max wait", "startup shutdown", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "MaxGPOScriptWait", 600)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "MaxGPOScriptWait")],
            DetectOps = [RegOp.CheckDword(SystemKey, "MaxGPOScriptWait", 600)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Explicitly sets the 600-second (10 min) script timeout; runaway scripts are forcibly terminated after this period.",
        },
        new TweakDef
        {
            Id = "gposcripts-hide-startup-scripts",
            Label = "GPO Scripts: Hide Startup Scripts (No Status Message)",
            Category = "GPO Scripts Policy",
            Description = "Suppresses the 'Running startup scripts...' status message and progress screen that Windows displays during boot when Group Policy startup scripts are executing. In environments where startup scripts handle sensitive operations (certificate enrollment, TPM initialization commands, encrypted volume mounting), displaying the script status messages onscreen may expose the types of security operations to anyone observing the boot screen.",
            Tags = ["gpo scripts", "startup scripts", "hidden", "status message", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "HideStartupScripts", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "HideStartupScripts")],
            DetectOps = [RegOp.CheckDword(SystemKey, "HideStartupScripts", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Hides the startup script progress screen; scripts still run, but no progress message is shown at boot.",
        },
        new TweakDef
        {
            Id = "gposcripts-hide-logon-scripts",
            Label = "GPO Scripts: Hide Logon Scripts (No Progress Window)",
            Category = "GPO Scripts Policy",
            Description = "Hides the 'Applying your personal settings...' and similar logon script progress messages that appear during user logon in verbose mode. While informative for administrators, these messages reveal that Group Policy logon scripts are running, potentially exposing script categories to end users. In secure environments, the logon process should be opaque — completing silently and presenting the desktop only when ready.",
            Tags = ["gpo scripts", "logon scripts", "hidden", "progress window", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "HideLogonScripts", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "HideLogonScripts")],
            DetectOps = [RegOp.CheckDword(SystemKey, "HideLogonScripts", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Suppresses the logon script progress window; logon may appear to 'hang' briefly — this is expected behavior.",
        },
        new TweakDef
        {
            Id = "gposcripts-hide-logoff-scripts",
            Label = "GPO Scripts: Hide Logoff Scripts (No Logoff Window)",
            Category = "GPO Scripts Policy",
            Description = "Suppresses the window that appears when Group Policy logoff scripts are executing at user sign-out. When logoff scripts clean up user sessions (removing temp credentials, wiping browser profiles, revoking certificates), showing the progress window to the user is unnecessary and can lead users to terminate the logoff early by pressing the power button, potentially leaving cleanup scripts incomplete.",
            Tags = ["gpo scripts", "logoff scripts", "hidden", "sign-out", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "HideLogoffScripts", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "HideLogoffScripts")],
            DetectOps = [RegOp.CheckDword(SystemKey, "HideLogoffScripts", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Hides logoff script progress; users see the default 'Signing out...' overlay while scripts complete in the background.",
        },
        new TweakDef
        {
            Id = "gposcripts-hide-shutdown-scripts",
            Label = "GPO Scripts: Hide Shutdown Scripts (Silent System Shutdown)",
            Category = "GPO Scripts Policy",
            Description = "Suppresses the shutdown script progress window that shows when Group Policy Computer Configuration shutdown scripts run during system power-down. Shutdown scripts commonly perform operations such as disk encryption key cleanup, network session teardown, and compliance logging. Hiding the progress window provides a cleaner shutdown experience and prevents disclosure of the shutdown script sequence to onlookers.",
            Tags = ["gpo scripts", "shutdown scripts", "hidden", "system shutdown", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "HideShutdownScripts", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "HideShutdownScripts")],
            DetectOps = [RegOp.CheckDword(SystemKey, "HideShutdownScripts", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Hides shutdown script progress; the machine may appear to shut down more slowly as scripts run silently.",
        },
        new TweakDef
        {
            Id = "gposcripts-run-scripts-first-at-user-logon",
            Label = "GPO Scripts: Run User Logon Scripts Before Group Policy Logon Scripts",
            Category = "GPO Scripts Policy",
            Description = "Forces user-level logon scripts (defined in profile properties) to run before the Group Policy client completes processing Computer and User Configuration logon scripts. In some deployment scenarios, user-specific scripts (which map personal drives or configure user-specific settings) must run before broader GPO changes are applied. This ordering ensures user context is established before group-level policies modify the environment.",
            Tags = ["gpo scripts", "logon scripts", "run order", "user scripts", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "RunScriptsFirstAtUserLogon", 1)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "RunScriptsFirstAtUserLogon")],
            DetectOps = [RegOp.CheckDword(SystemKey, "RunScriptsFirstAtUserLogon", 1)],
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Reorders script execution — user profile scripts run before GPO logon scripts; may expose environment to user scripts before GPO lockdown is applied.",
        },
        new TweakDef
        {
            Id = "gposcripts-set-max-noninteractive-runtime",
            Label = "GPO Scripts: Set Maximum Non-Interactive Script Runtime (5 minutes)",
            Category = "GPO Scripts Policy",
            Description = "Sets the maximum time a non-interactive Group Policy script (startup, shutdown, logon, logoff scripts running in non-interactive mode) is allowed to run. Setting this to 300 seconds (5 minutes) provides a tighter timeout than the default 600 seconds. For background scripts that should complete quickly, this reduces the window during which a script error or infinite loop delays the logon or shutdown sequence.",
            Tags = ["gpo scripts", "timeout", "non-interactive", "runtime limit", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SystemKey],
            ApplyOps = [RegOp.SetDword(SystemKey, "MaxNonInteractiveRunningTime", 300)],
            RemoveOps = [RegOp.DeleteValue(SystemKey, "MaxNonInteractiveRunningTime")],
            DetectOps = [RegOp.CheckDword(SystemKey, "MaxNonInteractiveRunningTime", 300)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Sets a 5-minute (300s) cap on non-interactive scripts; scripts that need more time must run interactively.",
        },
    ];
}
