namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class HomeGroupPolicy
{
    private const string HomeGroupKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\HomeGroup";
    private const string SharingKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Network Connections";
    private const string WorkplaceKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WorkplaceJoin";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "homegroup-disable-homegroup",
            Label = "HomeGroup: Disable HomeGroup (Prevent Creation and Join)",
            Category = "HomeGroup Policy",
            Description = "Prevents Windows from creating or joining HomeGroups. HomeGroup was a Windows feature (removed in Windows 10 1803) that allowed easy resource sharing over a local network. Where the underlying registry paths and services still exist (transition systems), disabling HomeGroup ensures no legacy sharing mechanism can be activated. This covers both domain-joined machines and upgraded systems that may still have HomeGroup registry entries.",
            Tags = ["homegroup", "sharing", "network", "policy", "legacy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [HomeGroupKey],
            ApplyOps = [RegOp.SetDword(HomeGroupKey, "DisableHomeGroup", 1)],
            RemoveOps = [RegOp.DeleteValue(HomeGroupKey, "DisableHomeGroup")],
            DetectOps = [RegOp.CheckDword(HomeGroupKey, "DisableHomeGroup", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "HomeGroup was removed in Windows 10 v1803; this policy simply enforces the removal on upgraded systems.",
        },
        new TweakDef
        {
            Id = "homegroup-block-sharing-wizard",
            Label = "HomeGroup: Block Network Sharing Wizard",
            Category = "HomeGroup Policy",
            Description = "Disables the Windows Network Setup and Sharing Wizard that appears when connecting to a new network, which includes prompts to share files and configure HomeGroup-style sharing. The sharing wizard can inadvertently configure broad file-sharing settings when users accept defaults without understanding the implications. Blocking it ensures network sharing is configured intentionally through a dedicated management interface.",
            Tags = ["homegroup", "sharing wizard", "network", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [HomeGroupKey],
            ApplyOps = [RegOp.SetDword(HomeGroupKey, "DisableSharingWizard", 1)],
            RemoveOps = [RegOp.DeleteValue(HomeGroupKey, "DisableSharingWizard")],
            DetectOps = [RegOp.CheckDword(HomeGroupKey, "DisableSharingWizard", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Suppresses the new-network sharing wizard; network sharing can still be configured manually.",
        },
        new TweakDef
        {
            Id = "homegroup-block-homegroup-creation",
            Label = "HomeGroup: Block HomeGroup Creation by Users",
            Category = "HomeGroup Policy",
            Description = "Prevents standard users from creating new HomeGroups. Even on systems where HomeGroup-related features have been removed at the UI level, the underlying service (HomeGroupProvider) may still be accessible through PowerShell or legacy APIs. This policy enforces a mandatory block on new HomeGroup creation regardless of the access method used.",
            Tags = ["homegroup", "creation", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [HomeGroupKey],
            ApplyOps = [RegOp.SetDword(HomeGroupKey, "DisableHomeGroupCreation", 1)],
            RemoveOps = [RegOp.DeleteValue(HomeGroupKey, "DisableHomeGroupCreation")],
            DetectOps = [RegOp.CheckDword(HomeGroupKey, "DisableHomeGroupCreation", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Blocks HomeGroup creation; no functional loss on modern Windows 10/11 where the feature is removed.",
        },
        new TweakDef
        {
            Id = "homegroup-block-join-existing",
            Label = "HomeGroup: Block Joining Existing HomeGroups",
            Category = "HomeGroup Policy",
            Description = "Prevents users on this machine from joining existing HomeGroups on the local network. If older machines on the same LAN still have active HomeGroups, this policy blocks the current machine from joining them and accessing their shared resources. This is particularly important in mixed-version environments where Windows 7/8.1 machines may still be using HomeGroup.",
            Tags = ["homegroup", "join", "network", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [HomeGroupKey],
            ApplyOps = [RegOp.SetDword(HomeGroupKey, "DisableHomeGroupJoin", 1)],
            RemoveOps = [RegOp.DeleteValue(HomeGroupKey, "DisableHomeGroupJoin")],
            DetectOps = [RegOp.CheckDword(HomeGroupKey, "DisableHomeGroupJoin", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Blocks joining legacy HomeGroups from other machines on the LAN; no impact on modern networks.",
        },
        new TweakDef
        {
            Id = "homegroup-disable-sharing-library-access",
            Label = "HomeGroup: Disable Shared Library Access via HomeGroup",
            Category = "HomeGroup Policy",
            Description = "Disables access to shared libraries (Music, Pictures, Videos, Documents folders) through any active HomeGroup connection. Even when HomeGroup creation is blocked, access to legacy shares may persist if the machine was previously part of a HomeGroup. This policy ensures that the library sharing mechanism cannot be used to access data through legacy share paths, regardless of prior HomeGroup membership.",
            Tags = ["homegroup", "library sharing", "pictures", "music", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [HomeGroupKey],
            ApplyOps = [RegOp.SetDword(HomeGroupKey, "DisableSharedLibraryAccess", 1)],
            RemoveOps = [RegOp.DeleteValue(HomeGroupKey, "DisableSharedLibraryAccess")],
            DetectOps = [RegOp.CheckDword(HomeGroupKey, "DisableSharedLibraryAccess", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Prevents library browsing via HomeGroup paths; does not remove regular SMB shares.",
        },
        new TweakDef
        {
            Id = "homegroup-block-network-bridge",
            Label = "HomeGroup: Block Network Bridge Creation",
            Category = "HomeGroup Policy",
            Description = "Prevents users from creating a network bridge between multiple network adapters. A network bridge connects two otherwise isolated network segments (e.g., a wired corporate LAN and a personal Wi-Fi hotspot), creating a routing path that bypasses network access controls. This is a long-standing attack vector for data exfiltration and is blocked in any CIS Benchmark Level 1 configuration.",
            Tags = ["homegroup", "network bridge", "network isolation", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SharingKey],
            ApplyOps = [RegOp.SetDword(SharingKey, "NC_AllowNetBridgeAdapters", 0)],
            RemoveOps = [RegOp.DeleteValue(SharingKey, "NC_AllowNetBridgeAdapters")],
            DetectOps = [RegOp.CheckDword(SharingKey, "NC_AllowNetBridgeAdapters", 0)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Prevents creating network bridges; a significant security control for preventing LAN isolation bypass.",
        },
        new TweakDef
        {
            Id = "homegroup-block-internet-connection-sharing",
            Label = "HomeGroup: Block Internet Connection Sharing (ICS)",
            Category = "HomeGroup Policy",
            Description = "Prevents users from enabling Internet Connection Sharing (ICS) which turns the machine into an ad-hoc NAT router, sharing an existing internet connection with other devices. ICS was historically bundled with HomeGroup and can be configured on any adapter. On corporate networks, ICS creates an unauthorized DHCP server and routing point, potentially interfering with the corporate DHCP infrastructure and creating a bypass path to the internet.",
            Tags = ["homegroup", "ics", "internet sharing", "network", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [SharingKey],
            ApplyOps = [RegOp.SetDword(SharingKey, "NC_ShowSharedAccessUI", 0)],
            RemoveOps = [RegOp.DeleteValue(SharingKey, "NC_ShowSharedAccessUI")],
            DetectOps = [RegOp.CheckDword(SharingKey, "NC_ShowSharedAccessUI", 0)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Hides and blocks ICS configuration; prevents corporate machine from acting as an unauthorized DHCP/NAT server.",
        },
        new TweakDef
        {
            Id = "homegroup-disable-workplace-join-toast",
            Label = "HomeGroup: Disable Workplace Join Toast Notifications",
            Category = "HomeGroup Policy",
            Description = "Suppresses Workplace Join (Azure AD / Entra ID device registration) toast notification prompts that appear on Windows Enterprise and Education when a user logs in with an organizational account but the device is not yet registered with MDM. While Workplace Join itself is a legitimate security feature, its notification dialog appearing on already-managed devices creates redundant prompts and user confusion in fully Intune-enrolled environments.",
            Tags = ["homegroup", "workplace join", "azure ad", "notification", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [WorkplaceKey],
            ApplyOps = [RegOp.SetDword(WorkplaceKey, "BlockAADWorkplaceJoin", 0)],
            RemoveOps = [RegOp.DeleteValue(WorkplaceKey, "BlockAADWorkplaceJoin")],
            DetectOps = [RegOp.CheckDword(WorkplaceKey, "BlockAADWorkplaceJoin", 0)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Explicitly allows Workplace Join (keeps value at 0/default); suppresses the block and allows existing MDM enrollment to function.",
        },
        new TweakDef
        {
            Id = "homegroup-suppress-peer-name-resolution",
            Label = "HomeGroup: Suppress Peer Name Resolution Protocol (PNRP)",
            Category = "HomeGroup Policy",
            Description = "Disables the Peer Name Resolution Protocol (PNRP) service, which HomeGroup and Windows Collaboration used for peer-to-peer device discovery on the local network. PNRP announces the machine's presence and identity to other devices on the same network segment and was a prerequisite for HomeGroup operation. On corporate networks, PNRP can result in inadvertent machine exposure and is not needed when domain-based or MDM-managed directory services are used.",
            Tags = ["homegroup", "pnrp", "peer to peer", "discovery", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [HomeGroupKey],
            ApplyOps = [RegOp.SetDword(HomeGroupKey, "DisablePeerNameResolution", 1)],
            RemoveOps = [RegOp.DeleteValue(HomeGroupKey, "DisablePeerNameResolution")],
            DetectOps = [RegOp.CheckDword(HomeGroupKey, "DisablePeerNameResolution", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Disables PNRP peer discovery; no functional impact on modern managed networks that do not use HomeGroup.",
        },
        new TweakDef
        {
            Id = "homegroup-block-homegroup-listener",
            Label = "HomeGroup: Disable HomeGroup Listener Service Policy",
            Category = "HomeGroup Policy",
            Description = "Applies the Group Policy flag that prevents the HomeGroupListener service from starting. The HomeGroupListener service (on older Windows 10 builds or those upgraded from Windows 8.1) processes HomeGroup notifications and sharing requests from network peers. Disabling it via policy ensures the service is blocked even if a service configuration change or script attempts to start it during a user session.",
            Tags = ["homegroup", "listener", "service", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [HomeGroupKey],
            ApplyOps = [RegOp.SetDword(HomeGroupKey, "DisableHomeGroupListener", 1)],
            RemoveOps = [RegOp.DeleteValue(HomeGroupKey, "DisableHomeGroupListener")],
            DetectOps = [RegOp.CheckDword(HomeGroupKey, "DisableHomeGroupListener", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Blocks HomeGroup network listener; equivalent to disabling the service but enforced via policy.",
        },
    ];
}
