namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class Input
{
    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "input-fast-keyboard-repeat",
            Label = "Maximize Keyboard Repeat Rate",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets keyboard repeat speed to maximum and delay to shortest.",
            Tags = ["input", "keyboard", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Keyboard"],
            ApplyOps =
            [
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardSpeed", "31"),
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardDelay", "0"),
            ],
            RemoveOps =
            [
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardSpeed", "31"),
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardDelay", "1"),
            ],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardDelay", "0")],
        },
        new TweakDef
        {
            Id = "input-disable-sticky-keys-prompt",
            Label = "Disable Sticky Keys Prompt (5x Shift)",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Prevents the Sticky Keys dialog from appearing when pressing Shift 5 times.",
            Tags = ["input", "accessibility", "gaming"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys", "Flags", "506")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys", "Flags", "510")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys", "Flags", "506")],
        },
        new TweakDef
        {
            Id = "input-disable-touchpad-tap",
            Label = "Disable Touchpad Tap-to-Click (Perf)",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables tap-to-click on precision touchpads to reduce accidental clicks and improve input accuracy. Default: Enabled. Recommended: Disabled for desktop users.",
            Tags = ["input", "touchpad", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "TapEnabled", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "TapEnabled", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "TapEnabled", 0)],
        },
        new TweakDef
        {
            Id = "input-increase-hover-time",
            Label = "Increase Mouse Hover Time (1s)",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Increases mouse hover delay from 400ms to 1000ms. Reduces accidental tooltip popups. Options: 400ms (default) / 1000ms. Recommended: 1000ms.",
            Tags = ["input", "mouse", "ux"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverTime", "1000")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverTime", "400")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverTime", "1000")],
        },
        new TweakDef
        {
            Id = "input-filter-keys",
            Label = "Disable Filter Keys",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables Filter Keys accessibility shortcut that can interfere with gaming.",
            Tags = ["input", "accessibility", "gaming"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Accessibility\FilterKeys"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\FilterKeys", "Flags", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\FilterKeys", "Flags", "126")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\FilterKeys", "Flags", "0")],
        },
        new TweakDef
        {
            Id = "input-toggle-keys",
            Label = "Disable Toggle Keys Beep",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables the Toggle Keys beep when pressing Num/Caps/Scroll Lock.",
            Tags = ["input", "accessibility", "gaming"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Accessibility\ToggleKeys"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\ToggleKeys", "Flags", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\ToggleKeys", "Flags", "62")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\ToggleKeys", "Flags", "0")],
        },
        new TweakDef
        {
            Id = "input-mouse-scroll-lines",
            Label = "Set Mouse Scroll to 5 Lines",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets mouse wheel scroll amount to 5 lines (default 3).",
            Tags = ["input", "mouse", "ux"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "WheelScrollLines", "5")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "WheelScrollLines", "3")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "WheelScrollLines", "5")],
        },
        new TweakDef
        {
            Id = "input-keyboard-delay-zero",
            Label = "Set Keyboard Repeat Delay to Minimum",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets keyboard repeat delay to 0 (minimum) for faster key repeat.",
            Tags = ["input", "keyboard", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Keyboard"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardDelay", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardDelay", "1")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardDelay", "0")],
        },
        new TweakDef
        {
            Id = "input-disable-touch-kb-auto",
            Label = "Disable Touch Keyboard Auto-Invoke",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Prevents the touch keyboard from automatically appearing on desktops without touchscreens. Default: Enabled. Recommended: Disabled.",
            Tags = ["input", "touch", "keyboard", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableDesktopModeAutoInvoke", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableDesktopModeAutoInvoke", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableDesktopModeAutoInvoke", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-sticky-keys",
            Label = "Disable Sticky Keys Shortcut",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables the Sticky Keys shortcut (pressing Shift 5 times). Prevents accidental activation during gaming. Default: Enabled (510). Recommended: Disabled (506).",
            Tags = ["input", "sticky-keys", "gaming", "accessibility"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys", "Flags", "506")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys", "Flags", "510")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys", "Flags", "506")],
        },
        new TweakDef
        {
            Id = "input-disable-spell-check",
            Label = "Disable Spell Checking",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables automatic spell checking in Windows text input. Reduces CPU usage from background spell-check processing. Default: Enabled. Recommended: Disabled for developers.",
            Tags = ["input", "spell-check", "typing", "performance"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableSpellchecking", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableSpellchecking", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableSpellchecking", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-text-suggestions",
            Label = "Disable Text Suggestions",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables text prediction and suggestions while typing. Prevents the suggestion bar from appearing above the keyboard. Default: Enabled. Recommended: Disabled for power users.",
            Tags = ["input", "text-prediction", "suggestions", "typing"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableTextPrediction", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableTextPrediction", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableTextPrediction", 0)],
        },
        new TweakDef
        {
            Id = "input-set-cursor-blink-rate",
            Label = "Set Fast Cursor Blink Rate",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Sets the cursor blink rate to 400 ms (faster than default). Makes the text cursor more visible and responsive. Default: 530 ms. Recommended: 400 ms for faster feedback.",
            Tags = ["input", "cursor", "blink-rate", "typing", "ux"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CursorBlinkRate", "400")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CursorBlinkRate", "530")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CursorBlinkRate", "400")],
        },
        new TweakDef
        {
            Id = "input-increase-double-click-speed",
            Label = "Increase Double-Click Speed",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Reduces the double-click detection interval to 200 ms for faster response. Requires quicker double-clicks but feels responsive. Default: 500 ms. Recommended: 200 ms for power users.",
            Tags = ["input", "mouse", "double-click", "speed", "ux"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "DoubleClickSpeed", "200")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "DoubleClickSpeed", "500")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "DoubleClickSpeed", "200")],
        },
        new TweakDef
        {
            Id = "input-disable-touch-feedback",
            Label = "Disable Touch Visual Feedback",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables visual feedback animations for touch and pen input. Removes the circle/ripple effect on touch and gesture indicators. Default: Enabled. Recommended: Disabled on non-touch devices.",
            Tags = ["input", "touch", "pen", "feedback", "visual"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Cursors"],
            ApplyOps =
            [
                RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "ContactVisualization", 0),
                RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "GestureVisualization", 0),
            ],
            RemoveOps =
            [
                RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "ContactVisualization", 1),
                RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "GestureVisualization", 31),
            ],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "ContactVisualization", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-sticky-keys-shortcut",
            Label = "Disable Sticky Keys Shortcut",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables the Shift×5 shortcut that activates Sticky Keys. Prevents accidental activation during gaming. Default: enabled.",
            Tags = ["input", "sticky-keys", "shortcut", "accessibility"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys", "Flags", "506")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys", "Flags", "510")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys", "Flags", "506")],
        },
        new TweakDef
        {
            Id = "input-increase-keyboard-repeat-rate",
            Label = "Increase Keyboard Repeat Rate",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets keyboard repeat rate to maximum (31). Makes held keys repeat faster. Default: 31.",
            Tags = ["input", "keyboard", "repeat", "rate"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Keyboard"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardSpeed", "31")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardSpeed", "31")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardSpeed", "31")],
        },
        new TweakDef
        {
            Id = "input-reduce-keyboard-delay",
            Label = "Reduce Keyboard Repeat Delay",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces the delay before a held key starts repeating to minimum (0 = ~250ms). Default: 1 (~500ms).",
            Tags = ["input", "keyboard", "delay", "repeat"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Keyboard"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardDelay", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardDelay", "1")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Keyboard", "KeyboardDelay", "0")],
        },
        new TweakDef
        {
            Id = "input-disable-mouse-trails",
            Label = "Disable Mouse Pointer Trails",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables the mouse pointer trail effect. Default: disabled.",
            Tags = ["input", "mouse", "trails", "pointer"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseTrails", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseTrails", "0")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseTrails", "0")],
        },
        new TweakDef
        {
            Id = "input-disable-snap-mouse-to-button",
            Label = "Disable Snap Mouse to Default Button",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables automatically snapping the mouse cursor to the default button in dialog boxes. Default: disabled.",
            Tags = ["input", "mouse", "snap", "dialog"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "SnapToDefaultButton", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "SnapToDefaultButton", "0")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "SnapToDefaultButton", "0")],
        },
        new TweakDef
        {
            Id = "input-disable-mouse-accel",
            Label = "Disable Mouse Acceleration",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables mouse acceleration (enhanced pointer precision). Provides 1:1 mouse movement for gaming and precision work. Default: acceleration enabled.",
            Tags = ["input", "mouse", "acceleration", "gaming"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps =
            [
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSpeed", "0"),
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseThreshold1", "0"),
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseThreshold2", "0"),
            ],
            RemoveOps =
            [
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSpeed", "1"),
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseThreshold1", "6"),
                RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseThreshold2", "10"),
            ],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSpeed", "0")],
        },
        new TweakDef
        {
            Id = "input-enhanced-pointer-precision",
            Label = "Disable Enhanced Pointer Precision",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables the Windows Enhanced Pointer Precision feature. Provides raw unfiltered mouse input for consistent cursor movement. Default: enabled.",
            Tags = ["input", "pointer", "precision", "raw"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSensitivity", "10")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSensitivity", "10")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSensitivity", "10")],
        },
        new TweakDef
        {
            Id = "input-touch-keyboard-disable",
            Label = "Disable Touch Keyboard Auto-Launch",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description =
                "Disables the touch keyboard from auto-launching when tapping text fields on non-tablet devices. Default: auto-launch on touch devices.",
            Tags = ["input", "touch", "keyboard", "disable"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableDesktopModeAutoInvoke", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableDesktopModeAutoInvoke")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "EnableDesktopModeAutoInvoke", 0)],
        },
        // ── Sprint 19 additions ────────────────────────────────────────────
        new TweakDef
        {
            Id = "input-disable-feedback-hub",
            Label = "Disable Feedback Hub Prompts",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Stops Windows from periodically asking for feedback via the Feedback Hub app. Default: enabled.",
            Tags = ["input", "feedback", "hub", "disable"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Siuf\Rules"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Siuf\Rules", "NumberOfSIUFInPeriod", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Software\Microsoft\Siuf\Rules", "NumberOfSIUFInPeriod")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Siuf\Rules", "NumberOfSIUFInPeriod", 0)],
        },
        new TweakDef
        {
            Id = "input-set-wheel-scroll-chars",
            Label = "Set Horizontal Scroll to 3 Characters",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets the horizontal mouse wheel scroll distance to 3 characters per notch. Default: 3.",
            Tags = ["input", "mouse", "scroll", "horizontal"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "WheelScrollChars", "3")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "WheelScrollChars", "3")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Desktop", "WheelScrollChars", "3")],
        },
        new TweakDef
        {
            Id = "input-disable-pen-workspace",
            Label = "Disable Pen Workspace",
            Category = "Input",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Disables the Pen Workspace (Screen Sketch, Sticky Notes shortcut). Useful on non-pen devices. Default: enabled.",
            Tags = ["input", "pen", "workspace", "disable"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace"],
            ApplyOps =
            [
                RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace", "AllowSuggestedAppsInWindowsInkWorkspace", 0),
            ],
            RemoveOps =
            [
                RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace", "AllowSuggestedAppsInWindowsInkWorkspace"),
            ],
            DetectOps =
            [
                RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace", "AllowSuggestedAppsInWindowsInkWorkspace", 0),
            ],
        },
        new TweakDef
        {
            Id = "input-disable-handwriting-panel",
            Label = "Disable Handwriting Panel",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables the handwriting input panel from appearing on touch/pen input. Default: enabled on pen devices.",
            Tags = ["input", "handwriting", "panel", "disable"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "TipbandDesiredVisibility", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "TipbandDesiredVisibility")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\TabletTip\1.7", "TipbandDesiredVisibility", 0)],
        },
        new TweakDef
        {
            Id = "input-set-mouse-hover-width",
            Label = "Increase Mouse Hover Detection Area",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Widens the mouse hover detection rectangle from 4 to 10 pixels. Reduces accidental tooltip triggering. Default: 4.",
            Tags = ["input", "mouse", "hover", "detection"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverWidth", "10")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverWidth", "4")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverWidth", "10")],
        },
        new TweakDef
        {
            Id = "input-disable-touch-visualizations",
            Label = "Disable Touch Visual Feedback",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Removes visual ripple effects shown at touch points. Reduces visual clutter on touchscreen devices. Default: enabled.",
            Tags = ["input", "touch", "visual", "feedback"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Cursors"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "ContactVisualization", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "ContactVisualization", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "ContactVisualization", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-gesture-visualizations",
            Label = "Disable Gesture Visual Feedback",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Removes visual arrow animations shown during multi-finger gestures. Default: enabled on touch devices.",
            Tags = ["input", "gesture", "visual", "feedback"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Cursors"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "GestureVisualization", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "GestureVisualization", 31)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Cursors", "GestureVisualization", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-input-personalization",
            Label = "Disable Input Personalization",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables Windows from collecting typing and inking data to personalize input. Improves privacy. Default: enabled.",
            Tags = ["input", "personalization", "privacy", "typing"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\InputPersonalization"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\InputPersonalization", "RestrictImplicitInkCollection", 1)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\InputPersonalization", "RestrictImplicitInkCollection", 0)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\InputPersonalization", "RestrictImplicitInkCollection", 1)],
        },
        new TweakDef
        {
            Id = "input-disable-writing-insights",
            Label = "Disable Writing Insights",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables Windows Writing Insights that analyse text input for suggestions. Improves privacy. Default: enabled.",
            Tags = ["input", "writing", "insights", "privacy"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Input\Settings"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Input\Settings", "InsightsEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_CURRENT_USER\Software\Microsoft\Input\Settings", "InsightsEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Input\Settings", "InsightsEnabled", 0)],
        },
        new TweakDef
        {
            Id = "input-set-mouse-pointer-speed",
            Label = "Set Mouse Pointer Speed to Maximum",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets the mouse pointer speed to maximum (20). Useful for high-resolution displays. Default: 10.",
            Tags = ["input", "mouse", "speed", "pointer"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSpeed", "2")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSpeed", "1")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSpeed", "2")],
        },
        new TweakDef
        {
            Id = "input-disable-mouse-sonar",
            Label = "Disable Mouse Sonar (Show Pointer on Ctrl Press)",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets MouseSonar=0 in Control Panel\\Mouse. Disables the feature that briefly shows animated rings around the mouse pointer when Ctrl is pressed to locate it.",
            Tags = ["input", "mouse", "sonar", "animation"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSonar", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSonar", "1")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseSonar", "0")],
        },
        new TweakDef
        {
            Id = "input-disable-mouse-vanish",
            Label = "Disable Mouse Vanish (Hide Pointer While Typing)",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets MouseVanish=0 in Control Panel\\Mouse. Stops Windows from hiding the mouse pointer whenever the user is typing. Useful when working across multiple monitors.",
            Tags = ["input", "mouse", "vanish", "typing"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseVanish", "0")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseVanish", "1")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseVanish", "0")],
        },
        new TweakDef
        {
            Id = "input-set-caret-width-2",
            Label = "Set Text Cursor (Caret) Width to 2 px",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets CaretWidth=2 in Desktop. Widens the blinking text insertion caret from the default 1 px to 2 px, making it easier to spot in dense code or document editors.",
            Tags = ["input", "caret", "cursor", "accessibility"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CaretWidth", 2)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CaretWidth", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "CaretWidth", 2)],
        },
        new TweakDef
        {
            Id = "input-disable-lang-switch-hotkey",
            Label = "Disable Keyboard Language Switch Hotkey (Alt+Shift)",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets ToggleHotkey=3 in Keyboard Layout\\Toggle. Disables the hotkey that switches between input languages (default: Left Alt+Shift or Ctrl+Shift), preventing accidental layout changes mid-sentence.",
            Tags = ["input", "keyboard", "language", "hotkey"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Keyboard Layout\Toggle"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Keyboard Layout\Toggle", "ToggleHotkey", "3")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Keyboard Layout\Toggle", "ToggleHotkey", "1")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Keyboard Layout\Toggle", "ToggleHotkey", "3")],
        },
        new TweakDef
        {
            Id = "input-set-mouse-hover-height",
            Label = "Set Mouse Hover Area Height to 4 px",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets MouseHoverHeight=4 in Control Panel\\Mouse. Defines the vertical size of the hover rectangle; keeping it small prevents unintended hover activations on dense UIs.",
            Tags = ["input", "mouse", "hover", "precision"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverHeight", "4")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverHeight", "4")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "MouseHoverHeight", "4")],
        },
        new TweakDef
        {
            Id = "input-disable-touchpad-two-finger-tap",
            Label = "Disable Precision Touchpad Two-Finger Tap (Right-Click)",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets TwoFingerTapEnabled=0 in PrecisionTouchPad. Disables the two-finger tap gesture that normally triggers a right-click, useful when two-finger scrolling also fires unintended context menus.",
            Tags = ["input", "touchpad", "gesture", "tap"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "TwoFingerTapEnabled", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "TwoFingerTapEnabled", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "TwoFingerTapEnabled", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-touchpad-edge-swipe",
            Label = "Disable Precision Touchpad Edge Swipe Gestures",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets EdgeSwipesEnabled=0 in PrecisionTouchPad. Disables swipe-from-edge gestures (open Action Center, Task View, etc.) that can fire accidentally near the trackpad border.",
            Tags = ["input", "touchpad", "edge", "swipe"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "EdgeSwipesEnabled", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "EdgeSwipesEnabled", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "EdgeSwipesEnabled", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-touchpad-three-finger-tap",
            Label = "Disable Precision Touchpad Three-Finger Tap",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets ThreeFingerTapEnabled=0 in PrecisionTouchPad. Prevents the three-finger tap from opening Cortana/Search, a common source of unintended gesture activations during fast typing.",
            Tags = ["input", "touchpad", "gesture", "three-finger"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "ThreeFingerTapEnabled", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "ThreeFingerTapEnabled", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "ThreeFingerTapEnabled", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-touchpad-four-finger-tap",
            Label = "Disable Precision Touchpad Four-Finger Tap",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets FourFingerTapEnabled=0 in PrecisionTouchPad. Disables the four-finger tap gesture that opens the Action Center, preventing accidental panel opens.",
            Tags = ["input", "touchpad", "gesture", "four-finger"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "FourFingerTapEnabled", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "FourFingerTapEnabled", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "FourFingerTapEnabled", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-touchpad-right-zone",
            Label = "Disable Precision Touchpad Right-Click Corner Zone",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets RightClickZoneEnabled=0 in PrecisionTouchPad. Removes the dedicated bottom-right corner tap zone that fires a right-click, helping users who accidentally trigger it.",
            Tags = ["input", "touchpad", "right-click", "zone"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "RightClickZoneEnabled", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "RightClickZoneEnabled", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "RightClickZoneEnabled", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-touchpad-swipe-nav",
            Label = "Disable Precision Touchpad Swipe Navigation (Back/Forward)",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets SwipeNavigationEnabled=0 in PrecisionTouchPad. Disables three-finger left/right swipe gestures that navigate back and forward in browsers and File Explorer.",
            Tags = ["input", "touchpad", "swipe", "navigation"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "SwipeNavigationEnabled", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "SwipeNavigationEnabled", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "SwipeNavigationEnabled", 0)],
        },
        new TweakDef
        {
            Id = "input-disable-touchpad-pinch-zoom",
            Label = "Disable Precision Touchpad Pinch-to-Zoom",
            Category = "Input",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets PinchZoomEnabled=0 in PrecisionTouchPad. Disables the two-finger pinch gesture that zooms in/out in supported apps and the browser, preventing accidental zoom changes.",
            Tags = ["input", "touchpad", "pinch", "zoom"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "PinchZoomEnabled", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "PinchZoomEnabled", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PrecisionTouchPad", "PinchZoomEnabled", 0)],
        },
    ];
}
