namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class InternetCommunicationPolicy
{
    private const string InetMgmtKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\InternetManagement";
    private const string InetRestrictKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\CurrentVersion\Software Protection Platform";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "inetcomm-restrict-internet-communication",
            Label = "Internet Communication: Restrict All Internet Communication Features",
            Category = "Internet Communication Policy",
            Description = "Enables the master Internet Communication Management policy that restricts or disables all Windows features that communicate with the internet, including Windows Error Reporting, Windows Update, Help and Support Center online search, Microsoft Customer Experience Improvement Program (CEIP), online activation, and other phone-home features. This is the master switch that enables sub-policies defined elsewhere under the InternetManagement key.",
            Tags = ["internet communication", "internet restriction", "privacy", "phone home", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [InetMgmtKey],
            ApplyOps = [RegOp.SetDword(InetMgmtKey, "RestrictInternetCommunication", 1)],
            RemoveOps = [RegOp.DeleteValue(InetMgmtKey, "RestrictInternetCommunication")],
            DetectOps = [RegOp.CheckDword(InetMgmtKey, "RestrictInternetCommunication", 1)],
            ImpactScore = 5,
            SafetyRating = 3,
            ImpactNote = "Broad internet communication block; may affect Windows Update, activation, and online Help. Test thoroughly before deploying.",
        },
        new TweakDef
        {
            Id = "inetcomm-disable-printing-over-http",
            Label = "Internet Communication: Disable Printing Over HTTP",
            Category = "Internet Communication Policy",
            Description = "Disables the ability for Windows to send print jobs over HTTP, which is used for sending documents to Internet Printing Protocol (IPP) printers outside the corporate network. HTTP printing can bypass proxy controls and DLP systems. On managed networks, all printing should be directed to IT-managed printer queues; direct-to-internet IPP printing is a potential data exfiltration vector.",
            Tags = ["internet communication", "printing", "http", "data loss prevention", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [InetMgmtKey],
            ApplyOps = [RegOp.SetDword(InetMgmtKey, "DisableHTTPPrinting", 1)],
            RemoveOps = [RegOp.DeleteValue(InetMgmtKey, "DisableHTTPPrinting")],
            DetectOps = [RegOp.CheckDword(InetMgmtKey, "DisableHTTPPrinting", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Disables Internet Printing Protocol (IPP) over HTTP; LAN-connected print servers are unaffected.",
        },
        new TweakDef
        {
            Id = "inetcomm-disable-windows-update-access",
            Label = "Internet Communication: Disable Access to Windows Update (Non-WSUS)",
            Category = "Internet Communication Policy",
            Description = "Blocks Windows from accessing Microsoft's Windows Update servers directly, restricting update access to corporate WSUS or Windows Update for Business (WUfB) only. Direct Windows Update connections bypass the organization's patch approval process, potentially installing untested updates or creating tracking data. This policy should be combined with a WSUS or Intune Update Ring configuration to ensure updates are still received through an approved channel.",
            Tags = ["internet communication", "windows update", "wsus", "patch management", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [InetMgmtKey],
            ApplyOps = [RegOp.SetDword(InetMgmtKey, "DisableWindowsUpdateAccess", 1)],
            RemoveOps = [RegOp.DeleteValue(InetMgmtKey, "DisableWindowsUpdateAccess")],
            DetectOps = [RegOp.CheckDword(InetMgmtKey, "DisableWindowsUpdateAccess", 1)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Blocks direct access to Windows Update; requires WSUS or WUfB to be configured for updates to be received.",
        },
        new TweakDef
        {
            Id = "inetcomm-disable-web-communities",
            Label = "Internet Communication: Disable Windows Web Communities Feature",
            Category = "Internet Communication Policy",
            Description = "Disables the Windows Web Communities feature that allowed Windows Explorer and Help Center to automatically submit queries to Microsoft-hosted community websites (forums, knowledge base, support articles). While useful in consumer scenarios, this feature sends details about the user's system context, open documents, and help searches to external Microsoft servers, which creates a data-leakage concern in regulated business environments.",
            Tags = ["internet communication", "communities", "help center", "telemetry", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [InetMgmtKey],
            ApplyOps = [RegOp.SetDword(InetMgmtKey, "DisableWebCommunities", 1)],
            RemoveOps = [RegOp.DeleteValue(InetMgmtKey, "DisableWebCommunities")],
            DetectOps = [RegOp.CheckDword(InetMgmtKey, "DisableWebCommunities", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Disables Windows community search in Help Center; standard online help articles are unaffected.",
        },
        new TweakDef
        {
            Id = "inetcomm-disable-event-viewer-links",
            Label = "Internet Communication: Disable Event Viewer Online Links",
            Category = "Internet Communication Policy",
            Description = "Prevents Event Viewer from displaying the 'More Information' link that opens a Microsoft online support page when viewing event log entries. Clicking these links sends event detail data (Event ID, source, parameters) to Microsoft's online event log lookup service. In sensitive environments, event log data may contain internal application identifiers, username fragments, or file path details that should not be transmitted outside the network.",
            Tags = ["internet communication", "event viewer", "online links", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [InetMgmtKey],
            ApplyOps = [RegOp.SetDword(InetMgmtKey, "DisableEventViewer", 1)],
            RemoveOps = [RegOp.DeleteValue(InetMgmtKey, "DisableEventViewer")],
            DetectOps = [RegOp.CheckDword(InetMgmtKey, "DisableEventViewer", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Removes 'More Information' online links from Event Viewer; local event logs are fully accessible.",
        },
        new TweakDef
        {
            Id = "inetcomm-disable-registration-wizard",
            Label = "Internet Communication: Disable Windows Registration Wizard",
            Category = "Internet Communication Policy",
            Description = "Disables the Windows Product Registration Wizard that appears after OS installation and prompts users to register the Windows license with Microsoft. The registration process transmits hardware information (CPU, RAM, disk size), Windows edition, and product key metadata to Microsoft's registration servers. On volume-licensed enterprise deployments, this registration is handled by Microsoft's volume activation infrastructure and the wizard is unnecessary.",
            Tags = ["internet communication", "registration", "product key", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [InetMgmtKey],
            ApplyOps = [RegOp.SetDword(InetMgmtKey, "DisableRegistration", 1)],
            RemoveOps = [RegOp.DeleteValue(InetMgmtKey, "DisableRegistration")],
            DetectOps = [RegOp.CheckDword(InetMgmtKey, "DisableRegistration", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Disables the Windows registration wizard; volume-licensed systems are unaffected — VL activation works separately.",
        },
        new TweakDef
        {
            Id = "inetcomm-disable-windows-activation-online",
            Label = "Internet Communication: Disable Windows Online Activation",
            Category = "Internet Communication Policy",
            Description = "Prevents Windows from attempting online activation via Microsoft's activation servers. In enterprise environments using KMS (Key Management Service) or MAK (Multiple Activation Key) volume licensing, Windows activates against the internal KMS server. Attempting simultaneous online activation can cause interference and may expose the KMS key or activation state to Microsoft's telemetry infrastructure.",
            Tags = ["internet communication", "activation", "kms", "volume license", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [InetRestrictKey],
            ApplyOps = [RegOp.SetDword(InetRestrictKey, "NoGenTicket", 1)],
            RemoveOps = [RegOp.DeleteValue(InetRestrictKey, "NoGenTicket")],
            DetectOps = [RegOp.CheckDword(InetRestrictKey, "NoGenTicket", 1)],
            ImpactScore = 3,
            SafetyRating = 3,
            ImpactNote = "Disables online activation; requires KMS or MAK infrastructure to be in place for Windows to remain activated.",
        },
        new TweakDef
        {
            Id = "inetcomm-disable-task-scheduler-download",
            Label = "Internet Communication: Disable Task Scheduler Internet Download",
            Category = "Internet Communication Policy",
            Description = "Prevents Windows Task Scheduler from downloading programs, scripts, or task definitions from internet URIs. Task Scheduler tasks can be configured with action items that fetch content from HTTP/HTTPS URLs. Blocking internet downloads from Task Scheduler prevents lateral movement via scheduled tasks that pull malware from C2 servers and prevents administrative tasks from overriding proxy policies by downloading directly.",
            Tags = ["internet communication", "task scheduler", "download", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [InetMgmtKey],
            ApplyOps = [RegOp.SetDword(InetMgmtKey, "DisableTaskSchedulerDownload", 1)],
            RemoveOps = [RegOp.DeleteValue(InetMgmtKey, "DisableTaskSchedulerDownload")],
            DetectOps = [RegOp.CheckDword(InetMgmtKey, "DisableTaskSchedulerDownload", 1)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Blocks internet downloads initiated by Task Scheduler actions; scheduled tasks with local scripts are unaffected.",
        },
        new TweakDef
        {
            Id = "inetcomm-disable-online-search-help",
            Label = "Internet Communication: Disable Windows Online Search in Help",
            Category = "Internet Communication Policy",
            Description = "Prevents the Windows Help and Support Center from augmenting local help content with online Microsoft documentation and search results. The online search feature sends the user's help query terms and partial system context to Microsoft's servers. In environments where query terms may contain project names, application names, or technical details classified as business-sensitive, disabling online help search prevents inadvertent disclosure.",
            Tags = ["internet communication", "help center", "online search", "privacy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [InetMgmtKey],
            ApplyOps = [RegOp.SetDword(InetMgmtKey, "DisableOnlineSearch", 1)],
            RemoveOps = [RegOp.DeleteValue(InetMgmtKey, "DisableOnlineSearch")],
            DetectOps = [RegOp.CheckDword(InetMgmtKey, "DisableOnlineSearch", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Limits Help Center to local offline articles; online Microsoft documentation is not fetched.",
        },
        new TweakDef
        {
            Id = "inetcomm-disable-driver-update-internet",
            Label = "Internet Communication: Disable Driver Download from Windows Update",
            Category = "Internet Communication Policy",
            Description = "Prevents Windows from automatically downloading device driver updates directly from Windows Update when a new device is plugged in. Driver updates fetched directly from Windows Update bypass the organization's driver qualification and testing process. In managed environments, all driver updates should go through SCCM, Intune, or another MDM platform that can test and stage driver deployments before production rollout.",
            Tags = ["internet communication", "driver update", "windows update", "device management", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [InetMgmtKey],
            ApplyOps = [RegOp.SetDword(InetMgmtKey, "DisableDriverUpdate", 1)],
            RemoveOps = [RegOp.DeleteValue(InetMgmtKey, "DisableDriverUpdate")],
            DetectOps = [RegOp.CheckDword(InetMgmtKey, "DisableDriverUpdate", 1)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Stops Windows from fetching driver updates via Windows Update; driver management must be handled via MDM or manual deployment.",
        },
    ];
}
