namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class NetworkAccessProtectionPolicy
{
    private const string NapKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\NetworkAccessProtection\MSNAPAgent";
    private const string QuarantineKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\NetworkAccessProtection\Quarantine";
    private const string NapAgentKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\NAPAgent";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "napcomp-enable-nap-client-enforcement",
            Label = "NAP Policy: Enable NAP Client Enforcement Mode",
            Category = "Network Access Protection Policy",
            Description = "Enables the Network Access Protection (NAP) client on the machine, allowing the machine to participate in NAP health validation and enforcement workflows. NAP is a policy-based network access control framework that evaluates the health state of a machine (antivirus, patch level, firewall status) before granting full network access. Enabling enforcement mode ensures that a machine reporting an unhealthy health state is placed in a restricted network segment until it is remediated.",
            Tags = ["nap", "network access protection", "compliance", "health validation", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NapKey],
            ApplyOps = [RegOp.SetDword(NapKey, "EnableNAPClient", 1)],
            RemoveOps = [RegOp.DeleteValue(NapKey, "EnableNAPClient")],
            DetectOps = [RegOp.CheckDword(NapKey, "EnableNAPClient", 1)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Enables NAP health enforcement; machines that fail health checks may lose full network access — ensure NHPs and remediation servers are configured.",
        },
        new TweakDef
        {
            Id = "napcomp-require-health-validation",
            Label = "NAP Policy: Require Health Certificate for Network Access",
            Category = "Network Access Protection Policy",
            Description = "Configures the NAP client to require a valid System Health Certificate (SHC) before being granted unrestricted network access. Without a health certificate, the machine is placed in the quarantine network. Health certificates are issued by the Health Registration Authority (HRA) after the NPS Health Policy Server verifies that all system health validators (SHVs) report a compliant state. This policy forms the core of the 802.1X-based NAP enforcement chain.",
            Tags = ["nap", "health certificate", "802.1x", "hps", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NapKey],
            ApplyOps = [RegOp.SetDword(NapKey, "RequireHealthCertificate", 1)],
            RemoveOps = [RegOp.DeleteValue(NapKey, "RequireHealthCertificate")],
            DetectOps = [RegOp.CheckDword(NapKey, "RequireHealthCertificate", 1)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Requires health certificate for full network access; misconfigured NAP infrastructure will quarantine all machines including healthy ones.",
        },
        new TweakDef
        {
            Id = "napcomp-enforce-vpn-shv",
            Label = "NAP Policy: Enable System Health Validation for VPN Connections",
            Category = "Network Access Protection Policy",
            Description = "Activates System Health Validator (SHV) evaluation for VPN-based NAP enforcement, ensuring that remote machines connecting via VPN are subject to the same health compliance checks as internally-connected machines. Without VPN-SHV enforcement, remote workers can connect to the corporate network with out-of-date antivirus signatures or missing security patches while bypassing the health gating that on-premises machines face.",
            Tags = ["nap", "vpn", "system health validator", "remote access", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NapKey],
            ApplyOps = [RegOp.SetDword(NapKey, "EnableVPNSHV", 1)],
            RemoveOps = [RegOp.DeleteValue(NapKey, "EnableVPNSHV")],
            DetectOps = [RegOp.CheckDword(NapKey, "EnableVPNSHV", 1)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Extends NAP health checks to VPN connections; requires a configured NAP Network Policy Server and VPN server with NAP support.",
        },
        new TweakDef
        {
            Id = "napcomp-disable-auto-remediation",
            Label = "NAP Policy: Disable Automatic Health Remediation",
            Category = "Network Access Protection Policy",
            Description = "Prevents the NAP client from automatically remediating detected health deficiencies by making software changes (e.g., enabling Windows Firewall, triggering Windows Update). Automatic remediation can make unexpected changes to a system without user awareness and may conflict with endpoint management tools (such as Intune or SCCM) that manage those settings centrally. Disabling auto-remediation forces the user or help desk to perform explicit remediation steps.",
            Tags = ["nap", "auto remediation", "endpoint management", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NapKey],
            ApplyOps = [RegOp.SetDword(NapKey, "DisableAutoRemediation", 1)],
            RemoveOps = [RegOp.DeleteValue(NapKey, "DisableAutoRemediation")],
            DetectOps = [RegOp.CheckDword(NapKey, "DisableAutoRemediation", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Disables auto-remediation; unhealthy machines stay quarantined until manual intervention — ensure help desk procedures are documented.",
        },
        new TweakDef
        {
            Id = "napcomp-enforce-quarantine-timeout",
            Label = "NAP Policy: Set Quarantine Timeout Period for Unhealthy Machines",
            Category = "Network Access Protection Policy",
            Description = "Configures how long (in minutes) a machine can remain in the quarantine network before its health is re-evaluated and upgraded to full access or flagged for intervention. A timeout of 480 minutes (8 hours) reflects a typical business-day remediation window. Without a timeout, a machine placed in quarantine due to a transient health failure stays restricted indefinitely unless an administrator intervenes or the NAP client is restarted.",
            Tags = ["nap", "quarantine", "timeout", "health policy", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [QuarantineKey],
            ApplyOps = [RegOp.SetDword(QuarantineKey, "QuarantineTimeoutMinutes", 480)],
            RemoveOps = [RegOp.DeleteValue(QuarantineKey, "QuarantineTimeoutMinutes")],
            DetectOps = [RegOp.CheckDword(QuarantineKey, "QuarantineTimeoutMinutes", 480)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Sets quarantine timeout to 8 hours; machines that remediate earlier will get re-evaluated when they reconnect.",
        },
        new TweakDef
        {
            Id = "napcomp-enable-quarantine-state-pki",
            Label = "NAP Policy: Enable PKI-Based Quarantine State Machine",
            Category = "Network Access Protection Policy",
            Description = "Activates the PKI-based state machine within the NAP client that uses X.509 certificates to encode the machine's health attestation state. The PKI state machine is required for the IPSEC enforcement method, which uses health certificates to gate machine-to-machine communication at the network layer. Without this, only 802.1X or DHCP-based NAP enforcement methods are available, which are less granular than IPSEC health-gated policies.",
            Tags = ["nap", "pki", "ipsec", "health attestation", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NapKey],
            ApplyOps = [RegOp.SetDword(NapKey, "EnablePKIStateMachine", 1)],
            RemoveOps = [RegOp.DeleteValue(NapKey, "EnablePKIStateMachine")],
            DetectOps = [RegOp.CheckDword(NapKey, "EnablePKIStateMachine", 1)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Activates PKI health-state machine; requires a Health Registration Authority (HRA) and certificate infrastructure.",
        },
        new TweakDef
        {
            Id = "napcomp-enable-dhcp-enforcement",
            Label = "NAP Policy: Enable DHCP-Based NAP Enforcement",
            Category = "Network Access Protection Policy",
            Description = "Enables the DHCP enforcement client for NAP, allowing the machine to participate in DHCP quarantine workflows. In DHCP enforcement mode, the DHCP server issues different IP address leases (quarantine vs. full-access scope) based on the client's health certificate. This is the simplest NAP enforcement method to deploy and requires no changes to network switches, making it suitable for organisations with legacy switching infrastructure.",
            Tags = ["nap", "dhcp enforcement", "quarantine", "network access", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NapAgentKey],
            ApplyOps = [RegOp.SetDword(NapAgentKey, "EnableDHCPEnforcement", 1)],
            RemoveOps = [RegOp.DeleteValue(NapAgentKey, "EnableDHCPEnforcement")],
            DetectOps = [RegOp.CheckDword(NapAgentKey, "EnableDHCPEnforcement", 1)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Enables DHCP-based NAP enforcement; requires NAP-capable DHCP server and NPS health policy configuration.",
        },
        new TweakDef
        {
            Id = "napcomp-enable-wired-8021x-enforcement",
            Label = "NAP Policy: Enable Wired 802.1X NAP Enforcement",
            Category = "Network Access Protection Policy",
            Description = "Activates the 802.1X enforcement client for wired network connections, enabling switch-level NAP quarantine for machines that fail health evaluations. 802.1X enforcement is the strongest NAP mechanism because it operates at the switch port level — a machine placed in quarantine cannot communicate on the network at all without passing through the enforcement switch, regardless of IP configuration. This method requires 802.1X-capable managed switches.",
            Tags = ["nap", "802.1x", "wired enforcement", "switch", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NapAgentKey],
            ApplyOps = [RegOp.SetDword(NapAgentKey, "EnableWired8021xEnforcement", 1)],
            RemoveOps = [RegOp.DeleteValue(NapAgentKey, "EnableWired8021xEnforcement")],
            DetectOps = [RegOp.CheckDword(NapAgentKey, "EnableWired8021xEnforcement", 1)],
            ImpactScore = 5,
            SafetyRating = 3,
            ImpactNote = "Activates 802.1X NAP; requires managed 802.1X switches and NPS RADIUS configuration — test in lab before broad deployment.",
        },
        new TweakDef
        {
            Id = "napcomp-enable-ts-gateway-enforcement",
            Label = "NAP Policy: Enable Terminal Services Gateway NAP Enforcement",
            Category = "Network Access Protection Policy",
            Description = "Enables the Terminal Services (Remote Desktop) Gateway NAP enforcement client. When active, the TS Gateway evaluates the client machine's NAP health certificate before establishing an RDP tunnel, ensuring that remote desktop sessions from unhealthy endpoints are blocked at the gateway. This is particularly important for privileged access workstations (PAWs) connecting to administrative systems — an infected admin workstation should not be allowed to initiate RDP sessions.",
            Tags = ["nap", "terminal services", "remote desktop", "gateway", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NapAgentKey],
            ApplyOps = [RegOp.SetDword(NapAgentKey, "EnableTSGatewayEnforcement", 1)],
            RemoveOps = [RegOp.DeleteValue(NapAgentKey, "EnableTSGatewayEnforcement")],
            DetectOps = [RegOp.CheckDword(NapAgentKey, "EnableTSGatewayEnforcement", 1)],
            ImpactScore = 4,
            SafetyRating = 3,
            ImpactNote = "Gates RDP gateway access on NAP health; requires a NAP-enabled TS Gateway and NPS policy configuration.",
        },
        new TweakDef
        {
            Id = "napcomp-enable-ipsec-enforcement",
            Label = "NAP Policy: Enable IPsec-Based NAP Enforcement",
            Category = "Network Access Protection Policy",
            Description = "Activates the IPsec enforcement client for NAP, which uses short-lived health certificates to enforce IPsec policies between machines on the same network. IPsec NAP enforcement ensures that only machines with current, valid health certificates can communicate over authenticated IPsec channels. This is the most granular NAP enforcement method and enables zero-trust-style east-west traffic control within a corporate network segment.",
            Tags = ["nap", "ipsec", "zero trust", "east-west", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NapAgentKey],
            ApplyOps = [RegOp.SetDword(NapAgentKey, "EnableIPsecEnforcement", 1)],
            RemoveOps = [RegOp.DeleteValue(NapAgentKey, "EnableIPsecEnforcement")],
            DetectOps = [RegOp.CheckDword(NapAgentKey, "EnableIPsecEnforcement", 1)],
            ImpactScore = 5,
            SafetyRating = 2,
            ImpactNote = "Activates IPsec NAP; requires HRA, NPS, and IPsec policy infrastructure — extremely disruptive if misconfigured. Production testing mandatory.",
        },
    ];
}
