namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class NtpGpoPolicy
{
    private const string NtpClientKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\W32Time\Client";
    private const string NtpParametersKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\W32Time\Parameters";
    private const string NtpConfigKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\W32Time\Config";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "ntpgpo-enable-ntp-client",
            Label = "NTP Policy: Enable Windows NTP Client via Group Policy",
            Category = "NTP Time Service Policy",
            Description = "Configures the Windows Time service (W32Time) client to retrieve time from an NTP server by enabling the NTP client via the Policies registry path. This policy controls the Windows Time service behaviour at the machine level. Accurate time synchronisation is a prerequisite for Kerberos authentication, SSL/TLS certificate validation, log correlation, and compliance auditing. Forcing the NTP client on ensures time sync cannot be accidentally disabled by local administrators.",
            Tags = ["ntp", "time sync", "w32time", "kerberos", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NtpClientKey],
            ApplyOps = [RegOp.SetDword(NtpClientKey, "Enabled", 1)],
            RemoveOps = [RegOp.DeleteValue(NtpClientKey, "Enabled")],
            DetectOps = [RegOp.CheckDword(NtpClientKey, "Enabled", 1)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Ensures Windows NTP client is active; required for domain Kerberos auth, certificate validation, and audit log consistency.",
        },
        new TweakDef
        {
            Id = "ntpgpo-enforce-ntp-type",
            Label = "NTP Policy: Enforce NTP Synchronisation Type",
            Category = "NTP Time Service Policy",
            Description = "Sets the Windows Time service synchronisation type to NTP, ensuring that the machine always uses an external NTP server rather than relying solely on the domain hierarchy (NT5DS) or free-running internal clock (NoSync). On machines that are occasionally disconnected from the domain, pure NT5DS mode means no time sync occurs when the DC is unreachable. Setting type to NTP with a fallback ensures time accuracy even during DC outages.",
            Tags = ["ntp", "time sync", "w32time", "domain", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NtpParametersKey],
            ApplyOps = [RegOp.SetString(NtpParametersKey, "Type", "NTP")],
            RemoveOps = [RegOp.DeleteValue(NtpParametersKey, "Type")],
            DetectOps = [RegOp.CheckString(NtpParametersKey, "Type", "NTP")],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Forces NTP sync type; domain machines normally use NT5DS — verify NTP server policy is also set before deploying.",
        },
        new TweakDef
        {
            Id = "ntpgpo-set-cross-site-sync-flags",
            Label = "NTP Policy: Set NTP Cross-Site Synchronisation Flags",
            Category = "NTP Time Service Policy",
            Description = "Sets the CrossSiteSyncFlags value in the W32Time Client policy to 2, allowing the Windows Time service to synchronise from NTP time sources across AD sites. By default, Windows Time prefers NTP sources within the same AD site. Setting this flag allows cross-site sync as a fallback when no local NTP source is available, preventing time drift in remote sites with poor DC connectivity.",
            Tags = ["ntp", "time sync", "active directory", "cross site", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NtpClientKey],
            ApplyOps = [RegOp.SetDword(NtpClientKey, "CrossSiteSyncFlags", 2)],
            RemoveOps = [RegOp.DeleteValue(NtpClientKey, "CrossSiteSyncFlags")],
            DetectOps = [RegOp.CheckDword(NtpClientKey, "CrossSiteSyncFlags", 2)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Allows NTP sync from DCs in other AD sites; recommended for branch-office deployments with limited local DC bandwidth.",
        },
        new TweakDef
        {
            Id = "ntpgpo-set-special-poll-interval",
            Label = "NTP Policy: Set Special Poll Interval for NTP Synchronisation",
            Category = "NTP Time Service Policy",
            Description = "Configures a specific NTP poll interval (in seconds) for the Windows Time service client operating in SpecialInterval mode. The default Windows Time poll interval can be too infrequent for high-security environments where clock drift is measured in seconds. A 900-second (15-minute) interval ensures that machines re-synchronise frequently enough to stay within the 5-minute Kerberos clock skew limit and to provide accurate timestamps for security event logs.",
            Tags = ["ntp", "time sync", "poll interval", "kerberos", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NtpClientKey],
            ApplyOps = [RegOp.SetDword(NtpClientKey, "SpecialPollInterval", 900)],
            RemoveOps = [RegOp.DeleteValue(NtpClientKey, "SpecialPollInterval")],
            DetectOps = [RegOp.CheckDword(NtpClientKey, "SpecialPollInterval", 900)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Sets NTP poll interval to 15 minutes; smaller intervals add network traffic but improve time accuracy.",
        },
        new TweakDef
        {
            Id = "ntpgpo-set-event-log-flags",
            Label = "NTP Policy: Set W32Time Event Log Verbosity Flags",
            Category = "NTP Time Service Policy",
            Description = "Sets the EventLogFlags value to 3 in the W32Time Config policy, enabling W32Time to log both time-source change events and significant time adjustments to the System event log. These events allow security analysts to detect unusual time manipulation attempts (a precursor to log tampering or Kerberos replay attacks). Without verbose logging, time sync anomalies are invisible in standard Windows monitoring pipelines.",
            Tags = ["ntp", "time sync", "event log", "security monitoring", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NtpConfigKey],
            ApplyOps = [RegOp.SetDword(NtpConfigKey, "EventLogFlags", 3)],
            RemoveOps = [RegOp.DeleteValue(NtpConfigKey, "EventLogFlags")],
            DetectOps = [RegOp.CheckDword(NtpConfigKey, "EventLogFlags", 3)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Enables W32Time change and adjustment events in System Event Log; minor increase in log volume.",
        },
        new TweakDef
        {
            Id = "ntpgpo-set-max-pos-phase-correction",
            Label = "NTP Policy: Set Maximum Positive Phase Correction for NTP",
            Category = "NTP Time Service Policy",
            Description = "Configures the MaxPosPhaseCorrection value (in seconds) to limit how far forward the Windows Time service will jump the local clock in a single correction. By default, Windows Time accepts any positive time correction from an NTP source, which means an adversary-controlled or misconfigured NTP server could jump the clock forward many hours in one step, invalidating all certificate-based authentication and causing log gaps. A 3600-second cap (1 hour) provides a reasonable safety limit.",
            Tags = ["ntp", "time sync", "phase correction", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NtpConfigKey],
            ApplyOps = [RegOp.SetDword(NtpConfigKey, "MaxPosPhaseCorrection", 3600)],
            RemoveOps = [RegOp.DeleteValue(NtpConfigKey, "MaxPosPhaseCorrection")],
            DetectOps = [RegOp.CheckDword(NtpConfigKey, "MaxPosPhaseCorrection", 3600)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Caps positive clock jumps at 1 hour; machines with severe clock drift may need multiple sync cycles to recover.",
        },
        new TweakDef
        {
            Id = "ntpgpo-set-max-neg-phase-correction",
            Label = "NTP Policy: Set Maximum Negative Phase Correction for NTP",
            Category = "NTP Time Service Policy",
            Description = "Configures the MaxNegPhaseCorrection value (in seconds) to limit how far backward the Windows Time service will roll back the local clock in a single correction. Unbounded backward time corrections can cause Kerberos ticket replay windows to expand unexpectedly, allow log entries to appear to pre-date their corresponding events, and trigger false positives in time-based security controls. A 3600-second limit (1 hour) is the recommended security baseline.",
            Tags = ["ntp", "time sync", "phase correction", "kerberos", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NtpConfigKey],
            ApplyOps = [RegOp.SetDword(NtpConfigKey, "MaxNegPhaseCorrection", 3600)],
            RemoveOps = [RegOp.DeleteValue(NtpConfigKey, "MaxNegPhaseCorrection")],
            DetectOps = [RegOp.CheckDword(NtpConfigKey, "MaxNegPhaseCorrection", 3600)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Caps negative (backward) clock corrections at 1 hour; machines that are very far ahead may need manual intervention.",
        },
        new TweakDef
        {
            Id = "ntpgpo-set-resolve-peer-backoff-min",
            Label = "NTP Policy: Set Minimum Peer Resolution Backoff Interval",
            Category = "NTP Time Service Policy",
            Description = "Sets the ResolvePeerBackOffMinutes value (in minutes) to 15, controlling the minimum time the Windows Time client waits before retrying a failed NTP peer resolution attempt. Short backoff intervals cause the W32Time service to hammer DNS and the NTP server with rapid retries after network outages. A 15-minute minimum backoff reduces NTP server load and prevents false-positive flapping alerts in network monitoring systems.",
            Tags = ["ntp", "time sync", "backoff", "network load", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NtpClientKey],
            ApplyOps = [RegOp.SetDword(NtpClientKey, "ResolvePeerBackOffMinutes", 15)],
            RemoveOps = [RegOp.DeleteValue(NtpClientKey, "ResolvePeerBackOffMinutes")],
            DetectOps = [RegOp.CheckDword(NtpClientKey, "ResolvePeerBackOffMinutes", 15)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Sets minimum NTP retry backoff to 15 minutes; reduces NTP/DNS chatter after transient network failures.",
        },
        new TweakDef
        {
            Id = "ntpgpo-set-resolve-peer-backoff-max",
            Label = "NTP Policy: Set Maximum Peer Resolution Backoff Retry Count",
            Category = "NTP Time Service Policy",
            Description = "Sets the ResolvePeerBackOffMaxTimes value to 7, controlling the maximum number of exponential backoff retry doublings before the Windows Time client gives up and stops attempting to resolve an NTP peer. Without a cap, the exponential backoff can grow indefinitely, resulting in machines that stop trying to sync hours after a network issue clears. Limiting to 7 doublings (max backoff of 15 min × 2^7 ≈ 32 hours) balances persistence with eventual giving-up.",
            Tags = ["ntp", "time sync", "backoff retry", "network resilience", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NtpClientKey],
            ApplyOps = [RegOp.SetDword(NtpClientKey, "ResolvePeerBackOffMaxTimes", 7)],
            RemoveOps = [RegOp.DeleteValue(NtpClientKey, "ResolvePeerBackOffMaxTimes")],
            DetectOps = [RegOp.CheckDword(NtpClientKey, "ResolvePeerBackOffMaxTimes", 7)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Limits NTP peer retry doublings to 7; after ~32 hours without an NTP response, the service stops retrying until restarted.",
        },
        new TweakDef
        {
            Id = "ntpgpo-set-announce-flags",
            Label = "NTP Policy: Configure W32Time Announce Flags for Domain Hierarchy",
            Category = "NTP Time Service Policy",
            Description = "Sets the AnnounceFlags value to 10 in W32Time Config, configuring the time service to announce itself as a reliable time source when acting as a DC-level NTP server for domain clients. A value of 10 (0x0A) enables both 'always reliable' and 'auto-reliable' flags. This prevents workstations from querying internet NTP sources instead of the authoritative domain hierarchy, and ensures PDC emulators are correctly identified as the time authority by child DCs.",
            Tags = ["ntp", "time sync", "announce flags", "domain controller", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [NtpConfigKey],
            ApplyOps = [RegOp.SetDword(NtpConfigKey, "AnnounceFlags", 10)],
            RemoveOps = [RegOp.DeleteValue(NtpConfigKey, "AnnounceFlags")],
            DetectOps = [RegOp.CheckDword(NtpConfigKey, "AnnounceFlags", 10)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Configures W32Time announce flags; primarily relevant on domain controllers — apply cautiously on standalone workstations.",
        },
    ];
}
