namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

[TweakModule]
internal static class PolicyWindowsStore
{
    private const string StoreKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\WindowsStore";

    public static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "storepl-policy-turn-off-store-notifications",
            Label = "Turn Off Store Notifications",
            Category = "System",
            Description =
                "Sets TurnOffStoreNotifications=1 under the WindowsStore Group Policy key. "
                + "Suppresses all notification toasts generated by the Windows Store, including app update availability, "
                + "promotional offers, and feature announcements. "
                + "Reduces notification noise in managed environments.",
            Tags = ["store", "notifications", "toasts", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Store-generated notification toasts are suppressed for all users.",
            ApplyOps = [RegOp.SetDword(StoreKey, "TurnOffStoreNotifications", 1)],
            RemoveOps = [RegOp.DeleteValue(StoreKey, "TurnOffStoreNotifications")],
            DetectOps = [RegOp.CheckDword(StoreKey, "TurnOffStoreNotifications", 1)],
        },
        new TweakDef
        {
            Id = "storepl-policy-disable-purchase",
            Label = "Disable Store App Purchases",
            Category = "System",
            Description =
                "Sets DisablePurchasePage=1 under the WindowsStore Group Policy key. "
                + "Prevents users from viewing or completing in-app purchases or paid app transactions in the Store. "
                + "Blocks the payment flow entirely, preventing accidental or unauthorised charges.",
            Tags = ["store", "purchase", "payment", "policy", "enterprise"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "In-app purchases and paid app transactions are blocked in the Store.",
            ApplyOps = [RegOp.SetDword(StoreKey, "DisablePurchasePage", 1)],
            RemoveOps = [RegOp.DeleteValue(StoreKey, "DisablePurchasePage")],
            DetectOps = [RegOp.CheckDword(StoreKey, "DisablePurchasePage", 1)],
        },
        new TweakDef
        {
            Id = "storepl-policy-disable-app-install",
            Label = "Block Users from Installing Apps",
            Category = "System",
            Description =
                "Sets BlockNonAdminUserInstall=1 under the WindowsStore Group Policy key. "
                + "Prevents non-administrator users from initiating app installations from any source via the Store. "
                + "Centralises app permission to administrators only.",
            Tags = ["store", "install", "non-admin", "policy", "enterprise"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Standard users cannot install apps; only administrators can approve and install.",
            ApplyOps = [RegOp.SetDword(StoreKey, "BlockNonAdminUserInstall", 1)],
            RemoveOps = [RegOp.DeleteValue(StoreKey, "BlockNonAdminUserInstall")],
            DetectOps = [RegOp.CheckDword(StoreKey, "BlockNonAdminUserInstall", 1)],
        },
        new TweakDef
        {
            Id = "storepl-policy-disable-video-streaming",
            Label = "Disable Store Video Streaming",
            Category = "System",
            Description =
                "Sets DisableVideoPage=1 under the WindowsStore Group Policy key. "
                + "Hides the Video section of the Microsoft Store, preventing access to streaming video content purchasing. "
                + "Reduces bandwidth usage and removes non-productivity content from the Store in enterprise settings.",
            Tags = ["store", "video", "streaming", "policy", "bandwidth"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Store Video section hidden; streaming purchases not accessible.",
            ApplyOps = [RegOp.SetDword(StoreKey, "DisableVideoPage", 1)],
            RemoveOps = [RegOp.DeleteValue(StoreKey, "DisableVideoPage")],
            DetectOps = [RegOp.CheckDword(StoreKey, "DisableVideoPage", 1)],
        },
        new TweakDef
        {
            Id = "storepl-policy-disable-music-streaming",
            Label = "Disable Store Music Streaming",
            Category = "System",
            Description =
                "Sets DisableMusicPage=1 under the WindowsStore Group Policy key. "
                + "Hides the Music section of the Microsoft Store, removing access to Groove/Xbox Music purchasing. "
                + "Complements DisableVideoPage in locking down the Store to business-relevant apps only.",
            Tags = ["store", "music", "streaming", "policy", "bandwidth"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Store Music section hidden; streaming music purchases not accessible.",
            ApplyOps = [RegOp.SetDword(StoreKey, "DisableMusicPage", 1)],
            RemoveOps = [RegOp.DeleteValue(StoreKey, "DisableMusicPage")],
            DetectOps = [RegOp.CheckDword(StoreKey, "DisableMusicPage", 1)],
        },
    ];
}
