#nullable enable
using RegiLattice.Core.Models;

namespace RegiLattice.Core.Tweaks;

internal static class UserProfilePolicy
{
    private const string SysKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System";

    public static IReadOnlyList<TweakDef> Tweaks =>
    [
        new TweakDef
        {
            Id = "upprof-enable-smartscreen-apps",
            Label = "Enable SmartScreen for Apps and Files",
            Category = "User Profile Policy",
            Description = "Activates Windows SmartScreen to check apps and files downloaded from the Internet before execution.",
            Tags = ["smartscreen", "security", "malware", "downloads", "system"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 5,
            SafetyRating = 5,
            ImpactNote = "SmartScreen value 1 = enabled; blocks unrecognized downloaded apps and shows a warning prompt.",
            ApplyOps = [RegOp.SetDword(SysKey, "EnableSmartScreen", 1)],
            RemoveOps = [RegOp.DeleteValue(SysKey, "EnableSmartScreen")],
            DetectOps = [RegOp.CheckDword(SysKey, "EnableSmartScreen", 1)],
        },
        new TweakDef
        {
            Id = "upprof-restrict-cmd-for-users",
            Label = "Restrict Command Prompt Access for Standard Users",
            Category = "User Profile Policy",
            Description = "Prevents standard (non-admin) users from launching Command Prompt (cmd.exe) directly.",
            Tags = ["cmd", "command-prompt", "restriction", "users", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Value 2 = disable cmd for users but allow cmd scripts; value 1 = disable both. Admins are unaffected.",
            ApplyOps = [RegOp.SetDword(SysKey, "DisableCMD", 2)],
            RemoveOps = [RegOp.DeleteValue(SysKey, "DisableCMD")],
            DetectOps = [RegOp.CheckDword(SysKey, "DisableCMD", 2)],
        },
        new TweakDef
        {
            Id = "upprof-run-logon-scripts-sync",
            Label = "Run Logon and Startup Scripts Synchronously",
            Category = "User Profile Policy",
            Description = "Runs all Group Policy logon and startup scripts synchronously before presenting the user desktop.",
            Tags = ["logon-scripts", "startup-scripts", "gpo", "synchronous", "user-profile"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Desktop shown only after all scripts complete; ensures drive mappings and profile settings are applied before login.",
            ApplyOps = [RegOp.SetDword(SysKey, "RunLogonScriptSync", 1)],
            RemoveOps = [RegOp.DeleteValue(SysKey, "RunLogonScriptSync")],
            DetectOps = [RegOp.CheckDword(SysKey, "RunLogonScriptSync", 1)],
        },
        new TweakDef
        {
            Id = "upprof-max-gpo-script-wait",
            Label = "Set Maximum Wait Time for Group Policy Scripts",
            Category = "User Profile Policy",
            Description = "Configures the maximum time (in seconds) Windows waits for Group Policy startup and shutdown scripts to complete.",
            Tags = ["gpo-scripts", "timeout", "logon", "user-profile"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Default is 600 seconds; prevents scripts from hanging system shutdown or logon indefinitely.",
            ApplyOps = [RegOp.SetDword(SysKey, "MaxGPOScriptWait", 600)],
            RemoveOps = [RegOp.DeleteValue(SysKey, "MaxGPOScriptWait")],
            DetectOps = [RegOp.CheckDword(SysKey, "MaxGPOScriptWait", 600)],
        },
        new TweakDef
        {
            Id = "upprof-enable-gp-refresh",
            Label = "Enable Background Group Policy Refresh",
            Category = "User Profile Policy",
            Description = "Ensures Group Policy is refreshed in the background on a schedule, even when the user is logged in.",
            Tags = ["group-policy", "gpo-refresh", "background", "user-profile"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Value 0 = allow background GP refresh (default-on but explicitly set via policy for enforcement).",
            ApplyOps = [RegOp.SetDword(SysKey, "DisableBkGndGroupPolicy", 0)],
            RemoveOps = [RegOp.DeleteValue(SysKey, "DisableBkGndGroupPolicy")],
            DetectOps = [RegOp.CheckDword(SysKey, "DisableBkGndGroupPolicy", 0)],
        },
        new TweakDef
        {
            Id = "upprof-block-roaming-profile-changes",
            Label = "Prevent Local Changes from Syncing Back to Roaming Profile",
            Category = "User Profile Policy",
            Description = "Prevents any changes made to a roaming user profile during a session from syncing back to the network share.",
            Tags = ["roaming-profile", "user-profile", "sync", "restriction"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 4,
            ImpactNote = "Discards local profile changes at logoff; changes made in the session are lost unless saved explicitly.",
            ApplyOps = [RegOp.SetDword(SysKey, "SlowLinkDefaultForDirectAccess", 0)],
            RemoveOps = [RegOp.DeleteValue(SysKey, "SlowLinkDefaultForDirectAccess")],
            DetectOps = [RegOp.CheckDword(SysKey, "SlowLinkDefaultForDirectAccess", 0)],
        },
        new TweakDef
        {
            Id = "upprof-verbose-logon-status",
            Label = "Disable Verbose Logon Status Messages",
            Category = "User Profile Policy",
            Description = "Suppresses the verbose 'Please wait...' and 'Applying computer settings...' status messages during logon.",
            Tags = ["logon", "status-messages", "ui", "boot", "user-profile"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Removes verbose status text at logon/logoff; cleaner experience in enterprise and kiosk deployments.",
            ApplyOps = [RegOp.SetDword(SysKey, "VerboseStatus", 0)],
            RemoveOps = [RegOp.DeleteValue(SysKey, "VerboseStatus")],
            DetectOps = [RegOp.CheckDword(SysKey, "VerboseStatus", 0)],
        },
        new TweakDef
        {
            Id = "upprof-block-profile-list-enumeration",
            Label = "Block Switching to Another User's Profile",
            Category = "User Profile Policy",
            Description = "Restricts the ability to download or load another user's roaming profile on this machine during interactive logon.",
            Tags = ["user-profile", "roaming-profile", "multi-user", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Prevents profile hijacking and cross-user profile leakage on shared workstations.",
            ApplyOps = [RegOp.SetDword(SysKey, "LocalProfile", 1)],
            RemoveOps = [RegOp.DeleteValue(SysKey, "LocalProfile")],
            DetectOps = [RegOp.CheckDword(SysKey, "LocalProfile", 1)],
        },
        new TweakDef
        {
            Id = "upprof-enable-logon-scripts-for-admins",
            Label = "Run Logon Scripts for Administrator Accounts",
            Category = "User Profile Policy",
            Description = "Ensures Group Policy logon scripts execute even when an administrator account is used to log on.",
            Tags = ["logon-scripts", "admin", "gpo", "user-profile"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "By default, some admin configs skip scripts; this enforces scripts run for admins too.",
            ApplyOps = [RegOp.SetDword(SysKey, "UserPoliciesAreMachinePolicies", 0)],
            RemoveOps = [RegOp.DeleteValue(SysKey, "UserPoliciesAreMachinePolicies")],
            DetectOps = [RegOp.CheckDword(SysKey, "UserPoliciesAreMachinePolicies", 0)],
        },
        new TweakDef
        {
            Id = "upprof-clear-recent-docs-on-logoff",
            Label = "Clear Recent Document Lists on Logoff",
            Category = "User Profile Policy",
            Description = "Deletes the list of recently accessed documents and applications from the user profile when they log off.",
            Tags = ["recent-docs", "logoff", "privacy", "user-profile"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Recent file list cleared at each logoff; improves privacy on shared workstations and kiosk machines.",
            ApplyOps = [RegOp.SetDword(SysKey, "ClearRecentDocsOnExit", 1)],
            RemoveOps = [RegOp.DeleteValue(SysKey, "ClearRecentDocsOnExit")],
            DetectOps = [RegOp.CheckDword(SysKey, "ClearRecentDocsOnExit", 1)],
        },
    ];
}
