namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

internal static class WiaImageAcquisitionPolicy
{
    private const string ScanKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Scanner";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        new TweakDef
        {
            Id = "imgacquire-disable-wia-service",
            Label = "Image Acquisition: Disable WIA (Windows Image Acquisition) Service",
            Category = "Image Acquisition Policy",
            Description = "Disables the Windows Image Acquisition (WIA) service via Group Policy, preventing scanners, cameras, and other WIA-compatible imaging devices from automatically launching the scanning wizard when connected. WIA devices can auto-trigger Windows Explorer and photo import dialogs. On managed workstations where scanning occurs through dedicated document management software, disabling WIA eliminates uncontrolled ad-hoc scanning to unmanaged locations.",
            Tags = ["image acquisition", "wia", "scanner", "camera", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ScanKey],
            ApplyOps = [RegOp.SetDword(ScanKey, "STINoInteractiveMode", 1)],
            RemoveOps = [RegOp.DeleteValue(ScanKey, "STINoInteractiveMode")],
            DetectOps = [RegOp.CheckDword(ScanKey, "STINoInteractiveMode", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Disables WIA interactive mode; connected scanners will not auto-launch import dialogs.",
        },
        new TweakDef
        {
            Id = "imgacquire-restrict-user-device-install",
            Label = "Image Acquisition: Restrict User-Initiated Device Installation for Cameras",
            Category = "Image Acquisition Policy",
            Description = "Prevents standard users from installing WIA-compatible cameras and imaging devices without administrator approval. Without this policy, plugging in a consumer camera can trigger a Plug-and-Play installation that adds imaging device drivers and WIA entries to the system. On managed environments, device drivers should only be installed through approved software deployment channels.",
            Tags = ["image acquisition", "wia", "camera", "device install", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ScanKey],
            ApplyOps = [RegOp.SetDword(ScanKey, "RestrictUserDeviceInstall", 1)],
            RemoveOps = [RegOp.DeleteValue(ScanKey, "RestrictUserDeviceInstall")],
            DetectOps = [RegOp.CheckDword(ScanKey, "RestrictUserDeviceInstall", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Prevents user-triggered camera/scanner driver installation; admin elevation required for new imaging devices.",
        },
        new TweakDef
        {
            Id = "imgacquire-disable-transferring-without-policy",
            Label = "Image Acquisition: Disable Image Transfer Without Policy Approval",
            Category = "Image Acquisition Policy",
            Description = "Blocks WIA from transferring images from connected cameras, scanners, or memory cards to the local filesystem without an approved destination policy being applied. Without this control, users can freely dump images from connected devices to any local folder, bypassing document management systems and creating unmanaged data. Enabling this policy ensures all image transfer operations occur through sanctioned software.",
            Tags = ["image acquisition", "wia", "image transfer", "data control", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ScanKey],
            ApplyOps = [RegOp.SetDword(ScanKey, "DisableTransferWithoutPolicy", 1)],
            RemoveOps = [RegOp.DeleteValue(ScanKey, "DisableTransferWithoutPolicy")],
            DetectOps = [RegOp.CheckDword(ScanKey, "DisableTransferWithoutPolicy", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Blocks ad-hoc image transfers from cameras/scanners; images must be transferred through approved document management software.",
        },
        new TweakDef
        {
            Id = "imgacquire-disable-scan-to-fax",
            Label = "Image Acquisition: Disable Scan-to-Fax WIA Feature",
            Category = "Image Acquisition Policy",
            Description = "Disables the WIA Scan-to-Fax destination that allows users to scan a document directly to a fax number through a Windows Fax and Scan workflow. Scan-to-fax functionality can be exploited to exfiltrate documents outside the organisation's content inspection boundary — fax transmissions often bypass DLP controls that monitor email and file-share uploads. Disabling this destination ensures all document workflows go through monitored channels.",
            Tags = ["image acquisition", "scan to fax", "wia", "data loss prevention", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ScanKey],
            ApplyOps = [RegOp.SetDword(ScanKey, "DisableScanToFax", 1)],
            RemoveOps = [RegOp.DeleteValue(ScanKey, "DisableScanToFax")],
            DetectOps = [RegOp.CheckDword(ScanKey, "DisableScanToFax", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Removes Scan-to-Fax from WIA destinations; Windows Fax and Scan direct-to-scanner functionality is unaffected.",
        },
        new TweakDef
        {
            Id = "imgacquire-disable-autoplay-camera",
            Label = "Image Acquisition: Disable AutoPlay for Camera Devices",
            Category = "Image Acquisition Policy",
            Description = "Prevents Windows AutoPlay from automatically launching when a camera or memory card is inserted, suppressing the dialog that asks what action to take (view photos, import as a folder, etc.). AutoPlay-triggered actions can automatically copy images from connected devices to default Photos or OneDrive locations without user awareness. Disabling AutoPlay ensures device connections require deliberate user action.",
            Tags = ["image acquisition", "autoplay", "camera", "memory card", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ScanKey],
            ApplyOps = [RegOp.SetDword(ScanKey, "DisableAutoPlayCamera", 1)],
            RemoveOps = [RegOp.DeleteValue(ScanKey, "DisableAutoPlayCamera")],
            DetectOps = [RegOp.CheckDword(ScanKey, "DisableAutoPlayCamera", 1)],
            ImpactScore = 2,
            SafetyRating = 5,
            ImpactNote = "Suppresses AutoPlay dialog for cameras and memory cards; no automatic photo import.",
        },
        new TweakDef
        {
            Id = "imgacquire-require-driver-signing",
            Label = "Image Acquisition: Require Signed Drivers for WIA Devices",
            Category = "Image Acquisition Policy",
            Description = "Enforces that only digitally-signed drivers can be loaded for WIA imaging devices. Unsigned WIA device drivers are a known malware vector — adversaries have used crafted WIA drivers to establish persistent kernel-mode access. Requiring driver signing ensures that all imaging device drivers are verifiable against Microsoft's WHQL certificate chain or a trusted enterprise root CA.",
            Tags = ["image acquisition", "wia", "driver signing", "security", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ScanKey],
            ApplyOps = [RegOp.SetDword(ScanKey, "RequireSignedDrivers", 1)],
            RemoveOps = [RegOp.DeleteValue(ScanKey, "RequireSignedDrivers")],
            DetectOps = [RegOp.CheckDword(ScanKey, "RequireSignedDrivers", 1)],
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Requires WHQL or enterprise-signed WIA drivers; unsigned legacy scanner drivers will fail to load.",
        },
        new TweakDef
        {
            Id = "imgacquire-disable-scan-to-sharepoint",
            Label = "Image Acquisition: Disable Scan-to-SharePoint WIA Feature",
            Category = "Image Acquisition Policy",
            Description = "Disables the WIA Scan-to-SharePoint destination that allows users to scan documents and automatically upload them to a SharePoint document library via the Windows Scan app. Scan-to-SharePoint can bypass normal document governance workflows by depositing files directly into collaboration sites without metadata tagging, classification, or legal-hold review. Disabling this destination ensures all scanned documents go through the organisation's records management system.",
            Tags = ["image acquisition", "scan to sharepoint", "wia", "document governance", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ScanKey],
            ApplyOps = [RegOp.SetDword(ScanKey, "DisableScanToSharePoint", 1)],
            RemoveOps = [RegOp.DeleteValue(ScanKey, "DisableScanToSharePoint")],
            DetectOps = [RegOp.CheckDword(ScanKey, "DisableScanToSharePoint", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Removes Scan-to-SharePoint from WIA destination list; manual upload to SharePoint via browser is unaffected.",
        },
        new TweakDef
        {
            Id = "imgacquire-disable-scanner-to-network",
            Label = "Image Acquisition: Disable Scan-to-Network Share Feature",
            Category = "Image Acquisition Policy",
            Description = "Disables the built-in scan-to-network-share facility in the WIA STI (Still Image) architecture that allows scanners with FTP/SMB push capability to send files directly to a Windows shared folder. Scan-to-network-share bypasses normal document management channels and can be used to exfiltrate documents to unauthorized UNC paths. Managed scanning environments should use dedicated secure document capture software instead.",
            Tags = ["image acquisition", "scanner", "network share", "data transfer", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ScanKey],
            ApplyOps = [RegOp.SetDword(ScanKey, "DisableScanToNetworkShare", 1)],
            RemoveOps = [RegOp.DeleteValue(ScanKey, "DisableScanToNetworkShare")],
            DetectOps = [RegOp.CheckDword(ScanKey, "DisableScanToNetworkShare", 1)],
            ImpactScore = 3,
            SafetyRating = 4,
            ImpactNote = "Disables scan-to-SMB/FTP from the WIA stack; dedicated scanning software configured by IT continues to work.",
        },
        new TweakDef
        {
            Id = "imgacquire-block-scan-to-email",
            Label = "Image Acquisition: Block Scan-to-Email Functionality",
            Category = "Image Acquisition Policy",
            Description = "Prevents the Windows Fax and Scan application and WIA-connected scanners from using the scan-to-email feature, which attaches scanned documents directly to email drafts. Scan-to-email can bypass DLP (Data Loss Prevention) policies by sending scanned documents through the default email client without content inspection. In regulated environments, document distribution must be controlled through DLP-aware channels.",
            Tags = ["image acquisition", "scanner", "email", "dlp", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ScanKey],
            ApplyOps = [RegOp.SetDword(ScanKey, "DisableScanToEmail", 1)],
            RemoveOps = [RegOp.DeleteValue(ScanKey, "DisableScanToEmail")],
            DetectOps = [RegOp.CheckDword(ScanKey, "DisableScanToEmail", 1)],
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Blocks scan-to-email; users must save scanned documents to approved locations and attach them manually.",
        },
        new TweakDef
        {
            Id = "imgacquire-restrict-scan-destination",
            Label = "Image Acquisition: Restrict Scan Destination to Approved Paths Only",
            Category = "Image Acquisition Policy",
            Description = "Enforces that WIA scan operations can only save documents to pre-approved local paths or managed network shares defined in Group Policy. Without this restriction, users can direct scanned content to removable drives, personal cloud sync folders (OneDrive, Dropbox), or mapped drives outside the corporate network perimeter. Restricting destinations ensures all scanned documents are stored in auditable, managed locations.",
            Tags = ["image acquisition", "scanner", "destination", "restriction", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            RegistryKeys = [ScanKey],
            ApplyOps = [RegOp.SetDword(ScanKey, "RestrictScanDestinations", 1)],
            RemoveOps = [RegOp.DeleteValue(ScanKey, "RestrictScanDestinations")],
            DetectOps = [RegOp.CheckDword(ScanKey, "RestrictScanDestinations", 1)],
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Limits scan destinations to IT-approved paths; scans to arbitrary local or cloud paths are blocked.",
        },
    ];
}
