#nullable enable
using RegiLattice.Core.Models;

namespace RegiLattice.Core.Tweaks;

internal static class WindowsUpdatePolicy
{
    private const string WuKey = @"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate";

    public static IReadOnlyList<TweakDef> Tweaks =>
    [
        new TweakDef
        {
            Id = "wupol-disable-wu-access",
            Label = "Disable Direct Windows Update Access",
            Category = "Windows Update Policy",
            Description = "Blocks direct access to Windows Update servers; devices must use an internal WSUS or managed update source.",
            Tags = ["windows-update", "wsus", "policy", "security"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Prevents unmanaged updates; requires a WSUS or Microsoft Endpoint Manager infrastructure to deliver updates.",
            ApplyOps = [RegOp.SetDword(WuKey, "DisableWindowsUpdateAccess", 1)],
            RemoveOps = [RegOp.DeleteValue(WuKey, "DisableWindowsUpdateAccess")],
            DetectOps = [RegOp.CheckDword(WuKey, "DisableWindowsUpdateAccess", 1)],
        },
        new TweakDef
        {
            Id = "wupol-block-internet-wu-locations",
            Label = "Block Direct Connection to Windows Update Internet Locations",
            Category = "Windows Update Policy",
            Description = "Forces all update traffic through an internal catalog; prevents the client from contacting Microsoft update servers directly.",
            Tags = ["windows-update", "internet", "policy", "wsus"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 4,
            ImpactNote = "Devices only receive updates through the configured internal source; requires WUServer to be set.",
            ApplyOps = [RegOp.SetDword(WuKey, "DoNotConnectToWindowsUpdateInternetLocations", 1)],
            RemoveOps = [RegOp.DeleteValue(WuKey, "DoNotConnectToWindowsUpdateInternetLocations")],
            DetectOps = [RegOp.CheckDword(WuKey, "DoNotConnectToWindowsUpdateInternetLocations", 1)],
        },
        new TweakDef
        {
            Id = "wupol-exclude-driver-updates",
            Label = "Exclude Hardware Drivers from Windows Update",
            Category = "Windows Update Policy",
            Description = "Prevents Windows Update from automatically delivering hardware driver updates through quality update channels.",
            Tags = ["windows-update", "drivers", "policy", "stability"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Driver updates must be installed manually or via WSUS driver category; prevents unstable driver push.",
            ApplyOps = [RegOp.SetDword(WuKey, "ExcludeWUDriversInQualityUpdate", 1)],
            RemoveOps = [RegOp.DeleteValue(WuKey, "ExcludeWUDriversInQualityUpdate")],
            DetectOps = [RegOp.CheckDword(WuKey, "ExcludeWUDriversInQualityUpdate", 1)],
        },
        new TweakDef
        {
            Id = "wupol-disable-os-upgrade",
            Label = "Disable OS Upgrade Offers via Windows Update",
            Category = "Windows Update Policy",
            Description = "Prevents Windows Update from offering or installing major operating system version upgrades.",
            Tags = ["windows-update", "upgrade", "feature-update", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Stops feature upgrades (e.g., Windows 10 → 11); quality and security patches are unaffected.",
            ApplyOps = [RegOp.SetDword(WuKey, "DisableOSUpgrade", 1)],
            RemoveOps = [RegOp.DeleteValue(WuKey, "DisableOSUpgrade")],
            DetectOps = [RegOp.CheckDword(WuKey, "DisableOSUpgrade", 1)],
        },
        new TweakDef
        {
            Id = "wupol-defer-quality-updates",
            Label = "Defer Quality Updates",
            Category = "Windows Update Policy",
            Description = "Enables deferral of quality (non-security) updates, delaying their installation after Microsoft release.",
            Tags = ["windows-update", "quality-update", "deferral", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Quality non-security updates are delayed; security patches are included in quality updates and also deferred.",
            ApplyOps = [RegOp.SetDword(WuKey, "DeferQualityUpdates", 1)],
            RemoveOps = [RegOp.DeleteValue(WuKey, "DeferQualityUpdates")],
            DetectOps = [RegOp.CheckDword(WuKey, "DeferQualityUpdates", 1)],
        },
        new TweakDef
        {
            Id = "wupol-defer-quality-updates-14d",
            Label = "Set Quality Update Deferral to 14 Days",
            Category = "Windows Update Policy",
            Description = "Defers quality updates by 14 days after Microsoft releases them, providing a burn-in window.",
            Tags = ["windows-update", "quality-update", "deferral", "days", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "14-day window to observe crash reports on early adopters before applying to managed devices.",
            ApplyOps = [RegOp.SetDword(WuKey, "DeferQualityUpdatesPeriodInDays", 14)],
            RemoveOps = [RegOp.DeleteValue(WuKey, "DeferQualityUpdatesPeriodInDays")],
            DetectOps = [RegOp.CheckDword(WuKey, "DeferQualityUpdatesPeriodInDays", 14)],
        },
        new TweakDef
        {
            Id = "wupol-defer-feature-updates",
            Label = "Defer Feature Updates",
            Category = "Windows Update Policy",
            Description = "Enables deferral of Windows feature updates, preventing the installation of new OS versions immediately.",
            Tags = ["windows-update", "feature-update", "deferral", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Feature updates are held back until the deferral period expires; quality updates can be deferred separately.",
            ApplyOps = [RegOp.SetDword(WuKey, "DeferFeatureUpdates", 1)],
            RemoveOps = [RegOp.DeleteValue(WuKey, "DeferFeatureUpdates")],
            DetectOps = [RegOp.CheckDword(WuKey, "DeferFeatureUpdates", 1)],
        },
        new TweakDef
        {
            Id = "wupol-defer-feature-updates-180d",
            Label = "Set Feature Update Deferral to 180 Days",
            Category = "Windows Update Policy",
            Description = "Defers Windows feature updates by 180 days, keeping the device on the current version for 6 months.",
            Tags = ["windows-update", "feature-update", "deferral", "days", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 4,
            SafetyRating = 5,
            ImpactNote = "Six-month stability window before upgrading OS; balance between security and compatibility testing.",
            ApplyOps = [RegOp.SetDword(WuKey, "DeferFeatureUpdatesPeriodInDays", 180)],
            RemoveOps = [RegOp.DeleteValue(WuKey, "DeferFeatureUpdatesPeriodInDays")],
            DetectOps = [RegOp.CheckDword(WuKey, "DeferFeatureUpdatesPeriodInDays", 180)],
        },
        new TweakDef
        {
            Id = "wupol-block-preview-builds",
            Label = "Block Windows Insider / Preview Builds",
            Category = "Windows Update Policy",
            Description = "Prevents users from opting in to Windows Insider or preview builds on managed devices.",
            Tags = ["windows-update", "insider", "preview", "policy", "stability"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Users cannot enrol in Windows Insider program; production build only on this device.",
            ApplyOps = [RegOp.SetDword(WuKey, "ManagePreviewBuilds", 1)],
            RemoveOps = [RegOp.DeleteValue(WuKey, "ManagePreviewBuilds")],
            DetectOps = [RegOp.CheckDword(WuKey, "ManagePreviewBuilds", 1)],
        },
        new TweakDef
        {
            Id = "wupol-set-semi-annual-channel",
            Label = "Set Update Branch to Semi-Annual Channel",
            Category = "Windows Update Policy",
            Description = "Configures Windows Update to use the Semi-Annual Channel for feature update readiness (General Availability).",
            Tags = ["windows-update", "branch", "semi-annual", "channel", "policy"],
            NeedsAdmin = true,
            CorpSafe = true,
            ImpactScore = 3,
            SafetyRating = 5,
            ImpactNote = "Value 16 = Semi-Annual Channel; device receives GA feature updates rather than Insider or preview rings.",
            ApplyOps = [RegOp.SetDword(WuKey, "BranchReadinessLevel", 16)],
            RemoveOps = [RegOp.DeleteValue(WuKey, "BranchReadinessLevel")],
            DetectOps = [RegOp.CheckDword(WuKey, "BranchReadinessLevel", 16)],
        },
    ];
}
