namespace RegiLattice.Core.Tweaks;

using RegiLattice.Core.Models;

/// <summary>
/// Visual appearance tweaks for title bars, scrollbars, fonts, icons, borders,
/// animations, tooltips, and accent colours — Phase 3 roadmap items.
/// </summary>
internal static class WindowAppearance
{
    private const string Metrics = @"HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics";
    private const string Desktop = @"HKEY_CURRENT_USER\Control Panel\Desktop";
    private const string Mouse = @"HKEY_CURRENT_USER\Control Panel\Mouse";
    private const string Dwm = @"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\DWM";
    private const string Explorer = @"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced";
    private const string Themes = @"HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize";
    private const string Accessibility = @"HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys";
    private const string Cursors = @"HKEY_CURRENT_USER\Control Panel\Cursors";
    private const string Colors = @"HKEY_CURRENT_USER\Control Panel\Colors";

    internal static IReadOnlyList<TweakDef> Tweaks { get; } =
    [
        // ── Title Bar & Window Chrome ────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-titlebar-color-active",
            Label = "Show Accent Color on Title Bars",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Colours active title bars and window borders with the system accent colour.",
            Tags = ["appearance", "titlebar", "accent", "color"],
            RegistryKeys = [Dwm],
            ApplyOps = [RegOp.SetDword(Dwm, "ColorPrevalence", 1)],
            RemoveOps = [RegOp.SetDword(Dwm, "ColorPrevalence", 0)],
            DetectOps = [RegOp.CheckDword(Dwm, "ColorPrevalence", 1)],
        },
        new TweakDef
        {
            Id = "winapp-titlebar-color-inactive",
            Label = "Show Accent Color on Inactive Title Bars",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Extends the accent colour to inactive window title bars for a uniform look.",
            Tags = ["appearance", "titlebar", "accent", "inactive"],
            RegistryKeys = [Dwm],
            ApplyOps = [RegOp.SetDword(Dwm, "AccentColorInactive", 1)],
            RemoveOps = [RegOp.DeleteValue(Dwm, "AccentColorInactive")],
            DetectOps = [RegOp.CheckDword(Dwm, "AccentColorInactive", 1)],
        },
        new TweakDef
        {
            Id = "winapp-start-taskbar-accent",
            Label = "Show Accent Color on Start and Taskbar",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Applies the system accent colour to the Start menu and taskbar background.",
            Tags = ["appearance", "accent", "start", "taskbar"],
            RegistryKeys = [Themes],
            ApplyOps = [RegOp.SetDword(Themes, "ColorPrevalence", 1)],
            RemoveOps = [RegOp.SetDword(Themes, "ColorPrevalence", 0)],
            DetectOps = [RegOp.CheckDword(Themes, "ColorPrevalence", 1)],
        },
        new TweakDef
        {
            Id = "winapp-disable-title-bar-flashing",
            Label = "Disable Title Bar Flashing",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Prevents applications from flashing their title bar to attract attention.",
            Tags = ["appearance", "titlebar", "flash", "focus"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetDword(Desktop, "ForegroundFlashCount", 0)],
            RemoveOps = [RegOp.SetDword(Desktop, "ForegroundFlashCount", 3)],
            DetectOps = [RegOp.CheckDword(Desktop, "ForegroundFlashCount", 0)],
        },
        new TweakDef
        {
            Id = "winapp-disable-window-shake",
            Label = "Disable Aero Shake (Minimize on Shake)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Prevents shaking a window title bar from minimising all other windows.",
            Tags = ["appearance", "aero", "shake", "minimize"],
            RegistryKeys = [Explorer],
            ApplyOps = [RegOp.SetDword(Explorer, "DisallowShaking", 1)],
            RemoveOps = [RegOp.DeleteValue(Explorer, "DisallowShaking")],
            DetectOps = [RegOp.CheckDword(Explorer, "DisallowShaking", 1)],
        },
        // ── Scrollbar & Window Metrics ───────────────────────────────────

        new TweakDef
        {
            Id = "winapp-scrollbar-width-thin",
            Label = "Thin Scrollbars (13px)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets scrollbar width to thin 13 pixels (default is 17). Requires sign-out.",
            Tags = ["appearance", "scrollbar", "width", "thin"],
            RegistryKeys = [Metrics],
            ApplyOps = [RegOp.SetString(Metrics, "ScrollWidth", "-195")],
            RemoveOps = [RegOp.SetString(Metrics, "ScrollWidth", "-255")],
            DetectOps = [RegOp.CheckString(Metrics, "ScrollWidth", "-195")],
            SideEffects = "Requires sign-out to take effect.",
        },
        new TweakDef
        {
            Id = "winapp-scrollbar-height-thin",
            Label = "Thin Scroll Arrows (13px)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets scrollbar button height to thin 13 pixels (default is 17). Requires sign-out.",
            Tags = ["appearance", "scrollbar", "height", "thin"],
            RegistryKeys = [Metrics],
            ApplyOps = [RegOp.SetString(Metrics, "ScrollHeight", "-195")],
            RemoveOps = [RegOp.SetString(Metrics, "ScrollHeight", "-255")],
            DetectOps = [RegOp.CheckString(Metrics, "ScrollHeight", "-195")],
            SideEffects = "Requires sign-out to take effect.",
        },
        new TweakDef
        {
            Id = "winapp-border-width-thin",
            Label = "Thin Window Borders (1px)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets window border width to 1 pixel (default is padded). Requires sign-out.",
            Tags = ["appearance", "border", "width", "thin"],
            RegistryKeys = [Metrics],
            ApplyOps = [RegOp.SetString(Metrics, "BorderWidth", "-15")],
            RemoveOps = [RegOp.SetString(Metrics, "BorderWidth", "-15")],
            DetectOps = [RegOp.CheckString(Metrics, "BorderWidth", "-15")],
            SideEffects = "Requires sign-out to take effect.",
        },
        new TweakDef
        {
            Id = "winapp-padded-border-zero",
            Label = "Remove Window Padding Border",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Removes the extra padded border around windows (-60 = 4px default, 0 = none). Requires sign-out.",
            Tags = ["appearance", "border", "padding"],
            RegistryKeys = [Metrics],
            ApplyOps = [RegOp.SetString(Metrics, "PaddedBorderWidth", "0")],
            RemoveOps = [RegOp.SetString(Metrics, "PaddedBorderWidth", "-60")],
            DetectOps = [RegOp.CheckString(Metrics, "PaddedBorderWidth", "0")],
            SideEffects = "Requires sign-out to take effect.",
        },
        new TweakDef
        {
            Id = "winapp-caption-height-compact",
            Label = "Compact Title Bar Height (20px)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces the title bar height to 20 pixels for more screen space (default ~22). Requires sign-out.",
            Tags = ["appearance", "titlebar", "height", "compact"],
            RegistryKeys = [Metrics],
            ApplyOps = [RegOp.SetString(Metrics, "CaptionHeight", "-300")],
            RemoveOps = [RegOp.SetString(Metrics, "CaptionHeight", "-330")],
            DetectOps = [RegOp.CheckString(Metrics, "CaptionHeight", "-300")],
            SideEffects = "Requires sign-out to take effect.",
        },
        // ── Icon Spacing ─────────────────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-icon-spacing-h-compact",
            Label = "Compact Horizontal Icon Spacing (60px)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces horizontal desktop icon spacing to 60 pixels (default 75). Requires sign-out.",
            Tags = ["appearance", "icon", "spacing", "horizontal"],
            RegistryKeys = [Metrics],
            ApplyOps = [RegOp.SetString(Metrics, "IconSpacing", "-900")],
            RemoveOps = [RegOp.SetString(Metrics, "IconSpacing", "-1125")],
            DetectOps = [RegOp.CheckString(Metrics, "IconSpacing", "-900")],
            SideEffects = "Requires sign-out to take effect.",
        },
        new TweakDef
        {
            Id = "winapp-icon-spacing-v-compact",
            Label = "Compact Vertical Icon Spacing (60px)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces vertical desktop icon spacing to 60 pixels (default 75). Requires sign-out.",
            Tags = ["appearance", "icon", "spacing", "vertical"],
            RegistryKeys = [Metrics],
            ApplyOps = [RegOp.SetString(Metrics, "IconVerticalSpacing", "-900")],
            RemoveOps = [RegOp.SetString(Metrics, "IconVerticalSpacing", "-1125")],
            DetectOps = [RegOp.CheckString(Metrics, "IconVerticalSpacing", "-900")],
            SideEffects = "Requires sign-out to take effect.",
        },
        // ── Menu & Animation ─────────────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-menu-show-delay-fast",
            Label = "Fast Menu Show Delay (100ms)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces the delay before sub-menus appear to 100ms (default 400ms).",
            Tags = ["appearance", "menu", "delay", "speed"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetString(Desktop, "MenuShowDelay", "100")],
            RemoveOps = [RegOp.SetString(Desktop, "MenuShowDelay", "400")],
            DetectOps = [RegOp.CheckString(Desktop, "MenuShowDelay", "100")],
        },
        new TweakDef
        {
            Id = "winapp-menu-show-delay-instant",
            Label = "Instant Menu Show Delay (0ms)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Eliminates the delay before sub-menus appear (default 400ms).",
            Tags = ["appearance", "menu", "delay", "instant"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetString(Desktop, "MenuShowDelay", "0")],
            RemoveOps = [RegOp.SetString(Desktop, "MenuShowDelay", "400")],
            DetectOps = [RegOp.CheckString(Desktop, "MenuShowDelay", "0")],
        },
        new TweakDef
        {
            Id = "winapp-disable-menu-animations",
            Label = "Disable Menu Fade/Slide Animations",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables fade and slide effects on menus for instant display.",
            Tags = ["appearance", "menu", "animation", "fade"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetString(Desktop, "UserPreferencesMask", "9012038010000000")],
            RemoveOps = [RegOp.DeleteValue(Desktop, "UserPreferencesMask")],
            DetectOps = [RegOp.CheckString(Desktop, "UserPreferencesMask", "9012038010000000")],
        },
        new TweakDef
        {
            Id = "winapp-disable-window-animation",
            Label = "Disable Window Min/Max Animations",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables the animation when minimising or maximising windows.",
            Tags = ["appearance", "window", "animation", "minimize", "maximize"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetString(Desktop, "MinAnimate", "0")],
            RemoveOps = [RegOp.SetString(Desktop, "MinAnimate", "1")],
            DetectOps = [RegOp.CheckString(Desktop, "MinAnimate", "0")],
        },
        new TweakDef
        {
            Id = "winapp-disable-cursor-blink",
            Label = "Disable Cursor Blinking",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Stops the text cursor from blinking by setting the rate to -1 (infinite).",
            Tags = ["appearance", "cursor", "blink"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetString(Desktop, "CursorBlinkRate", "-1")],
            RemoveOps = [RegOp.SetString(Desktop, "CursorBlinkRate", "530")],
            DetectOps = [RegOp.CheckString(Desktop, "CursorBlinkRate", "-1")],
        },
        // ── Tooltip ──────────────────────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-tooltip-delay-fast",
            Label = "Fast Tooltip Delay (200ms)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces tooltip delay to 200ms (default 400ms) for faster hover info.",
            Tags = ["appearance", "tooltip", "delay"],
            RegistryKeys = [Mouse],
            ApplyOps = [RegOp.SetString(Mouse, "MouseHoverTime", "200")],
            RemoveOps = [RegOp.SetString(Mouse, "MouseHoverTime", "400")],
            DetectOps = [RegOp.CheckString(Mouse, "MouseHoverTime", "200")],
        },
        new TweakDef
        {
            Id = "winapp-tooltip-delay-instant",
            Label = "Instant Tooltip Delay (0ms)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Eliminates tooltip delay for instant hover info display.",
            Tags = ["appearance", "tooltip", "delay", "instant"],
            RegistryKeys = [Mouse],
            ApplyOps = [RegOp.SetString(Mouse, "MouseHoverTime", "0")],
            RemoveOps = [RegOp.SetString(Mouse, "MouseHoverTime", "400")],
            DetectOps = [RegOp.CheckString(Mouse, "MouseHoverTime", "0")],
        },
        // ── Alt+Tab & Multitasking Appearance ────────────────────────────

        new TweakDef
        {
            Id = "winapp-alt-tab-classic",
            Label = "Classic Alt+Tab (No Thumbnails)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Switches Alt+Tab to the classic icon-only style without window thumbnails.",
            Tags = ["appearance", "alt-tab", "classic", "multitasking"],
            RegistryKeys = [Explorer],
            ApplyOps = [RegOp.SetDword(Explorer, "AltTabSettings", 1)],
            RemoveOps = [RegOp.DeleteValue(Explorer, "AltTabSettings")],
            DetectOps = [RegOp.CheckDword(Explorer, "AltTabSettings", 1)],
        },
        new TweakDef
        {
            Id = "winapp-alt-tab-no-edge-tabs",
            Label = "Alt+Tab: Open Windows Only (No Edge Tabs)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Prevents Edge browser tabs from appearing as separate items in Alt+Tab.",
            Tags = ["appearance", "alt-tab", "edge", "tabs"],
            RegistryKeys = [Explorer],
            ApplyOps = [RegOp.SetDword(Explorer, "MultiTaskingAltTabFilter", 3)],
            RemoveOps = [RegOp.DeleteValue(Explorer, "MultiTaskingAltTabFilter")],
            DetectOps = [RegOp.CheckDword(Explorer, "MultiTaskingAltTabFilter", 3)],
        },
        // ── Transparency & DWM Effects ───────────────────────────────────

        new TweakDef
        {
            Id = "winapp-enable-transparency",
            Label = "Enable Transparency Effects",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Enables transparency effects on Start, taskbar, and action centre.",
            Tags = ["appearance", "transparency", "visual"],
            RegistryKeys = [Themes],
            ApplyOps = [RegOp.SetDword(Themes, "EnableTransparency", 1)],
            RemoveOps = [RegOp.SetDword(Themes, "EnableTransparency", 0)],
            DetectOps = [RegOp.CheckDword(Themes, "EnableTransparency", 1)],
        },
        new TweakDef
        {
            Id = "winapp-disable-transparency",
            Label = "Disable Transparency Effects",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables all transparency effects for a solid look and slight performance gain.",
            Tags = ["appearance", "transparency", "performance"],
            RegistryKeys = [Themes],
            ApplyOps = [RegOp.SetDword(Themes, "EnableTransparency", 0)],
            RemoveOps = [RegOp.SetDword(Themes, "EnableTransparency", 1)],
            DetectOps = [RegOp.CheckDword(Themes, "EnableTransparency", 0)],
        },
        new TweakDef
        {
            Id = "winapp-dwm-enable-blur",
            Label = "Enable DWM Blur Behind",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Enables the blur-behind effect for DWM-managed windows (Aero Glass look).",
            Tags = ["appearance", "dwm", "blur", "aero"],
            RegistryKeys = [Dwm],
            ApplyOps = [RegOp.SetDword(Dwm, "EnableAeroPeek", 1)],
            RemoveOps = [RegOp.SetDword(Dwm, "EnableAeroPeek", 0)],
            DetectOps = [RegOp.CheckDword(Dwm, "EnableAeroPeek", 1)],
        },
        new TweakDef
        {
            Id = "winapp-dwm-disable-peek",
            Label = "Disable Desktop Peek (Aero Peek)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Prevents hovering over Show Desktop from making windows transparent.",
            Tags = ["appearance", "dwm", "peek", "desktop"],
            RegistryKeys = [Dwm],
            ApplyOps = [RegOp.SetDword(Dwm, "EnableAeroPeek", 0)],
            RemoveOps = [RegOp.SetDword(Dwm, "EnableAeroPeek", 1)],
            DetectOps = [RegOp.CheckDword(Dwm, "EnableAeroPeek", 0)],
        },
        new TweakDef
        {
            Id = "winapp-dwm-disable-flip3d",
            Label = "Disable Flip3D Effect",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables the 3D flip window switching effect (legacy feature, saves GPU resources).",
            Tags = ["appearance", "dwm", "flip3d", "visual"],
            RegistryKeys = [Dwm],
            ApplyOps = [RegOp.SetDword(Dwm, "Composition", 0)],
            RemoveOps = [RegOp.SetDword(Dwm, "Composition", 1)],
            DetectOps = [RegOp.CheckDword(Dwm, "Composition", 0)],
        },
        new TweakDef
        {
            Id = "winapp-enable-round-corners",
            Label = "Enable Rounded Window Corners",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Ensures rounded corners on windows (default on Win11). Set UseWindowFrameStagingBuffer to 1.",
            Tags = ["appearance", "corners", "rounded", "win11"],
            RegistryKeys = [Dwm],
            ApplyOps = [RegOp.SetDword(Dwm, "UseWindowFrameStagingBuffer", 1)],
            RemoveOps = [RegOp.DeleteValue(Dwm, "UseWindowFrameStagingBuffer")],
            DetectOps = [RegOp.CheckDword(Dwm, "UseWindowFrameStagingBuffer", 1)],
        },
        // ── Cursor & Mouse Visual ────────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-cursor-shadow",
            Label = "Enable Cursor Shadow",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Adds a shadow under the mouse cursor for better visibility on light backgrounds.",
            Tags = ["appearance", "cursor", "shadow"],
            RegistryKeys = [Cursors],
            ApplyOps = [RegOp.SetString(Cursors, "CursorShadow", "1")],
            RemoveOps = [RegOp.SetString(Cursors, "CursorShadow", "0")],
            DetectOps = [RegOp.CheckString(Cursors, "CursorShadow", "1")],
        },
        new TweakDef
        {
            Id = "winapp-disable-cursor-shadow",
            Label = "Disable Cursor Shadow",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Removes the shadow under the mouse cursor for a cleaner look.",
            Tags = ["appearance", "cursor", "shadow"],
            RegistryKeys = [Cursors],
            ApplyOps = [RegOp.SetString(Cursors, "CursorShadow", "0")],
            RemoveOps = [RegOp.SetString(Cursors, "CursorShadow", "1")],
            DetectOps = [RegOp.CheckString(Cursors, "CursorShadow", "0")],
        },
        new TweakDef
        {
            Id = "winapp-cursor-size-large",
            Label = "Large Mouse Cursor (48px)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Increases the mouse cursor size to large (48px) for better visibility.",
            Tags = ["appearance", "cursor", "size", "large", "accessibility"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Software\Microsoft\Accessibility"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Accessibility", "CursorSize", 3)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Software\Microsoft\Accessibility", "CursorSize", 1)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Software\Microsoft\Accessibility", "CursorSize", 3)],
        },
        // ── Dark/Light Mode Per-Area ─────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-dark-mode-apps",
            Label = "Dark Mode for Apps",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Forces dark mode for modern UWP/WinUI applications only.",
            Tags = ["appearance", "dark", "mode", "apps"],
            RegistryKeys = [Themes],
            ApplyOps = [RegOp.SetDword(Themes, "AppsUseLightTheme", 0)],
            RemoveOps = [RegOp.SetDword(Themes, "AppsUseLightTheme", 1)],
            DetectOps = [RegOp.CheckDword(Themes, "AppsUseLightTheme", 0)],
        },
        new TweakDef
        {
            Id = "winapp-light-mode-apps",
            Label = "Light Mode for Apps",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Forces light mode for modern UWP/WinUI applications only.",
            Tags = ["appearance", "light", "mode", "apps"],
            RegistryKeys = [Themes],
            ApplyOps = [RegOp.SetDword(Themes, "AppsUseLightTheme", 1)],
            RemoveOps = [RegOp.SetDword(Themes, "AppsUseLightTheme", 0)],
            DetectOps = [RegOp.CheckDword(Themes, "AppsUseLightTheme", 1)],
        },
        new TweakDef
        {
            Id = "winapp-dark-mode-system",
            Label = "Dark Mode for System UI",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Forces dark mode for system UI elements (Start, taskbar, action centre).",
            Tags = ["appearance", "dark", "mode", "system"],
            RegistryKeys = [Themes],
            ApplyOps = [RegOp.SetDword(Themes, "SystemUsesLightTheme", 0)],
            RemoveOps = [RegOp.SetDword(Themes, "SystemUsesLightTheme", 1)],
            DetectOps = [RegOp.CheckDword(Themes, "SystemUsesLightTheme", 0)],
        },
        new TweakDef
        {
            Id = "winapp-light-mode-system",
            Label = "Light Mode for System UI",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Forces light mode for system UI elements (Start, taskbar, action centre).",
            Tags = ["appearance", "light", "mode", "system"],
            RegistryKeys = [Themes],
            ApplyOps = [RegOp.SetDword(Themes, "SystemUsesLightTheme", 1)],
            RemoveOps = [RegOp.SetDword(Themes, "SystemUsesLightTheme", 0)],
            DetectOps = [RegOp.CheckDword(Themes, "SystemUsesLightTheme", 1)],
        },
        // ── Font & Text ──────────────────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-menu-font-size-small",
            Label = "Small Menu Font (14px)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets the system menu font height to 14 pixels for compact menus. Requires sign-out.",
            Tags = ["appearance", "font", "menu", "size", "small"],
            RegistryKeys = [Metrics],
            ApplyOps = [RegOp.SetString(Metrics, "MenuHeight", "-210")],
            RemoveOps = [RegOp.SetString(Metrics, "MenuHeight", "-285")],
            DetectOps = [RegOp.CheckString(Metrics, "MenuHeight", "-210")],
            SideEffects = "Requires sign-out to take effect.",
        },
        new TweakDef
        {
            Id = "winapp-small-caption-font",
            Label = "Small Caption Font for Toolbars",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces the small caption font height used by floating toolbars and palettes. Requires sign-out.",
            Tags = ["appearance", "font", "caption", "toolbar"],
            RegistryKeys = [Metrics],
            ApplyOps = [RegOp.SetString(Metrics, "SmCaptionHeight", "-225")],
            RemoveOps = [RegOp.SetString(Metrics, "SmCaptionHeight", "-330")],
            DetectOps = [RegOp.CheckString(Metrics, "SmCaptionHeight", "-225")],
            SideEffects = "Requires sign-out to take effect.",
        },
        // ── Desktop & Visual Tweaks ──────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-disable-desktop-icons",
            Label = "Hide All Desktop Icons",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Hides all desktop icons for a clean workspace look.",
            Tags = ["appearance", "desktop", "icons", "clean"],
            RegistryKeys = [Explorer],
            ApplyOps = [RegOp.SetDword(Explorer, "HideIcons", 1)],
            RemoveOps = [RegOp.SetDword(Explorer, "HideIcons", 0)],
            DetectOps = [RegOp.CheckDword(Explorer, "HideIcons", 1)],
        },
        new TweakDef
        {
            Id = "winapp-show-file-extensions",
            Label = "Show File Extensions on Desktop",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Shows file extensions for desktop icons, matching Explorer behaviour.",
            Tags = ["appearance", "desktop", "extensions", "files"],
            RegistryKeys = [Explorer],
            ApplyOps = [RegOp.SetDword(Explorer, "HideFileExt", 0)],
            RemoveOps = [RegOp.SetDword(Explorer, "HideFileExt", 1)],
            DetectOps = [RegOp.CheckDword(Explorer, "HideFileExt", 0)],
        },
        new TweakDef
        {
            Id = "winapp-disable-snap-assist-flyout",
            Label = "Disable Snap Assist Flyout",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Prevents the snap layout flyout from appearing when hovering the maximise button.",
            Tags = ["appearance", "snap", "flyout", "maximize"],
            RegistryKeys = [Explorer],
            ApplyOps = [RegOp.SetDword(Explorer, "EnableSnapAssistFlyout", 0)],
            RemoveOps = [RegOp.SetDword(Explorer, "EnableSnapAssistFlyout", 1)],
            DetectOps = [RegOp.CheckDword(Explorer, "EnableSnapAssistFlyout", 0)],
        },
        new TweakDef
        {
            Id = "winapp-taskbar-top-align",
            Label = "Taskbar: Left-Align Icons",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Moves taskbar icons to the left instead of the default centred layout on Windows 11.",
            Tags = ["appearance", "taskbar", "alignment", "left"],
            RegistryKeys = [Explorer],
            ApplyOps = [RegOp.SetDword(Explorer, "TaskbarAl", 0)],
            RemoveOps = [RegOp.SetDword(Explorer, "TaskbarAl", 1)],
            DetectOps = [RegOp.CheckDword(Explorer, "TaskbarAl", 0)],
        },
        new TweakDef
        {
            Id = "winapp-drag-full-windows",
            Label = "Drag Full Windows (Not Outlines)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Shows the full window content whilst dragging instead of a wire-frame outline.",
            Tags = ["appearance", "drag", "windows", "visual"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetString(Desktop, "DragFullWindows", "1")],
            RemoveOps = [RegOp.SetString(Desktop, "DragFullWindows", "0")],
            DetectOps = [RegOp.CheckString(Desktop, "DragFullWindows", "1")],
        },
        new TweakDef
        {
            Id = "winapp-drag-outline-only",
            Label = "Drag Window Outlines Only",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Shows only a wire-frame outline when dragging windows for lower CPU usage.",
            Tags = ["appearance", "drag", "outline", "performance"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetString(Desktop, "DragFullWindows", "0")],
            RemoveOps = [RegOp.SetString(Desktop, "DragFullWindows", "1")],
            DetectOps = [RegOp.CheckString(Desktop, "DragFullWindows", "0")],
        },
        // ── Wallpaper & Background ───────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-wallpaper-quality-max",
            Label = "Maximum Wallpaper JPEG Quality",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Sets wallpaper JPEG compression to maximum quality (100%). Prevents blurry desktop backgrounds.",
            Tags = ["appearance", "wallpaper", "quality", "jpeg"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetDword(Desktop, "JPEGImportQuality", 100)],
            RemoveOps = [RegOp.DeleteValue(Desktop, "JPEGImportQuality")],
            DetectOps = [RegOp.CheckDword(Desktop, "JPEGImportQuality", 100)],
        },
        new TweakDef
        {
            Id = "winapp-solid-color-background",
            Label = "Use Solid Color Desktop Background",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Switches the desktop background to a solid colour (no wallpaper) for a minimal look.",
            Tags = ["appearance", "wallpaper", "solid", "minimal"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetString(Desktop, "Wallpaper", "")],
            RemoveOps = [RegOp.DeleteValue(Desktop, "Wallpaper")],
            DetectOps = [RegOp.CheckString(Desktop, "Wallpaper", "")],
        },
        new TweakDef
        {
            Id = "winapp-disable-wallpaper-slideshow",
            Label = "Disable Desktop Slideshow",
            Category = "Window Appearance",
            NeedsAdmin = true,
            CorpSafe = true,
            Description = "Prevents the desktop wallpaper from cycling through images at timed intervals.",
            Tags = ["appearance", "wallpaper", "slideshow"],
            RegistryKeys = [@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization"],
            ApplyOps = [RegOp.SetDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization", "DesktopSlideShowEnabled", 0)],
            RemoveOps = [RegOp.DeleteValue(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization", "DesktopSlideShowEnabled")],
            DetectOps = [RegOp.CheckDword(@"HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization", "DesktopSlideShowEnabled", 0)],
        },
        // ── Focus & Activation ───────────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-focus-follows-mouse",
            Label = "Focus Follows Mouse (X-Mouse)",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Activates windows simply by hovering the mouse, without clicking (X11-style focus).",
            Tags = ["appearance", "focus", "mouse", "x-mouse"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Mouse"],
            ApplyOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "ActiveWindowTracking", "1")],
            RemoveOps = [RegOp.SetString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "ActiveWindowTracking", "0")],
            DetectOps = [RegOp.CheckString(@"HKEY_CURRENT_USER\Control Panel\Mouse", "ActiveWindowTracking", "1")],
        },
        new TweakDef
        {
            Id = "winapp-auto-raise-on-hover",
            Label = "Auto-Raise Window on Hover",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Automatically brings the hovered window to the front (requires Focus Follows Mouse).",
            Tags = ["appearance", "focus", "hover", "raise"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetDword(Desktop, "ActiveWndTrkTimeout", 200)],
            RemoveOps = [RegOp.DeleteValue(Desktop, "ActiveWndTrkTimeout")],
            DetectOps = [RegOp.CheckDword(Desktop, "ActiveWndTrkTimeout", 200)],
        },
        new TweakDef
        {
            Id = "winapp-foreground-lock-timeout",
            Label = "Reduce Foreground Lock Timeout",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Reduces the timeout that prevents apps from stealing focus to 0ms (instant focus switch).",
            Tags = ["appearance", "focus", "foreground", "lock"],
            RegistryKeys = [@"HKEY_CURRENT_USER\Control Panel\Desktop"],
            ApplyOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "ForegroundLockTimeout", 0)],
            RemoveOps = [RegOp.SetDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "ForegroundLockTimeout", 200000)],
            DetectOps = [RegOp.CheckDword(@"HKEY_CURRENT_USER\Control Panel\Desktop", "ForegroundLockTimeout", 0)],
        },
        // ── Visual Effects Granular ──────────────────────────────────────

        new TweakDef
        {
            Id = "winapp-disable-smooth-scrolling",
            Label = "Disable Smooth Scrolling",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables smooth scrolling animations in listboxes and controls.",
            Tags = ["appearance", "scrolling", "smooth", "performance"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetDword(Desktop, "SmoothScroll", 0)],
            RemoveOps = [RegOp.SetDword(Desktop, "SmoothScroll", 1)],
            DetectOps = [RegOp.CheckDword(Desktop, "SmoothScroll", 0)],
        },
        new TweakDef
        {
            Id = "winapp-disable-font-smoothing",
            Label = "Disable Font Smoothing",
            Category = "Window Appearance",
            NeedsAdmin = false,
            CorpSafe = true,
            Description = "Disables all font smoothing for a crisp pixel-perfect text look on high-DPI displays.",
            Tags = ["appearance", "font", "smoothing"],
            RegistryKeys = [Desktop],
            ApplyOps = [RegOp.SetString(Desktop, "FontSmoothing", "0")],
            RemoveOps = [RegOp.SetString(Desktop, "FontSmoothing", "2")],
            DetectOps = [RegOp.CheckString(Desktop, "FontSmoothing", "0")],
        },
    ];
}
